---
permalink: switch-cisco-3232c/cn1610-migrate-to-3232c-overview.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: 在配置Cisco Nexus 3232c 交换机之前，请先查看流程概述和命名规则。 
---
= 迁移要求
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C 交换机可用作AFF或FAS集群中的集群交换机。集群交换机允许您构建具有两个以上节点的ONTAP集群。


NOTE: 该过程需要同时使用ONTAP命令和Cisco Nexus 3000 系列交换机命令；除非另有说明，否则使用ONTAP命令。

如有需要，请参阅以下内容了解更多信息：

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 和 CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco以太网交换机"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== CN1610迁移要求

集群交换机支持以下节点连接：

* NetApp CN1610：端口 0/1 至 0/12 (10 GbE)
* Cisco Nexus 3232C：端口 e1/1-30（40 或 100 或 4x10GbE）


集群交换机使用以下交换机间链路 (ISL) 端口。

* NetApp CN1610：端口 0/13 至 0/16 (10 GbE)
* Cisco Nexus 3232C：端口 1/31-32 (100GbE)


[NOTE]
====
在Cisco Nexus 3232C 集群交换机上必须使用 4x10G 分支电缆。

====
下表显示了从NetApp CN1610 交换机过渡到Cisco Nexus 3232C 集群交换机时，每个阶段所需的布线连接：

|===
| 阶段 | 描述 | 所需电缆 


 a| 
初始
 a| 
CN1610 至 CN1610（SFP+ 至 SFP+）
 a| 
4根SFP+光纤或铜缆直连电缆



 a| 
过渡
 a| 
CN1610 至 3232C（QSFP 至 SFP+）
 a| 
1根QSFP和4根SFP+光纤或铜缆分支电缆



 a| 
终稿
 a| 
3232C 至 3232C（QSFP 至 QSFP）
 a| 
2根QSFP光纤或铜缆直连电缆

|===
您必须已下载适用的参考配置文件（RCF）。  10 GbE 和 40/100 GbE 端口的数量在可用的 RCF 中定义。link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco集群网络交换机参考配置文件下载"^] 。

此流程支持的ONTAP和 NX-OS 版本列于此处。link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco以太网交换机"^] 。

此流程支持的ONTAP和 FASTPATH 版本列于此处link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 和 CN1610 交换机"^]。

.关于所使用的示例
迁移过程中的示例使用了四个节点：

* 两个节点使用四个 10 GbE 集群互连端口：*e0a*、*e0b*、*e0c* 和 *e0d*。
* 另外两个节点使用两条 40 GbE 集群互连光纤电缆：*e4a* 和 *e4e*。
+
这link:https://hwu.netapp.com/["硬件宇宙"^]包含有关您平台集群光纤电缆的信息。



本流程中的示例使用以下开关和节点命名规则：

* 这些节点是 *n1*、*n2*、*n3* 和 *n4*。
* 命令输出可能因ONTAP软件版本不同而有所差异。
* 需要更换的 CN1610 交换机是 *CL1* 和 *CL2*。
* 用于替换 CN1610 交换机的 Nexus 3232C 交换机是 *C1* 和 *C2*。
* *n1_clus1* 是连接到节点 *n1* 的集群交换机 1 (CL1 或 C1) 的第一个集群逻辑接口 (LIF)。
* *n1_clus2* 是连接到节点 *n1* 的集群交换机 2 (CL2 或 C2) 的第一个集群 LIF。
* *n1_clus3* 是连接到节点 *n1* 的集群交换机 2 (CL2 或 C2) 的第二个 LIF。
* *n1_clus4* 是连接到节点 *n1* 的集群交换机 1 (CL1 或 C1) 的第二个 LIF。
* 10 GbE 和 40/100 GbE 端口的数量在参考配置文件 (RCF) 中定义，这些文件可在以下网址获取：link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco集群网络交换机参考配置文件下载"^] 。


.下一步是什么？
link:cn1610-prepare-to-migrate.html["做好迁移准备"]。
