---
permalink: switch-cisco-3232c/cn1610-replace-CL1.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: 您可以在AFF或FAS集群中使用Cisco Nexus 3232C 交换机作为集群交换机。 
---
= 将 CN1610 交换机 CL1 更换为 3232C 交换机 C1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照以下步骤将您的 CN1610 (CL1) 交换机更换为 Nexus 3232C (C1) 交换机。

.步骤
. 验证集群状态：
+
`network interface show -role cluster`

+
.显示示例
[%collapsible]
====
以下示例表明，所需的集群 LIF 已迁移到集群交换机 C2 上托管的相应集群端口：

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
(network interface show)
         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0b      false
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0c      false
         n2_clus1   up/up       10.10.0.5/24   n2       e0b      false
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0c      false

8 entries were displayed.
----
====
. 关闭所有节点上连接到 CL1 的节点端口：
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.显示示例
[%collapsible]
====
以下示例显示了节点 n1 和 n2 上特定端口的关闭情况：

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0a -up-admin false*
cluster::*> *network port modify -node n1 -port e0d -up-admin false*
cluster::*> *network port modify -node n2 -port e0a -up-admin false*
cluster::*> *network port modify -node n2 -port e0d -up-admin false*
----
====
. 关闭活动 3232C 交换机 C2 上的 ISL 端口 24、31 和 32。
+
有关Cisco命令的更多信息，请参阅以下位置列出的指南： https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 命令参考"^] 。

+
.显示示例
[%collapsible]
====
以下示例显示了在活动 3232C 交换机 C2 上关闭 ISL 24、31 和 32：

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *interface ethernet 1/24/1-4*
C2(config-if-range)# *shutdown*
C2(config-if-range)# *exit*
C2(config)# *interface ethernet 1/31-32*
C2(config-if-range)# *shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
C2#
----
====
. 拆下所有节点上连接到 CN1610 交换机 CL1 的电缆。
+
使用合适的线缆，必须将所有节点上断开的端口重新连接到 Nexus 3232C 交换机 C1。

. 从 Nexus 3232C C2 端口 e1/24 上移除 QSFP28 电缆。
+
您必须使用支持的Cisco QSFP28 光纤或直连电缆将 C1 上的端口 e1/31 和 e1/32 连接到 C2 上的端口 e1/31 和 e1/32。

. 恢复端口 24 的配置，并移除 C2 上的临时端口通道 2：
+
有关Cisco命令的更多信息，请参阅以下位置列出的指南： https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 命令参考"^] 。

+
.显示示例
[%collapsible]
====
以下示例展示了 `running-configuration`文件正在复制到 `startup-configuration`文件：

[listing, subs="+quotes"]
----
C2# configure
C2(config)# *no interface breakout module 1 port 24 map 10g-4x*
C2(config)# *no interface port-channel 2*
C2(config-if)# *interface e1/24*
C2(config-if)# *description 100GbE/40GbE Node Port*
C2(config-if)# *spanning-tree port type edge*
Edge port type (portfast) should only be enabled on ports connected to a single
host. Connecting hubs, concentrators, switches, bridges, etc...  to this
interface when edge port type (portfast) is enabled, can cause temporary bridging loops.
Use with CAUTION

Edge Port Type (Portfast) has been configured on Ethernet 1/24 but will only
have effect when the interface is in a non-trunking mode.

C2(config-if)# *spanning-tree bpduguard enable*
C2(config-if)# *mtu 9216*
C2(config-if-range)# *exit*
C2(config)# *exit*
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====
. 在活动 3232C 交换机 C2 上启用 ISL 端口 31 和 32。
+
有关Cisco命令的更多信息，请参阅以下位置列出的指南： https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 命令参考"^] 。

+
.显示示例
[%collapsible]
====
以下示例显示了 ISL 31 和 32 被引入到 3232C 交换机 C2 上：

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *interface ethernet 1/31-32*
C2(config-if-range)# *no shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====
. 确认 ISL 连接是否正常 `up`在 3232C 开关 C2 上。
+
有关Cisco命令的更多信息，请参阅以下位置列出的指南： https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 命令参考"^] 。

+
.显示示例
[%collapsible]
====
以下示例展示了 ISL 连接的验证过程。端口 Eth1/31 和 Eth1/32 指示 `(P)`这意味着两个 ISL 端口都是 `up`在端口通道中：

[listing, subs="+quotes"]
----
C1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        S - Switched    R - Routed
        U - Up (port-channel)
        M - Not in use. Min-links not met
------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
-----------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)

C2# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        S - Switched    R - Routed
        U - Up (port-channel)
        M - Not in use. Min-links not met
------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)
----
====
. 在所有节点上启用连接到新的 3232C 交换机 C1 的所有集群互连端口：
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.显示示例
[%collapsible]
====
以下示例显示了连接到新 3232C 交换机 C1 的所有集群互连端口的启动情况：

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0a -up-admin true*
cluster::*> *network port modify -node n1 -port e0d -up-admin true*
cluster::*> *network port modify -node n2 -port e0a -up-admin true*
cluster::*> *network port modify -node n2 -port e0d -up-admin true*
----
====
. 验证集群节点端口状态：
+
`network port show -role cluster`

+
.显示示例
[%collapsible]
====
以下示例显示了验证新 3232C 交换机 C1 上节点 n1 和 n2 的集群互连端口是否正常工作的输出。 `up` ：

[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
       (network port show)

Node: n1
                Broadcast              Speed (Mbps) Health   Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status   Health Status
----- --------- ---------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster    up    9000  auto/10000     -
e0b   cluster   cluster    up    9000  auto/10000     -
e0c   cluster   cluster    up    9000  auto/10000     -        -
e0d   cluster   cluster    up    9000  auto/10000     -        -

Node: n2
                Broadcast              Speed (Mbps) Health   Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status   Health Status
----- --------- ---------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster    up    9000  auto/10000     -
e0b   cluster   cluster    up    9000  auto/10000     -
e0c   cluster   cluster    up    9000  auto/10000     -
e0d   cluster   cluster    up    9000  auto/10000     -

8 entries were displayed.
----
====


.下一步是什么？
link:cn1610-complete-migration.html["完成迁移"]。
