---
permalink: switch-cisco-3232c/cn1610-migrate-to-3232c-overview.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: 在配置Cisco Nexus 3232c交换机之前、请查看此过程的概述以及术语。 
---
= 迁移要求
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C交换机可用作AFF 或FAS 集群中的集群交换机。通过集群交换机、您可以使用两个以上的节点构建ONTAP 集群。


NOTE: 操作步骤 要求同时使用 ONTAP 命令和 Cisco Nexus 3000 系列交换机命令；除非另有说明，否则使用 ONTAP 命令。

如有必要、请参见以下内容了解详细信息：

* http://support.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 问题描述 页面"^]
* http://support.netapp.com/NOW/download/software/cm_switches/["Cisco 以太网交换机问题描述 页面"^]
* http://hwu.netapp.com["Hardware Universe"^]




== CN1610迁移要求

集群交换机支持以下节点连接：

* NetApp CN1610 ：端口 0/1 到 0/12 （ 10 GbE ）
* Cisco Nexus 3232C ：端口 E1/1-30 （ 40 或 100 或 4x10GbE ）


集群交换机使用以下交换机间链路（ ISL ）端口。

* NetApp CN1610 ：端口 0/13 至 0/16 （ 10 GbE ）
* Cisco Nexus 3232C ：端口 1/31 至 32 （ 100GbE ）


[NOTE]
====
您必须在 Cisco Nexus 3232C 集群交换机上使用 4 根 10G 分支缆线。

====
下表显示了从 NetApp CN1610 交换机过渡到 Cisco Nexus 3232C 集群交换机时每个阶段所需的布线连接：

|===
| 阶段 | Description | 所需的缆线 


 a| 
初始
 a| 
CN1610 到 CN1610 （ SFP+ 到 SFP+ ）
 a| 
4 根 SFP+ 光纤或铜缆直连缆线



 a| 
过渡
 a| 
CN1610 到 3232C （ QSFP 到 SFP+ ）
 a| 
1 根 QSFP 和 4 根 SFP+ 光纤或铜缆分支缆线



 a| 
最终
 a| 
3232C 到 3232C （ QSFP 到 QSFP ）
 a| 
2 根 QSFP 光纤或铜缆直连缆线

|===
您必须已下载适用的参考配置文件（ Reference Configuration Files ， RCF ）。10 GbE 和 40/100 GbE 端口的数量在上提供的 RCF 中定义 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 集群网络交换机参考配置文件下载"^] 页面。

上列出了此操作步骤 支持的 ONTAP 和 NX-OS 版本 link:https://mysupport.netapp.com/NOW/download/software/cm_switches/.html["Cisco 以太网交换机页面"^]。

上列出了此操作步骤 支持的 ONTAP 和快速路径版本 link:http://support.netapp.com/NOW/download/software/cm_switches_ntap/.html["NetApp CN1601 和 CN1610 交换机页面"^]。

.关于所用示例
迁移过程中的示例使用四个节点：

* 两个节点使用四个10 GbE集群互连端口：* e0a*、* e0b*、* e0c*和* e0d*。
* 其他两个节点使用两根40 GbE集群互连光缆：* e4A*和* e4e*。
+
link:https://hwu.netapp.com/["_SIL_ Hardware Universe"^]提供了有关适用于您的平台的集群光缆的信息。



此操作步骤中的示例使用以下交换机和节点命名：

* 节点包括*n1*、*n2*、*n3*和*n4*。
* 根据不同版本的 ONTAP 软件，命令输出可能会有所不同。
* 要更换的CN1610交换机为*CL1*和*CL2*。
* 用于替代CN1610交换机的Nexus 3232C交换机为*C1*和*C2*。
* *n1_clus1*是连接到节点*n1*的集群交换机1 (CL1或C1)的第一个集群逻辑接口(LIF)。
* *n1_clus2*是连接到节点*n1*的集群交换机2 (CL2或C2)的第一个集群LIF。
* *n1_clus3*是连接到节点*n1*的集群交换机2 (CL2或C2)的第二个LIF。
* *n1_clus4*是连接到节点*n1*的集群交换机1 (CL1或C1)的第二个LIF。
* 10 GbE 和 40/100 GbE 端口的数量在上提供的参考配置文件（ RCF ）中定义 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 集群网络交换机参考配置文件下载"^] 页面。


.下一步是什么？
link:cn1610-prepare-to-migrate.html["准备迁移"](英文)
