---
permalink: switch-cisco-3232c/index.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: 您可以将 Cisco Nexus 3232C 交换机用作 AFF 或 FAS 集群中的集群交换机。 
---
= Cisco Nexus 3232C 交换机
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将 Cisco Nexus 3232C 交换机用作 AFF 或 FAS 集群中的集群交换机。

.概述
* 您可以安装交换机，从现有交换机迁移，更换交换机以及更新交换机上的 RCF 文件。
* 您可以在 Cisco Nexus 3232C 集群交换机上安装 NX-OS 和参考配置文件（ RCF ）。
* 您可以从双节点无交换机集群迁移到使用 Cisco Nexus 3232C 集群交换机的集群。
* 您可以更换 Cisco Nexus 3232C 集群或存储交换机。
* 您可以使用随交换机提供的自定义支架安装 Cisco Nexus 3232C 交换机（ X190100 ） NetApp 系统机柜，也可以将其安装在具有随交换机提供的标准支架的机架中。


下表列出了可用于 Cisco Nexus 3232C 交换机的文档。

|===


| 标题 | Description 


 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3232c/task-install-a-cisco-nexus-3232c-cluster-switch-and-pass-through-panel-in-a-netapp-cabinet.html["在 NetApp ® 机柜中安装 Cisco ® Nexus 3232C 集群交换机和直通面板 _"^]
 a| 
介绍如何将直通面板安装在系统机柜中，其中电源连接器位于机箱正面，配电单元位于机箱背面。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9336c-fx2/setup-switches.html["设置 Cisco ® Nexus 3232C 集群交换机 _"^]
 a| 
介绍如何设置和配置 Cisco Nexus 3232C 集群交换机。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3232c/task-install-nx-os-software-and-rcfs-on-cisco-nexus-3232-cluster-switches-running-ontap-9-4-and-later.html["安装 NX-OS 和参考配置文件（ RCF ） _"^]
 a| 
介绍如何在 Nexus 3232C 集群交换机上安装 NX-OS 和参考配置文件（ Reference Configuration Files ， RCF ）。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3232c/concept-migrate-from-a-cisco-5596-switch-to-a-cisco-nexus-3232c.html["_ 从 Cisco Nexus 5596 交换机迁移到 Cisco Nexus 3232C 交换机 _"^]
 a| 
介绍如何从使用旧版 Cisco 交换机的环境迁移到使用 Cisco 3232C 交换机的环境。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3232c/concept-migrate-a-cn1610-switch-to-a-cisco-nexus-3232c-cluster-switch.html["_ 从 CN1610 交换机迁移到 Cisco Nexus 3232C 交换机 _"^]
 a| 
介绍将 CN1610 交换机更换为 Cisco Nexus 3232C 集群交换机的操作步骤 。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3232c/concept-migrate-from-a-two-node-switchless-cluster-to-a-cluster-with-cisco-nexus-3232c-cluster-switches.html["_ 从双节点无交换机集群迁移 _"^]
 a| 
介绍如何使用 Cisco Nexus 3232C 集群交换机从双节点无交换机集群环境迁移到双节点有交换机环境。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3232c/concept-replace-a-cisco-nexus-3232c-cluster-switch.html["更换 Cisco Nexus 3232C 集群交换机 _"^]
 a| 
介绍用于更换集群中有故障的 Cisco Nexus 3232C 交换机以及下载交换机操作系统和参考配置文件的操作步骤 。



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3232c/concept-replace-a-cisco-nexus-3232c-storage-switch.html["更换 Cisco Nexus 3232C 存储交换机 _"^]
 a| 
介绍用于更换有故障的 Cisco Nexus 3232C 存储交换机以及下载交换机操作系统和参考配置文件的操作步骤 。

|===