---
permalink: switch-cisco-3232c/install-rcf-software-3232c.html 
sidebar: sidebar 
keywords: rcf, install, cluster switch, cisco nexus 3232c 
summary: '初始设置后，在 Cisco Nexus 3232C 集群交换机上安装参考配置文件 (RCF)。' 
---
= 在 Cisco Nexus 3232C 集群交换机上安装 RCF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
初始设置后，在 Cisco Nexus 3232C 集群交换机上安装参考配置文件 (RCF)。RCF 定义了集群操作所需的端口分配和网络设置。

.开始之前
请核实以下安装和连接：

* 交换机配置的当前备份。
* 一个功能齐全的集群（日志中没有错误或类似问题）。
* 当前的RCF。
* 与交换机的控制台连接，安装 RCF 时需要。


.关于此任务
此过程需要同时使用 ONTAP 命令和 Cisco Nexus 3000 系列交换机命令；除非另有说明，否则使用 ONTAP 命令。

在此过程中，无需操作交换机间链路 (ISL)。这是出于设计考虑，因为 RCF 版本更改可能会暂时影响 ISL 连接。为实现无中断集群操作，以下过程会在目标交换机上执行步骤的同时，将所有集群 LIF 迁移到运行中的配对交换机。

请务必完成 link:prepare-install-cisco-nexus-3232c.html["准备安装 NX-OS 和 RCF"] 中的步骤，然后按照以下步骤操作。



[[step-1-install-the-rcf-on-the-switches]]
== 步骤 1：在交换机上安装 RCF

. 使用 SSH 或串行控制台登录到交换机 cs2。
. 使用以下传输协议之一将 RCF 复制到交换机 cs2 的 bootflash：FTP、TFTP、SFTP 或 SCP。有关 Cisco 命令的更多信息，请参见 link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Cisco Nexus 3000 系列 NX-OS 命令参考"^] 中的相应指南。
+
.显示示例
[%collapsible]
====
此示例显示使用 TFTP 将 RCF 复制到交换机 cs2 上的 bootflash：

[listing, subs="+quotes"]
----
cs2# *copy tftp: bootflash: vrf management*
Enter source filename: *Nexus_3232C_RCF_v1.6-Cluster-HA-Breakout.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 将之前下载的 RCF 文件应用到启动闪存中。
+
有关 Cisco 命令的更多信息，请参见 link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Cisco Nexus 3000 系列 NX-OS 命令参考"^]

+
.显示示例
[%collapsible]
====
此示例显示了在交换机 cs2 上安装的 RCF 文件 `Nexus_3232C_RCF_v1.6-Cluster-HA-Breakout.txt`：

[listing, subs="+quotes"]
----
cs2# *copy Nexus_3232C_RCF_v1.6-Cluster-HA-Breakout.txt running-config echo-commands*
----
====
+
[NOTE]
====
请务必仔细阅读 RCF 的 *安装说明*、*重要说明* 和 *横幅* 部分。您必须阅读并遵循这些说明以确保交换机的正确配置和操作。

====
. 检查 `show banner motd`命令的横幅输出。您必须阅读并遵循*重要说明*下的说明，以确保交换机配置和操作正确。
. 请确认 RCF 文件是否为最新版本：
+
`show running-config`

+
检查输出结果以验证是否拥有正确的 RCF 时，请确保以下信息正确：

+
** RCF横幅
** 节点和端口设置
** 定制
+
输出结果会根据您的网站配置而有所不同。检查端口设置，并参考发行说明，了解您安装的 RCF 版本是否有任何特定更改。



. 重新应用之前对交换机配置所做的所有自定义设置。有关所需的任何进一步更改的详细信息，请参阅 link:cabling-considerations-3232c.html["审查布线和配置注意事项"]。
. 保存基本配置详细信息 `write_erase.cfg`启动闪存上的文件。
+
[NOTE]
====
确保配置以下内容： * 用户名和密码 * 管理 IP 地址 * 默认网关 * 交换机名称

====
+
`cs2# show run | section "switchname" > bootflash:write_erase.cfg`

+
`cs2# show run | section "hostname" >> bootflash:write_erase.cfg`

+
`cs2# show run | i "username admin password" >> bootflash:write_erase.cfg`

+
`cs2# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs2# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

. 安装 RCF 1.12 及更高版本时，请运行以下命令：
+
`cs2# echo "hardware access-list tcam region racl-lite 512" >> bootflash:write_erase.cfg`

+
`cs2# echo "hardware access-list tcam region qos 256" >> bootflash:write_erase.cfg`

+
有关更多详细信息，请参见知识库文章 link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["如何在保持远程连接的情况下清除Cisco互连交换机上的配置"^]。

. 确认 `write_erase.cfg`文件已按预期填充：
+
`show file bootflash:write_erase.cfg`

. 问题 `write erase`清除当前已保存配置的命令：
+
`cs2# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. 将之前保存的基本配置复制到启动配置中。
+
`cs2# *copy bootflash:write_erase.cfg startup-config*`

. 重启交换机 cs2：
+
`cs2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 在交换机 cs1 上重复步骤 1 至 12。
. 将ONTAP集群中所有节点的集群端口连接到交换机 cs1 和 cs2。




[[step-2-verify-the-switch-connections]]
== 步骤 2：验证交换机连接

. 确认连接到集群端口的交换机端口已启用。
+
`show interface brief | grep up`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show interface brief | grep up*
.
.
Eth1/1/1      1       eth  access up      none                    10G(D) --
Eth1/1/2      1       eth  access up      none                    10G(D) --
Eth1/7        1       eth  trunk  up      none                   100G(D) --
Eth1/8        1       eth  trunk  up      none                   100G(D) --
.
.
----
====
. 验证 cs1 和 cs2 之间的 ISL 连接是否正常：
+
`show port-channel summary`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)
cs1#
----
====
. 确认集群 LIF 已恢复到其原端口：
+
`network interface show -role cluster`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical            Status     Network            Current             Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node                Port    Home
----------- ------------------ ---------- ------------------ ------------------- ------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.3.4/23     cluster1-01         e0d     true
            cluster1-01_clus2  up/up      169.254.3.5/23     cluster1-01         e0d     true
            cluster1-02_clus1  up/up      169.254.3.8/23     cluster1-02         e0d     true
            cluster1-02_clus2  up/up      169.254.3.9/23     cluster1-02         e0d     true
            cluster1-03_clus1  up/up      169.254.1.3/23     cluster1-03         e0b     true
            cluster1-03_clus2  up/up      169.254.1.1/23     cluster1-03         e0b     true
            cluster1-04_clus1  up/up      169.254.1.6/23     cluster1-04         e0b     true
            cluster1-04_clus2  up/up      169.254.1.7/23     cluster1-04         e0b     true
8 entries were displayed.
cluster1::*>
----
====
+
如果任何集群 LIF 尚未返回其主端口，请手动还原它们：
`network interface revert -vserver <vserver_name> -lif <lif_name>`

. 验证集群是否运行正常：
+
`cluster show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
4 entries were displayed.
cluster1::*>
----
====




[[step-3-setup-your-ontap-cluster]]
== 步骤 3：设置您的 ONTAP 集群

NetApp建议您使用系统管理器来设置新的集群。

System Manager为集群设置和配置提供了简单易用的工作流程，包括分配节点管理IP地址、初始化集群、创建本地层、配置协议和配置初始存储。

有关设置说明，请参见 https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["使用 System Manager 在新集群上配置ONTAP"]。

.下一步是什么？
安装完 RCF 后，您可以…… link:configure-ssh-keys.html["验证 SSH 配置"]。
