---
permalink: switch-cisco-3232c/migrate-requirements-3232c.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: 当您用Cisco Nexus 3232C 集群交换机替换 CN1610 集群交换机时，您必须了解某些配置信息、端口连接和布线要求。 
---
= Cisco Nexus 3232C 集群交换机的迁移要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在迁移到Cisco Nexus 3232C 集群交换机之前，请先查看配置信息、端口连接和布线要求。



== CN1610迁移要求

集群交换机支持以下节点连接：

* NetApp CN1610：端口 0/1 至 0/12 (10 GbE)
* Cisco Nexus 3232C：端口 e1/1-30（40 或 100 或 4x10GbE）


集群交换机使用以下交换机间链路 (ISL) 端口。

* NetApp CN1610：端口 0/13 至 0/16 (10 GbE)
* Cisco Nexus 3232C：端口 1/31-32 (100GbE)


[NOTE]
====
在Cisco Nexus 3232C 集群交换机上必须使用 4x10G 分支电缆。

====
下表显示了从NetApp CN1610 交换机过渡到Cisco Nexus 3232C 集群交换机时，每个阶段所需的布线连接：

|===
| 阶段 | 描述 | 所需电缆 


 a| 
初始
 a| 
CN1610 至 CN1610（SFP+ 至 SFP+）
 a| 
4根SFP+光纤或铜缆直连电缆



 a| 
过渡
 a| 
CN1610 至 3232C（QSFP 至 SFP+）
 a| 
1根QSFP和4根SFP+光纤或铜缆分支电缆



 a| 
终稿
 a| 
3232C 至 3232C（QSFP 至 QSFP）
 a| 
2根QSFP光纤或铜缆直连电缆

|===
您必须已下载适用的参考配置文件（RCF）。  10 GbE 和 40/100 GbE 端口的数量在 RCF 中定义。link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco集群网络交换机参考配置文件下载"^] 。

此流程支持的ONTAP和 NX-OS 版本列于此处。link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco以太网交换机"^] 。

此流程支持的ONTAP和 FASTPATH 版本列于此处link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 和 CN1610 交换机"^]。



== CN5596 要求

集群交换机使用以下端口连接到节点：

* 端口 e1/1-40 (10 GbE)：Nexus 5596
* 端口 e1/1-30 (10/40/100 GbE)：Nexus 3232C
+
** 集群交换机使用以下交换机间链路 (ISL) 端口：


* 端口 e1/41-48 (10 GbE)：Nexus 5596
* 端口 e1/31-32 (40/100 GbE)：Nexus 3232C
+
** 这link:https://hwu.netapp.com/["硬件宇宙"^]包含有关 Nexus 3232C 交换机支持的布线信息：


* 具有 10 GbE 集群连接的节点需要 QSFP 转 SFP+ 光纤分支电缆或 QSFP 转 SFP+ 铜缆分支电缆。
* 具有 40/100 GbE 集群连接的节点需要支持 QSFP/QSFP28 光模块，并配备光纤电缆或 QSFP/QSFP28 铜缆直连电缆。
+
** 集群交换机使用相应的ISL电缆：


* 起始端：Nexus 5596（SFP+ 至 SFP+）
+
** 8根SFP+光纤或铜缆直连线缆


* 过渡期：Nexus 5596 至 Nexus 3232C（QSFP 至 4xSFP+ 突破）
+
** 1根QSFP转SFP+光纤分支线或铜缆分支线


* 最终版：Nexus 3232C 至 Nexus 3232C（QSFP28 至 QSFP28）
+
** 2根QSFP28光纤或铜缆直连电缆
+
*** 在 Nexus 3232C 交换机上，您可以将 QSFP/QSFP28 端口操作为 40/100 千兆以太网或 4 x 10 千兆以太网模式。
+
默认情况下，40/100 千兆以太网模式下有 32 个端口。这 40 个千兆以太网端口采用二元组命名规则进行编号。例如，第二个 40 千兆以太网端口编号为 1/2。将 40 千兆以太网配置更改为 10 千兆以太网的过程称为 _breakout_，将 10 千兆以太网配置更改为 40 千兆以太网的过程称为 _breakin_。当您将 40/100 千兆以太网端口拆分为 10 千兆以太网端口时，生成的端口将使用三元组命名规则进行编号。例如，第二个 40/100 千兆以太网端口的分线端口编号为 1/2/1、1/2/2、1/2/3 和 1/2/4。

*** Nexus 3232C 交换机的左侧有 2 个 SFP+ 端口，分别称为 1/33 和 1/34。
*** 您已将 Nexus 3232C 交换机上的一些端口配置为以 10 GbE 或 40/100 GbE 运行。
+
[NOTE]
====
您可以使用以下方法将前六个端口划分为 4x10 GbE 模式： `interface breakout module 1 port 1-6 map 10g-4x`命令。同样，您可以使用以下方法将前六个 QSFP+ 端口从分支配置中重新分组： `no interface breakout module 1 port 1-6 map 10g-4x`命令。

====
*** 您已完成规划、迁移，并阅读了有关从节点到 Nexus 3232C 集群交换机的 10 GbE 和 40/100 GbE 连接的必要文档。
*** 此流程支持的ONTAP和 NX-OS 版本为：link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco以太网交换机"^] 。





