---
permalink: switch-cisco-3232c/migrate-from-two-node-switchless-cluster.html 
sidebar: sidebar 
keywords: migrate, two-node cluster, switchless, cisco nexus 3232c 
summary: 使用 Cisco Nexus 3232C 集群交换机从双节点无交换机集群迁移到有交换机集群。此操作不会造成中断。 
---
= 从双节点无交换机集群迁移到 Cisco Nexus 3232C 集群交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 Cisco Nexus 3232C 集群交换机从双节点无交换机集群迁移到有交换机集群。此操作不会造成中断。



[[review-requirements]]
== 审查要求

.开始之前
请核实以下安装和连接：

* 端口可用于节点连接。集群交换机使用交换机间链路 (ISL) 端口 e1/31-32。
* 您有适当的集群连接电缆：
+
** 具有 10 GbE 集群连接的节点需要带有分支光纤电缆的 QSFP 光模块或 QSFP 至 SFP+ 铜分支电缆。
** 具有 40/100 GbE 集群连接的节点需要支持带有光纤电缆的 QSFP/QSFP28 光模块或 QSFP/QSFP28 铜缆直连电缆。
** 集群交换机需要适当的 ISL 电缆：2x QSFP28 光纤或铜线直连电缆。


* 配置已正确设置并正常运行。
+
两个节点必须在双节点无交换机集群设置中连接并运行。

* 集群所有端口均处于*开启*状态。
* 支持 Cisco Nexus 3232C 集群交换机。
* 现有集群网络配置如下：
+
** 两台交换机上的冗余且功能齐全的 Nexus 3232C 集群基础架构
** 交换机上的最新 RCF 和 NX-OS 版本
** 两台交换机上的管理连接
** 控制台（Console）访问两台交换机
** 所有处于 *up* 状态且未经迁移的集群逻辑接口 (LIF)
** 交换机的初始定制
** 所有 ISL 端口均已启用并完成布线




.关于示例
本流程中的示例使用以下开关和节点命名规则：

* Nexus 3232C 集群交换机，C1 和 C2。
* 节点为 n1 和 n2。


此过程中的示例使用两个节点，每个节点利用两个 40 GbE 集群互连端口 e4a 和 e4e。link:https://hwu.netapp.com/["Hardware Universe"^] 包含有关平台上集群端口的详细信息。

* n1_clus1 是节点 n1 连接到集群交换机 C1 的第一个集群逻辑接口（LIF）。
* n1_clus2 是节点 n1 连接到集群交换机 C2 的第一个集群 LIF。
* n2_clus1 是节点 n2 连接到集群交换机 C1 的第一个集群 LIF。
* n2_clus2 是节点 n2 连接到集群交换机 C2 的第二个集群 LIF。
* 10 GbE 和 40/100 GbE 端口的数量在参考配置文件 (RCF) 中定义，该文件可从 link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® 集群网络交换机参考配置文件下载"^] 获取。


[NOTE]
====
此过程需要同时使用 ONTAP 命令和 Cisco Nexus 3000 系列交换机命令；除非另有说明，否则使用 ONTAP 命令。

====


[[step-1-display-and-migrate-physical-and-logical-ports]]
== 步骤 1：显示和迁移物理和逻辑端口

. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ 是维护窗口的持续时间，单位为小时。

+
[NOTE]
====
AutoSupport消息会通知技术支持此维护任务，以便在维护窗口期间抑制自动创建案例。

====
. 确定每个集群接口的管理或运行状态：
+
.. 显示网络端口属性：
+
`network port show -role cluster`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -
4 entries were displayed.
----
====
.. 显示有关逻辑接口及其指定归属节点的信息：
+
`network interface show -role cluster`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ---
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true

4 entries were displayed.
----
====
.. 使用 advanced privilege 命令验证是否已启用无交换机集群检测：
+
`network options detect-switchless-cluster show``

+
.显示示例
[%collapsible]
====
以下示例中的输出显示启用了无交换机集群检测：

[listing, subs="+quotes"]
----
cluster::*> *network options detect-switchless-cluster show*
Enable Switchless Cluster Detection: true
----
====


. 验证是否在新的 3232C 交换机上安装了适当的 RCF 和映像，并进行任何必要的站点自定义，例如添加用户、密码和网络地址。
+
此时必须准备好两台交换机。如果您需要升级 RCF 和映像软件，则必须执行以下步骤：

+
.. 转到 NetApp 支持站点上的 _Cisco Ethernet Switches_ 页面。
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco以太网交换机"^]

.. 在该页面的表格中记下您的交换机和所需的软件版本。
.. 下载适当版本的 RCF。
.. 点击*描述*页面上的*CONTINUE*，接受许可协议，然后按照*下载*页面上的说明下载 RCF。
.. 下载合适版本的映像软件。
+
link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco 集群和管理网络交换机参考配置文件下载"^]。



. 点击*描述*页面上的*CONTINUE*，接受许可协议，然后按照*下载*页面上的说明下载 RCF。
. 在 Nexus 3232C 交换机 C1 和 C2 上，禁用所有面向节点的端口 C1 和 C2，但不要禁用 ISL 端口 e1/31-32。
+
有关 Cisco 命令的更多信息，请参见 link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 命令参考"^] 中列出的指南。

+
.显示示例
[%collapsible]
====
以下示例显示了使用 RCF `NX3232_RCF_v1.0_24p10g_24p100g.txt` 中支持的配置在 Nexus 3232C 集群交换机 C1 和 C2 上禁用端口 1 到 30 的操作：

[listing, subs="+quotes"]
----
C1# copy running-config startup-config
[########################################] 100% Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit
C2# copy running-config startup-config
[########################################] 100% Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. 使用支持的电缆将 C1 上的端口 1/31 和 1/32 连接到 C2 上的相同端口。
. 确认 ISL 端口在 C1 和 C2 上运行：
+
`show port-channel summary`

+
有关 Cisco 命令的更多信息，请参见 link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 命令参考"^] 中列出的指南。

+
.显示示例
[%collapsible]
====
以下示例显示了用于验证 ISL 端口在 C1 和 C2 上是否正常运行的 Cisco `show port-channel summary` 命令：

[listing, subs="+quotes"]
----
C1# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
      Port-
Group Channel      Type   Protocol  Member Ports
-------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------

Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. 显示交换机上相邻设备的列表。
+
有关 Cisco 命令的更多信息，请参见 link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 命令参考"^] 中列出的指南。

+
.显示示例
[%collapsible]
====
以下示例显示了用于显示交换机上相邻设备的 Cisco 命令 `show cdp neighbors`：

[listing, subs="+quotes"]
----
C1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3232C  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3232C  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
----
====
. 显示每个节点上的集群端口连接：
+
`network device-discovery show`

+
.显示示例
[%collapsible]
====
以下示例显示了双节点无交换机集群配置的集群端口连接：

[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
====
. 将 n1_clus1 和 n2_clus1 LIF 迁移到其目标节点的物理端口：
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ source-node _source-node-name_ -destination-port _destination-port-name_`

+
.显示示例
[%collapsible]
====
必须为每个本地节点执行命令，如以下示例所示：

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e4e*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e4e*
----
====




[[step-2-shut-down-the-reassigned-lifs-and-disconnect-the-cables]]
== 步骤 2：关闭重新分配的 LIF 并断开电缆

. 验证集群接口是否已成功迁移：
+
`network interface show -role cluster`

+
.显示示例
[%collapsible]
====
以下示例显示迁移完成后，n1_clus1 和 n2_clus1 LIF 的"Is Home"状态已变为"false"：

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
 4 entries were displayed.
----
====
. 关闭步骤 9 中迁移的 n1_clus1 和 n2_clus1 LIF 的集群端口：
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.显示示例
[%collapsible]
====
必须为每个端口执行命令，如以下示例所示：

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin false*
cluster::*> *network port modify -node n2 -port e4a -up-admin false*
----
====
. 验证远程集群接口的连接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`执行命令以启动集群连接性检查，然后显示详细信息：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*运行程序前请等待几秒钟 `show`显示详细信息的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.所有ONTAP版本
--
对于所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`检查连接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step4]] 断开节点 n1 上 e4a 的电缆。
+
您可以参考运行配置，使用 Nexus 3232C 交换机支持的电缆将交换机 C1 上的第一个 40 GbE 端口（本示例中的端口 1/7）连接到 n1 上的 e4a。





[[step-3-enable-the-cluster-ports]]
== 步骤 3：启用集群端口

. 断开节点 n2 上的电缆与 e4a 的连接。
+
您可以参考运行配置，使用支持的缆线将 e4a 连接到 C1 上的下一个可用 40 GbE 端口，即端口 1/8。

. 启用 C1 上所有面向节点的端口。
+
有关 Cisco 命令的更多信息，请参见 link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 命令参考"^] 中列出的指南。

+
.显示示例
[%collapsible]
====
以下示例显示了使用 RCF `NX3232_RCF_v1.0_24p10g_26p100g.txt` 中支持的配置在 Nexus 3232C 集群交换机 C1 和 C2 上启用端口 1 到 30 的情况：

[listing, subs="+quotes"]
----
C1# *configure*
C1(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C1(config-if-range)# *no shutdown*
C1(config-if-range)# *exit*
C1(config)# *exit*
----
====
. 在每个节点上启用第一个集群端口 e4a：
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin true*
cluster::*> *network port modify -node n2 -port e4a -up-admin true*
----
====
. 验证两个节点上的集群是否都处于运行状态：
+
`network port show -role cluster`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

4 entries were displayed.
----
====
. 对于每个节点，还原所有已迁移的集群互连 LIF：
+
`network interface revert -vserver cluster -lif _lif-name_`

+
.显示示例
[%collapsible]
====
必须将每个 LIF 单独还原到其主端口，如以下示例所示：

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver cluster -lif n1_clus1*
cluster::*> *network interface revert -vserver cluster -lif n2_clus1*
----
====
. 确认所有 LIF 现在都已恢复到其主端口：
+
`network interface show -role cluster`

+
 `Current Port` 列中列出的所有端口的  `Is Home` 列均应显示值  `true`。如果显示的值为  `false`，则表示该端口尚未恢复。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====




[[step-4-enable-the-reassigned-lifs]]
== 步骤 4：启用重新分配的 LIF

. 显示每个节点上的集群端口连接：
+
`network device-discovery show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    n1                  e4e              FAS9000
----
====
. 将 clus2 迁移到每个节点控制台上的端口 e4a：
+
`network interface migrate cluster -lif _lif-name_ -source-node _source-node-name_ -destination-node _destination-node-name_ -destination-port _destination-port-name_`

+
.显示示例
[%collapsible]
====
必须将每个 LIF 单独迁移到其主端口，如以下示例所示：

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus2 -source-node n1
-destination-node n1 -destination-port e4a*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus2 -source-node n2
-destination-node n2 -destination-port e4a*
----
====
. 关闭两个节点上的集群端口 clus2 LIF：
+
`network port modify`

+
.显示示例
[%collapsible]
====
以下示例显示了将指定的端口设置为 `false`，关闭两个节点上的端口：

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin false*
cluster::*> *network port modify -node n2 -port e4e -up-admin false*
----
====
. 验证集群 LIF 状态：
+
`network interface show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
====
. 断开节点 n1 上 e4e 的电缆。
+
您可以参考运行配置，使用适用于 Nexus 3232C 交换机型号的相应电缆，将交换机 C2 上的第一个 40 GbE 端口（本示例中的端口 1/7）连接到节点 n1 上的 e4e。

. 断开节点 n2 上 e4e 的电缆。
+
您可以参考运行配置，使用适用于 Nexus 3232C 交换机型号的相应电缆将 e4e 连接到 C2 上的下一个可用 40 GbE 端口（端口 1/8）。

. 启用 C2 上所有面向节点的端口。
+
.显示示例
[%collapsible]
====
以下示例显示了在 Nexus 3132Q-V 集群交换机 C1 和 C2 上使用 RCF `NX3232C_RCF_v1.0_24p10g_26p100g.txt` 支持的配置启用端口 1 到 30：

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C2(config-if-range)# *no shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
----
====
. 在每个节点上启用第二个集群端口 e4e：
+
`network port modify`

+
.显示示例
[%collapsible]
====
以下示例显示了每个节点上启动的第二个集群端口 e4e：

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin true*
cluster::*> *network port modify -node n2 -port e4e -up-admin true*s
----
====
. 对于每个节点，还原所有迁移的集群互连 LIF： `network interface revert`
+
.显示示例
[%collapsible]
====
以下示例显示迁移的 LIF 还原到其主端口。

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver Cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus2*
----
====
. 验证所有集群互连端口现在都已恢复到其主端口：
+
`network interface show -role cluster`

+
 `Current Port` 列中列出的所有端口的  `Is Home` 列均应显示值  `true`。如果显示的值为  `false`，则表示该端口尚未恢复。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 验证所有集群互连端口均处于 `up`状态：
+
`network port show -role cluster`

. 显示每个集群端口连接到每个节点所经过的集群交换机端口号： `network device-discovery show`
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1          /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    C2                  Ethernet1/7      N3K-C3232C
n2          /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    C2                  Ethernet1/8      N3K-C3232C
----
====
. 显示发现和监控的集群交换机：
+
`system cluster-switch show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *system cluster-switch show*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.101      NX3232CV
Serial Number: FOX000001
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP

C2                          cluster-network     10.10.1.102      NX3232CV
Serial Number: FOX000002
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP 2 entries were displayed.
----
====
. 验证无交换机集群检测是否已将无交换机集群选项更改为禁用：
+
`network options switchless-cluster show`

. 验证远程集群接口的连接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`执行命令以启动集群连接性检查，然后显示详细信息：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*运行程序前请等待几秒钟 `show`显示详细信息的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.所有ONTAP版本
--
对于所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`检查连接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step16]] 如果您禁止自动创建案例，请通过调用 AutoSupport 消息重新启用它：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.下一步是什么？
link:../switch-cshm/config-overview.html["配置交换机健康监控"]。
