---
permalink: switch-cisco-3232c/migrate-requirements-3232c.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: 将 CN1610 集群交换机替换为 Cisco Nexus 3232C 集群交换机时，必须了解某些配置信息、端口连接和布线要求。 
---
= Cisco Nexus 3232C 集群交换机的迁移要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在迁移到 Cisco Nexus 3232C 集群交换机之前，请查看配置信息、端口连接和布线要求。



[[cn1610-migrate-requirements]]
== CN1610 迁移要求

集群交换机支持以下节点连接：

* NetApp CN1610：端口 0/1 至 0/12（10 GbE）
* Cisco Nexus 3232C：端口 e1/1-30（40 或 100 或 4x10GbE）


集群交换机使用以下交换机间链路 (ISL) 端口。

* NetApp CN1610：端口 0/13 至 0/16（10 GbE）
* Cisco Nexus 3232C：端口 1/31-32 (100GbE)


[NOTE]
====
您必须在 Cisco Nexus 3232C 集群交换机上使用 4x10G 分支电缆。

====
下表显示了从 NetApp CN1610 交换机过渡到 Cisco Nexus 3232C 集群交换机时每个阶段所需的布线连接：

|===
| 阶段 | 描述 | 所需电缆 


 a| 
初始
 a| 
CN1610 至 CN1610（SFP+ 至 SFP+）
 a| 
4 根 SFP+ 光纤或铜质直连电缆



 a| 
过渡
 a| 
CN1610 至 3232C（QSFP 至 SFP+）
 a| 
1 根 QSFP 和 4 根 SFP+ 光纤或铜分支电缆



 a| 
终稿
 a| 
3232C 至 3232C（QSFP 至 QSFP）
 a| 
2根QSFP光纤或铜质直连电缆

|===
您必须已下载适用的参考配置文件 (RCF)。10 GbE 和 40/100 GbE 端口的数量在 link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® 集群网络交换机参考配置文件下载"^] 上提供的 RCF 中定义。

本程序中支持的 ONTAP 和 NX-OS 版本列于 link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco以太网交换机"^]。

此过程中支持的 ONTAP 和 FASTPATH 版本列于 link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 和 CN1610 开关"^]。



[[cn5596-requirements]]
== CN5596 要求

群集交换机使用以下端口连接到节点：

* 端口 e1/1-40 (10 GbE): Nexus 5596
* 端口 e1/1-30 (10/40/100 GbE): Nexus 3232C
+
** 集群交换机使用以下交换机间链路 (ISL) 端口：


* 端口e1/41-48 (10 GbE): Nexus 5596
* 端口e1/31-32 (40/100 GbE): Nexus 3232C
+
** link:https://hwu.netapp.com/["Hardware Universe"^] 包含有关支持的 Nexus 3232C 交换机布线的信息：


* 具有 10 GbE 集群连接的节点需要 QSFP 到 SFP+ 光纤分支电缆或 QSFP 到 SFP+ 铜分支电缆。
* 具有 40/100 GbE 集群连接的节点需要支持带有光纤电缆或 QSFP/QSFP28 铜缆直连电缆的 QSFP/QSFP28 光模块。
+
** 集群交换机使用适当的ISL布线：


* 初始：Nexus 5596（SFP+ 到 SFP+）
+
** 8 根 SFP+ 光纤或铜质直连电缆


* 临时：Nexus 5596 到 Nexus 3232C（QSFP 到 4xSFP+ 分支）
+
** 1 根 QSFP 至 SFP+ 光纤分支或铜分支电缆


* 最终：Nexus 3232C 至 Nexus 3232C（QSFP28 至 QSFP28）
+
** 2根QSFP28光纤或铜质直连电缆
+
*** 在 Nexus 3232C 交换机上，您可以在 40/100 千兆以太网或 4 x10 千兆以太网模式下操作 QSFP/QSFP28 端口。
+
默认情况下，40/100 千兆以太网模式下有 32 个端口。这 40 个千兆以太网端口按 2 元组命名约定编号。例如，第二个 40 千兆以太网端口编号为 1/2。将配置从 40 千兆以太网改为 10 千兆以太网的过程称为 _breakout_，将配置从 10 千兆以太网改为 40 千兆以太网的过程称为 _breakin_。当您将 40/100 千兆以太网端口分解为 10 千兆以太网端口时，将使用 3 元组命名约定对生成的端口进行编号。例如，第二个 40/100 千兆以太网端口的分支端口编号为 1/2/1、1/2/2、1/2/3 和 1/2/4。

*** Nexus 3232C 交换机的左侧有 2 个 SFP+ 端口，称为 1/33 和 1/34。
*** 您已将 Nexus 3232C 交换机上的一些端口配置为以 10 GbE 或 40/100 GbE 运行。
+
[NOTE]
====
您可以使用 `interface breakout module 1 port 1-6 map 10g-4x`命令将前六个端口分解为 4x10 GbE 模式。同样，您可以使用 `no interface breakout module 1 port 1-6 map 10g-4x`命令从分组配置中重组前六个 QSFP+ 端口。

====
*** 您已经完成了从节点到 Nexus 3232C 集群交换机的 10 GbE 和 40/100 GbE 连接的规划、迁移和阅读所需的文档。
*** 此过程中支持的 ONTAP 和 NX-OS 版本位于 link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco以太网交换机"^]。





