---
permalink: switch-cisco-3232c/setup-switch.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: 如果您还没有所需的配置信息和文档，则需要在设置集群和管理网络交换机之前收集这些信息。 
---
= 配置3232C集群交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照此操作步骤 设置和配置Cisco Nexus 3232C交换机。

.您需要的内容
* 访问安装站点上的HTTP、FTP或TFTP服务器、以下载适用的NX-OS和参考配置文件(RCF)版本。
* 适用的NX-OS版本、从下载 https://software.cisco.com/download/home["Cisco软件下载"^] 页面。
* 所需的集群网络和管理网络交换机文档。
+
请参见 link:required-documentation-3232c.html["所需文档"] 有关详细信息 ...

* 所需的控制器文档和ONTAP 文档。
+
https://netapp.com/us/documenation/index.aspx["NetApp 文档"^]

* 适用的许可证、网络和配置信息以及缆线。
* 已完成布线工作表。
* 适用的NetApp集群网络和管理网络RCF、从NetApp 支持站点 下载、网址为 http://mysupport.netapp.com/["mysupport.netapp.com"^] 用于接收的交换机。所有 Cisco 集群网络和管理网络交换机均采用标准的 Cisco 出厂默认配置。这些交换机还具有最新版本的NX-OS软件、但未加载RCF。


.步骤
. 将集群网络和管理网络交换机和控制器装入机架。
+
[cols="1,2"]
|===
| 如果要安装 ... | 那么 ... 


 a| 
NetApp 系统机柜中的 Cisco Nexus 3232C
 a| 
有关在 NetApp 机柜中安装交换机的说明，请参见《在 NetApp 机柜中安装 Cisco Nexus 3232C 集群交换机和直通面板》指南。



 a| 
电信机架中的设备
 a| 
请参见交换机硬件安装指南和 NetApp 安装和设置说明中提供的过程。

|===
. 使用已完成的布线工作表将集群网络和管理网络交换机连接到控制器。
. 打开集群网络以及管理网络交换机和控制器的电源。
. 对集群网络交换机执行初始配置。
+
首次启动交换机时、请针对以下初始设置问题提供适当的回答。您站点的安全策略定义了响应和服务，以实现：

+
[cols="1,2"]
|===
| 提示符 | 响应 


 a| 
是否中止自动配置并继续正常设置？（是 / 否）
 a| 
请回答 * 是 * 。默认值为 no



 a| 
是否要强制实施安全密码标准？（是 / 否）
 a| 
请回答 * 是 * 。默认值为 yes 。



 a| 
输入管理员的密码。
 a| 
默认密码为 "`admin` " ；您必须创建一个新的强密码。可以拒绝弱密码。



 a| 
是否要进入基本配置对话框？（是 / 否）
 a| 
在交换机的初始配置时，使用 * 是 * 进行响应。



 a| 
是否创建其他登录帐户？（是 / 否）
 a| 
您的问题解答取决于站点的策略，取决于备用管理员。默认值为 * 否 * 。



 a| 
是否配置只读 SNMP 社区字符串？（是 / 否）
 a| 
请使用 * 否 * 回答。默认值为 no



 a| 
是否配置读写 SNMP 社区字符串？（是 / 否）
 a| 
请使用 * 否 * 回答。默认值为 no



 a| 
输入交换机名称。
 a| 
交换机名称限制为 63 个字母数字字符。



 a| 
是否继续进行带外（ mgmt0 ）管理配置？（是 / 否）
 a| 
在该提示符处，使用 * 是 * （默认值）进行响应。在 mgmt0 IPv4 address ：提示符处，输入 IP 地址： ip_address



 a| 
是否配置 default-gateway ？（是 / 否）
 a| 
请回答 * 是 * 。在 default-gateway ：提示符的 IPv4 地址处，输入 default_gateway 。



 a| 
是否配置高级 IP 选项？（是 / 否）
 a| 
请使用 * 否 * 回答。默认值为 no



 a| 
是否启用 telnet 服务？（是 / 否）
 a| 
请使用 * 否 * 回答。默认值为 no



 a| 
是否已启用 SSH 服务？（是 / 否）
 a| 
请回答 * 是 * 。默认值为 yes 。


NOTE: 使用以太网交换机运行状况监控器(CSHM)收集日志功能时、建议使用SSH。为了增强安全性，还建议使用 SSHv2 。



 a| 
输入要生成的 SSH 密钥类型（ DSA/RSA/RSA/rsa1 ）。
 a| 
默认值为 * RSA * 。



 a| 
输入密钥位数（ 1024-2048 ）。
 a| 
输入密钥位数、范围为1024-2048。



 a| 
是否配置 NTP 服务器？（是 / 否）
 a| 
请使用 * 否 * 回答。默认值为 no



 a| 
配置默认接口层（ L3/L2 ）：
 a| 
请使用 * 二级 * 进行响应。默认值为 L2 。



 a| 
配置默认交换机端口接口状态（ shut/noshut ）：
 a| 
请使用 * noshut * 进行响应。默认值为 noshut 。



 a| 
配置 CoPP 系统配置文件（严格 / 中等 / 宽松 / 密集）：
 a| 
请使用 * 严格 * 回答。默认值为 strict 。



 a| 
是否要编辑此配置？（是 / 否）
 a| 
此时应显示新配置。查看并对您刚刚输入的配置进行任何必要的更改。如果您对配置满意，请在提示符处回答 * 否 * 。如果要编辑配置设置，请使用 * 是 * 进行响应。



 a| 
是否使用此配置并保存？（是 / 否）
 a| 
输入 * 是 * 以保存配置。此操作将自动更新 kickstart 和系统映像。


NOTE: 如果您在此阶段未保存配置，则下次重新启动交换机时，所有更改都不会生效。

|===
. 验证您在设置结束时显示的屏幕中所做的配置选择，并确保保存此配置。
. 检查集群网络交换机上的版本、如有必要、从将NetApp支持的软件版本下载到交换机 https://software.cisco.com/download/home["Cisco软件下载"^] 页面。


.下一步是什么？
link:prepare-install-cisco-nexus-3232c.html["准备安装NX-OS和RCF"]。
