---
permalink: switch-cisco-3232c/setup_worksheet_3232c.html 
sidebar: sidebar 
keywords: cable worksheet, Cisco NX 3232C 
summary: 如果要记录受支持的平台，则必须参考填写好的示例布线工作表来完成空白布线工作表。每个交换机均可配置为一个 100GbE ， 40GbE 端口或 4 个 10GbE 端口。 
---
= 完整的Cisco Nexus 3232C布线工作表
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要记录支持的平台、请下载此页面的PDF并填写布线工作表。

示例布线工作表提供了从交换机到控制器的建议端口分配示例。空白工作表提供了一个模板、可用于设置集群。

每个交换机均可配置为一个 100GbE ， 40GbE 端口或 4 个 10GbE 端口。



== 布线工作表示例

每对交换机上的端口定义示例如下：

[cols="1, 1, 1, 1"]
|===
2+| 集群交换机 A 2+| 集群交换机 B 


| 交换机端口 | 节点和端口使用情况 | 交换机端口 | 节点和端口使用情况 


 a| 
1.
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
1.
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
2.
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
2.
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
3.
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
3.
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
4.
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
4.
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
5.
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
5.
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
6.
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
6.
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
7.
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
7.
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
8.
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
8.
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
9
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
9
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
10
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
10
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
11.
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
11.
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
12
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
12
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
13
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
13
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
14
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
14
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
15
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
15
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
16.
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
16.
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
17
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
17
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
18
 a| 
4个10GbE/4个25GbE或40/100GbE节点
 a| 
18
 a| 
4个10GbE/4个25GbE或40/100GbE节点



 a| 
19
 a| 
40G/100GbE节点19
 a| 
19
 a| 
40G/100GbE节点19



 a| 
20
 a| 
40G/100GbE节点20
 a| 
20
 a| 
40G/100GbE节点20



 a| 
21
 a| 
40G/100GbE节点21
 a| 
21
 a| 
40G/100GbE节点21



 a| 
22.
 a| 
40G/100GbE节点22
 a| 
22.
 a| 
40G/100GbE节点22



 a| 
23
 a| 
40G/100GbE节点23
 a| 
23
 a| 
40G/100GbE节点23



 a| 
24
 a| 
40G/100GbE节点24
 a| 
24
 a| 
40G/100GbE节点24



 a| 
25 到 30
 a| 
已预留
 a| 
25 到 30
 a| 
已预留



 a| 
31
 a| 
100GbE ISL连接到交换机B端口31
 a| 
31
 a| 
100GbE ISL连接到交换机A端口31



 a| 
32
 a| 
100GbE ISL连接到交换机B端口32
 a| 
32
 a| 
100GbE ISL连接到交换机A端口32

|===


== 空布线工作表

您可以使用空白布线工作表记录支持用作集群节点的平台。的_Supported Cluster Connections_部分 https://hwu.netapp.com["Hardware Universe"^] 定义平台使用的集群端口。

[cols="1, 1, 1, 1"]
|===
2+| 集群交换机 A 2+| 集群交换机 B 


| 交换机端口 | 节点 / 端口使用情况 | 交换机端口 | 节点 / 端口使用情况 


 a| 
1.
 a| 
 a| 
1.
 a| 



 a| 
2.
 a| 
 a| 
2.
 a| 



 a| 
3.
 a| 
 a| 
3.
 a| 



 a| 
4.
 a| 
 a| 
4.
 a| 



 a| 
5.
 a| 
 a| 
5.
 a| 



 a| 
6.
 a| 
 a| 
6.
 a| 



 a| 
7.
 a| 
 a| 
7.
 a| 



 a| 
8.
 a| 
 a| 
8.
 a| 



 a| 
9
 a| 
 a| 
9
 a| 



 a| 
10
 a| 
 a| 
10
 a| 



 a| 
11.
 a| 
 a| 
11.
 a| 



 a| 
12
 a| 
 a| 
12
 a| 



 a| 
13
 a| 
 a| 
13
 a| 



 a| 
14
 a| 
 a| 
14
 a| 



 a| 
15
 a| 
 a| 
15
 a| 



 a| 
16.
 a| 
 a| 
16.
 a| 



 a| 
17
 a| 
 a| 
17
 a| 



 a| 
18
 a| 
 a| 
18
 a| 



 a| 
19
 a| 
 a| 
19
 a| 



 a| 
20
 a| 
 a| 
20
 a| 



 a| 
21
 a| 
 a| 
21
 a| 



 a| 
22.
 a| 
 a| 
22.
 a| 



 a| 
23
 a| 
 a| 
23
 a| 



 a| 
24
 a| 
 a| 
24
 a| 



 a| 
25 到 30
 a| 
已预留
 a| 
25 到 30
 a| 
已预留



 a| 
31
 a| 
100GbE ISL连接到交换机B端口31
 a| 
31
 a| 
100GbE ISL连接到交换机A端口31



 a| 
32
 a| 
100GbE ISL连接到交换机B端口32
 a| 
32
 a| 
100GbE ISL连接到交换机A端口32

|===
.下一步
link:install-switch-3232c.html["安装交换机"] 。
