---
permalink: switch-cisco-3232c/task-steps-to-replace-a-cisco-nexus-3232c-storage-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus, 3232c storage switch 
summary: 您可以通过执行一系列特定任务无中断地更换有故障的 Cisco Nexus 3232C 存储交换机。 
---
= 更换 Cisco Nexus 3232C 存储交换机的步骤
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过执行一系列特定任务无中断地更换有故障的 Cisco Nexus 3232C 存储交换机。



== 您将需要什么

现有网络配置必须具有以下特征：

* Cisco 以太网交换机页面会为您的交换机提供最新的 RCF 和 NX-OS 版本。
* 两台交换机上必须存在管理连接。-


====
确保已完成所有故障排除步骤，以确认您的交换机需要更换。

====
更换用的 Cisco Nexus 3232C 交换机必须具有以下特征：

* 管理网络连接必须正常工作。
* 必须能够通过控制台访问更换用的交换机。
* 必须将相应的 RCF 和 NX-OS 操作系统映像加载到交换机上。
* 必须完成交换机的初始自定义。


* 操作步骤 摘要： *

* * 确认要更换的交换机为 S2 （步骤 1-5 ） *
* * 断开交换机 S2 的缆线（步骤 6 ） *
* * 将缆线重新连接到交换机 NS2 （步骤 7 ） *
* * 验证交换机 NS2 上的所有设备配置（步骤 8 至 10 ） *
* 此操作步骤 将第二个 Nexus 3232C 存储交换机 S2 替换为新的 3232C 交换机 NS2
* 这两个节点分别为 node1 和 node2 。




== 步骤

. 如果在此集群上启用了 AutoSupport ，请通过调用 AutoSupport 消息来禁止自动创建案例： `ssystem node AutoSupport invoke -node * -type all - message MAINT=xh`
+
_x_ 是维护时段的持续时间，以小时为单位。

+
[NOTE]
====
AutoSupport 消息会通知技术支持此维护任务，以便在维护窗口期间禁止自动创建案例。

====
. 检查存储节点端口的运行状况，确保已连接到存储交换机 S1 ： `storage port show -port-type ENET`
+
[listing]
----
storage::*> storage port show -port-type ENET
                                      Speed                     VLAN
Node               Port Type  Mode    (Gb/s) State    Status      ID
------------------ ---- ----- ------- ------ -------- --------- ----
node1
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
node2
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
----
. 验证存储交换机 S1 是否可用： `network device-discovery show`
+
[listing]
----
storage::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- ----------------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
----
. 对工作交换机运行 `sHow LLDP neighbors` 命令，确认您可以同时看到节点和所有磁盘架： `sHow LLDP neighbors`
+
[listing]
----
S1# show lldp neighbors
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID               Local Intf      Hold-time  Capability  Port ID
node1                   Eth1/1          121        S           e3a
node2                   Eth1/2          121        S           e3a
SHFGD2008000011         Eth1/5          121        S           e0a
SHFGD2008000011         Eth1/6          120        S           e0a
SHFGD2008000022         Eth1/7          120        S           e0a
SHFGD2008000022         Eth1/8          120        S           e0a
----
. 验证存储系统中的磁盘架端口： `storage shelf port show -fields remote-device ， remote-port`
+
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port

shelf  id  remote-port  remote-device
-----  --  -----------  -------------
3.20   0   Ethernet1/5  S1
3.20   1   -            -
3.20   2   Ethernet1/6  S1
3.20   3   -            -
3.30   0   Ethernet1/7  S1
3.20   1   -            -
3.30   2   Ethernet1/8  S1
3.20   3   -            -
----
. 拔下连接到存储交换机 S2 的所有缆线。
. 将所有缆线重新连接到更换用的交换机 NS2 。
. 重新检查存储节点端口的运行状况： `storage port show -port-type ENET`
+
[listing]
----
storage::*> storage port show -port-type ENET
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ------------ ---
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
. 验证两个交换机是否均可用： `network device-discovery show`
+
[listing]
----
storage::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/1       NX3232C
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
            e7b    NS2                       Ethernet1/1       -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/2       NX3232C
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
            e7b    NS2                       Ethernet1/2       -
----
. 验证存储系统中的磁盘架端口： `storage shelf port show -fields remote-device ， remote-port`
+
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf id remote-port remote-device
----- -- ----------- -------------
3.20  0  Ethernet1/5 S1
3.20  1  Ethernet1/5 NS2
3.20  2  Ethernet1/6 S1
3.20  3  Ethernet1/6 NS2
3.30  0  Ethernet1/7 S1
3.20  1  Ethernet1/7 NS2
3.30  2  Ethernet1/8 S1
3.20  3  Ethernet1/8 NS2
----
. 如果禁止自动创建案例，请通过调用 AutoSupport 消息重新启用此功能： `ssystem node AutoSupport invoke -node * -type all -message MAINT=end`

