---
permalink: switch-cisco-3232c/upgrade-3232c-storage-switches.html 
sidebar: sidebar 
keywords: upgrade, cisco nexus, 3232c storage switch 
summary: 'Cisco Nexus 3232C 存储交换机可以升级Cisco NX-OS 软件和参考配置文件 (RCF)。' 
---
= 升级Cisco Nexus 3232C 存储交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
请按照以下步骤升级Cisco Nexus 3232C 交换机上的Cisco NX-OS 软件和参考配置文件 (RCF)。



== 审查要求

.开始之前
在升级存储交换机上的 NX-OS 软件和 RCF 之前，请确保满足以下条件：

* 交换机功能完全正常（日志中不应有任何错误或类似问题）。
* 如果您仅安装 NX-OS 并保留当前的 RCF 版本，则您已在 RCF 中检查或设置了所需的启动变量，以反映所需的启动映像。
+
如果需要更改启动变量以反映当前的启动映像，则必须在重新应用 RCF 之前进行更改，以便在以后的重启中实例化正确的版本。

* 您已参考了网站上提供的相应软件和升级指南。 http://www.cisco.com/en/US/products/ps9670/prod_installation_guides_list.html["CiscoNexus 3000 系列交换机"^]此页面包含有关Cisco存储升级和降级程序的完整文档。
* 10 GbE 和 40/100 GbE 端口的数量在参考配置文件 (RCF) 中定义，该文件可在以下位置获取： https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco®以太网交换机"^]页。




== 更换开关

.关于示例
本流程中的示例使用以下开关和节点命名规则：

* 这两个存储交换机的名称分别为 S1 和 S2。
* 节点分别为 node1 和 node2。


本流程中的示例使用了两个节点；节点 1 有两个存储端口，节点 2 也有两个存储端口。参见link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^]请确认您平台上的存储端口是否正确。


NOTE: 该过程需要同时使用ONTAP命令和Cisco Nexus 3000 系列交换机命令；除非另有说明，否则使用ONTAP命令。命令输出可能因ONTAP版本不同而有所差异。



=== 步骤 1：检查交换机和端口的运行状况

. 如果启用了AutoSupport，则通过调用AutoSupport消息来阻止自动创建案例：
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ 是维护窗口的持续时间，单位为小时。

+

NOTE: AutoSupport消息会通知技术支持此维护任务，以便在维护窗口期间抑制自动创建案例。

. 检查存储开关是否可用：
+
`system switch ethernet show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
S1
                            storage-network    172.17.227.5     NX3232C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(3)
    Version Source: CDP

S2
                            storage-network    172.17.227.6     NX3232C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(3)
    Version Source: CDP

2 entries were displayed.
storage::*>
----
====
. 确认节点端口运行正常：
+
`storage port show -port-type ENET`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ----------- ----
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
====
. 检查存储交换机或线缆是否存在问题：
+
`system health alert show -instance`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====




=== 步骤 2：将 RCF 复制到Cisco交换机 S2

. 使用以下传输协议之一将交换机 S2 上的 RCF 复制到交换机启动闪存：FTP、HTTP、TFTP、SFTP 或 SCP。
+
有关Cisco命令的更多信息，请参阅 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 命令参考"^]。

+
.显示示例
[%collapsible]
====
以下示例展示了如何使用 HTTP 将 RCF 文件复制到交换机 S2 的启动闪存中：

[listing, subs="+quotes"]
----
S2# *copy http://172.16.10.1//cfg/Nexus_3232C_RCF_v1.6-Storage.txt bootflash: vrf management*
% Total    % Received % Xferd  Average  Speed   Time    Time     Time                          Current
                               Dload    Upload  Total   Spent    Left                          Speed
  100        3254       100    3254     0       0       8175     0 --:--:-- --:--:-- --:--:-   8301
Copy complete, now saving to disk (please wait)...
Copy complete.
S2#
----
====
. 将之前下载的 RCF 文件应用到启动闪存中：
+
`copy bootflash:`

+
.显示示例
[%collapsible]
====
以下示例展示了 RCF 文件 `Nexus_3232C_RCF_v1.6-Storage.txt`正在交换机 S2 上安装：

[listing, subs="+quotes"]
----
S2# *copy Nexus_3232C_RCF_v1.6-Storage.txt running-config echo-commands*
----
====
. 请确认 RCF 文件是否为最新版本：
+
`show running-config`

+
检查输出结果以验证是否拥有正确的 RCF 时，请确保以下信息正确：

+
** RCF横幅
** 节点和端口设置
** 定制
+
输出结果会根据您的网站配置而有所不同。检查端口设置，并参考发行说明，了解您安装的 RCF 版本是否有任何特定更改。

+
[NOTE]
====
在横幅输出中 `show banner motd`要执行此命令，您必须阅读并遵循“*重要提示*”部分中的说明，以确保交换机的正确配置和操作。

====
+
.显示示例
[%collapsible]
====
[listing]
----
S2# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : Cisco Nexus 3232C
* Filename : Nexus_3232C_RCF_v1.6-Storage.txt
* Date     : Oct-20-2020
* Version  : v1.6
*
* Port Usage : Storage configuration
* Ports  1-32: Controller and Shelf Storage Ports
* Ports 33-34: Disabled
*
* IMPORTANT NOTES*
* - This RCF utilizes QoS and requires TCAM re-configuration, requiring RCF
*   to be loaded twice with the Storage Switch rebooted in between.
*
* - Perform the following 4 steps to ensure proper RCF installation:
*
*   (1) Apply RCF first time, expect following messages:
*       - Please save config and reload the system...
*       - Edge port type (portfast) should only be enabled on ports...
*       - TCAM region is not configured for feature QoS class IPv4 ingress...
*
*   (2) Save running-configuration and reboot Cluster Switch
*
*   (3) After reboot, apply same RCF second time and expect following messages:
*       - % Invalid command at '^' marker
*       - Syntax error while parsing...
*
*   (4) Save running-configuration again
******************************************************************************
S2#
----
====
+

NOTE: 首次应用 RCF 时，出现 *错误：写入 VSH 命令失败* 消息是正常的，可以忽略。



. 确认软件版本和交换机设置正确后，复制以下内容： `running-config`文件到 `startup-config`文件位于交换机 S2 上。
+
有关Cisco命令的更多信息，请参阅 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 命令参考"^]。

+
.显示示例
[%collapsible]
====
以下示例展示了 `running-config`文件已成功复制到 `startup-config`文件：

[listing]
----
S2# copy running-config startup-config
[########################################] 100% Copy complete.
----
====




=== 步骤 3：将 NX-OS 镜像复制到Cisco交换机 S2 并重启

. 复制 NX-OS 镜像到 S2 交换机。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
S2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos.9.3.4.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/nxos.9.3.4.bin  /bootflash/nxos.9.3.4.bin
/code/nxos.9.3.4.bin  100% 1261MB   9.3MB/s   02:15
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.

cs2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/n9000-epld.9.3.4.img*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/n9000-epld.9.3.4.img  /bootflash/n9000-epld.9.3.4.img
/code/n9000-epld.9.3.4.img  100%  161MB   9.5MB/s   00:16
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. 安装系统映像，以便下次交换机 S2 重启时加载新版本。
+
交换机将在 10 秒后重启，并应用如下输出所示的新镜像：

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
S2# *install all nxos bootflash:nxos.9.3.4.bin*
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.9.3.4.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  bootable          Impact  Install-type  Reason
------  --------  --------------  ------------  ------
     1       yes      disruptive         reset  default upgrade is not hitless


Images will be upgraded according to following table:
Module       Image                  Running-Version(pri:alt)           New-Version  Upg-Required
------  ----------  ----------------------------------------  --------------------  ------------
     1        nxos                                    9.3(3)                9.3(4)           yes
     1        bios     v08.37(01/28/2020):v08.23(09/23/2015)    v08.38(05/29/2020)            no


Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n] *y*
input string too long
Do you want to continue with the installation (y/n)?  [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS


Finishing the upgrade, switch will reboot in 10 seconds.
S2#
----
====
. 保存配置。
+
有关Cisco命令的更多信息，请参阅 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 系列 NX-OS 命令参考"^]。

+
系统提示您重新启动。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
S2# *copy running-config startup-config*
[########################################] 100% Copy complete.
S2# *reload*
This command will reboot the system. (y/n)?  [n] *y*
----
====
. 确认交换机上已更新为新的NX-OS版本号：
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
S2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 08.38
 NXOS: version 9.3(4)
  BIOS compile time:  05/29/2020
  NXOS image file is: bootflash:///nxos.9.3.4.bin
  NXOS compile time:  4/28/2020 21:00:00 [04/29/2020 02:28:31]


Hardware
  cisco Nexus3000 C3232C Chassis (Nexus 9000 Series)
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K

  Device name: S2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)

Last reset at 157524 usecs after Mon Nov  2 18:32:06 2020
  Reason: Reset due to upgrade
  System version: 9.3(3)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):

S2#
----
====




=== 步骤 4：重新检查交换机和端口的运行状况

. 重启后请再次检查存储交换机是否可用：
+
`system switch ethernet show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
S1
                            storage-network    172.17.227.5     NX3232C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

S2
                            storage-network    172.17.227.6    NX3232C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

2 entries were displayed.
storage::*>
----
====
. 重启后，请确认交换机端口运行正常：
+
`storage port show -port-type ENET`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ----------- ----
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
====
. 再次检查集群是否存在存储交换机或线缆问题：
+
`system health alert show -instance`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====
. 重复上述步骤，升级交换机 S1 上的 NX-OS 软件和 RCF。
. 如果您已禁用自动创建案例功能，请通过调用AutoSupport消息重新启用该功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`


