---
permalink: switch-cisco-9336/setup-required-information.html 
sidebar: sidebar 
keywords: configure, cluster, appropriate, number, cable, connector, switch, type, configuring, configure, console, port, network, information, required cluster configuration information - cisco nexus 9336c-fx2 
summary: 要配置集群，您需要为交换机配置适当数量和类型的缆线和缆线连接器。根据您最初配置的交换机类型，您需要使用随附的控制台缆线连接到交换机控制台端口；您还需要提供特定的网络信息。 
---
= 所需的集群配置信息
:icons: font
:imagesdir: ../media/


[role="lead"]
要配置集群，您需要为交换机配置适当数量和类型的缆线和缆线连接器。根据您最初配置的交换机类型，您需要使用随附的控制台缆线连接到交换机控制台端口；您还需要提供特定的网络信息。



== 所有交换机的所需网络信息

所有交换机配置都需要以下网络信息：

* 用于管理网络流量的 IP 子网
* 每个存储系统控制器和所有适用交换机的主机名和 IP 地址
* 大多数存储系统控制器通过 e0M 接口连接到以太网服务端口（扳手图标）进行管理。在 AFF A800 和 AFF A700 系统上， e0M 接口使用专用以太网端口。


有关最新信息，请参见 _SIL_ Hardware Universe 。

https://hwu.netapp.com["Hardware Universe"]



== Cisco Nexus 9336C-x2 ， 92300YC ， 3232C ， 3132Q-V 和 5596UP/5596T 交换机的所需网络信息

对于 Cisco Nexus 9336C-x2 ， 92300YC ， 3232C ， 3132Q-V 和 5596UP/5596T 交换机， 首次启动交换机时，您需要对以下初始设置问题做出适当的回答。您站点的安全策略定义了响应和服务，以实现：

* 是否中止自动配置并继续正常设置？（是 / 否）
+
请回答 yes 。默认值为 no

* 是否要强制实施安全密码标准？（是 / 否）
+
请回答 yes 。默认值为 yes 。

* 输入管理员的密码。
+
默认密码为 "`admin` " ；您必须创建一个新的强密码。可以拒绝弱密码。

* 是否要进入基本配置对话框？（是 / 否）
+
在交换机的初始配置时，回答 yes 。

* 是否创建其他登录帐户？（是 / 否）
+
您的问题解答取决于站点的策略，取决于备用管理员。默认值为 no

* 是否配置只读 SNMP 社区字符串？（是 / 否）
+
请回答 " 否 "默认值为 no

* 是否配置读写 SNMP 社区字符串？（是 / 否）
+
请回答 " 否 "默认值为 no

* 输入交换机名称。
+
交换机名称限制为 63 个字母数字字符。

* 是否继续进行带外（ mgmt0 ）管理配置？（是 / 否）
+
在该提示符处，以 yes （默认值）回答。在 mgmt0 IPv4 address ：提示符处，输入 IP 地址： ip_address

* 是否配置 default-gateway ？（是 / 否）
+
请回答 yes 。在 default-gateway ：提示符的 IPv4 地址处，输入 default_gateway 。

* 是否配置高级 IP 选项？（是 / 否）
+
请回答 " 否 "默认值为 no

* 是否启用 telnet 服务？（是 / 否）
+
请回答 " 否 "默认值为 no

* 是否已启用 SSH 服务？（是 / 否）
+
请回答 yes 。默认值为 yes 。

+

NOTE: 使用集群交换机运行状况监控器（ CSHM ）收集日志功能时，建议使用 SSH 。为了增强安全性，还建议使用 SSHv2 。

* 输入要生成的 SSH 密钥类型（ DSA/RSA/RSA/rsa1 ）。默认值为 RSA 。
* 输入密钥位数（ 1024-2048 ）。
* 是否配置 NTP 服务器？（是 / 否）
+
请回答 " 否 "默认值为 no

* 配置默认接口层（ L3/L2 ）：
+
使用 L2 进行响应。默认值为 L2 。

* 配置默认交换机端口接口状态（ shut/noshut ）：
+
响应 noshut 。默认值为 noshut 。

* 配置 CoPP 系统配置文件（严格 / 中等 / 宽松 / 密集）：
+
请严格答复。默认值为 strict 。

* 是否要编辑此配置？（是 / 否）
+
此时应显示新配置。查看并对您刚刚输入的配置进行任何必要的更改。如果您对配置满意，请在提示符处回答 no 。如果要编辑配置设置，请回答 yes 。

* 是否使用此配置并保存？（是 / 否）
+
回答 yes 以保存配置。此操作将自动更新 kickstart 和系统映像。

+

NOTE: 如果您在此阶段未保存配置，则下次重新启动交换机时，所有更改都不会生效。

+
有关交换机初始配置的详细信息，请参见以下指南：

+
https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#InstallandUpgradeGuides["《 Cisco Nexus 9336C-x2 安装和升级指南》"]

+
https://www.cisco.com/c/en/us/support/switches/nexus-92300yc-switch/model.html#InstallandUpgradeGuides["《 Cisco Nexus 92300YC 安装和升级指南》"]

+
https://www.cisco.com/c/en/us/support/switches/nexus-5000-series-switches/products-installation-guides-list.html["《 Cisco Nexus 5000 系列硬件安装指南》"]

+
https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["《 Cisco Nexus 3000 系列硬件安装指南》"]


