---
settings:
  name: Cluster and storage switches
  search: ontap-systems-switches
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  pdf:
    zip-level: 1
    zip-filename: ontap-systems-switches-pdfs.zip
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: AFF 和 FAS 交换机文档
    url: "/index.html"
  - title: 入门
    entries:
    - title: 新增功能
      url: "/whats-new.html"
    - title: 了解ONTAP 系统交换机
      url: "/get-started/learn-switch-concept.html"
    - title: 启动并运行
      url: "/get-started/get-up-and-running.html"
  - title: 集群交换机
    entries:
    - section: switch-bes-53248
    - section: switch-cisco-9336c-fx2
    - section: switch-nvidia-sn2100
  - title: 存储交换机
    entries:
    - section: switch-cisco-9336c-fx2-storage
    - section: switch-nvidia-sn2100-storage
  - title: 共享交换机
    entries:
    - section: switch-cisco-9336c-fx2-shared
  - title: 可用性终止的交换机
    entries:
    - title: 概述
      url: "/overview-eod.html"
    - section: switch-cisco-3232c
    - section: switch-cisco-3132q-v
    - section: switch-cisco-92300
    - section: switch-netapp-cn1610
  - title: 法律声明
    url: "/legal-notices.html"
product-family:
  name: AFF and FAS Systems
  repo: ontap-systems-family
