---
settings:
  name: Install and maintain
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  pdf:
    zip-level: 1
    zip-filename: ontap-systems-switches-pdfs.zip
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: 切换 ONTAP 存储系统的文档
    url: "/index.html"
  - title: 发行说明
    entries:
    - title: 交换机的新增功能
      url: "/whats-new.html"
    - title: 终止支持
      url: "/eoa-switches.html"
  - title: 开始使用
    entries:
    - title: 了解ONTAP系统交换机
      url: "/get-started/learn-switch-concept.html"
    - title: 快速启动
      url: "/get-started/get-up-and-running.html"
  - title: AFX 系统交换机
    url: "/afx/index.html"
    entries:
    - section: switch-cisco-9808
    - section: switch-cisco-9332d-gx2b
    - section: switch-cisco-9364d-gx2a
  - title: 集群交换机
    url: "/cluster/index.html"
    entries:
    - section: switch-bes-53248
    - section: switch-cisco-9336c-fx2
  - title: 存储交换机
    url: "/storage/index.html"
    entries:
    - section: switch-cisco-9336c-fx2-storage
  - title: 共享交换机
    url: "/shared/index.html"
    entries:
    - section: switch-cisco-9336c-fx2-shared
      pdf-filename: 思科9336c-fx2存储交换机
  - title: 监控交换机运行状况
    url: "/cshm/index.html"
    entries:
    - section: switch-cshm-configure
    - section: switch-cshm-monitor
    - section: switch-cshm-log-collection
  - title: 可用性终止开关
    url: "/eoa/index.html"
    entries:
    - section: switch-nvidia-sn2100
    - section: switch-nvidia-sn2100-storage
  - title: 法律声明
    url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family
