---
permalink: switch-nvidia-sn2100/cabling-considerations-sn2100-cluster.html 
sidebar: sidebar 
keywords: sn2100 SN2100 cabling setup, sn2100 switches configuration, cumulus linux os 
summary: 在配置NVIDIA SN2100交换机之前、请查看以下信息。 
---
= 查看布线和配置注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在配置NVIDIA SN2100交换机之前、请查看以下注意事项。



== NVIDIA端口详细信息

|===


| *交换机端口* | *端口使用情况* 


 a| 
swp1s0-3
 a| 
4个10GbE分支集群端口节点



 a| 
swp2s0-3
 a| 
4个25GbE分支集群端口节点



 a| 
swp3-14
 a| 
40/100集群端口节点



 a| 
swp15-16
 a| 
40/100交换机间链路(ISL)端口

|===
请参见 https://hwu.netapp.com/Switch/Index["Hardware Universe"^] 有关交换机端口的详细信息。



== 光纤连接

对于Cumulus Linux 4.4.2、使用X1151A NIC、X1146A NIC或板载100GbE端口的SN2100交换机仅支持光纤连接。例如：

* AFF A800位于端口e0a和e0b上
* AFF A320位于端口e0g和e0h上


对于Cumulus Linux 4.4.3及更高版本、需要进行以下配置更改才能修复此问题描述。

. 将以下两行添加到 `/etc/cumulus/switchd.conf` 使用40/100GbE铜缆的每个端口(swp <n>)的文件：
+
** `interface.swp<n>.enable_media_depended_linkup_flow=TRUE`
** `interface.swp<n>.enable_short_tuning=TRUE`


. 重新启动switchd守护进程： `systemctl restart switchd`


请参见以下内容 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric_Interconnect_and_Management_Switches/NVIDIA_SN2100_switch_fails_to_connect_using_40_100GbE_copper_cable["知识库"^] 了解更多详细信息。

.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *cat /etc/cumulus/switchd.conf | grep swp3*
interface.swp3.enable_media_depended_linkup_flow=TRUE
interface.swp3.enable_short_tuning=TRUE
cumulus@cumulus:mgmt:~$ *cat /etc/cumulus/switchd.conf | grep swp6*
interface.swp6.enable_media_depended_linkup_flow=TRUE
interface.swp6.enable_short_tuning=TRUE
cumulus@cumulus:mgmt:~$
----
====


== QSA适配器

使用QSA适配器连接到平台上的板载集群端口时、链路可能无法启动。

要解决此问题描述 、请执行以下操作：

* 对于10G、请手动将swp1s0-3链路速度设置为10000、并将自动协商设置为off。
* 对于25G、手动将swp2s0-3链路速度设置为25000、并将自动协商设置为off。



NOTE: 使用10G/25G QSA时、请将其插入非分支40/100G端口。请勿将QSA适配器插入为分支配置的端口。



== 设置分支端口上的接口速度

根据交换机端口中的收发器、您可能需要将交换机接口上的速度设置为固定速度。如果使用10G和25G分支端口、请确保自动协商已关闭、并在交换机上硬设置接口速度。例如：

[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ net add int swp1s3 link autoneg off && net com
--- /etc/network/interfaces     2019-11-17 00:17:13.470687027 +0000
+++ /run/nclu/ifupdown2/interfaces.tmp  2019-11-24 00:09:19.435226258 +0000
@@ -37,21 +37,21 @@
     alias 10G Intra-Cluster Node
     link-autoneg off
     link-speed 10000  *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp1s3
iface swp1s3
     alias 10G Intra-Cluster Node
-    link-autoneg off
+    link-autoneg on
     link-speed 10000 *<---- port speed set*
     mstpctl-bpduguard yes
     mstpctl-portadminedge yes
     mtu 9216

auto swp2s0
iface swp2s0
     alias 25G Intra-Cluster Node
     link-autoneg off
     link-speed 25000 *<---- port speed set*
----
.下一步是什么？
link:install-cable-shelves-sn2100-cluster.html["将NS224磁盘架作为交换机连接的存储进行布线"]。
