---
permalink: switch-nvidia-sn2100/migrate-cn1610-sn2100-cluster-switch.html 
sidebar: sidebar 
keywords: migrate cluster NVIDIA SN2100 cluster switches cn1610 
summary: 您可以将ONTAP集群的NetApp CN1610集群交换机无故障迁移到NVIDIA SN2100集群网络交换机。 
---
= 将CN1610集群交换机迁移到NVIDIA SN2100集群交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将ONTAP集群的NetApp CN1610集群交换机迁移到NVIDIA SN2100集群交换机。这是一个无中断操作步骤。



== 查看要求

在将NetApp CN1610集群交换机更换为NVIDIA SN2100集群交换机时、您必须了解某些配置信息、端口连接和布线要求。请参见 link:configure-overview-sn2100-cluster.html["NVIDIA SN2100交换机安装和配置概述"]。

.支持的交换机
支持以下集群交换机：

* NetApp CN1610
* NVIDIA SN2100


有关支持的端口及其配置的详细信息、请参见 https://hwu.netapp.com/["Hardware Universe"^]。

.开始之前
验证您的配置是否满足以下要求：

* 现有集群已正确设置且正常运行。
* 所有集群端口均处于*启动*状态、以确保无中断运行。
* NVIDIA SN2100集群交换机已配置、并在应用了参考配置文件(RCF)的正确版本的Cumulus Linux下运行。
* 现有集群网络配置具有以下功能：
+
** 一种使用CN1610交换机且功能完备的冗余NetApp集群。
** 对CN1610交换机和新交换机的管理连接和控制台访问。
** 所有处于up状态的集群Sup、并且集群Sup位于其主端口上。
** 已启用ISL端口、并已在CN1610交换机之间以及新交换机之间进行布线。


* NVIDIA SN2100交换机上的某些端口配置为以40GbE或100GbE运行。
* 您已规划、迁移和记录从节点到NVIDIA SN2100集群交换机的40GbE和100GbE连接。




== 迁移交换机

.关于示例
此操作步骤中的示例使用以下交换机和节点命名：

* 现有的CN1610集群交换机为_C1_和_C2_。
* 新的NVIDIA SN2100集群交换机为_sw1_和_SW2_。
* 节点为 _node1_ 和 _node2_ 。
* 集群 LIF 分别是节点 1 上的 _node1_clus1_ 和 _node1_clus2_ 以及节点 2 上的 _node2_clus1_ 和 _node2_clus2_ 。
* `cluster1 ：：： * >` 提示符指示集群的名称。
* 此操作步骤 中使用的集群端口为_e3A_和_e3b_。
* 分支端口采用以下格式：swp[port]s[分支端口0-3]。例如、swp1上的四个分支端口为_swp1s0_、_swp1s1_、_swp1s2_和_swp1s3_。


.关于此任务
此操作步骤包括以下情形：

* 交换机C2首先被交换机SW2取代。
+
** 关闭集群节点的端口。必须同时关闭所有端口、以避免集群不稳定。
** 然后、节点和C2之间的布线从C2断开、并重新连接到SW2。


* 交换机C1由交换机sw1取代。
+
** 关闭集群节点的端口。必须同时关闭所有端口、以避免集群不稳定。
** 然后、节点和C1之间的布线从C1断开、并重新连接到sw1。





NOTE: 在此操作步骤 期间、不需要可操作的交换机间链路(ISL)。这是设计上的原因、因为RCF版本更改可能会暂时影响ISL连接。为了确保集群无中断运行、以下操作步骤 会在对目标交换机执行步骤时将所有集群LIF迁移到运行中的配对交换机。



=== 第1步：准备迁移

. 如果在此集群上启用了 AutoSupport ，则通过调用 AutoSupport 消息禁止自动创建案例：
+
`ssystem node AutoSupport invoke -node * -type all -message MAINT=xh`

+
其中 _x_ 是维护时段的持续时间，以小时为单位。

. 将权限级别更改为高级，在系统提示您继续时输入 * y * ：
+
`set -privilege advanced`

+
此时将显示高级提示符（ * > ）。

. 在集群LIF上禁用自动还原：
+
`network interface modify -vserver cluster -lif *-auto-revert false`





=== 第2步：配置端口和布线

. 确定每个集群接口的管理或运行状态。
+
每个端口应显示为up `Link` 和 `healthy` 适用于 `Health Status`。

+
.. 显示网络端口属性：
+
`network port show -ipspace cluster`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
.. 显示有关这些LUN及其指定主节点的信息：
+
`network interface show -vserver cluster`

+
应显示每个LIF `up/up` 适用于 `Status Admin/Oper` 和 `true` 适用于 `Is Home`。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current     Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node        Port    Home
----------- -----------  ---------- ------------------ ----------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
            node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
            node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
            node2_clus2  up/up      169.254.19.183/16  node2       e3b     true

----
====


. 从节点的角度来看，每个节点上的集群端口均使用命令以以下方式连接到现有集群交换机：
+
`network device-discovery show -protocol`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e3a    c1 (6a:ad:4f:98:3b:3f)    0/1               -
            e3b    c2 (6a:ad:4f:98:4c:a4)    0/1               -
node2      /cdp
            e3a    c1 (6a:ad:4f:98:3b:3f)    0/2               -
            e3b    c2 (6a:ad:4f:98:4c:a4)    0/2               -
----
====
. 从交换机的角度来看，集群端口和交换机使用命令以以下方式进行连接：
+
`s如何使用 cdp 邻居`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 0/1           124     H          AFF-A400         e3a
node2                 0/2           124     H          AFF-A400         e3a
c2                    0/13          179     S I s      CN1610           0/13
c2                    0/14          175     S I s      CN1610           0/14
c2                    0/15          179     S I s      CN1610           0/15
c2                    0/16          175     S I s      CN1610           0/16

c2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 0/1           124    H           AFF-A400         e3b
node2                 0/2           124    H           AFF-A400         e3b
c1                    0/13          175    S I s       CN1610           0/13
c1                    0/14          175    S I s       CN1610           0/14
c1                    0/15          175    S I s       CN1610           0/15
c1                    0/16          175    S I s       CN1610           0/16
----
====
. 验证远程集群接口的连接：


[role="tabbed-block"]
====
.ONTAP 9.9.1及更高版本
--
您可以使用 `network interface check cluster-connectivity` 命令启动集群连接的可访问性检查、然后显示详细信息：

`network interface check cluster-connectivity start` 和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注：*请等待几秒钟、然后再运行 `show`命令以显示详细信息。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有ONTAP版本
--
对于所有ONTAP版本、您还可以使用 `cluster ping-cluster -node <name>` 用于检查连接的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e3a
Cluster node1_clus2 169.254.49.125 node1     e3b
Cluster node2_clus1 169.254.47.194 node2     e3a
Cluster node2_clus2 169.254.19.183 node2     e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[STEP5]]在交换机C2上、关闭连接到节点集群端口的端口、以便对集群Lifs进行故障转移。
+
[listing, subs="+quotes"]
----
(c2)# *configure*
(c2)(Config)# *interface 0/1-0/12*
(c2)(Interface 0/1-0/12)# *shutdown*
(c2)(Interface 0/1-0/12)# *exit*
(c2)(Config)# *exit*
(c2)#
----
. 使用NVIDIA SN2100支持的适当布线将节点集群端口从旧交换机C2移至新交换机SW2。
. 显示网络端口属性：
+
`network port show -ipspace cluster`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
. 现在，从节点的角度来看，每个节点上的集群端口均以以下方式连接到集群交换机：
+
`network device-discovery show -protocol`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /lldp
            e3a    c1  (6a:ad:4f:98:3b:3f)   0/1               -
            e3b    sw2 (b8:ce:f6:19:1a:7e)   swp3              -
node2      /lldp
            e3a    c1  (6a:ad:4f:98:3b:3f)   0/2               -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4              -
----
====
. 在交换机SW2上、验证所有节点集群端口是否均已启动：
+
`net show interface`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
====
. 在交换机C1上、关闭连接到节点的集群端口的端口、以便对集群生命周期进行故障转移。
+
[listing, subs="+quotes"]
----
(c1)# *configure*
(c1)(Config)# *interface 0/1-0/12*
(c1)(Interface 0/1-0/12)# *shutdown*
(c1)(Interface 0/1-0/12)# *exit*
(c1)(Config)# *exit*
(c1)#
----
. 使用NVIDIA SN2100支持的适当布线将节点集群端口从旧交换机C1移至新交换机sw1。
. 验证集群的最终配置：
+
`network port show -ipspace cluster`

+
应显示每个端口 `up` 适用于 `Link` 和 `healthy` 适用于 `Health Status`。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
. 现在，从节点的角度来看，每个节点上的集群端口均以以下方式连接到集群交换机：
+
`network device-discovery show -protocol`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3            -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3            -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4            -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4            -
----
====
. 在交换机sw1和SW2上、验证所有节点集群端口是否均已启动：
+
`net show interface`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3a               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3a               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw2 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw2 (swp16)       Master: cluster_isl(UP)


cumulus@sw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- -----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
====
. 验证两个节点与每个交换机之间是否有一个连接：
+
`net show lldp`

+
.显示示例
[%collapsible]
====
以下示例显示了这两个交换机的相应结果：

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost          RemotePort
---------  -----  ----------  ------------------  -----------
swp3       100G   Trunk/L2    node1               e3a
swp4       100G   Trunk/L2    node2               e3a
swp15      100G   BondMember  sw2                 swp15
swp16      100G   BondMember  sw2                 swp16

cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost          RemotePort
---------  -----  ----------  ------------------  -----------
swp3       100G   Trunk/L2    node1               e3b
swp4       100G   Trunk/L2    node2               e3b
swp15      100G   BondMember  sw1                 swp15
swp16      100G   BondMember  sw1                 swp16
----
====




=== 第3步：验证配置

. 在集群 LIF 上启用自动还原：
+
`cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true`

. 验证所有集群网络LIF是否均已恢复其主端口：
+
`network interface show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
----
====
. 将权限级别重新更改为 admin ：
+
`set -privilege admin`

. 如果禁止自动创建案例，请通过调用 AutoSupport 消息重新启用它：
+
`ssystem node AutoSupport invoke -node * -type all -message MAINT=end`



.下一步是什么？
迁移交换机后，您link:../switch-cshm/config-overview.html["配置交换机健康监控"]。
