---
permalink: switch-nvidia-sn2100/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, ontap, install the cluster switch health monitor (csm) configuration file for SN2100 switches' 
summary: 您可以使用此程序安装适用于NVIDIA SN2100 集群交换机的集群交换机健康状况监控配置文件。 
---
= 安装以太网交换机健康监视器配置文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要在NVIDIA以太网交换机上配置以太网交换机健康状况监控，请按照以下步骤操作。

如果NVIDIA X190006-PE 和 X190006-PI 开关未被正确检测到，则适用以下说明，可通过运行以下命令来确认这一点： `system switch ethernet show`并检查您的型号是否显示“其他”选项。要识别您的NVIDIA交换机型号，请使用以下命令查找部件号。 `nv show platform hardware`适用于NVIDIA CL 5.8 及更早版本或 `nv show platform`适用于后续版本。

[NOTE]
====
如果您希望在使用NVIDIA CL 5.11.x 和以下ONTAP版本时，健康监控和日志收集能够按预期工作，也建议执行这些步骤。即使不采取这些步骤，健康监测和日志收集功能也可能仍然有效，但遵循这些步骤可确保一切正常运行。

* 9.10.1P20、9.11.1P18、9.12.1P16、9.13.1P8、9.14.1、9.15.1 及更高版本的补丁


====
.开始之前
* 请确保ONTAP集群已启动并正在运行。
* 在交换机上启用 SSH，即可使用 CSHM 中的所有功能。
* 清除 `/mroot/etc/cshm_nod/nod_sign/`所有节点上的目录：
+
.. 进入节点 shell：
+
`system node run -node <name>`

.. 切换到高级权限：
+
`priv set advanced`

.. 列出配置文件。 `/etc/cshm_nod/nod_sign`目录。如果目录存在且包含配置文件，则会列出文件名。
+
`ls /etc/cshm_nod/nod_sign`

.. 删除与所连接的交换机型号对应的所有配置文件。
+
如果您不确定，请删除上面列出的受支持型号的所有配置文件，然后下载并安装这些型号的最新配置文件。

+
`rm /etc/cshm_nod/nod_sign/<filename>`

.. 确认已删除的配置文件已不在目录中：
+
`ls /etc/cshm_nod/nod_sign`





.步骤
. 根据相应的ONTAP版本下载以太网交换机健康监控器配置 zip 文件。该文件可从以下位置获取： https://mysupport.netapp.com/site/info/nvidia-cluster-switch["NVIDIA以太网交换机"^]页。
+
.. 在NVIDIA SN2100 软件下载页面上，选择 *Nvidia CSHM 文件*。
.. 在“注意事项/必读”页面上，选中复选框表示同意。
.. 在最终用户许可协议页面上，选中复选框表示同意，然后单击“接受并继续”。
.. 在 Nvidia CSHM 文件 - 下载页面上，选择适用的配置文件。以下文件可供下载：




[role="tabbed-block"]
====
.ONTAP 9.15.1 及更高版本
--
* MSN2100-CB2FC-v1.4.zip
* MSN2100-CB2RC-v1.4.zip
* X190006-PE-v1.4.zip
* X190006-PI-v1.4.zip


--
.ONTAP 9.11.1 至 9.14.1
--
* MSN2100-CB2FC_PRIOR_R9.15.1-v1.4.zip
* MSN2100-CB2RC_PRIOR_R9.15.1-v1.4.zip
* X190006-PE_PRIOR_9.15.1-v1.4.zip
* X190006-PI_PRIOR_9.15.1-v1.4.zip


--
====
. [[step2]]将相应的 zip 文件上传到您的内部 Web 服务器。
. 从集群中的某个ONTAP系统访问高级模式设置。
+
`set -privilege advanced`

. 运行交换机健康监控器配置命令。
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet configure-health-monitor*
----
. 请确认您的ONTAP版本命令输出是否以以下文本结尾：


[role="tabbed-block"]
====
.ONTAP 9.15.1 及更高版本
--
以太网交换机健康监控已安装配置文件。

--
.ONTAP 9.11.1 至 9.14.1
--
SHM 已安装配置文件。

--
.ONTAP 9.10.1
--
CSHM下载包已成功处理。

--
====
如果发生错误，请联系NetApp支持。

. [[step6]]等待以太网交换机健康监视器轮询间隔的两倍，该间隔可通过运行以下命令找到。 `system switch ethernet polling-interval show`在完成下一步之前。
. 运行该命令 `system switch ethernet configure-health-monitor show`在ONTAP系统中，确保已发现集群交换机，并且监控字段设置为 *True*，序列号字段不显示 *Unknown*。
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet configure-health-monitor show*
----



NOTE: 如果应用配置文件后，您的模型仍然显示“*OTHER*”，请联系NetApp支持。

参见 https://docs.netapp.com/us-en/ontap-cli/system-switch-ethernet-configure-health-monitor.html["系统交换机以太网配置-健康-监控"^]运行命令以获取更多详情。

.下一步是什么？
安装 CSHM 文件后，您可以……link:../switch-cshm/config-overview.html["配置交换机健康监控"] 。
