---
permalink: switch-nvidia-sn2100/upgrade-cl-version.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: 完成以下步骤以升级您的Cumulus Linux版本。 
---
= 升级Cumulus Linux版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
完成以下操作步骤 以根据需要升级您的Cumulus Linux版本。

.开始之前
确保您已具备以下条件：

* 中级Linux知识。
* 熟悉基本文本编辑、UNIX文件权限和进程监控。预安装了各种文本编辑器、包括 `vi` 和 `nano`。
* 访问Linux或UNIX Shell。如果您运行的是Windows、请使用Linux环境作为命令行工具与Cumulus Linux进行交互。
* 对于NVIDIA SN2100交换机控制台访问、串行控制台交换机上的波特率要求设置为115200、如下所示：
+
** 115200 波特
** 8 个数据位
** 1 个停止位
** 奇偶校验：无
** 流量控制：无




.关于此任务
请注意以下事项：


NOTE: 每次升级Cumulus Linux时、都会擦除并重建整个文件系统结构。现有配置将被擦除。在更新Cumulus Linux之前、您必须保存并记录交换机配置。


CAUTION: 累积用户帐户的默认密码为*累积用户*。首次登录到Cumulus Linux时、必须更改此默认密码。在安装新映像之前、您必须更新所有自动化脚本。Cumulus Linux提供了命令行选项、用于在安装过程中自动更改默认密码。

有关详细信息、请参见 https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-510/Installation-Management/Installing-a-New-Cumulus-Linux-Image/["安装新的积云Linux映像"^]。

.步骤
[role="tabbed-block"]
====
.Cumulus Linux 4.4.x 至 Cumulus Linux 5.4.0
--
. 将集群交换机连接到管理网络。
. 使用 ping 命令验证与托管 Cumulus Linux 和 RCF 的服务器的连接。
. 显示连接到集群交换机的每个节点上的集群端口：
+
`network device-discovery show`

. 检查每个集群端口的管理和运行状态。
+
.. 验证所有集群端口是否均已启动且状态正常：
+
`network port show -role cluster`

.. 验证所有集群接口（ LIF ）是否均位于主端口上：
+
`network interface show -role cluster`

.. 验证集群是否同时显示两个集群交换机的信息：
+
`ssystem cluster-switch show -is-monitoring-enableed-Operational true`



. 在集群 LIF 上禁用自动还原。在目标交换机上执行升级过程时、这些集群Cifs将故障转移到配对集群交换机并保留在该交换机上：
+
`network interface modify -vserver cluster -lif *-auto-revert false`

. 检查当前的Cumulus Linux版本和连接的端口：
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show system*
Hostname......... cumulus
Build............ *Cumulus Linux 4.4.3*
Uptime........... 0:08:20.860000
Model............ Mlnx X86
CPU.............. x86_64 Intel Atom C2558 2.40GHz
Memory........... 8GB
Disk............. 14.7GB
ASIC............. Mellanox Spectrum MT52132
Ports............ 16 x 100G-QSFP28
Part Number...... MSN2100-CB2FC
Serial Number.... MT2105T05177
Platform Name.... x86_64-mlnx_x86-r0
Product Name..... MSN2100
ONIE Version..... 2019.11-5.2.0020-115200
Base MAC Address. 04:3F:72:43:92:80
Manufacturer..... Mellanox

cumulus@cumulus:mgmt:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                    Summary
-----  ------  ----  -----  ----------  ----------------------  --------------------
.
.
UP     swp1    100G  9216   Trunk/L2    node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2    node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2    SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2    SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2    SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2    SHFFG1826000102 (e0b)   Master: bridge(UP))
.
.
----
. 下载Cumulux Linux 5.4.0映像：
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo onie-install -a -i http://_<ip-to-webserver>_/path/to/cumulus-linux-5.4.0-mlx-amd64.bin*
[sudo] password for cumulus:
Fetching installer: http://_<ip-to-webserver>_/path/to/cumulus-linux-5.4.0-mlx-amd64.bin
Downloading URL: http://_<ip-to-webserver>_/path/to/cumulus-linux-5.4.0-mlx-amd64.bin
######################################################################### 100.0%
Success: HTTP download complete.
EFI variables are not supported on this system
Warning: SecureBoot is not available.
Image is signed.
.
.
.
Staging installer image...done.
WARNING:
WARNING: Activating staged installer requested.
WARNING: This action will wipe out all system data.
WARNING: Make sure to back up your data.
WARNING:
Are you sure (y/N)? *y*
Activating staged installer...done.
Reboot required to take effect.
----
. 重新启动交换机：
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo reboot*
----
. 更改密码：
+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password:
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
Linux cumulus 5.10.0-cl-1-amd64 #1 SMP Debian 5.10.162-1+cl5.4.0u1 (2023-01-20) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)

ZTP in progress. To disable, do 'ztp -d'
----
. 检查Cumulus Linux版本： `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
           operational    applied
---------- -------------- ----------
hostname   cumulus        cumulus
build      Cumulus Linux 5.4.0
uptime     14:07:08
timezone   Etc/UTC
----
. 更改主机名：
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set system hostname sw1*
cumulus@cumulus:mgmt:~$ *nv config apply*
Warning: The following files have been changed since the last save, and they WILL be overwritten.
- /etc/nsswitch.conf
- /etc/synced/synced.conf
.
.
----
. 注销并再次登录到交换机、以便在提示符处查看更新后的交换机名称：
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *exit*
logout

Debian GNU/Linux 10 cumulus ttyS0

cumulus login: *cumulus*
Password:
Last login: Tue Dec 15 21:43:13 UTC 2020 on ttyS0
Linux cumulus 5.10.0-cl-1-amd64 #1 SMP Debian 5.10.162-1+cl5.4.0u1 (2023-01-20) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)


ZTP in progress. To disable, do 'ztp -d'

cumulus@sw1:mgmt:~$
----
. 设置IP地址：
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *nv set interface eth0 ip address 10.231.80.206/22*
cumulus@sw1:mgmt:~$ *nv set interface eth0 ip gateway 10.231.80.1*
cumulus@sw1:mgmt:~$ *nv config apply*
applied [rev_id: 2]
cumulus@sw1:mgmt:~$ *ip route show vrf mgmt*
default via 10.231.80.1 dev eth0 proto kernel
unreachable default metric 4278198272
10.231.80.0/22 dev eth0 proto kernel scope link src 10.231.80.206
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. 创建新用户并将此用户添加到 `sudo` 组。只有在重新启动控制台/SSH会话后、此用户才会生效。
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----
. 添加供管理员用户访问的其他用户组 `nv` 命令：
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser admin nvshow*
     [sudo] password for cumulus:
     Adding user `admin' to group `nvshow' ...
     Adding user admin to group nvshow
     Done.
----
+
请参见 https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-54/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["NVIDIA用户帐户"^] 有关详细信息 ...



--
.Cumulus Linux 5.x 至 Cumulus Linux 5.4.0
--
. 将集群交换机连接到管理网络。
. 使用 ping 命令验证与托管 Cumulus Linux 和 RCF 的服务器的连接。
. 显示连接到集群交换机的每个节点上的集群端口：
+
`network device-discovery show`

. 检查每个集群端口的管理和运行状态。
+
.. 验证所有集群端口是否均已启动且状态正常：
+
`network port show -role cluster`

.. 验证所有集群接口（ LIF ）是否均位于主端口上：
+
`network interface show -role cluster`

.. 验证集群是否同时显示两个集群交换机的信息：
+
`ssystem cluster-switch show -is-monitoring-enableed-Operational true`



. 在集群 LIF 上禁用自动还原。在目标交换机上执行升级过程时、这些集群Cifs将故障转移到配对集群交换机并保留在该交换机上：
+
`network interface modify -vserver cluster -lif *-auto-revert false`

. 检查当前的Cumulus Linux版本和连接的端口：
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *nv show system*
                    operational          applied
------------------- -------------------- -----------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.3.0
uptime              6 days, 8:37:36
timezone            Etc/UTC

cumulus@sw1:mgmt:~$ *nv show interface*
Interface     MTU   Speed State Remote Host         Remote Port- Type      Summary
------------- ----- ----- ----- ------------------- ------------ --------- -------------
+ cluster_isl 9216  200G  up                                      bond
+ eth0        1500  100M  up    mgmt-sw1            Eth105/1/14   eth       IP Address: 10.231.80 206/22
  eth0                                                                      IP Address: fd20:8b1e:f6ff:fe31:4a0e/64
+ lo          65536       up                                      loopback  IP Address: 127.0.0.1/8
  lo                                                                        IP Address: ::1/128
+ swp1s0      9216 10G    up cluster01                e0b         swp
.
.
.
+ swp15      9216 100G    up sw2                      swp15       swp
+ swp16      9216 100G    up sw2                      swp16       swp
----
. 下载Cumulux Linux 5.4.0映像：
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<ip-to-webserver>_/path/to/cumulus-linux-5.4.0-mlx-amd64.bin*
[sudo] password for cumulus:
Fetching installer: http://_<ip-to-webserver>_/path/to/cumulus-linux-5.4.0-mlx-amd64.bin
Downloading URL: http://_<ip-to-webserver>_/path/to/cumulus-linux-5.4.0-mlx-amd64.bin
######################################################################### 100.0%
Success: HTTP download complete.
EFI variables are not supported on this system
Warning: SecureBoot is not available.
Image is signed.
.
.
.
Staging installer image...done.
WARNING:
WARNING: Activating staged installer requested.
WARNING: This action will wipe out all system data.
WARNING: Make sure to back up your data.
WARNING:
Are you sure (y/N)? *y*
Activating staged installer...done.
Reboot required to take effect.
----
. 重新启动交换机：
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. 更改密码：
+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password:
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
Linux cumulus 5.10.0-cl-1-amd64 #1 SMP Debian 5.10.162-1+cl5.4.0u1 (2023-01-20) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)

ZTP in progress. To disable, do 'ztp -d'
----
. 检查Cumulus Linux版本： `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational    applied
-------------- ----------------
hostname       cumulus cumulus
build          Cumulus Linux 5.4.0
uptime         14:07:08
timezone       Etc/UTC
----
. 更改主机名：
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set system hostname sw1*
cumulus@cumulus:mgmt:~$ *nv config apply*
Warning: The following files have been changed since the last save, and they WILL be overwritten.
- /etc/nsswitch.conf
- /etc/synced/synced.conf
.
.
----
. 注销并重新登录到交换机、以便在提示符处查看更新后的交换机名称：
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *exit*
logout

Debian GNU/Linux 10 cumulus ttyS0

cumulus login: *cumulus*
Password:
Last login: Tue Dec 15 21:43:13 UTC 2020 on ttyS0
Linux cumulus 5.10.0-cl-1-amd64 #1 SMP Debian 5.10.162-1+cl5.4.0u1 (2023-01-20) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)


ZTP in progress. To disable, do 'ztp -d'

cumulus@sw1:mgmt:~$
----
. 设置IP地址：
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *nv unset interface eth0 ip address dhcp*
cumulus@sw1:mgmt:~$ *nv set interface eth0 ip address 10.231.80.206/22*
cumulus@sw1:mgmt:~$ *nv set interface eth0 ip gateway 10.231.80.1*
cumulus@sw1:mgmt:~$ *nv config apply*
applied [rev_id: 2]
cumulus@sw1:mgmt:~$ *ip route show vrf mgmt*
default via 10.231.80.1 dev eth0 proto kernel
unreachable default metric 4278198272
10.231.80.0/22 dev eth0 proto kernel scope link src 10.231.80.206
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----
. 创建新用户并将此用户添加到 `sudo` 组。只有在重新启动控制台/SSH会话后、此用户才会生效。
+
`sudo adduser --ingroup netedit admin`

+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser --ingroup netedit admin*
[sudo] password for cumulus:
Adding user 'admin' ...
Adding new user 'admin' (1001) with group `netedit' ...
Creating home directory '/home/admin' ...
Copying files from '/etc/skel' ...
New password:
Retype new password:
passwd: password updated successfully
Changing the user information for admin
Enter the new value, or press ENTER for the default
Full Name []:
Room Number []:
Work Phone []:
Home Phone []:
Other []:
Is the information correct? [Y/n] *y*

cumulus@sw1:mgmt:~$ *sudo adduser admin sudo*
[sudo] password for cumulus:
Adding user `admin' to group `sudo' ...
Adding user admin to group sudo
Done.
cumulus@sw1:mgmt:~$ *exit*
logout
Connection to 10.233.204.71 closed.

[admin@cycrh6svl01 ~]$ ssh admin@10.233.204.71
admin@10.233.204.71's password:
Linux sw1 4.19.0-cl-1-amd64 #1 SMP Cumulus 4.19.206-1+cl4.4.1u1 (2021-09-09) x86_64
Welcome to NVIDIA Cumulus (R) Linux (R)

For support and online technical documentation, visit
http://www.cumulusnetworks.com/support

The registered trademark Linux (R) is used pursuant to a sublicense from LMI, the exclusive licensee of Linus Torvalds, owner of the mark on a world-wide basis.
admin@sw1:mgmt:~$
----
. 添加供管理员用户访问的其他用户组 `nv` 命令：
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo adduser admin nvshow*
     [sudo] password for cumulus:
     Adding user `admin' to group `nvshow' ...
     Adding user admin to group nvshow
     Done.
----
+
请参见 https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-54/System-Configuration/Authentication-Authorization-and-Accounting/User-Accounts/["NVIDIA用户帐户"^] 有关详细信息 ...



--
.Cumulus Linux 5.4.0 至 Cumulus Linux 5.11.0
--
. 将集群交换机连接到管理网络。
. 使用 ping 命令验证与托管 Cumulus Linux 和 RCF 的服务器的连接。
. 显示连接到集群交换机的每个节点上的集群端口：
+
`network device-discovery show`

. 检查每个集群端口的管理和运行状态。
+
.. 验证所有集群端口是否均已启动且状态正常：
+
`network port show -role cluster`

.. 验证所有集群接口（ LIF ）是否均位于主端口上：
+
`network interface show -role cluster`

.. 验证集群是否同时显示两个集群交换机的信息：
+
`ssystem cluster-switch show -is-monitoring-enableed-Operational true`



. 在集群 LIF 上禁用自动还原。在目标交换机上执行升级过程时、这些集群Cifs将故障转移到配对集群交换机并保留在该交换机上：
+
`network interface modify -vserver cluster -lif *-auto-revert false`

. 检查当前的Cumulus Linux版本和连接的端口：
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *nv show system*
                    operational          applied
------------------- -------------------- -----------------
hostname            cumulus              cumulus
build               Cumulus Linux 5.4.0
uptime              6 days, 8:37:36
timezone            Etc/UTC

cumulus@sw1:mgmt:~$ *nv show interface*
Interface     MTU   Speed State Remote Host         Remote Port- Type      Summary
------------- ----- ----- ----- ------------------- ------------ --------- -------------
+ cluster_isl 9216  200G  up                                      bond
+ eth0        1500  100M  up    mgmt-sw1            Eth105/1/14   eth       IP Address: 10.231.80 206/22
  eth0                                                                      IP Address: fd20:8b1e:f6ff:fe31:4a0e/64
+ lo          65536       up                                      loopback  IP Address: 127.0.0.1/8
  lo                                                                        IP Address: ::1/128
+ swp1s0      9216 10G    up cluster01                e0b         swp
.
.
.
+ swp15      9216 100G    up sw2                      swp15       swp
+ swp16      9216 100G    up sw2                      swp16       swp
----
. 下载Cumulux Linux 5.11.0映像：
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo onie-install -a -i http://_<ip-to-webserver>_/path/to/cumulus-linux-5.11.0-mlx-amd64.bin*
[sudo] password for cumulus:
Fetching installer: http://_<ip-to-webserver>_/path/to/cumulus-linux-5.11.0-mlx-amd64.bin
Downloading URL: http://_<ip-to-webserver>_/path/to/cumulus-linux-5.11.0-mlx-amd64.bin
######################################################################### 100.0%
Success: HTTP download complete.
EFI variables are not supported on this system
Warning: SecureBoot is not available.
Image is signed.
.
.
.
Staging installer image...done.
WARNING:
WARNING: Activating staged installer requested.
WARNING: This action will wipe out all system data.
WARNING: Make sure to back up your data.
WARNING:
Are you sure (y/N)? *y*
Activating staged installer...done.
Reboot required to take effect.
----
. 重新启动交换机：
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *sudo reboot*
----
. 更改密码：
+
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password:
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
Linux cumulus 5.11.0-cl-1-amd64 #1 SMP Debian 5.10.162-1+cl5.4.0u1 (2023-01-20) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)

ZTP in progress. To disable, do 'ztp -d'
----
. 检查Cumulus Linux版本： `nv show system`
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv show system*
operational    applied
-------------- ----------------
hostname       cumulus cumulus
build          Cumulus Linux 5.11.0
uptime         14:07:08
timezone       Etc/UTC
----
. 更改主机名：
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *nv set system hostname sw1*
cumulus@cumulus:mgmt:~$ *nv config apply*
Warning: The following files have been changed since the last save, and they WILL be overwritten.
- /etc/nsswitch.conf
- /etc/synced/synced.conf
.
.
----
. 注销并再次登录交换机，即可在提示符下看到更新后的交换机名称：
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *exit*
logout

Debian GNU/Linux 10 cumulus ttyS0

cumulus login: *cumulus*
Password:
Last login: Tue Dec 15 21:43:13 UTC 2020 on ttyS0
Linux cumulus 5.11.0-cl-1-amd64 #1 SMP Debian 5.10.162-1+cl5.4.0u1 (2023-01-20) x86_64

Welcome to NVIDIA Cumulus (R) Linux (R)


ZTP in progress. To disable, do 'ztp -d'

cumulus@sw1:mgmt:~$
----
. 设置IP地址：
+
[listing, subs="+quotes"]
----
cumulus@sw1:mgmt:~$ *nv unset interface eth0 ip address dhcp*
cumulus@sw1:mgmt:~$ *nv set interface eth0 ip address 10.231.80.206/22*
cumulus@sw1:mgmt:~$ *nv set interface eth0 ip gateway 10.231.80.1*
cumulus@sw1:mgmt:~$ *nv config apply*
applied [rev_id: 2]
cumulus@sw1:mgmt:~$ *ip route show vrf mgmt*
default via 10.231.80.1 dev eth0 proto kernel
unreachable default metric 4278198272
10.231.80.0/22 dev eth0 proto kernel scope link src 10.231.80.206
127.0.0.0/8 dev mgmt proto kernel scope link src 127.0.0.1
----


--
====
.下一步是什么？
升级 Cumulus Linux 版本后，您可以……link:install-rcf-sn2100-cluster.html["安装或升级 RCF 脚本"] 。
