---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-storage/configure-reqs-9336c-storage.html 
keywords: shared storage cluster switch 
summary: 从ONTAP 9.9.1 开始，您可以使用Cisco Nexus 9336C-FX2 交换机将存储和集群功能组合到共享交换机场景中。 
---
= Cisco Nexus 9336C-FX2 和 9336C-FX2-T 存储交换机的配置要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
对于Cisco Nexus 9336C-FX2 和 9336C-FX2-T 交换机的安装和维护，请务必检查配置和网络要求。



== ONTAP 支持

[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
从ONTAP 9.9.1 开始，您可以使用Cisco Nexus 9336C-FX2 交换机将存储和集群功能组合到共享交换机配置中。

如果要构建包含两个以上节点的ONTAP集群，则需要两个受支持的网络交换机。


NOTE: 以太网交换机健康监视器不支持ONTAP 9.13.1P8 及更早版本、9.14.1P3 及更早版本或 NX-OS 版本 10.3(4a)(M)。

--
.ONTAP 9.10.1 及更高版本
--
此外，从ONTAP 9.10.1 开始，您可以使用Cisco Nexus 9336C-FX2-T 交换机将存储和集群功能组合到共享交换机配置中。

如果要构建包含两个以上节点的ONTAP集群，则需要两个受支持的网络交换机。

--
====


== 配置要求

配置时，您需要为交换机准备相应数量和类型的电缆和电缆连接器。

根据您最初配置的交换机类型，您需要使用随附的控制台电缆连接到交换机控制台端口；您还需要提供具体的网络信息。



== 网络要求

所有交换机配置都需要以下网络信息。

* 管理网络流量的 IP 子网
* 每个存储系统控制器和所有适用交换机的主机名和 IP 地址
* 大多数存储系统控制器通过连接到以太网服务端口（扳手图标）通过 e0M 接口进行管理。在AFF A800和AFF A700s系统中，e0M 接口使用专用以太网端口。
* 请参阅 https://hwu.netapp.com["Hardware Universe"]获取最新信息。


有关交换机初始配置的更多信息，请参阅以下指南： https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9336c-fx2-e/cisco-nexus-9336c-fx2-e-nx-os-mode-switch-hardware-installation-guide.html["Cisco Nexus 9336C-FX2 安装和升级指南"] 。

.下一步
在您查看完配置要求后，您可以确认您的配置。 link:components-9336c-storage.html["组件和零件编号"]。
