---
permalink: switch-cisco-9336c-fx2/index.html 
sidebar: sidebar 
keywords: cisco, switch, cisco 9336 switch 
summary: 'Cisco 936-x2` 交换机' 
---
= 概述和要求：Cisco Nexus 9336C-x2交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
对于Cisco Nexus 9336C-x2交换机安装和维护、请务必查看配置要求和文档要求。

如果要使用两个以上的节点构建 ONTAP 集群，则需要两个受支持的集群网络交换机。您可以使用其他管理交换机，这些交换机是可选的。

您可以将 Cisco Nexus 9336C-x2 交换机（ X190200/X190210 ）安装在 NetApp 系统机柜或第三方机柜中，并使用交换机附带的标准支架。



== 交换机组件

下表列出了 9336C-fx2 交换机，风扇和电源的部件号和问题描述：

[cols="1,2"]
|===
| 部件号 | Description 


 a| 
X190200-CS-PE
 a| 
N9K-9336C-f2 ， CS ， PTSX ， 36PT10/25/40/100GQSFP28



 a| 
X190200-CS-PI
 a| 
N9K-9336C-f2 ， CS ， PSIN ， 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PE
 a| 
N9K-9336C ， FTE ， PTSX ， 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PI
 a| 
N9K-9336C ， FTE ， PSIN ， 36PT10/25/40/100GQSFP28



 a| 
X190002
 a| 
附件套件 X190001/X190003



 a| 
X-NXA-PA-11000W-PE2
 a| 
N9K-9336C 交流 1100 W PSU —端口侧排气



 a| 
X-NXA-PC-11000W-PI2
 a| 
N9K-9336C 交流 1100 W PSU —端口侧进气气流



 a| 
X-NXA-Fan-65CFM-PE
 a| 
N9K-9336C 65CFM ，端口侧排气



 a| 
X-NXA-Fan-65CFM-PI
 a| 
N9K-9336C 65CFM ，端口侧进气气流

|===


== 配置要求

要配置集群，您需要为交换机配置适当数量和类型的缆线和缆线连接器。根据您最初配置的交换机类型，您需要使用随附的控制台缆线连接到交换机控制台端口；您还需要提供特定的网络信息。



== 网络要求

所有交换机配置都需要以下网络信息：

* 用于管理网络流量的 IP 子网
* 每个存储系统控制器和所有适用交换机的主机名和 IP 地址
* 大多数存储系统控制器通过 e0M 接口连接到以太网服务端口（扳手图标）进行管理。在 AFF A800 和 AFF A700 系统上， e0M 接口使用专用以太网端口。


请参见 https://["Hardware Universe"^] 了解最新信息。



== 智能自动通报要求

智能自动通报功能可监控网络上的硬件和软件组件，以生成基于电子邮件的关键系统情况通知。当设备上发生事件时，智能自动通报会向目标配置文件中配置的所有收件人发出警报。

您必须将集群网络交换机配置为使用电子邮件与智能自动通报系统进行通信。您可以选择设置集群网络交换机，以利用 Cisco 的嵌入式智能自动通报支持功能。

在使用智能自动通报功能之前，您需要了解以下注意事项：

* 电子邮件服务器必须已就位。
* 交换机必须与电子邮件服务器建立 IP 连接。
* 必须配置联系人姓名（ SNMP 服务器联系人），电话号码和街道地址信息。要确定收到的消息的来源，必须执行此操作。
* CCO ID 必须与贵公司的相应 Cisco SMARTnet 服务合同相关联。
* 要注册设备，必须已安装 Cisco SMARTnet 服务。


。 http://["Cisco 支持站点"^] 包含有关用于配置智能自动通报的命令的信息。



== 文档要求

要设置Cisco 9333-FX2交换机和ONTAP 集群、您需要特定的交换机和控制器文档。



=== 交换机文档

要设置Cisco Nexus 9336C-FX2交换机、您需要中的以下文档 https://["Cisco Nexus 9000 系列交换机支持"^] 页面。

[cols="1,2"]
|===
| 文档标题 | Description 


 a| 
_Nexus 9000 系列硬件安装指南 _
 a| 
提供有关站点要求，交换机硬件详细信息和安装选项的详细信息。



 a| 
_Cisco Nexus 9000 系列交换机软件配置指南 _ （选择适用于交换机上安装的 NX-OS 版本的指南）
 a| 
提供为 ONTAP 操作配置交换机之前所需的初始交换机配置信息。



 a| 
_Cisco Nexus 9000 系列 NX-OS 软件升级和降级指南 _ （选择适用于交换机上安装的 NX-OS 版本的指南）
 a| 
提供有关如何根据需要将交换机降级为 ONTAP 支持的交换机软件的信息。



 a| 
_Cisco Nexus 9000 系列 NX-OS 命令参考主索引 _
 a| 
提供 Cisco 提供的各种命令参考的链接。



 a| 
_Cisco Nexus 9000 MIB 参考 _
 a| 
介绍 Nexus 9000 交换机的管理信息库（ Management Information Base ， MIB ）文件。



 a| 
_Nexus 9000 系列 NX-OS 系统消息参考 _
 a| 
介绍 Cisco Nexus 9000 系列交换机的系统消息，信息性消息以及可能有助于诊断链路，内部硬件或系统软件问题的其他消息。



 a| 
_Cisco Nexus 9000 系列 NX-OS 发行说明（为交换机上安装的 NX-OS 版本选择注释） _
 a| 
介绍 Cisco Nexus 9000 系列的功能，错误和限制。



 a| 
Cisco Nexus 9000 系列的合规性和安全信息
 a| 
提供 Nexus 9000 系列交换机的国际机构合规性，安全性和法定信息。

|===


=== ONTAP 系统文档

要设置 ONTAP 系统，您需要在中为您的操作系统版本提供以下文档 https://["ONTAP 9 文档中心"^]。

[cols="1,2"]
|===
| Name | Description 


 a| 
特定于控制器的安装和设置说明
 a| 
介绍如何安装 NetApp 硬件。



 a| 
ONTAP 文档
 a| 
提供有关 ONTAP 版本各个方面的详细信息。



 a| 
https://["Hardware Universe"^]
 a| 
提供 NetApp 硬件配置和兼容性信息。

|===


=== 导轨套件和机柜文档

要在NetApp机柜中安装Cisco 9333-FX2交换机、请参见以下硬件文档。

[cols="1,2"]
|===
| Name | Description 


 a| 
https://["42U 系统机柜，深度指南"^]
 a| 
介绍与 42U 系统机柜关联的 FRU ，并提供维护和 FRU 更换说明。



 a| 
link:install-switch-and-passthrough-panel.html["在NetApp机柜中安装Cisco 9333-FX2交换机"^]
 a| 
介绍如何在四柱NetApp机柜中安装Cisco Nexus 9336C-fx2交换机。

|===