---
permalink: switch-cisco-9336c-fx2-storage/install-9336c-storage.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: 如果您还没有所需的配置信息和文档，则需要在设置集群和管理网络交换机之前收集这些信息。 
---
= 安装9336C-x2存储交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照此操作步骤 安装Cisco Nexus 9336C-x2存储交换机。

.您需要的内容
* 访问安装站点上的HTTP、FTP或TFTP服务器、以下载适用的NX-OS和参考配置文件(RCF)版本。
* 适用的NX-OS版本、从下载 https://software.cisco.com/download/home["Cisco 软件下载"^] 页面。
* 适用的许可证、网络和配置信息以及缆线。
* 已完成 link:setup-worksheet-9336c-storage.html["布线工作表"]。
* 从NetApp 支持站点 下载的适用NetApp集群网络和管理网络RCF、网址为 http://mysupport.netapp.com/["mysupport.netapp.com"^]。所有 Cisco 集群网络和管理网络交换机均采用标准的 Cisco 出厂默认配置。这些交换机还具有最新版本的 NX-OS 软件，但未加载 RCF 。
* 所需的交换机文档。请参见 link:required-documentation-9336c-storage.html["所需文档"] 有关详细信息 ...


.步骤
. 将集群网络和管理网络交换机和控制器装入机架。
+
[cols="1,2"]
|===
| 如果要安装 ... | 那么 ... 


 a| 
NetApp 系统机柜中的 Cisco Nexus 9336C-x2
 a| 
请参见 link:install-switch-and-passthrough-panel-9336c-storage.html["将交换机安装在NetApp机柜中"] 有关在NetApp机柜中安装交换机的说明。



 a| 
电信机架中的设备
 a| 
请参见交换机硬件安装指南和 NetApp 安装和设置说明中提供的过程。

|===
. 使用已完成的布线工作表将集群网络和管理网络交换机连接到控制器。
. 打开集群网络以及管理网络交换机和控制器的电源。


.下一步是什么？
转至 link:setup-switch-9336c-storage.html["配置Cisco Nexus 9336C-x2存储交换机"]。
