---
permalink: switch-cisco-9336c-fx2-storage/install-9336c-storage.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, storage, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: 如果您还没有所需的配置信息和文档，则需要在设置存储和管理网络交换机之前收集这些信息。 
---
= 安装 9336C-FX2 和 9336C-FX2-T 存储交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照以下步骤安装Cisco Nexus 9336C-FX2 和 9336C-FX2-T 存储交换机。

.开始之前
请确保您拥有以下物品：

* 在安装现场访问 HTTP、FTP 或 TFTP 服务器，以下载适用的 NX-OS 和参考配置文件 (RCF) 版本。
* 适用的NX-OS版本，可从以下网址下载： https://software.cisco.com/download/home["Cisco软件下载"^]页。
* 适用的许可证、网络和配置信息以及线缆。
* 完全的link:setup-worksheet-9336c-storage.html["布线工作表"]。
* 从 NetApp 支持站点下载的适用 NetApp 存储网络和管理网络 RCF，网址为 http://mysupport.netapp.com/["mysupport.netapp.com"^]。
+
所有 Cisco 存储网络和管理网络交换机均采用标准的 Cisco 出厂默认配置。这些交换机还具有当前版本的 NX-OS 软件，但没有加载 RCF。

* 需要提供交换机文档。看link:required-documentation-9336c-storage.html["所需文件"]了解更多信息。


.步骤
. 将网络和管理网络交换机和控制器安装到机架中。
+
[cols="1,2"]
|===
| 如果您正在安装…… | 操作 


 a| 
NetApp系统机柜中的Cisco Nexus 9336C-FX2
 a| 
看link:install-switch-and-passthrough-panel-9336c-storage.html["在NetApp机柜中安装交换机"]有关在NetApp机柜中安装交换机的说明。



 a| 
电信机架中的设备
 a| 
请参阅交换机硬件安装指南和NetApp安装设置说明中提供的步骤。

|===
. 使用完成的布线工作表将网络交换机和管理网络交换机连接到控制器。
. 打开网络和管理网络交换机和控制器的电源。


.下一步是什么？
（可选） link:install-switch-and-passthrough-panel-9336c-storage.html["在NetApp机柜中安装Cisco Nexus 9336C-FX2 交换机"]。否则，请前往 link:setup-switch-9336c-storage.html["配置交换机"]。
