---
permalink: switch-cisco-9336c-fx2-storage/replace-storage-switch-9336c-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: 更换集群网络中存在故障的 Nexus 9336C-x2 交换机是无中断操作步骤 \ （ NDU\ ）。 
---
= 更换 Cisco Nexus 9336C-x2 存储交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更换集群网络中存在故障的Nexus 9336C-x2交换机。这是一个无中断操作步骤。

.您需要的内容
在Cisco Nexus 9336C-x2存储交换机上安装NX-OS软件和RCF之前、请确保：

* 您的系统可以支持 Cisco Nexus 9336C-x2 存储交换机。
* 您已查看Cisco以太网交换机页面上的交换机兼容性表、了解支持的ONTAP 、NX-OS和RCF版本。
* 您已参考Cisco网站上提供的相应软件和升级指南。


Cisco Nexus 3000系列交换机：

* 您已下载适用的RCF。
* 现有网络配置具有以下特征：
+
** Cisco 以太网交换机页面会为您的交换机提供最新的 RCF 和 NX-OS 版本。
** 两台交换机上必须存在管理连接。


* 更换用的Cisco Nexus 9336C-x2交换机具有以下特征：
+
** 管理网络连接正常。
** 可以通过控制台访问替代交换机。
** 相应的RCF和NX-OS操作系统映像将加载到交换机上。
** 交换机的初始配置已完成。




.关于此任务
此操作步骤 将第二个Nexus 9336C-fx2存储交换机S2替换为新的9336C-FX交换机NS2。这两个节点分别为 node1 和 node2 。

完成步骤：

* 确认要更换的交换机为 S2 。
* 断开交换机 S2 的缆线。
* 将缆线重新连接到交换机 NS2 。
* 验证交换机 NS2 上的所有设备配置。
+

NOTE: RCF和NX-OS版本中的命令语法之间可能存在依赖关系。



.步骤
. 如果在此集群上启用了 AutoSupport ，则通过调用 AutoSupport 消息禁止自动创建案例：
+
`ssystem node AutoSupport invoke -node * -type all - 消息 MAINT=xh`

+
_x_ 是维护时段的持续时间，以小时为单位。

. 检查存储节点端口的运行状况，确保已连接到存储交换机 S1 ：
+
`storage port show -port-type ENET`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
====
. 验证存储交换机S1是否可用：
+
`network device-discovery show`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
node1/cdp
           e3a   S1                        Ethernet1/1 NX9336C
           e4a   node2                     e4a         AFF-A700
           e4e   node2                     e4e         AFF-A700
node1/lldp
           e3a   S1                        Ethernet1/1 -
           e4a   node2                     e4a         -
           e4e   node2                     e4e         -
node2/cdp
           e3a   S1                        Ethernet1/2 NX9336C
           e4a   node1                     e4a         AFF-A700
           e4e   node1                     e4e         AFF-A700
node2/lldp
           e3a   S1                        Ethernet1/2 -
           e4a   node1                     e4a         -
           e4e   node1                     e4e         -
storage::*>
----
====
. 运行此演示 `lldp neighbors` 命令确认您可以同时看到节点和所有磁盘架：
+
`show lldp neighbors`

+
.显示示例
[%collapsible]
====
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
node1            Eth1/1       121          S             e3a
node2            Eth1/2       121          S             e3a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====
. 验证存储系统中的磁盘架端口：
+
`storage shelf port show -fields remote-device,remote-port`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   S1
3.20    1   -             -
3.20    2   Ethernet1/6   S1
3.20    3   -             -
3.30    0   Ethernet1/7   S1
3.20    1   -             -
3.30    2   Ethernet1/8   S1
3.20    3   -             -
storage::*>
----
====
. 拔下连接到存储交换机 S2 的所有缆线。
. 将所有缆线重新连接到更换用的交换机 NS2 。
. 重新检查存储节点端口的运行状况：
+
`storage port show -port-type ENET`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
====
. 验证两个交换机是否均可用：
+
`network device-discovery show`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
node1/cdp
          e3a  S1                         Ethernet1/1 NX9336C
          e4a  node2                      e4a         AFF-A700
          e4e  node2                      e4e         AFF-A700
          e7b   NS2                       Ethernet1/1 NX9336C
node1/lldp
          e3a  S1                         Ethernet1/1 -
          e4a  node2                      e4a         -
          e4e  node2                      e4e         -
          e7b  NS2                        Ethernet1/1 -
node2/cdp
          e3a  S1                         Ethernet1/2 NX9336C
          e4a  node1                      e4a         AFF-A700
          e4e  node1                      e4e         AFF-A700
          e7b  NS2                        Ethernet1/2 NX9336C
node2/lldp
          e3a  S1                         Ethernet1/2 -
          e4a  node1                      e4a         -
          e4e  node1                      e4e         -
          e7b  NS2                        Ethernet1/2 -
storage::*>
----
====
. 验证存储系统中的磁盘架端口：
+
`storage shelf port show -fields remote-device,remote-port`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     S1
3.20    1     Ethernet1/5     NS2
3.20    2     Ethernet1/6     S1
3.20    3     Ethernet1/6     NS2
3.30    0     Ethernet1/7     S1
3.20    1     Ethernet1/7     NS2
3.30    2     Ethernet1/8     S1
3.20    3     Ethernet1/8     NS2
storage::*>
----
====
. 如果禁止自动创建案例，请通过调用 AutoSupport 消息重新启用它：
+
`ssystem node AutoSupport invoke -node * -type all -message MAINT=end`


