---
permalink: switch-cisco-9336c-fx2-storage/replace-storage-switch-9336c-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: '更换集群网络中有缺陷的 Nexus 9336C-FX2 交换机是一个无中断过程 \(NDU\)。' 
---
= 更换Cisco Nexus 9336C-FX2 和 9336C-FX2-T 存储交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更换集群网络中有缺陷的 Nexus 9336C-FX2 和 9336C-FX2-T 交换机。这是一个非破坏性的过程。

.开始之前
在Cisco Nexus 9336C-FX2 和 9336C-FX2-T 存储交换机上安装 NX-OS 软件和 RCF 之前，请确保：

* 您的系统可以支持Cisco Nexus 9336C-FX2 和 9336C-FX2-T 存储交换机。
* 您已在Cisco以太网交换机页面上查阅了交换机兼容性表，以了解支持的ONTAP、NX-OS 和 RCF 版本。
* 您已参考Cisco网站上提供的相应软件和升级指南。
* 您已下载适用的 RCF 文件。
* 现有网络配置具有以下特点：
+
** Cisco以太网交换机页面包含交换机上最新的 RCF 和 NX-OS 版本。
** 两台交换机都必须具备管理连接功能。


* 替代CiscoNexus 9336C-FX2 交换机具有以下特点：
+
** 管理网络连接正常。
** 已具备对替换开关的控制台访问权限。
** 将相应的 RCF 和 NX-OS 操作系统映像加载到交换机上。
** 交换机的初始配置已完成。




.关于此任务
此过程将第二个 Nexus 9336C-FX2 存储交换机 s2 替换为新的 9336C-FX 交换机 ns2。两个节点分别是 cluster1-01 和 cluster1-02。

完成步骤：

* 确认要更换的交换机为 s2。
* 从交换机 s2 上拔下电缆。
* 将电缆重新连接到交换机 ns2。
* 验证交换机 ns2 上的所有设备配置。
+

NOTE: RCF 和 NX-OS 版本中的命令语法可能存在依赖关系。



.步骤
. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
_x_ 是维护窗口的持续时间，单位为小时。

. 检查存储节点端口的运行状况，以确保已连接到存储交换机 s1：
+
`storage port show -port-type ENET`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
cluster1-02
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
.
.
----
====
. 验证存储交换机 s1 是否可用：
+
`network device-discovery show`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
cluster1-01/cdp
           e5a   s1                        Ethernet1/1 NX9336C
           e4a   cluster1-02               e4a         AFF-A700
           e4e   cluster1-02               e4e         AFF-A700
cluster1-01/lldp
           e5a   s1                        Ethernet1/1 -
           e4a   cluster1-02               e4a         -
           e4e   cluster1-02               e4e         -
cluster1-02/cdp
           e3b   s1                        Ethernet1/2 NX9336C
           e4a   cluster1-01               e4a         AFF-A700
           e4e   cluster1-01               e4e         AFF-A700
cluster1-02/lldp
           e3b   s1                        Ethernet1/2 -
           e4a   cluster1-01               e4a         -
           e4e   cluster1-01               e4e         -
.
.
----
====
. 掌控全场 `lldp neighbors`在工作交换机上执行命令，确认可以看到两个节点和所有机架：
+
`show lldp neighbors`

+
.显示示例
[%collapsible]
====
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
cluster1-01      Eth1/1       121          S             e5a
cluster1-02      Eth1/2       121          S             e5a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====
. 验证存储系统中的存储架端口：
+
`storage shelf port show -fields remote-device,remote-port`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   s1
3.20    1   -             -
3.20    2   Ethernet1/6   s1
3.20    3   -             -
3.30    0   Ethernet1/7   s1
3.20    1   -             -
3.30    2   Ethernet1/8   s1
3.20    3   -             -
.
.
----
====
. 拆下连接到存储开关 s2 的所有电缆。
. 将所有电缆重新连接到更换开关 ns2。
. 请重新检查存储节点端口的运行状况：
+
`storage port show -port-type ENET`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
cluster1-02
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
.
.
----
====
. 确认两个交换机均可用：
+
`network device-discovery show`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
cluster1-01/cdp
          e3a  s1                         Ethernet1/1 NX9336C
          e4a  cluster1-02                e4a         AFF-A700
          e4e  cluster1-02                e4e         AFF-A700
          e7b  ns2                       Ethernet1/1 NX9336C
cluster1-01/lldp
          e3a  s1                         Ethernet1/1 -
          e4a  cluster1-02                e4a         -
          e4e  cluster1-02                e4e         -
          e7b  ns2                        Ethernet1/1 -
cluster1-02/cdp
          e3a  s1                         Ethernet1/2 NX9336C
          e4a  cluster1-01                e4a         AFF-A700
          e4e  cluster1-01                e4e         AFF-A700
          e7b  ns2                        Ethernet1/2 NX9336C
cluster1-02/lldp
          e3a  s1                         Ethernet1/2 -
          e4a  cluster1-01                e4a         -
          e4e  cluster1-01                e4e         -
          e7b  ns2                        Ethernet1/2 -
.
.
----
====
. 检查存储系统中的货架端口：
+
`storage shelf port show -fields remote-device,remote-port`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     s1
3.20    1     Ethernet1/5     ns2
3.20    2     Ethernet1/6     s1
3.20    3     Ethernet1/6     ns2
3.30    0     Ethernet1/7     s1
3.20    1     Ethernet1/7     ns2
3.30    2     Ethernet1/8     s1
3.20    3     Ethernet1/8     ns2
storage::*>
----
====
. 如果您已禁用自动创建案例功能，请通过调用AutoSupport消息重新启用该功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.下一步是什么？
更换开关后，您可以 link:../switch-cshm/config-overview.html["配置交换机健康监控"]。
