---
permalink: switch-cisco-9336c-fx2-storage/upgrade-rcf-software-9336c-storage.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: 您可以使用此过程升级您的 RCF 版本。 
---
= 升级您的参考配置文件 (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当您的运行交换机上已安装了现有版本的 RCF 文件时，您需要升级 RCF 版本。

.开始之前
请确保您拥有以下物品：

* 交换机配置的当前备份。
* 一个功能齐全的集群（日志中没有错误或类似问题）。
* 当前的RCF。
* 如果您要更新 RCF 版本，则需要在 RCF 中进行启动配置，以反映所需的启动映像。
+
如果需要更改启动配置以反映当前的启动映像，则必须在重新应用 RCF 之前进行更改，以便在以后的重启中实例化正确的版本。




NOTE: 在此过程中不需要任何可操作的交换机间链路 (ISL)。这是设计使然，因为 RCF 版本的更改可能会暂时影响 ISL 连接。为确保集群运行不中断，以下步骤将所有集群 LIF 迁移到运行伙伴交换机，同时在目标交换机上执行相应步骤。


CAUTION: 安装新的交换机软件版本和 RCF 之前，必须清除交换机设置并执行基本配置。在清除交换机设置之前，您必须使用串行控制台连接到交换机，或者保留基本配置信息。



== 第一步：准备升级

. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 _x_ 为维护窗口的持续时间（小时）。

. 将权限级别更改为高级，并在提示继续时输入 *y*：
+
`set -privilege advanced`

+
出现高级提示符（*>）。

. 显示每个节点上连接到交换机的端口：
+
[source, cli]
----
network device-discovery show
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID) Interface       Platform
----------- ------ ------------------------ --------------- ---------
node1-01/cdp
            e3a    cs1                       Ethernet1/7     N9K-C9336C
            e3b    cs2                       Ethernet1/7     N9K-C9336C
node1-02/cdp
            e3a    cs1                       Ethernet1/8     N9K-C9336C
            e3b    cs2                       Ethernet1/8     N9K-C9336C
.
.
.
----
====
. 验证所有存储端口均处于正常状态：
+
[source, cli]
----
storage port show -port-type ENET
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e3a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
                   e7a ENET  -         100   enabled  online
                   e7b ENET  -         100   enabled  online
node1-02
                   e3a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
                   e7a ENET  -         100   enabled  online
                   e7b ENET  -         100   enabled  online
.
.
.
----
====
. 禁用集群 LIF 的自动回滚功能。
+
`network interface modify -vserver Cluster -lif * -auto-revert false`





== 步骤 2：配置端口

. 在交换机cs1上，关闭与节点所有端口相连的端口。
+
[listing, subs="+quotes"]
----
cs1> *enable*
cs1# *configure*
cs1(config)# *interface eth1/1/1-2,eth1/7-8*
cs1(config-if-range)# *shutdown*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
----
+

CAUTION: 确保关闭所有连接的端口以避免任何网络连接问题。请参阅知识库文章 https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["在切换操作系统升级期间迁移集群 LIF 时，节点脱离仲裁。"^]更多详情请见下文。

. 验证集群 LIF 是否已故障转移到交换机 cs1 上托管的端口。这可能需要几秒钟。
+
[source, cli]
----
network interface show -role cluster
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*

            Logical         Status     Network            Current     Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node        Port    Home
----------- --------------- ---------- ------------------ ----------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.36.44/16   node1-01    e7a     true
            node1-01_clus2  up/up      169.254.7.5/16     node1-01    e7b     true
            node1-02_clus1  up/up      169.254.197.206/16 node1-02    e7a     true
            node1-02_clus2  up/up      169.254.195.186/16 node1-02    e7b     true
            node1-03_clus1  up/up      169.254.192.49/16  node1-03    e7a     true
            node1-03_clus2  up/up      169.254.182.76/16  node1-03    e7b     true
            node1-04_clus1  up/up      169.254.59.49/16   node1-04    e7a     true
            node1-04_clus2  up/up      169.254.62.244/16  node1-04    e7b     true

8 entries were displayed.
----
====
. 验证集群是否运行正常：
+
`cluster show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health  Eligibility   Epsilon
----------------- ------- ------------  -------
node1-01          true    true          false
node1-02          true    true          false
node1-03          true    true          true
node1-04          true    true          false

4 entries were displayed.
----
====
. 如果您尚未保存当前交换机配置，请将以下命令的输出复制到文本文件中：
+
`show running-config`

+
.. 记录当前版本与当前版本之间的任何自定义添加内容。 `running-config`以及正在使用的 RCF 文件（例如贵组织的 SNMP 配置）。
.. 对于 NX-OS 10.2 及更高版本，请使用 `show diff running-config`用于与 bootflash 中保存的 RCF 文件进行比较的命令。否则，请使用第三方差异比较工具。


. 保存基本配置详细信息 `write_erase.cfg`启动闪存上的文件。
+
[NOTE]
====
确保配置以下内容：

** 用户名和密码
** 管理 IP 地址
** 默认网关
** 交换机名称


====
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`

+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`

. 升级到 RCF 版本 1.12 及更高版本时，请运行以下命令：
`cs1# echo "hardware access-list tcam region ing-racl 1024" >> bootflash:write_erase.cfg`
+
`cs1# echo "hardware access-list tcam region egr-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-l2-qos 1280 >> bootflash:write_erase.cfg`

+
请参阅知识库文章link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["如何在保持远程连接的情况下清除Cisco互连交换机上的配置"^]更多详情请见下文。

. 确认 `write_erase.cfg`文件已按预期填充：
+
`*show file bootflash:write_erase.cfg*`

. 问题 `write erase`清除当前已保存配置的命令：
+
`cs1# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. 将之前保存的基本配置复制到启动配置中。
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. 重启交换机：
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 管理 IP 地址恢复正常后，通过 SSH 登录交换机。
+
您可能需要更新与 SSH 密钥相关的 hosts 文件条目。

. 使用以下传输协议之一将 RCF 复制到交换机 cs1 的 bootflash：FTP、TFTP、SFTP 或 SCP。
+
有关Cisco命令的更多信息，请参阅 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 系列 NX-OS 命令参考"^]指南。

+
.显示示例
[%collapsible]
====
此示例展示了如何使用 TFTP 将 RCF 文件复制到交换机 cs1 的启动闪存中：

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *Nexus_9336C_RCF_v1.6-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 将之前下载的 RCF 文件应用到启动闪存中。
+
有关Cisco命令的更多信息，请参阅 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 系列 NX-OS 命令参考"^]指南。

+
此示例展示了 RCF 文件 `NX9336C-FX2-RCF-v1.13-1-Storage.txt`正在交换机 cs1 上安装：

+
[listing, subs="+quotes"]
----
cs1# *copy Nexus_9336C_RCF_v1.6-Storage.txt running-config echo-commands*
----
+
[CAUTION]
====
确保仔细阅读 RCF 的 *安装说明*、*重要说明* 和 *横幅* 部分。您必须阅读并遵循这些说明以确保交换机的正确配置和操作。

====
. 请确认 RCF 文件是否为最新版本：
+
`show running-config`

+
检查输出结果以验证是否拥有正确的 RCF 时，请确保以下信息正确：

+
** RCF横幅
** 节点和端口设置
** 定制
+
输出结果会根据您的网站配置而有所不同。检查端口设置，并参考发行说明，了解您安装的 RCF 版本是否有任何特定更改。



. 将之前对交换机配置所做的任何自定义设置重新应用。
. 确认 RCF 版本、自定义添加项和交换机设置正确后，复制以下内容： `running-config`文件到 `startup-config`文件。
+
有关Cisco命令的更多信息，请参阅 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 系列 NX-OS 命令参考"^]指南。

+
`cs1# *copy running-config startup-config*`

+
`[########################################] 100% Copy complete`

. 重启交换机cs1。在交换机重启期间，您可以忽略节点上报告的“集群交换机健康监视器”警报和“集群端口关闭”事件。
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 验证所有存储端口均处于正常状态：
+
[source, cli]
----
storage port show -port-type ENET
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e3a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
                   e7a  ENET  -          100 enabled  online
                   e7b  ENET  -          100 enabled  online
node1-02
                   e3a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
                   e7a  ENET  -          100 enabled  online
                   e7b  ENET  -          100 enabled  online
.
.
.
----
====
. 验证集群是否运行正常：
+
`cluster show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health   Eligibility   Epsilon
----------------- -------- ------------- -------
node1-01          true     true          false
node1-02          true     true          false
node1-03          true     true          true
node1-04          true     true          false

4 entries were displayed.
----
====
. 在交换机 cs2 上重复步骤 4 至 19。
. 启用集群 LIF 的自动回滚功能。
+
`network interface modify -vserver Cluster -lif * -auto-revert true`





== 步骤 3：验证集群网络配置和集群健康状况

. 确认连接到集群端口的交换机端口已启用。
+
[source, cli]
----
show interface brief
----
. 确认预期节点仍然连接：
+
[source, cli]
----
show cdp neighbors
----
. 使用以下命令验证集群节点是否位于正确的集群 VLAN 中：
+
[source, cli]
----
show vlan brief
----
+
[source, cli]
----
show interface trunk
----
. 确认集群 LIF 已恢复到其原端口：
+
[source, cli]
----
network interface show -role cluster
----
+
如果任何集群 LIF 尚未返回到其源端口，请从本地节点手动将其还原：

+
`network interface revert -vserver vserver_name -lif <lif-name>`

. 验证集群是否运行正常：
+
[source, cli]
----
cluster show
----
. 验证远程集群接口的连接性：
+
.. 你可以使用 `network interface check cluster-connectivity show`用于显示集群连接性可访问性检查详细信息的命令：
+
[source, cli]
----
network interface check cluster-connectivity show
----
.. 或者，您可以使用 `cluster ping-cluster -node <node-name>`检查连接性的命令：
+
[source, cli]
----
cluster ping-cluster -node <node-name>
----




.下一步是什么？
升级 RCF 后，您可以link:configure-ssh-keys.html["验证 SSH 配置"]。
