---
permalink: switch-cisco-9808/configure-install-rcf-9808.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: 在 Cisco Nexus 9808 交换机上安装 RCF，用于新的 AFX 2K 系统安装、主管模块更换或出厂默认重置。 
---
= 在 Cisco Nexus 9808 交换机上安装 RCF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在 Cisco Nexus 9808 交换机上安装参考配置文件 (RCF)，适用于新的 AFX 2K 系统安装、主管模块更换或将交换机重置为出厂默认设置的情况。

.开始之前
* 必须打开交换机电源，并且您必须已完成 link:configure-complete-initial-setup-9808.html["完成初始交换机设置"] 程序。
* 您必须已使用link:configure-install-nxos-9808.html["安装 NX-OS"]过程安装所需的 NX-OS 版本。
* 您必须已阅读link:configure-install-upgrade-rcf-overview-9808.html["安装或升级 RCF 概述"]页面。
* 如果要在交换机上安装 RCF 作为主管模块更换或交换机重置为出厂默认设置的一部分，请验证集群是否完全正常运行，即日志中没有错误或类似问题。
+
如果要在新的 AFX 系统安装过程中安装 RCF，则可以跳过此要求，因为在 AFX 系统安装和设置过程中，此时 AFX 系统中的控制器尚未通电。



.关于此任务
* 如果在新的 AFX 2K 系统安装过程中安装了交换机，则在第一台交换机 (cs1) 上安装参考配置文件 (RCF)，然后使用此过程对第二台交换机 (cs2) 重复上述步骤。
* 此过程仅需要使用 Cisco Nexus 9000 系列交换机命令。
* 本程序中的示例将第一个交换机称为 cs1，将第二个交换机称为 cs2。




[[step-1-prepare-to-install-the-rcf]]
== 步骤 1：准备安装 RCF

通过确保您具有下载 RCF 所需的连接来准备在交换机上安装 RCF，然后下载 RCF。

.步骤
. 您必须能够访问HTTP、FTP或TFTP服务器。通过访问其中一台服务器，您可以下载受支持的RCF版本。
. 从 NetApp 支持站点 link:http://mysupport.netapp.com/["mysupport.netapp.com"^] 下载适用于您的 AFX 系统类型的 RCF。
+

NOTE: 新交换机出厂时未安装 RCF。您必须在交换机上安装 RCF。

. 每台交换机必须连接到控制台，或者您必须能够远程访问每台交换机。
. 您必须使用串行控制台连接到交换机或保留基本配置信息。这是因为 RCF 升级过程要求您清除交换机设置并执行基本配置。




[[step-2-install-the-rcf]]
== 步骤 2：安装 RCF

通过将 RCF 复制并应用于引导闪存、检查横幅输出、验证 RCF 版本是否正确、记录任何自定义添加内容、保存基本配置详细信息、验证 `write_erase.cfg`文件是否已填充、擦除当前保存的配置、将之前保存的基本配置复制到启动配置中，然后重新启动交换机，从而在第一台交换机 (cs1) 上安装 RCF。如果要在新的 AFX 系统安装过程中安装 RCF，请在第二台交换机 (cs2) 上重复这些步骤。

. 使用 SSH 或通过串行控制台登录到交换机 cs1。
. 使用以下传输协议之一将 RCF 复制到交换机 cs1 的 bootflash：FTP、TFTP、SFTP 或 SCP。
+
有关 Cisco 命令的更多信息，请参见 https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 系列 NX-OS 命令参考"^]指南中的相应指南。

+
`copy <protocol>: bootflash: vrf management`

+
.显示示例
[%collapsible]
====
此示例展示了如何使用 TFTP 将 RCF 文件复制到交换机 cs1 的启动闪存中：

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *RCF-v10.1-NX9808-CL1-ST1.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 应用先前复制到引导闪存的 RCF。
+
有关 Cisco 命令的更多信息，请参见 https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 系列 NX-OS 命令参考"^]指南中的相应指南。

+
此示例显示了在交换机 cs1 上安装的 RCF 文件 `RCF-v10.1-NX9808-CL1-ST1.txt`：

+
[listing, subs="+quotes"]
----
cs1# *copy RCF-v10.1-NX9808-CL1-ST1.txt running-config echo-commands*
----
. 检查横幅输出 `show banner motd`命令。您必须阅读并遵循这些说明以确保交换机的正确配置和操作。
+
.显示示例
[%collapsible]
====
[listing]
----
cs1# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : NX9808
* Filename : RCF-v10.1-NX9808-CL1-ST1.txt
* Date     : 06-15-2026
* Version  : v10.1
* Port Usage:
* Ports   1-18 (LC1-LC8) : 400GbE Cluster/Storage/HA ports.
* Ports   19-35 (LC1-LC8): 4 * 100 GbE Storage shelf ports, int e1-e8/{19-35}/1-4
* Port    36 (LC1-LC8)   : Intra-Cluster ISL Ports, int e1-e8/36
* IMPORTANT NOTES
* Interface port-channel998/9 is reserved to identify the version of this file.

******************************************************************************
----
====
. 验证 RCF 版本是否正确：
+
`show running-config`

+
检查输出结果以验证是否拥有正确的 RCF 时，请确保以下信息正确：

+
** RCF横幅
** 节点和端口设置
** 定制
+
输出结果会根据您的网站配置而有所不同。检查端口设置，并参考发行说明，了解您安装的 RCF 版本是否有任何特定更改。



. 将当前运行配置复制到启动配置以使其持久化。
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. 重启交换机：
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 在交换机 cs2 上重复这些步骤。


.下一步是什么？
在交换机中安装 RCF 后，您 link:configure-verify-ssh-9808.html["验证日志收集的 SSH"]。
