---
permalink: switch-cisco-9808/configure-complete-initial-setup-9808.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9808 
summary: 使用配置向导完成 Cisco Nexus 9808 交换机的初始设置，适用于新 AFX 2K 系统安装、主管模块更换或出厂默认重置。 
---
= 在 Cisco Nexus 9808 交换机上完成初始设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用配置向导完成 Cisco Nexus 9808 交换机的初始设置。本程序适用于新的 AFX 2K 系统安装、主管模块更换以及交换机重置为出厂默认设置。

.开始之前
确保您拥有每台交换机的网络和配置信息以及适用的许可证。

.关于此任务
* 您必须在每台交换机上完成初始设置。
* 如果需要，您可以参考您的 NX-OS 版本的 link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/106x/configuration/fundamentals/cisco-nexus-9000-series-nx-os-fundamentals-configuration-guide-release-106x.html["Cisco Nexus 9000 系列交换机 NX-OS 软件配置指南"^]，了解有关设置交换机的信息，请参阅"使用 Cisco NX-OS 设置实用程序"一章。您还可以在"配置终端设置和会话"一章中找到有关终端设置的信息。


.步骤
. 将笔记本电脑连接到交换机的串行控制台端口。
+
.. 使用 N-8-1 将笔记本电脑上的串行控制台端口设置为 9,600 波特。


. 根据提示设置管理员用户的密码。
. 通过回答以下问题来完成初始交换机设置。
+

NOTE: 您网站的安全策略定义了要启用的响应和服务。

+
[cols="1,2"]
|===
| 迅速的 | 响应 


 a| 
中止自动配置并继续进行正常设置？  （是/否）
 a| 
请回答“是”。默认值为否。



 a| 
您是否希望强制执行安全密码标准？  （是/否）
 a| 
请回答“是”。默认值为“是”。



 a| 
请输入管理员密码。
 a| 
默认密码为“`admin`”；您必须创建一个新的、强密码。弱密码可能会被拒绝。



 a| 
您想进入基本配置对话框吗？  （是/否）
 a| 
在交换机的初始配置阶段，请回答“是”。



 a| 
创建另一个登录帐户？  （是/否）
 a| 
答案取决于您网站关于备用管理员的政策。默认值为*否*。



 a| 
配置只读 SNMP 团体字符串？  （是/否）
 a| 
回答“不”。默认值为否。



 a| 
配置读写 SNMP 团体字符串？  （是/否）
 a| 
回答“不”。默认值为否。



 a| 
请输入交换机名称。
 a| 
请输入交换机名称，字数限制为 63 个字母数字字符。



 a| 
继续进行带外（mgmt0）管理配置？  （是/否）
 a| 
在该提示出现时，请回答“是”（默认值）。在 mgmt0 IPv4 地址提示符处，输入您的 IP 地址：ip_address。



 a| 
配置默认网关？  （是/否）
 a| 
请回答“是”。在默认网关的 IPv4 地址提示符处，输入您的默认网关。



 a| 
配置高级 IP 选项？  （是/否）
 a| 
回答“不”。默认值为否。



 a| 
启用 Telnet 服务？  （是/否）
 a| 
回答“不”。默认值为否。



 a| 
已启用 SSH 服务？  （是/否）
 a| 
请回答“是”。默认值为“是”。


NOTE: 在使用以太网交换机运行状况监视器 (CSHM) 的日志收集功能时，建议使用 SSH。此外，建议使用 SSHv2 以增强安全性。



 a| 
请输入要生成的 SSH 密钥类型（dsa/rsa/rsa1）。
 a| 
默认值为 *rsa*。



 a| 
请输入密钥位数（1024-2048）。
 a| 
请输入1024到2048之间的密钥位数。



 a| 
配置NTP服务器？  （是/否）
 a| 
回答“不”。默认值为否。



 a| 
配置默认接口层（L3/L2）
 a| 
请用*L2*回复。默认值为 L2。



 a| 
配置交换机端口接口的默认状态（关闭/不关闭）
 a| 
回复 *noshut*。默认设置为 noshut。



 a| 
配置 CoPP 系统配置文件（严格/中等/宽松/严格）
 a| 
回复时请使用 *strict*。默认设置为严格。



 a| 
您想修改配置吗？  （是/否）
 a| 
此时您应该可以看到新的配置。请检查并对您刚刚输入的配置进行必要的更改。如果对配置满意，请在提示时回答“否”。如果要编辑配置设置，请回复“是”。



 a| 
使用此配置并保存？  （是/否）
 a| 
回复“是”以保存配置。这会自动更新启动镜像和系统镜像。


NOTE: 如果此时不保存配置，下次重启交换机时，所有更改都将失效。

|===
. 在设置结束时显示的界面中，确认您所做的配置选择，并确保保存配置。


.下一步是什么？
完成初始交换机设置后，即可link:configure-review-cabling-config-requirements-9808.html["查看布线和配置要求"]。
