---
permalink: switch-cisco-9808/configure-install-upgrade-rcf-overview-9808.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9808 
summary: 在 Cisco Nexus 9808 交换机上安装或升级 RCF，用于 AFX 2K 系统安装、supervisor 模块更换或支持新硬件或 ONTAP 版本。 
---
= 了解如何在 Cisco Nexus 9808 交换机上安装或升级 RCF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在 Cisco Nexus 9808 交换机上安装或升级参考配置文件 (RCF)。为 AFX 2K 系统安装或主管模块更换安装新的 RCF，或升级现有的 RCF 以支持新的硬件或 ONTAP 版本。


NOTE: RCF 安装或升级独立于 NX-OS 安装或升级。如果您要安装或升级 NX-OS 和 RCF，建议您先安装或升级 NX-OS。



[[understand-the-supported-rcf-versions]]
=== 了解支持的 RCF 版本

AFX 系统上运行的 ONTAP 版本以及 Cisco Nexus 9808 交换机上的 NX-OS 版本决定了交换机支持的 RCF 版本。RCF 版本具有预设的端口速度配置，可确定有多少交换机端口处于分路模式（4x100GbE）和非分路模式。

[NOTE]
====
要查看支持的 RCF 版本的当前列表，请参阅 link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["NetApp Cisco 以太网交换机"^]。

交换机端口信息也可在 link:https://hwu.netapp.com["NetApp Hardware Universe"^] 中找到。

====

NOTE: 有关特定端口和 VLAN 使用情况的详细信息，请参见 RCF 中的横幅和重要注意事项部分。有关详细信息，请参见 link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["NetApp Cisco 以太网交换机"^]。

例如，下表显示了基于 RCF 版本 10.1 的交换机端口的预设组、端口速度和使用情况。

[cols="1,2"]
|===
| 交换机端口组 | 端口速度和使用率 


 a| 
Ethernet1/1 到 Ethernet1/18
 a| 
用于集群内、HA 和存储架连接的 400GbE 模式



 a| 
Ethernet1/19 到 Ethernet1/35
 a| 
用于集群内、HA 和存储连接的 4x100GbE 模式



 a| 
Ethernet1/36
 a| 
400GbE 集群内 ISL 连接

|===


[[change-port-speed-configuration]]
=== 更改端口速度配置

对于具有 RCF 10.1 及更高版本的交换机，当需要为 AFX 系统适应不同的端口速度配置时，可以更改端口速度配置，以调整分路模式（4x100GbE）和非分路模式（400GbE）下的交换机端口数。所做的任何端口修改都是根据当前使用的线路卡进行的。

您在 RCF 安装或 RCF 升级过程中执行此更改。这些步骤将引导您访问此页面。

您可以在两个交换机上输入命令。

[cols="1,2"]
|===
| 更改端口速度 | 步骤 


 a| 
将非分支端口更改为分支端口
 a| 
. 在命令行界面中进入配置模式。
. 修改交换机上的端口速度和分路模式：
+
要指定分线端口，请使用 `interface breakout module`命令。

+
例如，要将 400GbE 模式端口 19-22 指定为分支（4x100GbE）端口，请使用以下方法：

+
`interface breakout module 1 port 19-22 map 100g-4x`

. 使用需要使用端口配置文件以获得所需端口速度的新端口修改端口列表。
+
例如，要使用新端口 19-22 修改 100G 速度端口配置文件的端口列表，请使用以下命令：

+
`interface e1/19/1-4, e1/20/1-4, e1/21/1-4, e1/22/1-4`

. 对交换机分支端口（4x100GbE）进行 100GbE 的硬编码。如果不对速度进行硬编码，则端口将不会打开并处于错误禁用状态：
+
`speed 100000`

+
`no negotiate auto`





 a| 
将分支端口恢复为非分支端口
 a| 
. 在命令行界面中进入配置模式。
. 要将分支端口返回到非分支端口，请在配置模式下使用 `no interface breakout`命令。
+
例如，要将端口 19-22 返回到 400GbE 模式，请使用以下命令：

+
`no interface breakout module 1 port 19-22`



|===


[[suggested-documentation]]
=== 建议的文档

在交换机上安装或升级 RCF 之前，建议您查看以下文档：

* 有关安装或升级 RCF 的详细信息，请参见 NetApp 知识库文章link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["如何在保持远程连接的情况下清除Cisco互连交换机上的配置"^]。
* 请参见  https://hwu.netapp.com/SWITCH/INDEX["NetApp Hardware Universe"^] 以验证您平台上的正确端口。
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco以太网交换机（NSS）"^]
+
请参阅NetApp支持网站上的交换机兼容性表格，了解支持的ONTAP和 RCF 版本。请注意，RCF 中的命令语法与特定版本的 NX-OS 中的语法之间可能存在命令依赖关系。

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["CiscoNexus 9000 系列交换机"^]
+
有关Cisco交换机升级和降级程序的完整文档，请参阅Cisco网站上提供的相应软件和升级指南。



.下一步是什么？
在查看安装或升级 RCF 概述后，您可以根据需要link:configure-install-rcf-9808.html["安装 RCF"]或link:configure-upgrade-rcf-9808.html["升级 RCF"]。
