---
permalink: switch-cisco-9808/configure-install-nxos-9808.html 
sidebar: sidebar 
keywords: procedure, install, nx-os, software, nexus, cluster, switch, install the nx-os software - cisco nexus 9808 
summary: 在 Cisco Nexus 9808 交换机上安装 NX-OS，以用于新的 AFX 2K 系统安装、主管模块更换或出厂默认重置。 
---
= 在 Cisco Nexus 9808 交换机上安装 NX-OS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在 Cisco Nexus 9808 交换机上安装 NX-OS，适用于新的 AFX 2K 系统安装、主管模块更换或将交换机重置为出厂默认设置。

.开始之前
* 必须打开交换机电源，并且您必须已完成 link:configure-complete-initial-setup-9808.html["完成初始交换机设置"] 程序。
* 如果要在交换机上安装 NX-OS 作为新 AFX 系统安装或 supervisor 模块更换的一部分，请验证交换机上的 NX-OS 版本是否为当前 NetApp 支持的版本。
+
** 如果您的交换机具有当前 NetApp 支持的版本，则无需安装 NX-OS。您需要安装参考配置文件 (RCF)。从 link:configure-install-upgrade-rcf-overview-9808.html["安装或升级 RCF 概述"] 开始。
** 如果您的交换机没有当前 NetApp 支持的版本，请继续执行此过程以安装 NX-OS。


* 如果要在交换机上安装 NX-OS 作为交换机更换或交换机重置为出厂默认设置的一部分，请验证集群是否完全正常运行，即日志中没有错误或类似问题。
* 如果要在新的 AFX 系统安装过程中安装 NX-OS，则可以跳过此要求，因为在 AFX 系统安装和设置过程中，此时 AFX 系统中的控制器尚未通电。


.关于此任务
* AFX 系统上运行的 ONTAP 版本决定了交换机支持的 NX-OS 版本。
+
** 对于 AFX 2K 系统中的交换机，支持运行 ONTAP 9.19.1GA 或更高版本以及 NX-OS 10.6(3) 或更高版本。
+
要查看支持的 NX-OS 版本的当前列表，请参阅 link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["NetApp Cisco 以太网交换机"^]。



* 此过程仅需要使用 Cisco Nexus 9000 系列交换机命令。
* 本程序中的示例将第一个交换机称为 cs1，将第二个交换机称为 cs2。
* 如果在新的 AFX 2K 系统安装过程中安装了交换机，则在第一台交换机（cs1）上安装 NX-OS，然后使用此过程对第二台交换机（cs2）重复上述步骤。




[[step-1-prepare-to-install-the-nx-os]]
== 步骤 1：准备安装 NX-OS

通过确保您有权访问具有受支持的 NX-OS 版本的服务器、下载 NX-OS、连接到管理网络以进行文件传输，然后验证与服务器的连接，准备在交换机上安装 NX-OS。

.步骤
. 您必须能够访问 HTTP、SFTP、FTP 或 TFTP 服务器。通过访问其中一台服务器，您可以下载受支持的 NX-OS 版本。
. 从 https://software.cisco.com/download/home["Cisco软件下载"^]页面将正确版本的 NX-OS 和 EPLD 映像下载到交换机。
. 将交换机连接到管理网络（用于文件传输）。
. 使用 `ping`命令验证与托管 NX-OS 的服务器的连接。
+
`ping <IP address>`

+
.显示示例
[%collapsible]
====
此示例验证交换机可以访问 IP 地址为 172.19.2.1 的服务器：

[listing, subs="+quotes"]
----
cs1# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====




[[step-2-install-the-nx-os-and-epld-image]]
== 步骤 2：安装 NX-OS 和 EPLD 映像

通过安装和验证 NX-OS 和 EPLD 映像版本，在第一台交换机 (cs1) 上安装 NX-OS 和 EPLD 映像，然后，如果您将 NX-OS 作为新 AFX 系统安装的一部分进行安装，则在第二台交换机 (cs2) 上重复这些步骤。

. 将 NX-OS 和 EPLD 映像复制到第一台交换机。
+
`copy <protocol>: bootflash: vrf management`

+
.显示示例
[%collapsible]
====
示例使用 sftp。

[listing, subs="+quotes"]
----
cs1# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos64-s1.10.6.3.F.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> *progress*
  Progress meter enabled
sftp> *get code/nxos64-s1.10.6.3.F.bin /bootflash/nxos64-s1.10.6.3.F.bin*
/code/nxos64-s1.10.6.3.F.bin  100% 1261MB   9.3MB/s   02:15
sftp> *exit*
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. 验证正在运行的 NX-OS 版本：
+
`show version`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.5(3)(F) [Feature Release]
  Host NXOS: version 10.5(3)(F)
  BIOS compile time:  11/25/2024
  NXOS image file is: bootflash:///nxos64-s1.10.5.3.F.bin
  NXOS compile time:  02/27/2026 12:00:00 [03/14/2026 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco Nexus9000 C9808 Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLMXXXXXXXX
  Device name: cs1
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Mar 5 15:55:08 2026
  Reason: Reset Requested by CLI command reload
  System version: 10.5(3)(F)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):

cs1#
----
====
. 安装 NX-OS 和 EPLD 映像。
+
安装镜像文件后，每次交换机重启时都会加载该文件。

+
`install all nxos bootflash:nxos.<image_file>.bin`

+
.显示示例
[%collapsible]
====
示例使用 NX-OS 版本 10.6(3)(F)。

[listing, subs="+quotes"]
----
cs1# *install all nxos bootflash:nxos64-s1.10.6.3.F.bin*

Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos64-s1.10.6.3.F.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos64-s1.10.6.3.F.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos64-s1.10.6.3.F.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  Bootable  Impact          Install-type  Reason
------  --------  --------------- ------------  ---------
  1     yes       Disruptive      Reset         Default upgrade is not hitless



Images will be upgraded according to following table:

Module   Image    Running-Version(pri:alt)                 New-Version         Upg-Required
------- --------- ---------------------------------------- ------------------- ------------
  1      nxos     10.5(3)(F)                               10.6(3)(F)          Yes
  1      bios     xx.xx.:xx.xx                             xxx                 No


Switch will be reloaded for disruptive upgrade.

Do you want to continue with the installation (y/n)? [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS

Finishing the upgrade, switch will reboot in 10 seconds.
----
====
. 在交换机重新启动后，验证新版本的 NX-OS：
+
`show version`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.6(3)(F) [Feature Release]
  Host NXOS: version 10.6(3)(F)
  BIOS compile time:  11/25/2024
  NXOS image file is: bootflash:///nxos64-s1.10.6.3.F.bin
  NXOS compile time:  05/30/2026 12:00:00 [06/14/2026 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco Nexus9000 C9808 Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLMXXXXXXXX
  Device name: cs1
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Jun 5 15:55:08 2026
  Reason: Reset Requested by CLI command reload
  System version: 10.6(3)(F)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):

cs1#
----
====
. 确认已成功加载新版本的 EPLD：
+
`show install epld status`

+
.显示示例
[%collapsible]
====
该示例使用 EPLD 版本 10.6(3)(F)。

[listing, subs="+quotes"]
----
cs1# *show install epld status*

1) Module 2 upgraded on Mon May  4 09:17:08 2026 (631239  us)
EPLD Install Image: EPLD image file 10.6.3.F. built on Fri Apr 24 19:49:50 2026

Status: EPLD Upgrade was Successful

EPLD                             Curr Ver       Old Ver
-------------------------------------------------------
MI FPGA                         0x10014         0x1000b
IO FPGA                         0x10033         0x10006

2) Module 27 upgraded on Wed Apr  1 15:03:13 2026 (193093  us)
EPLD Install Image: EPLD image file 10.6.3.F. built on Mon Mar 16 03:28:47 2026

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
IO FPGA                         0x1002d         0x10020

3) Module 28 upgraded on Wed Apr  1 14:59:53 2026 (843907  us)
EPLD Install Image: EPLD image file 10.6.3.F. built on Mon Mar 16 03:28:47 2026

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
IO FPGA                         0x1002d         0x10020

4) Module 27 upgraded on Fri Mar 27 21:55:55 2026 (132290  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

5) Module 27 upgraded on Fri Mar 27 21:50:16 2026 (  4899  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

6) Module 27 upgraded on Fri Mar 27 21:44:36 2026 (775397  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

7) Module 27 upgraded on Fri Mar 27 21:38:58 2026 (330582  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

8) Module 27 upgraded on Fri Mar 27 21:33:19 2026 (112679  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

9) Module 27 upgraded on Fri Mar 27 21:27:41 2026 (957182  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

10) Module 27 upgraded on Fri Mar 27 21:22:03 2026 ( 90303  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
FM-19 FPGA                      0x10006         0x10000
FM-20 FPGA                      0x10006         0x10000
FM-21 FPGA                      0x10006         0x10000
FM-22 FPGA                      0x10006         0x10000
FM-23 FPGA                      0x10006         0x10000
FM-24 FPGA                      0x10006         0x10000
FM-25 FPGA                      0x10006         0x10000
FM-26 FPGA                      0x10006         0x10000

11) Module 1 upgraded on Fri Mar 27 21:16:24 2026 (240369  us)
EPLD Install Image: EPLD image file 10.6.2.F. built on Fri Dec 12 11:15:18 2025

Status: EPLD Upgrade was Successful

EPLD                            Curr Ver        Old Ver
-------------------------------------------------------
MI FPGA                         0x10014         0x1000b
IO FPGA                         0x10033         0x10006
cs1#
----
====
. 如果要在新 AFX 系统安装过程中安装 NX-OS，请重复以下步骤在交换机 cs2 上安装 NX-OS 和 EPLD 映像。


.下一步是什么？
在交换机上安装 NX-OS 后，请从 link:configure-install-upgrade-rcf-overview-9808.html["安装或升级 RCF 概述"] 开始安装 RCF。
