---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switched-configuration-dat-storage.html 
keywords:  
summary:  
---
= 从交换式配置迁移到直连存储
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以通过添加两个新的共享交换机，从具有直连存储的交换式配置迁移到共享式配置。

.支持的交换机
支持以下交换机：

* Nexus 9336C-FX2
* Nexus 3232C


此过程中支持的ONTAP和 NX-OS 版本请参见Cisco以太网交换机页面。看 https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco以太网交换机"]。

.连接端口
交换机使用以下端口连接到节点：

* Nexus 9336C-FX2：
+
** 端口 1-3：分支模式 (4x10G) 集群内端口，内部 e1/1/1-4、e1/2/1-4、e1/3/1-4
** 端口 4-6：分支模式 (4x25G) 集群内/高可用性端口，内部 e1/4/1-4、e1/5/1-4、e1/6/1-4
** 端口 7-34：40/100GbE 集群内/高可用性端口，内部 e1/7-34


* Nexus 3232C：
+
** 端口 1-30：10/40/100 GbE


* 这些交换机使用以下交换机间链路（ISL）端口：
+
** 端口 int e1/35-36：Nexus 9336C-FX2
** 端口 e1/31-32：Nexus 3232C




这 https://hwu.netapp.com["Hardware Universe"]包含有关所有集群交换机支持的布线信息。

.你需要什么
* 请确保您已完成以下任务：
+
** 将 Nexus 9336C-FX2 交换机上的一些端口配置为以 100 GbE 运行。
** 规划、迁移并记录了从节点到 Nexus 9336C-FX2 交换机的 100 GbE 连接。
** 将其他Cisco集群交换机从ONTAP集群无中断地迁移到Cisco Nexus 9336C-FX2 网络交换机。


* 现有交换网络已正确设置并正常运行。
* 所有端口均处于*开启*状态，以确保运行不中断。
* Nexus 9336C-FX2 交换机已配置并运行在已安装的正确版本的 NX-OS 和已应用的参考配置文件 (RCF) 下。
* 现有网络配置如下：
+
** 使用较旧的Cisco交换机构建冗余且功能齐全的NetApp集群。
** 对旧款Cisco交换机和新款交换机的管理连接和控制台访问。
** 集群中所有处于 *up* 状态的 LIF 都位于其主端口上。
** ISL 端口已启用，并且已在其他Cisco交换机之间以及新交换机之间连接了电缆。




.关于示例
本流程中的示例使用以下开关和节点命名规则：

* 现有的Cisco Nexus 3232C 集群交换机是 _c1_ 和 _c2_。
* 新的 Nexus 9336C-FX2 交换机型号为 _sh1_ 和 _sh2_。
* 节点分别为 _node1_ 和 _node2_。
* 节点 1 上的集群 LIF 分别为 _node1_clus1_ 和 _node1_clus2_，节点 2 上的集群 LIF 分别为 _node2_clus1_ 和 _node2_clus2_。
* 首先将交换机 c2 替换为交换机 sh2，然后将交换机 c1 替换为交换机 sh1。


.步骤
. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=x h`

+
其中 x 为维护窗口的持续时间（小时）。

. 检查每个集群端口的管理和运行状态。
. 确认集群所有端口均已启动且状态正常：
+
`network port show –role cluster`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
====


. [[步骤4]]验证所有集群接口（LIF）是否都在主端口上：
+
`network interface show -role cluster`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
====


. [[步骤5]]验证集群是否显示两个集群交换机的信息：
+
`system cluster-switch show -is-monitoring-enabled-operational true`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
====


. [[step6]]禁用集群 LIF 的自动还原功能。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
====


. [[step7]]关闭 c2 交换机。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
c2# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# *interface ethernet <int range>*
c2(config)# *shutdown*
----
====


. [[步骤8]]验证集群 LIF 是否已迁移到集群交换机 sh1 上托管的端口：
+
`network interface show -role cluster`

+
这可能需要几秒钟。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
====


. [[step9]]将交换机 c2 替换为新的交换机 sh2，并重新连接新交换机的电缆。
. 请确认 sh2 上的端口是否已恢复正常。  *注意* LIF 仍然在交换机 c1 上。
. 关闭 c1 交换机。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# *interface ethernet <int range>*
c1(config)# *shutdown*
----
====


. [[step12]]验证集群 LIF 是否已迁移到集群交换机 sh2 上托管的端口。这可能需要几秒钟。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
====


. [[step13]]将交换机 c1 更换为新的交换机 sh1，并重新连接新交换机的电缆。
. 请确认 sh1 上的端口是否已恢复正常。  *注意* LIF 仍然在交换机 c2 上。
. 启用集群 LIF 的自动回滚功能：
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert True*
----
====


. [[步骤16]]验证集群是否健康：
+
`cluster show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----
====


.下一步是什么？
交换机迁移完成后，您可以…… link:../switch-cshm/config-overview.html["配置交换机健康监控"]。
