---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switchless-cluster-dat-storage.html 
keywords:  
summary:  
---
= 从具有直连存储的无交换机集群迁移
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以通过添加两个新的共享交换机从具有直连存储的无交换机集群进行迁移。

您使用的操作步骤取决于每个控制器上是有两个专用集群网络端口，还是每个控制器上有一个集群端口。记录的过程适用于使用光纤或双轴端口的所有节点、但如果节点使用板载10 Gb Base-T RJ45端口作为集群网络端口、则此交换机不支持此过程。

大多数系统需要在每个控制器上使用两个专用集群网络端口。请参见 https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 以太网交换机"] 有关详细信息 ...

如果您现有的双节点无交换机集群环境，则可以使用 Cisco Nexus 9336C-FX2 交换机迁移到双节点有交换机集群环境，以便可以扩展到集群中的两个节点以上。



== 查看要求

确保：

* 对于双节点无交换机配置：
+
** 双节点无交换机配置已正确设置并正常运行。
** 这些节点运行的是ONTAP 9.8及更高版本。
** 所有集群端口均处于*启动*状态。
** 所有集群逻辑接口(LIF)均处于*启动*状态、并位于其*主端口上。


* 对于Cisco Nexus 9336C-x2交换机配置：
+
** 这两台交换机都具有管理网络连接。
** 可以通过控制台访问集群交换机。
** Nexus 9336C-f2节点到节点交换机和交换机到交换机连接使用双轴电缆或光缆。
** NetApp https://hwu.netapp.com["Hardware Universe"] 包含有关布线的详细信息。
** 交换机间链路(ISL)缆线连接到两个9336C-x2交换机上的端口1/35和1/36。


* 9336C-x2交换机的初始自定义已完成。这样：
+
** 9336C-x2 交换机正在运行最新版本的软件
** 参考配置文件（ Reference Configuration Files ， RCF ）已应用于交换机
** 在新交换机上配置任何站点自定义、例如SMTP、SNMP和SSH。






== 迁移交换机

.关于示例
此操作步骤中的示例使用以下集群交换机和节点命名：

* 9336C-fx2 交换机的名称是 _CS1_ 和 _CS2_ 。
* 集群 SVM 的名称是 _node1_ 和 _node2_ 。
* LIF 的名称分别是节点 1 上的 _node1_clus1_ 和 _node1_clus2_ 以及节点 2 上的 _node2_clus1_ 和 _node2_clus2_ 。
* cluster1 ：：： * > 提示符指示集群的名称。
* 根据 AFF A400 控制器，此操作步骤中使用的集群端口为 _e3A_ 和 _e3b_ 。。 https://hwu.netapp.com["Hardware Universe"] 包含有关平台的实际集群端口的最新信息。




=== 第1步：从直接连接的无交换机集群迁移

. 如果在此集群上启用了 AutoSupport ，请通过调用 AutoSupport 消息来禁止自动创建案例： `ssystem node AutoSupport invoke -node * -type all -message MAINT=xh` 。
+
其中 x 是维护时段的持续时间，以小时为单位。




NOTE: AutoSupport 消息会通知技术支持此维护任务，以便在维护窗口期间禁止自动创建案例。

. 【第2步】将权限级别更改为高级、在系统提示您继续时输入y：
+
`set -privilege advanced`

+
此时将显示高级提示符（ * > ）。

. 在新集群交换机 CS1 和 CS2 上禁用所有面向节点的端口（而不是 ISL 端口）。不得禁用 ISL 端口。
+
.显示示例
[%collapsible]
====
以下示例显示了交换机 CS1 上面向节点的端口 1 到 34 已禁用：

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *shutdown*
----
====


. 【第4步】验证端口1/35和1/36上的ISL和两个9336C-x2交换机CS1和CS2之间的ISL物理端口是否已启动：
+
`s如何执行端口通道摘要`

+
.显示示例
[%collapsible]
====
以下示例显示交换机 CS1 上的 ISL 端口已启动：

[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
以下示例显示交换机 CS2 上的 ISL 端口已启动：

[listing, subs="+quotes"]
----
       cs2# *show port-channel summary*
        Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
====


. 【第5步】显示相邻设备的列表：
+
`s如何使用 cdp 邻居`

+
此命令可提供有关连接到系统的设备的信息。

+
.显示示例
[%collapsible]
====
以下示例列出了交换机 CS1 上的相邻设备：

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 2
----
以下示例列出了交换机 CS2 上的相邻设备：

[listing, subs="+quotes"]
----
cs2# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
====


. 【第6步】验证所有集群端口是否均已启动：
+
`network port show - ipspace Cluster`

+
每个端口都应显示为"Link"(链路)和"Health"(运行状况良好)。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: node2
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.
----
====


. 【第7步】验证所有集群LIF是否均已启动且正常运行：
+
`network interface show - vserver Cluster`

+
对于 `为 Home` ，每个集群 LIF 均应显示 true ，并且状态为 Admin/Oper 为 up/up 。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical     Status     Network            Current       Current Is
Vserver     Interface   Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.
----
====


. 【第8步】验证是否已在所有集群LIF上启用自动还原：
+
`network interface show - vserver Cluster -fields auto-revert`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*
       Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
4 entries were displayed.
----
====


. 【第 9 步】从 node1 上的集群端口 E3A 断开缆线连接，然后使用 9336C-x2 交换机支持的适当布线方式将 E3A 连接到集群交换机 CS1 上的端口 1 。
+
NetApp https://hwu.netapp.com["Hardware Universe"] 包含有关布线的详细信息。

. 从节点 2 上的集群端口 E3A 断开缆线连接，然后使用 9336C-x2 交换机支持的相应布线方式将 E3A 连接到集群交换机 CS1 上的端口 2 。
. 启用集群交换机 CS1 上面向节点的所有端口。
+
.显示示例
[%collapsible]
====
以下示例显示交换机 CS1 上的端口 1/1 到 1/34 已启用：

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *no shutdown*
----
====


. 【第12步】验证所有集群LIF是否均为*已启动*、正常运行且显示为true `Is Home`：
+
`network interface show - vserver Cluster`

+
.显示示例
[%collapsible]
====
以下示例显示 node1 和 node2 上的所有 LIF 均为 * 上 * ，并且 `为主目录` 结果为 * 上 * ：

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current     Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node        Port    Home
--------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2       e3b     true
4 entries were displayed.
----
====


. 【第13步】显示有关集群中节点状态的信息：
+
`cluster show`

+
.显示示例
[%collapsible]
====
以下示例显示了有关集群中节点的运行状况和资格的信息：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====


. 【第 14 步】从 node1 上的集群端口 e3b 拔下缆线，然后使用 9336C-x2 交换机支持的适当布线方式将 e3b 连接到集群交换机 CS2 上的端口 1 。
. 断开节点 2 上集群端口 e3b 的缆线连接，然后使用 9336C-x2 交换机支持的相应布线方式将 e3b 连接到集群交换机 CS2 上的端口 2 。
. 启用集群交换机 CS2 上面向节点的所有端口。
+
.显示示例
[%collapsible]
====
以下示例显示交换机 CS2 上的端口 1/1 到 1/34 已启用：

[listing, subs="+quotes"]
----
cs2# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# *interface e1/1-34*
cs2(config-if-range)# *no shutdown*
----
====


. 【第17步】验证所有集群端口是否均已启动：
+
`network port show - ipspace Cluster`

+
.显示示例
[%collapsible]
====
以下示例显示 node1 和 node2 上的所有集群端口均已启动：

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
----
====


. 【第18步】验证所有接口是否均为true `Is Home`：
+
`network interface show - vserver Cluster`

+

NOTE: 完成此操作可能需要几分钟时间。

+
.显示示例
[%collapsible]
====
以下示例显示 node1 和 node2 上的所有 LIF 均为 * 上 * ，并且 `为主目录` 结果为 true ：

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true
4 entries were displayed.
----
====


. 【第19步】验证两个节点各自与每个交换机之间是否有一个连接：
+
`s如何使用 cdp 邻居`

+
.显示示例
[%collapsible]
====
以下示例显示了这两个交换机的相应结果：

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3a
node2              Eth1/2         133    H           AFFA400       e3a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3b
node2              Eth1/2         133    H           AFFA400       e3b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
====


. 【第20步】显示有关集群中发现的网络设备的信息：
+
`network device-discovery show -protocol cdp`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2       /cdp
            e3a    cs1                       0/2               N9K-C9336C
            e3b    cs2                       0/2               N9K-C9336C

node1       /cdp
            e3a    cs1                       0/1               N9K-C9336C
            e3b    cs2                       0/1               N9K-C9336C
4 entries were displayed.
----
====


. 【第21步】验证HA对1 (和HA对2)的存储配置是否正确且无错误：
+
`system switch ethernet show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------- --------------- ----------
sh1
                          storage-network        172.17.227.5    C9336C

       Serial Number: FOC221206C2
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====


. 【第22步】验证这些设置是否已禁用：
+
`network options switchless-cluster show`

+

NOTE: 完成此命令可能需要几分钟的时间。等待 " 三分钟生命周期到期 " 公告。

+
以下示例中的 `false` 输出显示配置设置已禁用：

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
====


. 【第23步】验证集群中节点成员的状态：
+
`cluster show`

+
.显示示例
[%collapsible]
====
以下示例显示了有关集群中节点的运行状况和资格的信息：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====


. 【第24步】确保集群网络具有完全连接：
+
`cluster ping-cluster -node node-name`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====


. 【第25步】将权限级别改回管理员：
+
`set -privilege admin`





=== 第2步：设置共享交换机

此操作步骤中的示例使用以下交换机和节点命名：

* 两个共享交换机的名称分别为 _SH1_ 和 _SH2_ 。
* 节点为 _node1_ 和 _node2_ 。



NOTE: 操作步骤要求同时使用 ONTAP 命令和 Cisco Nexus 9000 系列交换机命令，除非另有说明，否则会使用 ONTAP 命令。

. 验证HA对1 (和HA对2)的存储配置是否正确且无错误：
+
`system switch ethernet show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------  --------------- -------
sh1
                          storage-network        172.17.227.5    C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. 验证存储节点端口是否运行正常：
+
`storage port show -port-type ENET`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage          100      enabled  online        30
        e5a     ENET   storage          100      enabled  online        30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage           100      enabled  online        30
        e5a     ENET  storage           100      enabled  online        30
        e5b     ENET  storage           100      enabled  online        30
----
====


. 【第 3 步】将 HA 对 1 的 NSM224 路径 A 端口移至 SH1 端口范围 11-22 。
. 安装从 HA 对 1 节点 1 路径 A 到 SH1 端口范围 11-22 的缆线。例如， AFF A400 上的存储端口路径为 e0c 。
. 安装从 HA 对 1 节点 2 路径 A 到 SH1 端口范围 11-22 的缆线。
. 验证节点端口是否运行正常：
+
`storage port show -port-type ENET`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. 检查集群是否没有存储交换机或布线问题：
+
`system health alert show -instance`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====
. 将HA对1的NSM224路径B端口移至SH2端口范围11-22。
. 安装从 HA 对 1 节点 1 路径 B 到 SH2 端口范围 11-22 的缆线。例如， AFF A400 上的路径 B 存储端口为 e5b 。
. 安装从 HA 对 1 节点 2 路径 B 到 SH2 端口范围 11-22 的缆线。
. 验证节点端口是否运行正常：
+
`storage port show -port-type ENET`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. 验证HA对1的存储配置是否正确且无错误：
+
`system switch ethernet show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address          Model
------------------------- ---------------------- ---------------- ----------
sh1
                          storage-network        172.17.227.5     C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6     C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. 重新配置HA对1上未使用的(控制器)二级存储端口、使其从存储连接到网络连接。如果直接连接了多个 NS224 ，则应重新配置一些端口。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
storage port modify –node [node name] –port [port name] –mode network
----
====
+
将存储端口置于广播域中：

+
** `network port broadcast-domain create` （根据需要创建新域）
** `network port broadcast-domain add-ports` （用于向现有域添加端口）


. 如果禁止自动创建案例，请通过调用 AutoSupport 消息重新启用它：
+
`ssystem node AutoSupport invoke -node * -type all -message MAINT=end`



.下一步是什么？
link:../switch-cshm/config-overview.html["配置交换机运行状况监控"](英文)
