---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/setup-and-configure-9336c-shared.html 
keywords:  
summary:  
---
= 配置Cisco Nexus 9336C-x2共享交换机
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
按照以下说明配置Cisco Nexus 9336C-x2共享交换机。

.开始之前
确保您已具备以下条件：

* 所需的共享交换机文档、控制器文档和ONTAP 文档。请参见 link:required-documentation-9336c-shared.html["Cisco Nexus 9336C-x2共享交换机的文档要求"] 和 https://docs.netapp.com/us-en/ontap/index.html["NetApp ONTAP 文档"^]。
* 适用的许可证、网络和配置信息以及缆线。
* 已完成布线工作表。请参见 link:cable-9336c-shared.html["填写Cisco Nexus 9336C-x2布线工作表"]。有关布线的详细信息、请参见 https://hwu.netapp.com["Hardware Universe"]。


.步骤
. 【第3步】对交换机执行初始配置。
+
要进行配置，您需要为交换机提供适当数量和类型的缆线和缆线连接器。

+
根据您最初配置的交换机类型，您需要使用随附的控制台缆线连接到交换机控制台端口；您还需要提供特定的网络信息。

. 启动交换机。
+
首次启动交换机时、请针对以下初始设置问题提供相应的回答。

+
您站点的安全策略定义了响应和服务，以实现：

+
.. 是否中止自动配置并继续正常设置？（是 / 否）
+
请回答 * 是 * 。默认值为 no

.. 是否要强制实施安全密码标准？（是 / 否）
+
请回答 * 是 * 。默认值为 yes 。

.. 输入管理员的密码。
+
默认密码为 admin ；您必须创建一个新的强密码。

+
可以拒绝弱密码。

.. 是否要进入基本配置对话框？（是 / 否）
+
在交换机的初始配置时，使用 * 是 * 进行响应。

.. 是否创建其他登录帐户？（是 / 否）
+
您的问题解答取决于站点的策略，取决于备用管理员。默认值为 no

.. 是否配置只读 SNMP 社区字符串？（是 / 否）
+
请使用 * 否 * 回答。默认值为 no

.. 是否配置读写 SNMP 社区字符串？（是 / 否）
+
请使用 * 否 * 回答。默认值为 no

.. 输入交换机名称。
+
交换机名称限制为 63 个字母数字字符。

.. 是否继续进行带外（ mgmt0 ）管理配置？（是 / 否）
+
在该提示符处，使用 * 是 * （默认值）进行响应。在 mgmt0 IPv4 address ：提示符处，输入 IP 地址： ip_address

.. 是否配置 default-gateway ？（是 / 否）
+
请回答 * 是 * 。在 default-gateway ：提示符的 IPv4 地址处，输入 default_gateway 。

.. 是否配置高级 IP 选项？（是 / 否）
+
请使用 * 否 * 回答。默认值为 no

.. 是否启用 telnet 服务？（是 / 否）
+
请使用 * 否 * 回答。默认值为 no

.. 是否启用 SSH 服务？（是 / 否）
+
请回答 * 是 * 。默认值为 yes 。

+

NOTE: 使用以太网交换机运行状况监控器(CSHM)收集日志功能时、建议使用SSH。为了增强安全性，还建议使用 SSHv2 。

.. 【第 14 步】输入要生成的 SSH 密钥类型（ DSA/RSA/RSA/rsa1 ）。默认值为 RSA 。
.. 输入密钥位数（ 1024-2048 ）。
.. 是否配置 NTP 服务器？（是 / 否）
+
请使用 * 否 * 回答。默认值为 no

.. 配置默认接口层（ L3/L2 ）：
+
请使用 * 二级 * 进行响应。默认值为 L2 。

.. 配置默认交换机端口接口状态（ shut/noshut ）：
+
请使用 * noshut * 进行响应。默认值为 noshut 。

.. 配置 CoPP 系统配置文件（严格 / 中等 / 宽松 / 密集）：
+
请使用 * 严格 * 回答。默认值为 strict 。

.. 是否要编辑此配置？（是 / 否）
+
此时应显示新配置。查看并对您刚刚输入的配置进行任何必要的更改。如果您对配置满意，请在提示符处回答 no 。如果要编辑配置设置，请使用 * 是 * 进行响应。

.. 是否使用此配置并保存？（是 / 否）
+
输入 * 是 * 以保存配置。此操作将自动更新 kickstart 和系统映像。



. 验证您在设置结束时显示的屏幕中所做的配置选择，并确保保存此配置。
+

NOTE: 如果您在此阶段未保存配置，则下次重新启动交换机时，所有更改都不会生效。

. 检查集群网络交换机上的版本、如有必要、从将NetApp支持的软件版本下载到交换机 https://software.cisco.com/download/home["Cisco软件下载"^] 页面。


.下一步是什么？
link:prepare-nxos-rcf-9336c-shared.html["准备安装NX-OS和RCF"]。
