---
permalink: switch-cisco-9332d-gx2b/configure-install-nxos-9332d.html 
sidebar: sidebar 
keywords: procedure, install, nx-os, software, nexus, cluster, switch, install the nx-os software - cisco nexus 9332d-gc2b 
summary: 您可以在 Cisco Nexus 9332D-GX2B 交换机上安装 NX-OS，作为新 AFX 1K 或 AFX 2K 系统安装、交换机更换或交换机重置为出厂默认设置的一部分。 
---
= 安装 NX-OS - Cisco Nexus 9332D-GX2B
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在 Cisco Nexus 9332D-GX2B 交换机上安装 NX-OS，作为新 AFX 1K 或 AFX 2K 系统安装、交换机更换或交换机重置为出厂默认设置的一部分。

.开始之前
* 必须打开交换机电源，并且您必须已完成 link:configure-complete-initial-setup-9332d.html["完成初始交换机设置"] 程序。
* 如果要在交换机上安装 NX-OS 作为新 AFX 系统安装或交换机更换的一部分，请验证交换机上的 NX-OS 版本是否为当前 NetApp 支持的版本。
+
** 如果您的交换机具有当前 NetApp 支持的版本，则无需安装 NX-OS。您需要安装 RCF。从 link:configure-install-upgrade-rcf-overview-9332d.html["安装或升级 RCF 概述"] 开始。
** 如果您的交换机没有当前 NetApp 支持的版本，请继续执行此过程以安装 NX-OS。


* 如果要在交换机上安装 NX-OS 作为交换机更换或交换机重置为出厂默认设置的一部分，请验证集群是否完全正常运行，即日志中没有错误或类似问题。



NOTE: 如果要在新的 AFX 系统安装过程中安装 NX-OS，则可以跳过此要求，因为在 AFX 系统安装和设置过程中，此时 AFX 系统中的控制器尚未通电。

.关于此任务
* AFX 系统上运行的 ONTAP 版本决定了交换机支持的 NX-OS 版本。
+
** 对于 AFX 1K 系统中的交换机，运行任何受支持版本的 ONTAP，均支持 NX-OS 10.4.2 及更高版本。
** 对于运行 ONTAP 9.19.1GA 或更高版本的 AFX 2K 系统中的交换机，支持 NX-OS 10.6 及更高版本。
+
有关受支持的 NX-OS 版本的当前列表，请参见link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["NetApp Cisco 以太网交换机"^]页面。



* 此过程仅需要使用 Cisco Nexus 9000 系列交换机命令。
* 本程序中的示例将第一个交换机称为 cs1，将第二个交换机称为 cs2。
* 如果您在新的 AFX 1K 或 AFX 2K 系统安装过程中安装了交换机，则此过程要求您在第一台交换机（cs1）上安装 NX-OS，然后对第二台交换机（cs2）重复这些步骤。
* 本程序中显示的示例适用于运行 RCF 10.0 的交换机的 AFX 1K 系统。如果您有 AFX 2K 系统，则输入和输出可能会有所不同。




[[step-1-prepare-to-install-the-nx-os]]
== 步骤 1：准备安装 NX-OS

通过确保您有权访问具有受支持的 NX-OS 版本的服务器、下载 NX-OS、连接到管理网络以进行文件传输，然后验证与服务器的连接，准备在交换机上安装 NX-OS。

.步骤
. 您必须能够访问 HTTP、FTP 或 TFTP 服务器。通过访问其中一台服务器，您可以下载受支持的 NX-OS 版本。
. 从 https://software.cisco.com/download/home["Cisco软件下载"^]页面将正确版本的 NX-OS 下载到交换机。
. 将交换机连接到管理网络（用于文件传输）。
. 使用 ping 命令验证与托管 NX-OS 的服务器的连接。
+
`ping <IP address>`

+
.显示示例
[%collapsible]
====
此示例验证交换机可以访问 IP 地址为 172.19.2.1 的服务器：

[listing, subs="+quotes"]
----
cs1# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====




[[step-2-install-the-nx-os]]
== 步骤 2：安装 NX-OS

通过安装和验证 NX-OS 版本、升级和验证 EPLD 映像，在第一台交换机 (cs1) 上安装 NX-OS，然后，如果您将 NX-OS 作为新 AFX 系统安装的一部分进行安装，则在第二台交换机 (cs2) 上重复这些步骤。

. 将 NX-OS 和 EPLD 映像复制到第一个交换机。
+
您使用此命令两次：第一次是复制 NX-OS 版本，第二次是复制 EPLD 版本。

+
`copy <protocol>: bootflash: vrf management`

+
.显示示例
[%collapsible]
====
示例使用 sftp。

[listing, subs="+quotes"]
----
cs1# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos.10.4.2.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *root*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
root@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/nxos.10.4.2.bin  /bootflash/nxos.10.4.2.bin
/code/nxos.10.4.2.bin  100% 1261MB   9.3MB/s   02:15
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.

cs1# *copy sftp: bootflash: vrf management*
Enter source filename: */code/n9000-epld.10.4.2.F.img*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/n9000-epld.10.4.2.F.img  /bootflash/n9000-epld.10.4.2.F.img
/code/n9000-epld.10.4.2.F.img  100%  161MB   9.5MB/s   00:16
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. 验证正在运行的 NX-OS 版本：
+
`show version`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.4(1) [Feature Release]
  Host NXOS: version 10.4(1)
  BIOS compile time:  11/25/2024
  NXOS image file is: bootflash:///nxos64-cs.10.4.1.F.bin
  NXOS compile time:  11/30/2023 12:00:00 [12/14/2023 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco Nexus9000 C9332D-GX2B Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLMXXXXXXXX
  Device name: cs2
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Jun  5 15:55:08 2025
  Reason: Reset Requested by CLI command reload
  System version: 10.4(1)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):

cs1#
----
====
. 安装 NX-OS 镜像。
+
安装镜像文件后，每次交换机重启时都会加载该文件。

+
`install all nxos bootflash:nxos.<version number>.bin`

+
.显示示例
[%collapsible]
====
示例使用 NX-OS 版本 10.4.2。

[listing, subs="+quotes"]
----
cs1# *install all nxos bootflash:nxos.10.4.2.bin*

Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.10.4.2.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.10.4.2.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.10.4.2.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  Bootable  Impact          Install-type  Reason
------  --------  --------------- ------------  ---------
  1     yes       Disruptive      Reset         Default upgrade is not hitless



Images will be upgraded according to following table:

Module   Image    Running-Version(pri:alt)                 New-Version         Upg-Required
------- --------- ---------------------------------------- ------------------- ------------
  1      nxos     10.4(1)                                  10.4(2)             Yes
  1      bios     xx.xx.:xx.xx                             xxx                 No


Switch will be reloaded for disruptive upgrade.

Do you want to continue with the installation (y/n)? [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS

Finishing the upgrade, switch will reboot in 10 seconds.
----
====
. 在交换机重新启动后，验证新版本的 NX-OS：
+
`show version`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.4(2) [Feature Release]
  Host NXOS: version 10.4(2)
  BIOS compile time:  11/25/2024
  NXOS image file is: bootflash:///nxos64-cs.10.4.2.F.bin
  NXOS compile time:  11/30/2023 12:00:00 [12/14/2023 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco Nexus9000 C9332D-GX2B Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLMXXXXXXXX
  Device name: cs1
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Jun  5 15:55:08 2025
  Reason: Reset Requested by CLI command reload
  System version: 10.4(2)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):

cs1#
----
====
. 使用以下命令升级 EPLD 映像：
+
`show version module 1 epld`

+
`install epld bootflash:n9000-epld.<version>.img module all`

+
执行最后一个命令后，交换机重新启动。

+
.显示示例
[%collapsible]
====
示例使用 EPLD 版本 10.4.2.F

[listing, subs="+quotes"]
----
cs1# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI   FPGA                        0x7
IO   FPGA                        0x17
MI   FPGA2                       0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2

cs1# *install epld bootflash:n9000-epld.10.4.2.F.img module all*
Compatibility check:
Module        Type         Upgradable        Impact    Reason
------  ------------------ ----------------- --------- -----------
     1         SUP         Yes       disruptive  Module Upgradable

Retrieving EPLD versions.... Please wait.
Images will be upgraded according to following table:
Module  Type   EPLD              Running-Version   New-Version  Upg-Required
------- ------ ----------------- ----------------- ------------ ------------
     1  SUP    MI FPGA           0x07              0x07         No
     1  SUP    IO FPGA           0x17              0x19         Yes
     1  SUP    MI FPGA2          0x02              0x02         No
The above modules require upgrade.
The switch will be reloaded at the end of the upgrade
Do you want to continue (y/n) ?  [n] *y*

Proceeding to upgrade Modules.

Starting Module 1 EPLD Upgrade

Module 1 : IO FPGA [Programming] : 100.00% (     64 of      64 sectors)
Module 1 EPLD upgrade is successful.
Module   Type  Upgrade-Result
-------- ----- --------------
     1   SUP   Success

EPLDs upgraded.

Module 1 EPLD upgrade is successful.
----
====
. 交换机重新启动后，登录并验证新版本的 EPLD 已成功加载：
+
`show version module 1 epld`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI   FPGA                        0x7
IO   FPGA                        0x19
MI   FPGA2                       0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
----
====
. 如果要在新的 AFX 系统安装过程中安装 NX-OS，请重复以下步骤在交换机 cs2 上安装 NX-OS 和 EPLD 映像。


.下一步是什么？
在交换机上安装 NX-OS 后，请从 link:configure-install-upgrade-rcf-overview-9332d.html["安装或升级 RCF 概述"] 开始安装 RCF。
