---
permalink: switch-cisco-9332d-gx2b/install-rcf-software-9332d-cluster.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: 首次设置 Nexus 9332D-GX2B 交换机后，您可以安装 RCF。 
---
= 安装参考配置文件（RCF）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
首次设置 Nexus 9332D-GX2B 交换机后，安装参考配置文件 (RCF)。

.开始之前
请核实以下安装和连接：

* 控制台与交换机的连接。如果您可以远程访问交换机，则控制台连接是可选的。
* 交换机 cs1 和交换机 cs2 已通电，交换机初始设置已完成（管理 IP 地址和 SSH 已设置）。
* 已安装所需的NX-OS版本。
* 交换机之间的ISL连接已连接。




== 步骤 1：在交换机上安装 RCF

. 使用 SSH 或串行控制台登录到 switch cs1。
. 使用以下传输协议之一将 RCF 复制到交换机 cs1 的 bootflash：FTP、TFTP、SFTP 或 SCP。
+
有关Cisco命令的更多信息，请参阅 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 系列 NX-OS 命令参考"^]指南。

+
.显示示例
[%collapsible]
====
此示例展示了如何使用 TFTP 将 RCF 文件复制到交换机 cs1 的启动闪存中：

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *NX9332D-GX2B-RCF-v10.0-Shared.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 将之前下载的 RCF 文件应用到启动闪存中。
+
有关Cisco命令的更多信息，请参阅 https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 系列 NX-OS 命令参考"^]指南。

+
此示例展示了 RCF 文件 `NX9332D-GX2B-RCF-v10.0-Shared.txt`正在交换机 cs1 上安装：

+
[listing, subs="+quotes"]
----
cs1# *copy NX9332D-GX2B-RCF-v10.0-Shared.txt running-config echo-commands*
----
. 检查横幅输出 `show banner motd`命令。您必须阅读并遵循这些说明以确保交换机的正确配置和操作。
+
.显示示例
[%collapsible]
====
[listing]
----
cs1# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : NX9332D-GX2B
* Filename : NX9332D-GX2B-RCF-v10.0-Shared.txt
* Date     : 05-09-2025
* Version  : v10.0
* Port Usage:
* Ports  1-30: 100GbE Intra-Cluster/HA/Storage Ports, int e1/{1-30}/1-4
* Ports 31-32: Intra-Cluster ISL Ports, int e1/31-32
*
* IMPORTANT NOTES
* Interface port-channel999 is reserved to identify the version of this file.
******************************************************************************
----
====
. 请确认 RCF 文件是否为最新版本：
+
`show running-config`

+
检查输出结果以验证是否拥有正确的 RCF 时，请确保以下信息正确：

+
** RCF横幅
** 节点和端口设置
** 定制
+
输出结果会根据您的网站配置而有所不同。检查端口设置，并参考发行说明，了解您安装的 RCF 版本是否有任何特定更改。



. 保存基本配置详细信息 `write_erase.cfg`启动闪存上的文件。
+
[NOTE]
====
确保配置以下内容：

** 用户名和密码
** 管理 IP 地址
** 默认网关
** 交换机名称


====
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`

+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region egr-racl 1024" >> bootflash:write_erase.cfg`

+
`cs1# echo "hardware access-list tcam region ing-l2-qos 1536" >> bootflash:write_erase.cfg`

+
请参阅知识库文章link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["如何在保持远程连接的情况下清除Cisco互连交换机上的配置"^]更多详情请见下文。

. 确认 `write_erase.cfg`文件已按预期填充：
+
`*show file bootflash:write_erase.cfg*`

. 问题 `write erase`清除当前已保存配置的命令：
+
`cs1# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. 将之前保存的基本配置复制到启动配置中。
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. 重启交换机：
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 在交换机 cs2 上重复步骤 1 至 10。
. 将ONTAP集群中所有节点的端口连接到交换机 cs1 和 cs2。




== 步骤 2：验证交换机连接

. 验证连接到集群端口的交换机端口是否已启动：
+
`show interface brief`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show interface brief | grep up*
.
.
Eth1/9/3        1       eth  trunk  up      none                     100G(D) --
Eth1/9/4        1       eth  trunk  up      none                     100G(D) --
Eth1/15/1       1       eth  trunk  up      none                     100G(D) --
Eth1/15/2       1       eth  trunk  up      none                     100G(D) --
Eth1/15/3       1       eth  trunk  up      none                     100G(D) --
Eth1/15/4       1       eth  trunk  up      none                     100G(D) --
Eth1/16/1       1       eth  trunk  up      none                     100G(D) --
Eth1/16/2       1       eth  trunk  up      none                     100G(D) --
Eth1/16/3       1       eth  trunk  up      none                     100G(D) --
Eth1/16/4       1       eth  trunk  up      none                     100G(D) --
Eth1/17/1       1       eth  trunk  up      none                     100G(D) --
Eth1/17/2       1       eth  trunk  up      none                     100G(D) --
Eth1/17/3       1       eth  trunk  up      none                     100G(D) --
Eth1/17/4       1       eth  trunk  up      none                     100G(D) --
.
.
----
====
. 使用以下命令验证集群节点是否位于正确的集群 VLAN 中：
+
`show vlan brief`

+
`show interface trunk`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show vlan brief*
VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Po1, Po999, Eth1/31, Eth1/32
                                                Eth1/33, Eth1/34, Eth1/1/1
                                                Eth1/1/2, Eth1/1/3, Eth1/1/4
                                                Eth1/2/1, Eth1/2/2, Eth1/2/3
                                                Eth1/2/4, Eth1/3/1, Eth1/3/2
                                                Eth1/3/3, Eth1/3/4, Eth1/4/1
                                                Eth1/4/2, Eth1/4/3, Eth1/4/4
                                                Eth1/5/1, Eth1/5/2, Eth1/5/3
                                                Eth1/5/4, Eth1/6/1, Eth1/6/2
                                                Eth1/6/3, Eth1/6/4, Eth1/7/1
                                                Eth1/7/2, Eth1/7/3, Eth1/7/4
                                                Eth1/8/1, Eth1/8/2, Eth1/8/3
                                                Eth1/8/4, Eth1/9/1, Eth1/9/2
                                                Eth1/9/3, Eth1/9/4, Eth1/10/1
                                                Eth1/10/2, Eth1/10/3, Eth1/10/4
                                                Eth1/11/1, Eth1/11/2, Eth1/11/3
                                                Eth1/11/4, Eth1/12/1, Eth1/12/2
                                                Eth1/12/3, Eth1/12/4, Eth1/13/1
                                                Eth1/13/2, Eth1/13/3, Eth1/13/4
                                                Eth1/14/1, Eth1/14/2, Eth1/14/3
                                                Eth1/14/4, Eth1/15/1, Eth1/15/2
                                                Eth1/15/3, Eth1/15/4, Eth1/16/1
                                                Eth1/16/2, Eth1/16/3, Eth1/16/4
                                                Eth1/17/1, Eth1/17/2, Eth1/17/3
                                                Eth1/17/4, Eth1/18/1, Eth1/18/2
                                                Eth1/18/3, Eth1/18/4, Eth1/19/1
                                                Eth1/19/2, Eth1/19/3, Eth1/19/4
                                                Eth1/20/1, Eth1/20/2, Eth1/20/3
                                                Eth1/20/4, Eth1/21/1, Eth1/21/2
                                                Eth1/21/3, Eth1/21/4, Eth1/22/1
                                                Eth1/22/2, Eth1/22/3, Eth1/22/4
                                                Eth1/23/1, Eth1/23/2, Eth1/23/3
                                                Eth1/23/4, Eth1/24/1, Eth1/24/2
                                                Eth1/24/3, Eth1/24/4, Eth1/25/1
                                                Eth1/25/2, Eth1/25/3, Eth1/25/4
                                                Eth1/26/1, Eth1/26/2, Eth1/26/3
                                                Eth1/26/4, Eth1/27/1, Eth1/27/2
                                                Eth1/27/3, Eth1/27/4, Eth1/28/1
                                                Eth1/28/2, Eth1/28/3, Eth1/28/4
                                                Eth1/29/1, Eth1/29/2, Eth1/29/3
                                                Eth1/29/4, Eth1/30/1, Eth1/30/2
                                                Eth1/30/3, Eth1/30/4
17   VLAN0017                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
18   VLAN0018                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
30   VLAN0030                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4
40   VLAN0040                         active    Eth1/1/1, Eth1/1/2, Eth1/1/3
                                                Eth1/1/4, Eth1/2/1, Eth1/2/2
                                                Eth1/2/3, Eth1/2/4, Eth1/3/1
                                                Eth1/3/2, Eth1/3/3, Eth1/3/4
                                                Eth1/4/1, Eth1/4/2, Eth1/4/3
                                                Eth1/4/4, Eth1/5/1, Eth1/5/2
                                                Eth1/5/3, Eth1/5/4, Eth1/6/1
                                                Eth1/6/2, Eth1/6/3, Eth1/6/4
                                                Eth1/7/1, Eth1/7/2, Eth1/7/3
                                                Eth1/7/4, Eth1/8/1, Eth1/8/2
                                                Eth1/8/3, Eth1/8/4, Eth1/9/1
                                                Eth1/9/2, Eth1/9/3, Eth1/9/4
                                                Eth1/10/1, Eth1/10/2, Eth1/10/3
                                                Eth1/10/4, Eth1/11/1, Eth1/11/2
                                                Eth1/11/3, Eth1/11/4, Eth1/12/1
                                                Eth1/12/2, Eth1/12/3, Eth1/12/4
                                                Eth1/13/1, Eth1/13/2, Eth1/13/3
                                                Eth1/13/4, Eth1/14/1, Eth1/14/2
                                                Eth1/14/3, Eth1/14/4, Eth1/15/1
                                                Eth1/15/2, Eth1/15/3, Eth1/15/4
                                                Eth1/16/1, Eth1/16/2, Eth1/16/3
                                                Eth1/16/4, Eth1/17/1, Eth1/17/2
                                                Eth1/17/3, Eth1/17/4, Eth1/18/1
                                                Eth1/18/2, Eth1/18/3, Eth1/18/4
                                                Eth1/19/1, Eth1/19/2, Eth1/19/3
                                                Eth1/19/4, Eth1/20/1, Eth1/20/2
                                                Eth1/20/3, Eth1/20/4, Eth1/21/1
                                                Eth1/21/2, Eth1/21/3, Eth1/21/4
                                                Eth1/22/1, Eth1/22/2, Eth1/22/3
                                                Eth1/22/4, Eth1/23/1, Eth1/23/2
                                                Eth1/23/3, Eth1/23/4, Eth1/24/1
                                                Eth1/24/2, Eth1/24/3, Eth1/24/4
                                                Eth1/25/1, Eth1/25/2, Eth1/25/3
                                                Eth1/25/4, Eth1/26/1, Eth1/26/2
                                                Eth1/26/3, Eth1/26/4, Eth1/27/1
                                                Eth1/27/2, Eth1/27/3, Eth1/27/4
                                                Eth1/28/1, Eth1/28/2, Eth1/28/3
                                                Eth1/28/4, Eth1/29/1, Eth1/29/2
                                                Eth1/29/3, Eth1/29/4, Eth1/30/1
                                                Eth1/30/2, Eth1/30/3, Eth1/30/4

cs1# *show interface trunk*
--------------------------------------------------------------------------------
Port          Native  Status        Port
              Vlan                  Channel
--------------------------------------------------------------------------------
Eth1/1/1      1       trunking      --
Eth1/1/2      1       trunking      --
Eth1/1/3      1       trunking      --
Eth1/1/4      1       trunking      --
Eth1/2/1      1       trunking      --
Eth1/2/2      1       trunking      --
Eth1/2/3      1       trunking      --
Eth1/2/4      1       trunking      --
.
.
.
Eth1/30/1     none
Eth1/30/2     none
Eth1/30/3     none
Eth1/30/4     none
Eth1/31       none
Eth1/32       none
Po1           1
----
====
+

NOTE: 有关具体端口和 VLAN 使用详情，请参阅 RCF 中的横幅和重要说明部分。

. 验证 cs1 和 cs2 之间的 ISL 连接是否正常：
+
[source, cli]
----
show port-channel summary
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)
999   Po999(SD)   Eth      NONE      --
cs1#
----
====




== 步骤 3：设置ONTAP集群

NetApp建议您使用系统管理器来设置新的集群。

系统管理器为集群设置和配置提供了简单易用的工作流程，包括分配节点管理 IP 地址、初始化集群、创建本地层、配置协议和配置初始存储。

前往 https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["使用 System Manager 在新集群上配置ONTAP"]有关设置说明，请参阅相关文档。

.下一步是什么？
安装完 RCF 后，你 link:configure-ssh-keys.html["验证 SSH 配置"]。
