---
permalink: switch-cisco-9332d-gx2b/setup-switch-9332d-cluster.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9332d-gx2b 
summary: 按照以下步骤配置Cisco Nexus 9332D-GX2B 交换机。 
---
= 配置 9332D-GX2B 交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照以下步骤配置Cisco Nexus 9332D-GX2B 交换机。

.开始之前
确保您拥有：

* 已打开交换机电源。
* 在安装现场访问 HTTP、FTP 或 TFTP 服务器，以下载适用的 NX-OS 和参考配置文件 (RCF) 版本。
* 适用的NX-OS版本，可从以下网址下载： https://software.cisco.com/download/home["Cisco软件下载"^]页。


[IMPORTANT]
====
* NX-OS 10.4.2 是ONTAP集群中Cisco Nexus 9332D-GX2B 交换机唯一支持的版本。
* 请勿将您的 NX-OS 版本升级或降级为不受支持的版本；目前仅支持 10.4.2。


====
* 适用的许可证、网络和配置信息以及线缆。
* 可从NetApp支持站点下载适用的NetApp共享网络和管理网络 RCF。 http://mysupport.netapp.com/["mysupport.netapp.com"^] 。所有Cisco共享网络和管理网络交换机均采用标准Cisco出厂默认配置。这些交换机也具有当前版本的 NX-OS 软件，但未加载 RCF。
* link:required-documentation-9332d-cluster.html["所需的交换机和ONTAP文档"]。


.步骤
. 执行共享网络交换机的初始配置。
+
首次启动交换机时，请对以下初始设置问题提供相应的答案。您网站的安全策略定义了要启用的响应和服务。

+
[cols="1,2"]
|===
| 迅速的 | 响应 


 a| 
中止自动配置并继续进行正常设置？  （是/否）
 a| 
请回答“是”。默认值为否。



 a| 
您是否希望强制执行安全密码标准？  （是/否）
 a| 
请回答“是”。默认值为“是”。



 a| 
请输入管理员密码。
 a| 
默认密码为“`admin`”；您必须创建一个新的、强密码。弱密码可能会被拒绝。



 a| 
您想进入基本配置对话框吗？  （是/否）
 a| 
在交换机的初始配置阶段，请回答“是”。



 a| 
创建另一个登录帐户？  （是/否）
 a| 
答案取决于您网站关于备用管理员的政策。默认值为*否*。



 a| 
配置只读 SNMP 团体字符串？  （是/否）
 a| 
回答“不”。默认值为否。



 a| 
配置读写 SNMP 团体字符串？  （是/否）
 a| 
回答“不”。默认值为否。



 a| 
请输入交换机名称。
 a| 
请输入交换机名称，字数限制为 63 个字母数字字符。



 a| 
继续进行带外（mgmt0）管理配置？  （是/否）
 a| 
在该提示出现时，请回答“是”（默认值）。在 mgmt0 IPv4 地址提示符处，输入您的 IP 地址：ip_address。



 a| 
配置默认网关？  （是/否）
 a| 
请回答“是”。在默认网关的 IPv4 地址提示符处，输入您的默认网关。



 a| 
配置高级 IP 选项？  （是/否）
 a| 
回答“不”。默认值为否。



 a| 
启用 Telnet 服务？  （是/否）
 a| 
回答“不”。默认值为否。



 a| 
已启用 SSH 服务？  （是/否）
 a| 
请回答“是”。默认值为“是”。


NOTE: 使用以太网交换机健康监视器 (CSHM) 时，建议使用 SSH 进行日志收集。为了提高安全性，建议使用 SSHv2。



 a| 
请输入要生成的 SSH 密钥类型（dsa/rsa/rsa1）。
 a| 
默认值为 *rsa*。



 a| 
请输入密钥位数（1024-2048）。
 a| 
请输入1024到2048之间的密钥位数。



 a| 
配置NTP服务器？  （是/否）
 a| 
回答“不”。默认值为否。



 a| 
配置默认接口层（L3/L2）
 a| 
请用*L2*回复。默认值为 L2。



 a| 
配置交换机端口接口的默认状态（关闭/不关闭）
 a| 
回复 *noshut*。默认设置为 noshut。



 a| 
配置 CoPP 系统配置文件（严格/中等/宽松/严格）
 a| 
回复时请使用 *strict*。默认设置为严格。



 a| 
您想修改配置吗？  （是/否）
 a| 
此时您应该可以看到新的配置。请检查并对您刚刚输入的配置进行必要的更改。如果对配置满意，请在提示时回答“否”。如果要编辑配置设置，请回复“是”。



 a| 
使用此配置并保存？  （是/否）
 a| 
回复“是”以保存配置。这会自动更新启动镜像和系统镜像。


NOTE: 如果此时不保存配置，下次重启交换机时，所有更改都将失效。

|===
. 在设置结束时显示的界面中，确认您所做的配置选择，并确保保存配置。
. 检查共享网络交换机上的软件版本，如有必要，请从 NetApp 官网下载NetApp支持的软件版本到交换机。 https://software.cisco.com/download/home["Cisco软件下载"^]页。


.下一步是什么？
配置好交换机之后，你 link:install-nxos-overview-9332d-cluster.html["准备安装NX-OS软件和RCF"]。
