---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2/components-9336c-cluster.html 
keywords: shared storage cluster switch 
summary: 从ONTAP 9.9.1 开始，您可以使用Cisco Nexus 9336C-FX2 交换机将存储和集群功能组合到共享交换机场景中。 
---
= Cisco Nexus 9336C-FX2 和 9336C-FX2-T 集群交换机的组件和部件号
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
对于Cisco Nexus 9336C-FX2 和 9336C-FX2-T 交换机的安装和维护，请务必查看组件和部件号列表。



== 零件编号详情

下表列出了 9336C-FX2 和 9336C-FX2-T 交换机、风扇和电源的部件号和描述：

[cols="1,2"]
|===
| 零件编号 | 描述 


 a| 
X190200-CS-PE
 a| 
集群开关，N9336C 36点 PTSX 10/25/40/100G



 a| 
X190200-CS-PI
 a| 
集群交换机，N9336C 36点 PSIN 10/25/40/100G



 a| 
X190212-CS-PE
 a| 
集群开关，N9336C 12点 (9336C-FX2-T) PTSX 10/25/40/100G



 a| 
X190212-CS-PI
 a| 
集群交换机，N9336C 12点 (9336C-FX2-T) PSIN 10/25/40/100G



 a| 
SW-N9K-FX2-24P-UPG
 a| 
SW，Cisco9336CFX2 24 端口 POD 许可证



 a| 
X190210-FE-PE
 a| 
N9K-9336C、FTE、PTSX、36PT 10/25/40/100GQSFP28



 a| 
X190210-FE-PI
 a| 
N9K-9336C，FTE，PSIN，36PT 10/25/40/100GQSFP28



 a| 
X190002
 a| 
附件套件 X190001/X190003



 a| 
X-NXA-PAC-1100W-PE2
 a| 
N9K-9336C 交流 1100W 电源 - 端口侧排气



 a| 
X-NXA-PAC-1100W-PI2
 a| 
N9K-9336C 交流 1100W 电源 - 端口侧进气



 a| 
X-NXA-FAN-65CFM-PE
 a| 
N9K-9336C 65CFM，左舷排气气流



 a| 
X-NXA-FAN-65CFM-PI
 a| 
N9K-9336C 65CFM，左舷进气气流

|===


== 仅适用于 9336C-FX2-T 端口的Cisco智能许可证

要激活Cisco Nexus 9336C-FX-T 集群交换机上的 12 个以上端口，您必须购买Cisco Smart 许可证。  Cisco Smart 许可证通过Cisco Smart 帐户进行管理。

. 如有需要，请创建新的 Smart 账户。看 https://id.cisco.com/signin/register["创建新的智能账户"^]了解详情。
. 请求访问现有Smart账户。看 https://id.cisco.com/oauth2/default/v1/authorize?response_type=code&scope=openid%20profile%20address%20offline_access%20cci_coimemberOf%20email&client_id=cae-okta-web-gslb-01&state=s2wvKDiBja__7ylXonWrq8w-FAA&redirect_uri=https%3A%2F%2Frpfa.cloudapps.cisco.com%2Fcb%2Fsso&nonce=qO6s3cZE5ZdhC8UKMEfgE6fbu3mvDJ8PTw5jYOp6z30["请求访问现有智能账户"^]了解详情。



NOTE: 购买 Smart 许可证后，安装相应的 RCF 以启用和配置所有 36 个可用端口。

.下一步
确认组件和零件编号后，您可以进行审核。 link:required-documentation-9336c-cluster.html["所需文件"]。
