---
permalink: switch-cisco-9336c-fx2/replace-storage-switch-9336c-cluster.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: '更换集群网络中有缺陷的 Nexus 9336C-FX2 交换机是一个无中断过程 \(NDU\)。' 
---
= 更换Cisco Nexus 9336C-FX2 存储交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
更换Cisco Nexus 9336C-FX2 存储交换机时，您必须了解某些配置信息、端口连接和布线要求。

.你需要什么
在Cisco Nexus 9336C-FX2 存储交换机上安装 NX-OS 软件和 RCF 之前，必须验证以下条件是否存在：

* 您的系统可以支持Cisco Nexus 9336C-FX2 存储交换机。
* 您必须查阅Cisco以太网交换机页面上的交换机兼容性表格，以了解支持的ONTAP、NX-OS 和 RCF 版本。
* 您一定参考过Cisco网站上提供的相应软件和升级指南。CiscoNexus 3000 系列交换机
* 您必须已下载适用的 RCF 文件。
* 现有网络配置必须具备以下特征：
+
** Cisco以太网交换机页面包含交换机上最新的 RCF 和 NX-OS 版本。
** 两台交换机都必须具备管理连接功能。


* 替换用的CiscoNexus 9336C-FX2 交换机必须具备以下特性：
+
** 管理网络连接必须正常。
** 必须具备对更换开关的控制台访问权限。
** 必须将相应的 RCF 和 NX-OS 操作系统映像加载到交换机上。
** 交换机的初始配置必须完成。




.关于此任务
此过程将第二个 Nexus 9336C-FX2 存储交换机 S2 替换为新的 9336C-FX 交换机 NS2。这两个节点分别是节点1和节点2。

完成步骤：

* 确认要更换的开关是 S2。
* 断开交换机 S2 的电缆。
* 重新连接电缆至 NS2 交换机。
* 请核实交换机 NS2 上的所有设备配置。
+

NOTE: RCF 和 NX-OS 版本中的命令语法可能存在依赖关系。



.步骤
. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ 是维护窗口的持续时间，单位为小时。

. 检查存储节点端口的运行状况，确保与存储交换机S1有连接：
+
`storage port show -port-type ENET`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
====
. 确认存储交换机 S1 可用：
+
`network device-discovery show`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
node1/cdp
           e3a   S1                        Ethernet1/1 NX9336C
           e4a   node2                     e4a         AFF-A700
           e4e   node2                     e4e         AFF-A700
node1/lldp
           e3a   S1                        Ethernet1/1 -
           e4a   node2                     e4a         -
           e4e   node2                     e4e         -
node2/cdp
           e3a   S1                        Ethernet1/2 NX9336C
           e4a   node1                     e4a         AFF-A700
           e4e   node1                     e4e         AFF-A700
node2/lldp
           e3a   S1                        Ethernet1/2 -
           e4a   node1                     e4a         -
           e4e   node1                     e4e         -
storage::*>
----
====
. 掌控全场 `lldp neighbors`在工作交换机上执行命令，确认可以看到两个节点和所有机架：
+
`show lldp neighbors`

+
.显示示例
[%collapsible]
====
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
node1            Eth1/1       121          S             e3a
node2            Eth1/2       121          S             e3a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====
. 检查存储系统中的货架端口：
+
`storage shelf port show -fields remote-device,remote-port`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   S1
3.20    1   -             -
3.20    2   Ethernet1/6   S1
3.20    3   -             -
3.30    0   Ethernet1/7   S1
3.20    1   -             -
3.30    2   Ethernet1/8   S1
3.20    3   -             -
storage::*>
----
====
. 拆下连接到存储交换机 S2 的所有电缆。
. 将所有电缆重新连接到替换交换机 NS2。
. 请重新检查存储节点端口的运行状况：
+
`storage port show -port-type ENET`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
====
. 确认两个交换机均可用：
+
`network device-discovery show`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
node1/cdp
          e3a  S1                         Ethernet1/1 NX9336C
          e4a  node2                      e4a         AFF-A700
          e4e  node2                      e4e         AFF-A700
          e7b   NS2                       Ethernet1/1 NX9336C
node1/lldp
          e3a  S1                         Ethernet1/1 -
          e4a  node2                      e4a         -
          e4e  node2                      e4e         -
          e7b  NS2                        Ethernet1/1 -
node2/cdp
          e3a  S1                         Ethernet1/2 NX9336C
          e4a  node1                      e4a         AFF-A700
          e4e  node1                      e4e         AFF-A700
          e7b  NS2                        Ethernet1/2 NX9336C
node2/lldp
          e3a  S1                         Ethernet1/2 -
          e4a  node1                      e4a         -
          e4e  node1                      e4e         -
          e7b  NS2                        Ethernet1/2 -
storage::*>
----
====
. 检查存储系统中的货架端口：
+
`storage shelf port show -fields remote-device,remote-port`

+
.显示示例
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     S1
3.20    1     Ethernet1/5     NS2
3.20    2     Ethernet1/6     S1
3.20    3     Ethernet1/6     NS2
3.30    0     Ethernet1/7     S1
3.20    1     Ethernet1/7     NS2
3.30    2     Ethernet1/8     S1
3.20    3     Ethernet1/8     NS2
storage::*>
----
====
. 如果您已禁用自动创建案例功能，请通过调用AutoSupport消息重新启用该功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`


