---
permalink: switch-cisco-9336c-fx2/replace_9336c_storage_switch.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: 更换集群网络中存在故障的 Nexus 9336C-x2 交换机是无中断操作步骤 \ （ NDU\ ）。 
---
= 更换 Cisco Nexus 9336C-x2 存储交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
更换 Cisco Nexus 9336C-x2 存储交换机时，您必须了解某些配置信息，端口连接和布线要求。

在 Cisco Nexus 9336C-x2 存储交换机上安装 NX-OS 软件和 RCF 之前，必须验证是否存在以下条件：

* 您的系统可以支持 Cisco Nexus 9336C-x2 存储交换机。
* 您必须已查看 Cisco 以太网交换机页面上的交换机兼容性表以了解受支持的 ONTAP ， NX-OS 和 RCF 版本。
+

NOTE: 请注意， RCF 和 NX-OS 版本中的命令语法之间可能存在依赖关系。

* 您必须已参考 Cisco 网站上提供的相应软件和升级指南，以获取有关 Cisco 交换机升级和降级过程的完整文档。Cisco Nexus 3000 系列交换机
* 您必须已下载适用的 RCF 。


现有网络配置必须具有以下特征：

* Cisco 以太网交换机页面会为您的交换机提供最新的 RCF 和 NX-OS 版本。
* 两台交换机上必须存在管理连接。
+

NOTE: 确保已完成所有故障排除步骤，以确认您的交换机需要更换。

+
更换用的 Cisco Nexus 9336C-x2 交换机必须具有以下特征：

* 管理网络连接必须正常工作。
* 必须能够通过控制台访问更换用的交换机。
* 必须将相应的 RCF 和 NX-OS 操作系统映像加载到交换机上。
* 必须完成交换机的初始自定义。




== 操作步骤摘要

此操作步骤将第二个 Nexus 9336C-x2 存储交换机 S2 替换为新的 9336C-x2 交换机 NS2 。这两个节点分别为 node1 和 node2 。

完成步骤：

* 确认要更换的交换机为 S2 。
* 断开交换机 S2 的缆线。
* 将缆线重新连接到交换机 NS2 。
* 验证交换机 NS2 上的所有设备配置。


.步骤
. 如果在此集群上启用了 AutoSupport ，请通过调用 AutoSupport 消息来禁止自动创建案例： `ssystem node AutoSupport invoke -node * -type all - message MAINT=xh`
+
_x_ 是维护时段的持续时间，以小时为单位。

. 检查存储节点端口的运行状况，确保已连接到存储交换机 S1 ：
+
`storage port show -port-type ENET`

+
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
. 验证存储交换机 S1 是否可用： `network device-discovery show`
+
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
node1/cdp
           e3a   S1                        Ethernet1/1 NX9336C
           e4a   node2                     e4a         AFF-A700
           e4e   node2                     e4e         AFF-A700
node1/lldp
           e3a   S1                        Ethernet1/1 -
           e4a   node2                     e4a         -
           e4e   node2                     e4e         -
node2/cdp
           e3a   S1                        Ethernet1/2 NX9336C
           e4a   node1                     e4a         AFF-A700
           e4e   node1                     e4e         AFF-A700
node2/lldp
           e3a   S1                        Ethernet1/2 -
           e4a   node1                     e4a         -
           e4e   node1                     e4e         -
storage::*>
----
. 在工作交换机上运行 show `llDP neighbors` 命令，确认您可以同时看到节点和所有磁盘架： `sLLDP 邻居如何`
+
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
node1            Eth1/1       121          S             e3a
node2            Eth1/2       121          S             e3a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
. 验证存储系统中的磁盘架端口： `storage shelf port show -fields remote-device ， remote-port`
+
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   S1
3.20    1   -             -
3.20    2   Ethernet1/6   S1
3.20    3   -             -
3.30    0   Ethernet1/7   S1
3.20    1   -             -
3.30    2   Ethernet1/8   S1
3.20    3   -             -
storage::*>
----
. 拔下连接到存储交换机 S2 的所有缆线。
. 将所有缆线重新连接到更换用的交换机 NS2 。
. 重新检查存储节点端口的运行状况： `storage port show -port-type ENET`
+
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
. 验证两个交换机是否均可用： `network device-discovery show`
+
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
node1/cdp
          e3a  S1                         Ethernet1/1 NX9336C
          e4a  node2                      e4a         AFF-A700
          e4e  node2                      e4e         AFF-A700
          e7b   NS2                       Ethernet1/1 NX9336C
node1/lldp
          e3a  S1                         Ethernet1/1 -
          e4a  node2                      e4a         -
          e4e  node2                      e4e         -
          e7b  NS2                        Ethernet1/1 -
node2/cdp
          e3a  S1                         Ethernet1/2 NX9336C
          e4a  node1                      e4a         AFF-A700
          e4e  node1                      e4e         AFF-A700
          e7b  NS2                        Ethernet1/2 NX9336C
node2/lldp
          e3a  S1                         Ethernet1/2 -
          e4a  node1                      e4a         -
          e4e  node1                      e4e         -
          e7b  NS2                        Ethernet1/2 -
storage::*>
----
. 验证存储系统中的磁盘架端口： `storage shelf port show -fields remote-device ， remote-port`
+
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     S1
3.20    1     Ethernet1/5     NS2
3.20    2     Ethernet1/6     S1
3.20    3     Ethernet1/6     NS2
3.30    0     Ethernet1/7     S1
3.20    1     Ethernet1/7     NS2
3.30    2     Ethernet1/8     S1
3.20    3     Ethernet1/8     NS2
storage::*>
----
. 如果禁止自动创建案例，请通过调用 AutoSupport 消息重新启用此功能： `ssystem node AutoSupport invoke -node * -type all -message MAINT=end`

