---
permalink: switch-cisco-9336c-fx2/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, nexus, ontap, install the cluster switch health monitor (csm) configuration file for 92300yc switches - cisco nexus 9336c-fx2' 
summary: 您可以使用此操作步骤为Nexus 92300YC集群交换机的集群交换机运行状况监控安装适用的配置文件。 
---
= 安装集群交换机运行状况监控器(SHM)配置文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
请按照此操作步骤安装适用于Nexus 9334C)和Nexus 9334C)集群交换机的集群交换机运行状况监控(SHM)的配置文件。

.您需要的内容
在为9334C-查 务器设置SHM之前、请确保ONTAP集群已启动且正在运行。


NOTE: 您还应启用SSH以使用SHM中提供的所有功能。

.步骤
. 根据相应的ONTAP版本下载集群SHM配置zip文件。此文件可从获取 https://mysupport.netapp.com/NOW/cgi-bin/software/["NetApp 软件下载"^] 页面。
+
.. 在软件下载页面上，选择 * 交换机运行状况监控器配置文件 *
.. 选择Platform =* ONTAP *，然后选择*开始！*
.. 在“Switch Health Monitor Configuration Files for ONTAP”(交换机运行状况监控器配置文件)页上，选择“*查看并下载*”
.. 在"Switch Health Monitor Configuration Files for ONTAP (交换机运行状况监控器配置文件问题描述)">"Nexus "页面上、为适用的集群交换机型号选择*下载*、例如：* Cisco Nexus 9335C*
.. 在“最终用户许可协议”页面上，选择*accept *
.. 在"Switch Health Monitor Configuration Files for ONTAP > Download"(交换机运行状况监控器配置文件>下载)页面上、选择适用的配置文件、例如*Cisco_Nexus _9336-x2.zip*


. 将适用的 zip 文件上传到 IP 地址为 X.X.X.X.X 的内部 Web 服务器
+
对于内部 Web 服务器 IP 地址 192.168.2.2 并假设存在 /usr/download 目录，您可以使用 scp 将 zip 文件上传到 Web 服务器：

+
[listing]
----
% scp Cisco_Nexus_9336C-FX2.zip admin@192.168.2.20:/usr/download/Cisco_Nexus_9336C-FX2.zip
----
. 从集群中的一个ONTAP系统访问高级模式设置：
+
`set-privilege advanced`

+
[listing]
----
cluster1::> set -privilege advanced
----
. 运行交换机运行状况监控器配置命令 `system cluster-switch configure-health-monitor -node * -package-url X.X.X.X/location_to_download_zip_file`：
+
[listing]
----
cluster1::> system cluster-switch configure-health-monitor -node * -package-url 192.168.2.20/usr/download/Cisco_Nexus_9336C-FX2.zip
----
. 验证命令输出是否包含文本字符串 "downloaded package processed successfully" 。如果发生错误，请联系 NetApp 支持部门。
. 运行命令 `system cluster-switch show` 在ONTAP系统上、确保发现集群交换机、并且"Monitored"(监控)字段设置为"True"(真)。
+
[listing]
----
cluster1::> system cluster-switch show
----
+

NOTE: 如果在任何时候还原到早期版本的ONTAP、则需要重新安装SHM配置文件以启用9334C-查 尔特克集群交换机的SHM。


