---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: '按照以下步骤在BES-53248集群交换机上安装以太网网络结构操作系统(EFOS)软件。' 
---
= 安装 EFOS 软件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照以下步骤在BES-53248集群交换机上安装以太网网络结构操作系统(EFOS)软件。

EFOS软件包括一组高级网络功能和协议、用于开发以太网和IP基础架构系统。此软件架构适用于使用需要全面数据包检查或隔离的应用程序的任何网络组织设备。



== 准备安装

.开始之前
* 此操作步骤仅适用于新安装。
* 从下载适用于集群交换机的Broadcom EFOS软件 https://www.broadcom.com/support/bes-switch["Broadcom 以太网交换机支持"^] 站点
* 确保 link:configure-install-initial.html["配置了BES-53248集群交换机"]。




== 安装软件

使用以下方法之一安装EFOS软件：

* <<方法1：安装EFOS>>。适用于大多数情况。
* <<方法2：在ONIE模式下安装EFOS>>。如果一个EFOS版本符合FIPS、而另一个EFOS版本不符合FIPS、则使用。




=== 方法1：安装EFOS

执行以下步骤以安装EFOS软件。

.步骤
. 登录到交换机串行控制台端口或使用SSH连接。
. 使用 `ping` 命令验证与托管 EFOS ，许可证和 RCF 文件的服务器的连接。
+
.显示示例
[%collapsible]
====
此示例验证交换机是否已连接到 IP 地址为 172.19.2.1 的服务器：

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. 将映像文件下载到交换机。
+
有关支持的复制协议的信息、请查看下表：

+
|===


| *协议* | *先决条件* 


 a| 
简单文件传输协议(Trivial File Transfer Protocol、TFTP)
 a| 
无



 a| 
SSH文件传输协议(SFTP)
 a| 
您的软件包必须支持安全管理



 a| 
FTP
 a| 
密码为必填项



 a| 
XModem
 a| 
无



 a| 
Ymodem
 a| 
无



 a| 
Zmodem
 a| 
无



 a| 
安全复制协议(SCP)
 a| 
您的软件包必须支持安全管理



 a| 
HTTP
 a| 
如果本机wget实用程序可用、则选定平台支持基于命令行界面的文件传输



 a| 
HTTPS
 a| 
如果本机wget实用程序可用、则选定平台支持基于命令行界面的文件传输

|===
+
将映像文件复制到活动映像意味着，重新启动时，该映像将建立正在运行的 EFOS 版本。上一个映像仍可用作备份。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. 显示活动配置和备份配置的启动映像：
+
`s如何启动 var`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====
. 重新启动交换机：
+
`re负载`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
====
. 重新登录并验证 EFOS 软件的新版本：
+
`s如何使用版本`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. 完成安装。
按照以下五个步骤重新配置交换机：
+
.. link:configure-licenses.html["安装许可证"]
.. link:configure-install-rcf.html["安装RCF文件"]
.. link:configure-ssh.html["启用 SSH ："]
.. link:CSHM_log_collection.html["启用日志收集"]
.. link:CSHM_snmpv3.html["配置SNMPv3以进行监控"]


. 对配对交换机重复步骤1至7。




=== 方法2：在ONIE模式下安装EFOS

如果一个 EFOS 版本符合 FIPS ，而另一个 EFOS 版本不符合 FIPS ，则可以执行以下步骤。如果交换机无法启动，可通过以下步骤从 ONIE 安装非 FIPS 或 FIPS 兼容 EFOS 3.7.x.x 映像。

.步骤
. 连接到连接到交换机串行端口的控制台。
. 将交换机启动至 ONIE 安装模式。
+
在启动期间、当您看到提示时选择ONIE。

+
.显示示例
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
选择* ONIE*后、交换机将加载并为您提供多个选项。选择*安装OS*。

+
.显示示例
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
交换机将启动至ONIE安装模式。

. 停止 ONIE 发现并配置以太网接口。
+
出现以下消息时、按*输入*以调用ONIE控制台：

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIE发现将继续、并将消息打印到控制台。

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. 使用配置交换机管理端口的以太网接口并添加路由 `ifconfig eth0 <ipAddress> netmask <netmask> up` 和 `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. 验证托管 ONIE 安装文件的服务器是否可访问：
+
`ping`

+
.显示示例
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. 安装新的交换机软件：
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.显示示例
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
软件将安装并重新启动交换机。让交换机正常重新启动到新的 EFOS 版本。

. 登录并验证是否已安装新交换机软件：
+
`s如何启动 var`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
 1      3.7.0.4     3.7.0.4    3.7.0.4        3.10.0.3
(cs2) #
----
====
. 完成安装。
交换机在未应用任何配置的情况下重新启动、并重置为出厂默认值。按照以下六个步骤重新配置交换机：
+
.. link:configure-install-initial.html["配置交换机"]
.. link:configure-licenses.html["安装许可证"]
.. link:configure-install-rcf.html["安装RCF文件"]
.. link:configure-ssh.html["启用 SSH ："]
.. link:CSHM_log_collection.html["启用日志收集"]
.. link:CSHM_snmpv3.html["配置SNMPv3以进行监控"]


. 对配对交换机重复步骤1至8。


.下一步
安装完 EFOS 软件后，您可以…… link:configure-licenses.html["安装您的许可证"]。
