---
permalink: switch-bes-53248/configure-licenses.html 
sidebar: sidebar 
keywords: bes, cluster, switch, base, model, license, 10gbe, 25gbe, 100gbe, port, add, purchasing, purchase, install licenses for bes-53248 cluster switches - bes-53248 switches 
summary: BES-53248 集群交换机基本型号已获得 16 个 10GbE 或 25GbE 端口和 2 个 100GbE 端口的许可。可以通过购买更多许可证来添加新端口。 
---
= 安装 BES-53248 集群交换机的许可证
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 集群交换机基本型号已获得 16 个 10GbE 或 25GbE 端口和 2 个 100GbE 端口的许可。您可以通过购买更多许可证来添加新端口。


CAUTION: 对于EFOS 3-16及更高版本，请按照中的安装步骤进行操作link:efos-install-rcf-license-file.html["安装参考配置文件(Reference Configuration File、RCF)和许可证文件"]。



== 查看可用许可证

以下许可证可用于 BES-53248 集群交换机：

[cols="1,2,3"]
|===
| 许可证类型 | 许可证详细信息 | 支持的固件版本 


 a| 
SW-BES-53248A2-8P-2P
 a| 
Broadcom 8pt-10G25G + 2pt-40G100G许可密钥、X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES-53248A2-8P-1025G
 a| 
Broadcom 8端口10G25G许可密钥，X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES53248A2-6P-40-100G
 a| 
Broadcom 6端口40G100G许可密钥，X190005/R
 a| 
EFOS 3.4.4.6 及更高版本

|===


== 旧版许可证

下表列出了可在BES-53248集群交换机上使用的原有许可证：

[cols="1,2,3"]
|===
| 许可证类型 | 许可证详细信息 | 支持的固件版本 


 a| 
SW-BES-53248A1-G1-8P-LIC
 a| 
Broadcom 8P 10-25 ， 2P40-100 许可证密钥， X190005/R
 a| 
EFOS 3.4.3.3 及更高版本



 a| 
SW-BES-53248A1-G1-16P-LIC
 a| 
Broadcom 16P 10-25 ， 4P40-100 许可证密钥， X190005/R
 a| 
EFOS 3.4.3.3 及更高版本



 a| 
SW-BES-53248A1-G1-24P 许可证
 a| 
Broadcom 24P 10-25 ， 6P40-100 许可证密钥， X190005/R
 a| 
EFOS 3.4.3.3 及更高版本



 a| 
SW-BES542400-40-100G-LIC
 a| 
Broadcom 6 端口 40G100G 许可证密钥， X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES53248-8P-10G25G-LIC
 a| 
Broadcom 8 端口 10G25G 许可证密钥， X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES53248/16P-1025G-LIC
 a| 
Broadcom 16 端口 10G25G 许可证密钥， X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES532424-24P-1025G-LIC
 a| 
Broadcom 24 端口 10G25G 许可证密钥， X190005/R
 a| 
EFOS 3.4.4.6 及更高版本

|===

NOTE: 基本配置不需要许可证。



== 安装许可证文件

按照以下步骤为BES-53248集群交换机安装许可证。

.步骤
. 将集群交换机连接到管理网络。
. 使用 `ping` 命令验证与托管 EFOS ，许可证和 RCF 文件的服务器的连接。
+
.显示示例
[%collapsible]
====
此示例验证交换机是否已连接到 IP 地址为 172.19.2.1 的服务器：

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. 检查交换机 CS2 上的当前许可证使用情况：
+
`s如何许可`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----
====
. 安装许可证文件。
+
重复此步骤可加载更多许可证并使用不同的密钥索引编号。

+
.显示示例
[%collapsible]
====
以下示例使用 SFTP 将许可证文件复制到密钥索引 1 。

[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...


License Key transfer operation completed successfully. System reboot is required.
----
====
. 显示所有当前许可证信息，并在重新启动交换机 CS2 之前记下许可证状态：
+
`s如何许可`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----
====
. 显示所有已许可的端口：
+
`s如何全部端口 | 排除断开`

+
只有在重新启动交换机后，才会显示其他许可证文件中的端口。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----
====
. 重新启动交换机：
+
`re负载`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----
====
. 检查新许可证是否处于活动状态，并注意此许可证是否已应用：
+
`s如何许可`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----
====
. 检查所有新端口是否可用：
+
`s如何全部端口 | 排除断开`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----
====



CAUTION: 安装其他许可证时、必须手动配置新接口。请勿将RCF重新应用于现有工作正常的生产交换机。



== 对安装问题进行故障排除

如果在安装许可证时出现问题、请在运行之前运行以下调试命令 `copy` 命令。

要使用的调试命令：`debug transfer`和`debug license`

.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *debug transfer*
Debug transfer output is enabled.
(cs2)# *debug license*
Enabled capability licensing debugging.
----
====
运行时 `copy` 命令 `debug transfer` 和 `debug license` options enabled、将返回日志输出。

.显示示例
[%collapsible]
====
[listing]
----
transfer.c(3083):Transfer process  key or certificate file type = 43
transfer.c(3229):Transfer process  key/certificate cmd = cp /mnt/download//license.dat.1 /mnt/fastpath/ >/dev/null 2>&1CAPABILITY LICENSING :
Fri Sep 11 13:41:32 2020: License file with index 1 added.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Validating hash value 29de5e9a8af3e510f1f16764a13e8273922d3537d3f13c9c3d445c72a180a2e6.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Parsing JSON buffer {
  "license": {
    "header": {
      "version": "1.0",
      "license-key": "964B-2D37-4E52-BA14",
      "serial-number": "QTFCU38290012",
      "model": "BES-53248"
  },
  "description": "",
  "ports": "0+6"
  }
}.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: License data does not contain 'features' field.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Serial number QTFCU38290012 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Model BES-53248 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Feature not found in license file with index = 1.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Applying license file 1.
----
====
在调试输出中检查以下内容：

* 检查序列号是否匹配： `s序列号 QTCU38290012 匹配。`
* 检查交换机型号是否匹配： `model BES-53248 matched 。`
* 检查指定的许可证索引是否以前未使用过。如果已使用许可证索引，则返回以下错误： `License file /mnt/download//license.date.1 already exists.`
* 端口许可证不是功能许可证。因此，应遵循以下语句：在索引为 1.` 的许可证文件中未找到 `功能


使用 `copy` 用于将端口许可证备份到服务器的命令：

[listing, subs="+quotes"]
----
(cs2)# *copy nvram:license-key 1 scp://<UserName>@<IP_address>/saved_license_1.dat*
----

CAUTION: 如果需要将交换机软件从 3.4.4.6 版降级，则许可证将被删除。这是预期行为。

在还原到软件的旧版本之前，您必须安装相应的旧版许可证。



== 激活新许可的端口

要激活新许可的端口、您需要编辑最新版本的RCF并取消注释适用的端口详细信息。

默认许可证会激活端口 0/1 到 0/16 以及从 0/55 到 0/56 ，而新许可的端口将位于端口 0/17 到 0/54 之间，具体取决于可用许可证的类型和数量。例如、要激活SW-BES54244-40-100G-LIC许可证、必须取消注释RCF中的以下部分：

.显示示例
[%collapsible]
====
[listing]
----
.
.
!
! 2-port or 6-port 40/100GbE node port license block
!
interface 0/49
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/50
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/51
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/52
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/53
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/54
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
.
.
----
====

NOTE: 对于介于0/49到0/54之间的高速端口、取消对每个端口的注释、但仅对RCF中每个端口的一个*速度*行进行注释、如示例所示：*速度100G全双工*或*速度40G全双工*。对于介于 0/17 到 0/48 之间的低速度端口，激活相应的许可证后，取消对整个 8 端口部分的注释。

.下一步是什么？
link:configure-install-rcf.html["安装参考配置文件（ RCF ）"] 或 link:upgrade-rcf.html["升级RC框架"]。
