---
permalink: switch-bes-53248/configure-licenses.html 
sidebar: sidebar 
keywords: bes, cluster, switch, base, model, license, 10gbe, 25gbe, 100gbe, port, add, purchasing, purchase, install licenses for bes-53248 cluster switches - bes-53248 switches 
summary: BES-53248 集群交换机基本型号已获得 16 个 10GbE 或 25GbE 端口和 2 个 100GbE 端口的许可。可以通过购买更多许可证来添加新端口。 
---
= 安装 BES-53248 集群交换机的许可证
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 集群交换机基本型号已获得 16 个 10GbE 或 25GbE 端口和 2 个 100GbE 端口的许可。可以通过购买更多许可证来添加新端口。

以下许可证可用于 BES-53248 集群交换机：

[cols="1,2,3"]
|===
| 许可证类型 | 许可证详细信息 | 支持的固件版本 


 a| 
SW-BES-53248A1-G1-8P-LIC
 a| 
Broadcom 8P 10-25 ， 2P40-100 许可证密钥， X190005/R
 a| 
EFOS 3.4.3.3 及更高版本



 a| 
SW-BES-53248A1-G1-16P-LIC
 a| 
Broadcom 16P 10-25 ， 4P40-100 许可证密钥， X190005/R
 a| 
EFOS 3.4.3.3 及更高版本



 a| 
SW-BES-53248A1-G1-24P 许可证
 a| 
Broadcom 24P 10-25 ， 6P40-100 许可证密钥， X190005/R
 a| 
EFOS 3.4.3.3 及更高版本



 a| 
SW-BES542400-40-100G-LIC
 a| 
Broadcom 6 端口 40G100G 许可证密钥， X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES53248-8P-10G25G-LIC
 a| 
Broadcom 8 端口 10G25G 许可证密钥， X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES53248/16P-1025G-LIC
 a| 
Broadcom 16 端口 10G25G 许可证密钥， X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES532424-24P-1025G-LIC
 a| 
Broadcom 24 端口 10G25G 许可证密钥， X190005/R
 a| 
EFOS 3.4.4.6 及更高版本

|===
.步骤
. 将集群交换机连接到管理网络。
. 使用 `ping` 命令验证与托管 EFOS ，许可证和 RCF 文件的服务器的连接。
+
此示例验证交换机是否已连接到 IP 地址为 172.19.2.1 的服务器：

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. 检查交换机 CS2 上的当前许可证使用情况：
+
`s如何许可`

+
[listing, subs="+quotes"]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----
. 安装许可证文件。以下示例使用 SFTP 将许可证文件复制到密钥索引 1 。
+
重复此步骤可加载更多许可证并使用不同的密钥索引编号。

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...


License Key transfer operation completed successfully. System reboot is required.
----
. 显示所有当前许可证信息，并在重新启动交换机 CS2 之前记下许可证状态：
+
`s如何许可`

+
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----
. 显示所有已许可的端口：
+
`s如何全部端口 | 排除断开`

+
只有在重新启动交换机后，才会显示其他许可证文件中的端口。

+
[listing, subs="+quotes"]
----
(cs2)# *show port all \| exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----
. 重新启动交换机：
+
`re负载`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----
. 检查新许可证是否处于活动状态，并注意此许可证是否已应用：
+
`s如何许可`

+
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----
. 检查所有新端口是否可用：
+
`s如何全部端口 | 排除断开`

+
[listing, subs="+quotes"]
----
(cs2)# *show port all \| exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----



CAUTION: 安装其他许可证时、必须手动配置新接口。建议不要将RCF重新应用于现有正常运行的生产交换机。
