---
permalink: switch-bes-53248/configure-new-switch-overview.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure new bes-53248 switch 
summary: 在配置BES-53248集群交换机之前、请查看配置概述。 
---
= BES-53248交换机的安装和配置概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248是一款裸机交换机、设计用于2到24个节点的ONTAP 集群。



== 初始配置概述

要在运行ONTAP 的系统上初始配置BES-53248集群交换机、请执行以下步骤：

. link:install-hardware-bes53248.html["安装BES-53248集群交换机的硬件"]。
+
有关说明、请参见_Broadcom-Supported BES-53248 Cluster Switch Installation Guide_。

. link:configure-install-initial.html["配置BES-53248集群交换机"]。
+
对BES-53248集群交换机执行初始设置。

. link:configure-efos-software.html["安装 EFOS 软件"]。
+
在BES-53248集群交换机上下载并安装以太网阵列操作系统(EFOS)软件。

. link:configure-licenses.html["安装 BES-53248 集群交换机的许可证"]。
+
或者、也可以通过购买和安装更多许可证来添加新端口。此交换机基本型号已获得16个10GbE或25GbE端口和两个100GbE端口的许可。

. link:configure-install-rcf.html["安装参考配置文件（ RCF ）"]。
+
在BES-53248集群交换机上安装或升级RCF、然后在应用RCF后验证端口以获取额外许可证。

. link:configure-health-monitor.html["安装集群交换机运行状况监控器（ CSHM ）配置文件"]。
+
安装适用于集群交换机运行状况监控的配置文件。

. link:configure-ssh.html["在 BES-53248 集群交换机上启用 SSH"]。
+
如果使用集群交换机运行状况监控器(Cluster Switch Health Monitor、CSHM)和日志收集功能、请在交换机上启用SSH。

. link:configure-log-collection.html["启用日志收集功能"]。
+
使用日志收集功能在ONTAP 中收集与交换机相关的日志文件。





== 追加信息

开始安装或维护之前、请务必查看以下内容：

* link:configure-reqs-bes53248.html["配置要求"]
* link:components-bes53248.html["组件和部件号"]
* link:required-documentation-bes53248.html["所需文档"]

