---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: 您可以使用此操作步骤在 BES-53248 集群交换机上安装 EFOS 软件。您可以从 Broadcom 以太网交换机支持站点下载适用于集群交换机的 Broadcom EFOS 软件。 
---
= 安装 EFOS 软件
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用此操作步骤在 BES-53248 集群交换机上安装 EFOS 软件。您可以从 Broadcom 以太网交换机支持站点下载适用于集群交换机的 Broadcom EFOS 软件。



==== 关于此任务

====
* 请注意以下事项： *

* 从 EFOS 3.4.x.x 升级到 EFOS 3.7.x.x 或更高版本时，交换机必须运行 EFOS 3.4.4.6 （或更高版本 3.4.x.x ）。如果您运行的是之前的版本，请先将交换机升级到 EFOS 3.4.4.6 （或更高版本 3.4.x.x ），然后再将交换机升级到 EFOS 3.7.x.x 或更高版本。
* EFOS 3.4.x.x 和 3.7.x.x 或更高版本的配置有所不同。要将 EFOS 版本从 3.4.x.x 更改为 3.7.x.x 或更高版本，或者反之，则需要将交换机重置为出厂默认值，并重新应用相应 EFOS 版本的 RCF 文件。此操作步骤需要通过串行控制台端口进行访问。
* 从 EFOS 3.7.x.x 或更高版本开始，可以使用非 FIPS 兼容版本和 FIPS 兼容版本。从不符合 FIPS 的版本迁移到符合 FIPS 的版本时，需执行不同的步骤，反之亦然。将 EFOS 从不符合 FIPS 的版本更改为符合 FIPS 的版本，或者反之，则会将交换机重置为出厂默认值。此操作步骤需要通过串行控制台端口进行访问。


====
|===


| * 操作步骤 * | * 当前 EFOS 版本 * | * 新 EFOS 版本 * | * 高级步骤 * 


 a| 
在两个（非） FIPS 兼容版本之间升级 EFOS 的步骤
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
使用方法 1 安装新的 EFOS 映像）配置和许可证信息将保留



 a| 
3.4.4.6 （或更高版本 3.4.x.x ）
 a| 
不符合 FIPS 的 3.7.x.x 或更高版本
 a| 
使用方法 1 升级 EFOS 。将交换机重置为出厂默认设置，并对 EFOS 3.7.x.x 或更高版本应用 RCF 文件



.2+| 不符合 FIPS 的 3.7.x.x 或更高版本  a| 
3.4.4.6 （或更高版本 3.4.x.x ）
 a| 
使用方法 1 降级 EFOS 。将交换机重置为出厂默认设置，并对 EFOS 3.4.x.x 应用 RCF 文件



 a| 
不符合 FIPS 的 3.7.x.x 或更高版本
 a| 
使用方法 1 安装新的 EFOS 映像。配置和许可证信息会保留下来



 a| 
符合 3.7.x.x 或更高版本 FIPS
 a| 
符合 3.7.x.x 或更高版本 FIPS
 a| 
使用方法 1 安装新的 EFOS 映像。配置和许可证信息会保留下来



 a| 
升级到 / 从 FIPS 兼容 EFOS 版本的步骤
 a| 
不符合 FIPS
 a| 
符合 FIPS
 a| 
使用方法 2 安装 EFOS 映像。交换机配置和许可证信息将丢失。



 a| 
符合 FIPS
 a| 
不符合 FIPS

|===

IMPORTANT: 请注意，将 BES-53248 集群交换机从 EFOS 3.3.x.x 或 3.4.x.x 升级到 EFOS 3.7.0.4 或 3.8.0.2 后，交换机间链路（ ISL ）和端口通道将标记为 * 关闭 * 状态。请参见此内容 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["知识库文章"^] 了解更多详细信息。

.步骤
. 将 BES-53248 集群交换机连接到管理网络。
. 使用 `ping` 命令验证与托管 EFOS ，许可证和 RCF 文件的服务器的连接。
+
此示例验证交换机是否已连接到 IP 地址为 172.19.2.1 的服务器：

+
[listing]
----
(cs2) # ping 172.19.2.1
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. 备份 CS2 上的当前活动映像：
+
`s如何启动 var`

+
[listing]
----
(cs2) # show bootvar

 Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------

    1      3.4.3.3     Q.10.22.1     3.4.3.3           3.4.3.3
(cs2) # copy active backup
Copying active to backup
Management access will be blocked for the duration of the operation
Copy operation successful

(cs2) # show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------

    1      3.4.3.3     3.4.3.3     3.4.3.3           3.4.3.3
(cs2) #
----
. 验证运行的 EFOS 软件版本：
+
`s如何使用版本`

+
[listing]
----
(cs2) # show version

Switch: 1

System Description............................. Quanta IX8-B 48x25GB SFP 8x100GB QSFP, 3.4.3.3, Linux 4.4.117-ceeeb99d, 2016.05.00.04
Machine Type................................... Quanta IX8-B 48x25GB SFP 8x100GB QSFP
Machine Model.................................. IX8-B
Serial Number.................................. QTFCU38260014
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:12:3D
Software Version............................... 3.4.3.3
Operating System............................... Linux 4.4.117-ceeeb99d
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
. 将映像文件下载到交换机。
+
将映像文件复制到活动映像意味着，重新启动时，该映像将建立正在运行的 EFOS 版本。上一个映像仍可用作备份。

+
[listing]
----
(cs2) # copy sftp://root@172.19.2.1//tmp/EFOS-3.4.4.6.stk active
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.4.4.6.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. 显示活动配置和备份配置的启动映像：
+
`s如何启动 var`

+
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     3.4.3.3     3.4.3.3            3.4.3.3            3.4.4.6
----
. 重新启动交换机：
+
`re负载`

+
[listing]
----
(cs2) # reload

The system has unsaved changes.
Would you like to save them now? (y/n) y

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
. 重新登录并验证 EFOS 软件的新版本：
+
`s如何使用版本`

+
[listing]
----
(cs2) # show version

Switch: 1

System Description............................. x86_64-quanta_common_rglbmc-r0, 3.4.4.6, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... x86_64-quanta_common_rglbmc-r0
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.4.4.6
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----




== 使用 ONIE 操作系统安装升级 EFOS

如果一个 EFOS 版本符合 FIPS ，而另一个 EFOS 版本不符合 FIPS ，则可以执行以下步骤。如果交换机无法启动，可通过以下步骤从 ONIE 安装非 FIPS 或 FIPS 兼容 EFOS 3.7.x.x 映像。


NOTE: 此功能仅适用于不符合 FIPS 的 EFOS 3.7.x.x 或更高版本。

.步骤
. 将交换机启动至 ONIE 安装模式。
+
在启动期间，如果出现以下屏幕，请选择 ONIE ：

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
选择 * ONIE"* 后，交换机将加载并向您提供以下选项：

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
此时，交换机将启动至 ONIE 安装模式。

. 停止 ONIE 发现并配置以太网接口。
+
出现以下消息后，按 <Enter> 键以调用 ONIE 控制台：

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIE 发现将继续，并将消息打印到控制台。

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. 配置以太网接口并使用 `ifconfig eth0 <ipAddress> netmask <netmask> up` 和 `route add default gw <gatewayAddress>` 添加路由
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. 验证托管 ONIE 安装文件的服务器是否可访问：
+
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
. 安装新的交换机软件：
+
[listing]
----
ONIE:/ # onie-nos-install http:// 50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http:// 50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http:// 50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
+
软件将安装并重新启动交换机。让交换机正常重新启动到新的 EFOS 版本。

. 验证是否已安装新的交换机软件： `show bootvar`
+
[listing, subs="+quotes"]
----
(cs2) # *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
1 	  3.7.0.4     3.7.0.4  3.7.0.4         3.7.0.4
(cs2) #
----
. 完成安装。
+
交换机将在未应用任何配置的情况下重新启动，并重置为出厂默认值。



* 相关信息 *

https://www.broadcom.com/support/bes-switch["Broadcom 以太网交换机支持"^]
