---
permalink: switch-bes-53248/configure-install-initial.html 
sidebar: sidebar 
keywords: switches initial setup,initial setup,efos download 
summary: 您可以使用此程序执行 BES-53248 集群交换机的初始安装。 
---
= 配置 BES-53248 集群交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照以下步骤对 BES-53248 集群交换机进行初始设置。

.开始之前
* 硬件已按所述方式安装。link:install-hardware-bes53248.html["安装硬件"] 。
* 您已审阅以下内容：
+
** link:configure-reqs-bes53248.html["配置要求"]
** link:components-bes53248.html["组件和零件编号"]
** link:required-documentation-bes53248.html["文档要求"]




.关于示例
配置过程中的示例使用以下交换机和节点命名规则：

* NetApp交换机的名称是 `cs1`和 `cs2`。升级从第二个交换机 _cs2 开始。
* 集群 LIF 名称为 `node1_clus1`和 `node1_clus2`对于节点1，以及 `node2_clus1`和 `node2_clus2`对于节点2。
* IP空间名称为Cluster。
* 这 `cluster1::>`prompt 指示集群名称。
* 每个节点上的集群端口都命名为 `e0a`和 `e0b`。参见 https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^]针对您的平台实际支持的集群端口。
* NetApp交换机支持的交换机间链路 (ISL) 为端口 0/55 和 0/56。
* NetApp交换机支持的节点连接为端口 0/1 至 0/16，采用默认许可。
* 示例中使用了两个节点，但集群中最多可以有 24 个节点。


.步骤
. 将串口连接到主机或串口。
. 将管理端口（交换机左侧的 RJ-45 扳手端口）连接到 TFTP 服务器所在的同一网络。
. 在控制台上，设置主机端串口设置：
+
** 115200 波特
** 8 位数据
** 1 停止位
** 奇偶性：无
** 流量控制：无


. 以管理员身份登录交换机。 `admin`当系统提示输入密码时，按 *Enter* 键。默认交换机名称为 *routing*。出现提示时，输入 `enable`。这样您就可以访问特权 EXEC 模式以进行交换机配置。
+
[listing, subs="+quotes"]
----
User: *admin*
Password:
(Routing)> *enable*
Password:
(Routing)#
----
. 将交换机名称更改为 *cs2*。
+
[listing, subs="+quotes"]
----
(Routing)# *hostname cs2*
(cs2)#
----
. 要为交换机的服务端口设置静态 IPv4 或 IPv6 管理地址：


[role="tabbed-block"]
====
.IPv4
--
服务端口默认设置为使用 DHCP。  IP地址、子网掩码和默认网关地址将自动分配。

[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ip <ip-address> <netmask> <gateway>*
----
--
.IPv6
--
服务端口默认设置为使用 DHCP。  IP地址、子网掩码和默认网关地址将自动分配。

[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ipv6 <address>*
(cs2)# *serviceport ipv6 <gateway>*
----
--
====
. [[步骤7]]使用以下命令验证结果：
+
`show serviceport`

+
[listing, subs="+quotes"]
----
(cs2)# *show serviceport*
Interface Status............................... Up
IP Address..................................... 172.19.2.2
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 172.19.2.254
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe71:123c/64
IPv6 Default Router............................ fe80::20b:45ff:fea9:5dc0
Configured IPv4 Protocol....................... DHCP
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:71:12:3C
----
. 配置域名和名称服务器：
+
[source, cli]
----
ip domain name <domain_name>
ip name server <server_name>
----
+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *ip domain name company.com*
(cs2)(Config)# *ip name server 10.10.99.1 10.10.99.2*
(cs2)(Config)# *exit*
(cs2)#
----
. 配置NTP服务器。


[role="tabbed-block"]
====
.EFOS 3.10.0.3 及更高版本
--
配置时区和时间同步（NTP）：

[source, cli]
----
sntp server <server_name>
clock
----
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *ntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
.EFOS 3.9.0.2 及更早版本
--
配置时区和时间同步（SNTP）：

[source, cli]
----
sntp client mode <client_mode>
sntp server <server_name>
clock
----
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *sntp client mode unicast*
(cs2)(Config)# *sntp server 10.99.99.5*
(cs2)(Config)# *clock timezone -7*
(cs2)(Config)# *exit*
(cs2)#
----
--
====
. [[step10]]如果您在上一步中没有配置 NTP 服务器，请手动配置时间。


[role="tabbed-block"]
====
.EFOS 3.10.0.3 及更高版本
--
手动设置时间。

`clock`

[listing, subs="+quotes"]
----

(cs2)# *configure*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2023*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2023
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
.EFOS 3.9.0.2 及更早版本
--
手动设置时间。

`clock`

[listing, subs="+quotes"]
----

(cs2)# *configure*
(cs2)(Config)# *no sntp client mode*
(cs2)(Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2)(Config)# *clock timezone -5 zone EST*
(cs2)(Config)# *clock set 07:00:00*
(cs2)(Config)# *clock set 10/20/2023*
(cs2)(Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2023
No time source

(cs2)(Config)# *exit*
(cs2)#
----
--
====
. [[步骤11]]将运行配置保存到启动配置中：
+
`write memory`

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----


.下一步是什么？
配置好交换机后，您可以…… link:configure-efos-software.html["安装 EFOS 软件"]。
