---
permalink: switch-bes-53248/configure-licenses.html 
sidebar: sidebar 
keywords: bes, cluster, switch, base, model, license, 10gbe, 25gbe, 100gbe, port, add, purchasing, purchase, install licenses for bes-53248 cluster switches - bes-53248 switches 
summary: BES-53248 集群交换机基本型号授权配备 16 个 10GbE 或 25GbE 端口和 2 个 100GbE 端口。可以通过购买更多许可证来添加新端口。 
---
= 安装 BES-53248 集群交换机的许可证
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 集群交换机基本型号授权配备 16 个 10GbE 或 25GbE 端口和 2 个 100GbE 端口。您可以通过购买更多许可证来添加新端口。


CAUTION: 对于 EFOS 3.12 及更高版本，请按照以下安装步骤进行操作：link:efos-install-rcf-license-file.html["安装参考配置文件 (RCF) 和许可证文件"] 。



== 查看可用许可证

以下许可证可用于 BES-53248 集群交换机：

[cols="1,2,3"]
|===
| 许可证类型 | 许可证详情 | 支持的固件版本 


 a| 
SW-BES-53248A2-8P-2P
 a| 
博通 8PT-10G25G + 2PT-40G100G 许可证密钥，X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES-53248A2-8P-1025G
 a| 
博通8端口10G25G许可证密钥，X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES53248A2-6P-40-100G
 a| 
博通 6 端口 40G/100G 许可证密钥，X190005/R
 a| 
EFOS 3.4.4.6 及更高版本

|===


== 旧版许可证

下表列出了可在 BES-53248 集群交换机上使用的旧版许可证：

[cols="1,2,3"]
|===
| 许可证类型 | 许可证详情 | 支持的固件版本 


 a| 
SW-BES-53248A1-G1-8P-LIC
 a| 
Broadcom 8P 10-25,2P40-100 许可证密钥，X190005/R
 a| 
EFOS 3.4.3.3 及更高版本



 a| 
SW-BES-53248A1-G1-16P-LIC
 a| 
Broadcom 16P 10-25,4P40-100 许可证密钥，X190005/R
 a| 
EFOS 3.4.3.3 及更高版本



 a| 
SW-BES-53248A1-G1-24P-LIC
 a| 
Broadcom 24P 10-25,6P40-100 许可证密钥，X190005/R
 a| 
EFOS 3.4.3.3 及更高版本



 a| 
SW-BES54248-40-100G-LIC
 a| 
博通 6 端口 40G/100G 许可证密钥，X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES53248-8P-10G25G-LIC
 a| 
博通8端口10G25G许可证密钥，X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES53248-16P-1025G-LIC
 a| 
博通 16 端口 10G25G 许可证密钥，X190005/R
 a| 
EFOS 3.4.4.6 及更高版本



 a| 
SW-BES53248-24P-1025G-LIC
 a| 
博通 24 端口 10G/25G 许可证密钥，X190005/R
 a| 
EFOS 3.4.4.6 及更高版本

|===

NOTE: 基本配置不需要许可证。



== 安装许可证文件

请按照以下步骤安装 BES-53248 集群交换机的许可证。

.步骤
. 将集群交换机连接到管理网络。
. 使用 `ping`用于验证与托管 EFOS、许可证和 RCF 文件的服务器的连接性的命令。
+
.显示示例
[%collapsible]
====
此示例验证交换机是否已连接到 IP 地址为 172.19.2.1 的服务器：

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. 检查交换机 CS2 的当前许可证使用情况：
+
`show license`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----
====
. 安装许可证文件。
+
重复此步骤以加载更多许可证并使用不同的密钥索引号。

+
.显示示例
[%collapsible]
====
以下示例使用 SFTP 将许可证文件复制到密钥索引 1。

[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...


License Key transfer operation completed successfully. System reboot is required.
----
====
. 显示所有当前许可证信息，并在交换机 cs2 重启前记录许可证状态：
+
`show license`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----
====
. 显示所有已授权端口：
+
`show port all | exclude Detach`

+
交换机重启后才会显示附加许可证文件中的端口。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----
====
. 重启交换机：
+
`reload`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----
====
. 请检查新许可证是否已激活，并确认许可证已应用：
+
`show license`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----
====
. 检查所有新端口是否可用：
+
`show port all | exclude Detach`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----
====



CAUTION: 安装其他许可证时，必须手动配置新接口。不要对现有正在运行的生产交换机重新应用 RCF。



== 排查安装问题

如果在安装许可证时出现问题，请在运行以下命令之前运行以下调试命令： `copy`再次发出命令。

可使用的调试命令： `debug transfer`和 `debug license`

.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *debug transfer*
Debug transfer output is enabled.
(cs2)# *debug license*
Enabled capability licensing debugging.
----
====
当你运行 `copy`使用命令 `debug transfer`和 `debug license`启用这些选项后，将返回日志输出。

.显示示例
[%collapsible]
====
[listing]
----
transfer.c(3083):Transfer process  key or certificate file type = 43
transfer.c(3229):Transfer process  key/certificate cmd = cp /mnt/download//license.dat.1 /mnt/fastpath/ >/dev/null 2>&1CAPABILITY LICENSING :
Fri Sep 11 13:41:32 2020: License file with index 1 added.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Validating hash value 29de5e9a8af3e510f1f16764a13e8273922d3537d3f13c9c3d445c72a180a2e6.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Parsing JSON buffer {
  "license": {
    "header": {
      "version": "1.0",
      "license-key": "964B-2D37-4E52-BA14",
      "serial-number": "QTFCU38290012",
      "model": "BES-53248"
  },
  "description": "",
  "ports": "0+6"
  }
}.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: License data does not contain 'features' field.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Serial number QTFCU38290012 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Model BES-53248 matched.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Feature not found in license file with index = 1.
CAPABILITY LICENSING : Fri Sep 11 13:41:32 2020: Applying license file 1.
----
====
请检查调试输出中的以下内容：

* 请检查序列号是否匹配： `Serial number QTFCU38290012 matched.`
* 检查交换机型号是否匹配： `Model BES-53248 matched.`
* 检查指定的许可证索引是否之前未被使用过。如果许可证索引已被使用，则会返回以下错误： `License file /mnt/download//license.dat.1 already exists.`
* 端口许可证并非功能许可证。因此，预期会出现以下语句： `Feature not found in license file with index = 1.`


使用 `copy`将端口许可证备份到服务器的命令：

[listing, subs="+quotes"]
----
(cs2)# *copy nvram:license-key 1 scp://<UserName>@<IP_address>/saved_license_1.dat*
----

CAUTION: 如果需要将交换机软件从 3.4.4.6 版本降级，则许可证将被移除。此行为是预期的。

在恢复到软件的旧版本之前，您必须先安装相应的旧版本许可证。



== 激活新授权的端口

要激活新授权的端口，您需要编辑最新版本的 RCF 文件，并取消注释相应的端口详细信息。

默认许可证激活端口 0/1 至 0/16 和 0/55 至 0/56，而新授权的端口将根据可用许可证的类型和数量在端口 0/17 至 0/54 之间。例如，要激活 SW-BES54248-40-100G-LIC 许可证，您必须取消注释 RCF 中的以下部分：

.显示示例
[%collapsible]
====
[listing]
----
.
.
!
! 2-port or 6-port 40/100GbE node port license block
!
interface 0/49
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/50
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/51
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/52
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/53
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/54
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
.
.
----
====

NOTE: 对于 0/49 到 0/54 之间的高速端口（含 0/49 和 0/54），取消注释每个端口，但每个端口的 RCF 中仅取消注释一行 *speed*，可以是：*speed 100G 全双工* 或 *speed 40G 全双工*，如示例所示。对于 0/17 到 0/48 之间的低速端口（含 0/17 和 0/48），当激活相应的许可证后，请取消注释整个 8 端口部分。

.下一步是什么？
安装许可证后，您可以 link:configure-install-rcf.html["安装参考配置文件（RCF）"] 或者 link:upgrade-rcf.html["升级 RCF"]。
