---
permalink: switch-bes-53248/migrate-to-2n-switched.html 
sidebar: sidebar 
keywords: two-node switchless clusters, migrating to a two-node switched BES-53248 cluster environment,BES-53248 switches, migrating two-node switched clusters,2-node 
summary: 如果您使用双节点无交换机集群、则可以无中断地迁移到包含Broadcom支持的BES-53248集群交换机的双节点有交换机集群 
---
= 迁移到交换式 NetApp 集群环境
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您有一个现有的双节点无交换机集群环境、则可以使用支持Broadcom的BES-53248集群交换机迁移到双节点_switched_cluster环境、从而可以扩展到集群中的两个节点以上。

迁移过程适用于使用光纤或双轴端口的所有集群节点端口、但如果节点使用板载10GBASE-T RJ45端口作为集群网络端口、则此交换机不支持迁移过程。



== 查看要求

查看集群环境的以下要求。

* 请注意、大多数系统在每个控制器上都需要两个专用的集群网络端口。
* 确保按照中所述设置BES-53248集群交换机 link:replace-switch-reqs.html["更换要求"] 开始此迁移过程之前。
* 对于双节点无交换机配置、请确保：
+
** 双节点无交换机配置已正确设置并正常运行。
** 这些节点运行的是ONTAP 9.5P8及更高版本。从 EFOS 固件版本 3.4.4.6 及更高版本开始，支持 40/100 GbE 集群端口。
** 所有集群端口均处于*启动*状态。
** 所有集群逻辑接口(LIF)均处于*启动*状态、并位于其主端口上。


* 对于Broadcom支持的BES-53248集群交换机配置、请确保：
+
** BES-53248集群交换机在这两台交换机上均可完全正常运行。
** 这两台交换机都具有管理网络连接。
** 可以通过控制台访问集群交换机。
** BES-53248节点到节点交换机和交换机到交换机连接使用双轴电缆或光缆。
+
。 https://hwu.netapp.com/Home/Index["_NetApp Hardware Universe"^] 包含有关ONTAP 兼容性、支持的EFOS固件以及连接到BES-53248交换机的布线的信息。



* 交换机间链路(ISL)缆线连接到两个BES-53248交换机上的端口0/55和0/56。
* 已完成对两个BES-53248交换机的初始自定义、以便：
+
** BES-53248交换机正在运行最新版本的软件。
** BES-53248交换机已安装可选端口许可证(如果已购买)。
** 参考配置文件(Reference Configuration Files、RCF)将应用于交换机。


* 所有站点自定义(SMTP、SNMP和SSH)均在新交换机上配置。




== 迁移到集群环境

.关于示例
此操作步骤中的示例使用以下集群交换机和节点命名：

* BES-53248 交换机的名称是 `CS1` 和 `CS2` 。
* 集群 SVM 的名称为 `node1` 和 `node2` 。
* LIF 的名称分别为节点 1 上的 `node1_clus1` 和 `node1_clus2` ，节点 2 上的 `node2_clus1` 和 `node2_clus2` 。
* `cluster1 ：：： * >` 提示符指示集群的名称。
* 此操作步骤中使用的集群端口为 `e0a` 和 `e0b` 。
+
。 https://hwu.netapp.com/Home/Index["_NetApp Hardware Universe"^] 包含有关平台的实际集群端口的最新信息。





=== 第1步：准备迁移

. 如果在此集群上启用了 AutoSupport ，则通过调用 AutoSupport 消息禁止自动创建案例：
+
`ssystem node AutoSupport invoke -node * -type all -message MAINT=xh`

+
其中 x 是维护时段的持续时间，以小时为单位。

+

NOTE: AutoSupport 消息会通知技术支持此维护任务，以便在维护窗口期间禁止自动创建案例。

+
以下命令将禁止自动创建案例 2 小时：

+
[listing]
----
cluster1::*> system node autosupport invoke -node \* -type all -message MAINT=2h
----
. 将权限级别更改为高级，在系统提示您继续时输入 * y * ：
+
`set -privilege advanced`

+
此时将显示高级提示符（` * >` ）。





=== 第2步：配置端口和布线

. 在新集群交换机 CS1 * 和 * CS2 上禁用所有已激活的面向节点的端口（而不是 ISL 端口）。
+

NOTE: 不得禁用 ISL 端口。

+
以下示例显示了交换机 CS1 上面向节点的端口 1 到 16 已禁用：

+
[listing, subs="+quotes"]
----
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *shutdown*
(cs1)(Interface 0/1-0/16)# *exit*
(cs1)(Config)# *exit*
----
. 验证两个BES-53248交换机CS1和CS2之间的ISL和ISL上的物理端口是否为*已启动*：
+
`s如何使用端口通道`

+
.显示示例
[%collapsible]
====
以下示例显示交换机CS1上的ISL端口为*上*：

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
以下示例显示交换机CS2上的ISL端口为*上*：

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. 显示相邻设备的列表：
+
`s如何使用 isdp 邻居`

+
此命令可提供有关连接到系统的设备的信息。

+
.显示示例
[%collapsible]
====
以下示例列出了交换机 CS1 上的相邻设备：

[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
以下示例列出了交换机 CS2 上的相邻设备：

[listing, subs="+quotes"]
----
(cs2)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
====
. 验证所有集群端口是否均已启动：
+
`network port show -ipspace cluster`

+
对于、每个端口都应显示"up" `Link` 和"运行状况良好" `Health Status`。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy
----
====
. 验证所有集群LIF是否均已"启动"且正常运行： `network interface show -vserver Cluster`
+
对于、每个集群LIF都应显示"true" `Is Home` 并具有 `Status Admin/Oper` "启动/启动"

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
----
====
. 在集群 LIF 上禁用自动还原。
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. 从 node1 上的集群端口 e0a 断开缆线连接，然后使用 BES-53248 交换机支持的相应布线方式将 e0a 连接到集群交换机 CS1 上的端口 1 。
+
。 https://hwu.netapp.com/Home/Index["_NetApp Hardware Universe"^] 包含有关布线的详细信息。

. 从节点 2 上的集群端口 e0a 断开缆线连接，然后使用 BES-53248 交换机支持的相应布线方式将 e0a 连接到集群交换机 CS1 上的端口 2 。
. 启用集群交换机 CS1 上面向节点的所有端口。
+
以下示例显示交换机 CS1 上的端口 1 到 16 已启用：

+
[listing, subs="+quotes"]
----
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *no shutdown*
(cs1)(Interface 0/1-0/16)# *exit*
(cs1)(Config)# *exit*
----
. 验证所有集群 LIF 是否均已启动，正常运行并显示为 `true` for `is Home` ：
+
`network interface show -vserver cluster`

+
.显示示例
[%collapsible]
====
以下示例显示 node1 和 node2 上的所有 LIF 均已启动，并且 `为 Home` Results 为 `true` ：

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true
----
====
. 显示有关集群中节点状态的信息：
+
`cluster show`

+
.显示示例
[%collapsible]
====
以下示例显示了有关集群中节点的运行状况和资格的信息：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. 从 node1 上的集群端口 e0b 断开缆线连接，然后使用 BES-53248 交换机支持的相应布线方式将 e0b 连接到集群交换机 CS2 上的端口 1 。
. 从节点 2 上的集群端口 e0b 断开缆线连接，然后使用 BES-53248 交换机支持的相应布线方式将 e0b 连接到集群交换机 CS2 上的端口 2 。
. 启用集群交换机 CS2 上面向节点的所有端口。
+
以下示例显示交换机 CS2 上的端口 1 到 16 已启用：

+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *interface 0/1-0/16*
(cs2)(Interface 0/1-0/16)# *no shutdown*
(cs2)(Interface 0/1-0/16)# *exit*
(cs2)(Config)# *exit*
----
. 验证所有集群端口是否均为*已启动*：
+
`network port show -ipspace cluster`

+
.显示示例
[%collapsible]
====
以下示例显示node1和node2上的所有集群端口均为*启动*：

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====




=== 第3步：验证配置

. 在集群 LIF 上启用自动还原。
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert true*
----
. 验证集群LIF是否已还原到其主端口(这可能需要一分钟时间)：
+
`network interface show -vserver cluster`

+
如果集群LIF尚未还原到其主端口、请手动还原它们：

+
`network interface revert -vserver cluster -lif *`

. 验证所有接口是否显示 `true` for `is Home` ：
+
`network interface show -vserver cluster`

+

NOTE: 完成此操作可能需要几分钟时间。

+
.显示示例
[%collapsible]
====
以下示例显示 node1 和 node2 上的所有 LIF 均已启动，并且 `为 Home` Results 为 `true` ：

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true
----
====
. 验证两个节点与每个交换机之间是否有一个连接：
+
`s如何使用 isdp 邻居`

+
.显示示例
[%collapsible]
====
以下示例显示了这两个交换机的相应结果：

[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform -- Port ID
-------------- ------------ --------- ------------ ----------- ----------
node1          0/1          175       H            FAS2750     e0a
node2          0/2          157       H            FAS2750     e0a
cs2            0/55         178       R            BES-53248   0/55
cs2            0/56         178       R            BES-53248   0/56


(cs2)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform    Port ID
-------------- ------------ --------- ------------ ----------- ------------
node1          0/1          137       H            FAS2750     e0b
node2          0/2          179       H            FAS2750     e0b
cs1            0/55         175       R            BES-53248   0/55
cs1            0/56         175       R            BES-53248   0/56
----
====
. 显示有关集群中发现的网络设备的信息：
+
`network device-discovery show -protocol cdp`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
----
====
. 验证这些设置是否已禁用：
+
`network options switchless-cluster show`

+

NOTE: 完成此命令可能需要几分钟的时间。等待 " 三分钟生命周期到期 " 公告。

+
以下示例中的 `false` 输出显示配置设置已禁用：

+
[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
. 验证集群中节点成员的状态：
+
`cluster show`

+
.显示示例
[%collapsible]
====
以下示例显示了有关集群中节点的运行状况和资格的信息：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. 使用命令验证集群网络是否已完全连接：
+
`cluster ping-cluster -node _node-name_`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*

Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 192.168.168.26 node1 e0a
Cluster node1_clus2 192.168.168.27 node1 e0b
Cluster node2_clus1 192.168.168.28 node2 e0a
Cluster node2_clus2 192.168.168.29 node2 e0b
Local = 192.168.168.28 192.168.168.29
Remote = 192.168.168.26 192.168.168.27
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 4 path(s):
    Local 192.168.168.28 to Remote 192.168.168.26
    Local 192.168.168.28 to Remote 192.168.168.27
    Local 192.168.168.29 to Remote 192.168.168.26
    Local 192.168.168.29 to Remote 192.168.168.27
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====
. 将权限级别重新更改为 admin ：
+
`set -privilege admin`

. 如果禁止自动创建案例，请通过调用 AutoSupport 消息重新启用它：
+
`ssystem node AutoSupport invoke -node * -type all -message MAINT=end`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster1::*> system node autosupport invoke -node \* -type all -message MAINT=END
----
====
+
有关详细信息，请参见 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetApp 知识库文章： How to suppress automatic case creation during scheduled maintenance windows."^]



.下一步是什么？
迁移完成后，您可能需要安装所需的配置文件，以支持 BES-53248 集群交换机的集群交换机运行状况监控器（ Cluster Switch Health Monitor ， CSHM ）。请参见 link:configure-health-monitor.html["安装集群交换机运行状况监控器（ CSHM ）配置文件"] 和 link:configure-log-collection.html["启用日志收集功能"]。
