---
permalink: switch-bes-53248/migrate-cn1610-overview.html 
sidebar: sidebar 
keywords: BES-53248 switches,replacing with BES-53248 switches, migrate cluster switches 
summary: 在将 CN1610 集群交换机迁移到支持 Broadcom 的 BES-53248 集群交换机时，您必须了解某些配置信息，端口连接和布线要求。 
---
= 将 CN1610 集群交换机迁移到支持 Broadcom 的 BES-53248 集群交换机
:icons: font
:imagesdir: ../media/


[role="lead"]
在将 CN1610 集群交换机迁移到支持 Broadcom 的 BES-53248 集群交换机时，您必须了解某些配置信息，端口连接和布线要求。

* 支持以下集群交换机：
+
** CN1610
** BES-53248


* 集群交换机支持以下节点连接：
+
** NetApp CN1610 ：端口 0/1 到 0/12 （ 10 GbE ）
** BES-53248 ：端口 0/1-0/16 （ 10/25 GbE ）
+

NOTE: 可以通过购买端口许可证来激活其他端口。



* 集群交换机使用以下交换机间链路（ ISL ）端口：
+
** NetApp CN1610 ：端口 0/13 至 0/16 （ 10 GbE ）
** BES-53248 ：端口 0/55-0/56 （ 100 GbE ）


* Hardware Universe 包含有关 ONTAP 兼容性，支持的 EFOS 固件以及 BES-53248 集群交换机布线的信息。
* 相应的 ISL 布线如下所示：
+
** * 起始： * 对于 CN1610 到 CN1610 （ SFP+ 到 SFP+ ），需要四根 SFP+ 光纤或铜缆直连缆线。
** * 临时： * 对于 CN1610 到 BES-53248 （ SFP+ 到 SFP28 ），使用四根 10G SFP+ 光纤收发器 / 光纤或铜缆直连。
** * 最终版本： * 对于 BES-53248 到 BES-53248 （ QSFP28 到 QSFP28 ），需要两根 QSFP28 光纤收发器 / 光纤或铜缆直连缆线。





NOTE: 迁移完成后，您可能需要安装所需的配置文件，以支持 BES-53248 集群交换机的集群交换机运行状况监控器（ Cluster Switch Health Monitor ， CSHM ）。

请参见 http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-sw-ix8-setup/GUID-211616A4-C962-464A-A70E-5E057D7B13E1.html["安装集群交换机运行状况监控器（ CSHM ）配置文件"] 在《适用于 Broadcom 支持的 BES-53248 交换机的 _Switch 设置和配置指南》中。

请参见中的 _Configuring the cluster switch log Collection feature_ http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-sw-ix8-setup/home.html["《适用于 Broadcom 支持的 BES-53248 交换机的交换机设置和配置指南》"] 用于启用集群运行状况交换机日志收集以收集交换机相关日志文件所需的步骤。
