---
permalink: switch-bes-53248/migrate-to-2n-switched.html 
sidebar: sidebar 
keywords: two-node switchless clusters, migrating to a two-node switched BES-53248 cluster environment,BES-53248 switches, migrating two-node switched clusters,2-node 
summary: 如果您有一个双节点无交换机集群，您可以无中断地迁移到包含博通支持的 BES-53248 集群交换机的双节点有交换机集群。 
---
= 迁移到交换式NetApp集群环境
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您已经拥有一个双节点无交换机集群环境，则可以使用博通支持的 BES-53248 集群交换机迁移到双节点有交换机集群环境，从而使集群能够扩展到两个以上的节点。

迁移过程适用于所有使用光纤或 Twinax 端口的集群节点端口，但如果节点使用板载 10GBASE-T RJ45 端口作为集群网络端口，则此交换机不支持此迁移过程。



== 审查要求

请查看以下集群环境要求。

* 请注意，大多数系统需要在每个控制器上设置两个专用的集群网络端口。
* 请确保按照以下说明设置 BES-53248 集群开关：link:replace-switch-reqs.html["替换要求"]在开始迁移过程之前。
* 对于双节点无交换机配置，请确保：
+
** 双节点无交换机配置已正确设置并运行正常。
** 这些节点运行的是ONTAP 9.5P8 及更高版本。从 EFOS 固件版本 3.4.4.6 及更高版本开始支持 40/100 GbE 集群端口。
** 集群所有端口均处于*开启*状态。
** 所有集群逻辑接口（LIF）均处于 *up* 状态，并位于其所属端口上。


* 对于博通支持的 BES-53248 集群交换机配置，请确保：
+
** 两个交换机上的 BES-53248 集群开关功能完全正常。
** 两台交换机都具备管理网络连接功能。
** 可以通过控制台访问集群交换机。
** BES-53248 节点到节点交换机和交换机到交换机的连接使用 Twinax 或光纤电缆。
+
这 link:https://hwu.netapp.com/Home/Index["NetApp硬件世界"^] 包含有关ONTAP兼容性、支持的 EFOS 固件以及与 BES-53248 交换机的布线的信息。看 link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["安装HWU中没有的设备还需要哪些额外信息？"^] 有关交换机安装要求的更多信息。



* 交换机间链路 (ISL) 电缆连接到两个 BES-53248 交换机上的端口 0/55 和 0/56。
* 两台 BES-53248 交换机的初始定制工作已完成，具体如下：
+
** BES-53248 交换机运行的是最新版本的软件。
** BES-53248 交换机如果购买，则已安装可选端口许可证。
** 参考配置文件（RCF）应用于交换机。


* 所有站点自定义（SMTP、SNMP 和 SSH）均在新交换机上配置。


.端口组速度限制
* 48 个 10/25GbE (SFP28/SFP+) 端口组合成 12 个 4 端口组，如下：端口 1-4、5-8、9-12、13-16、17-20、21-24、25-28、29-32、33-36、37-40、41-44 和 45-48。
* 4 端口组中所有端口的 SFP28/SFP+ 端口速度必须相同（10GbE 或 25GbE）。
* 如果 4 个端口组中的速度不同，交换机端口将无法正常工作。




== 迁移到集群环境

.关于示例
本流程中的示例使用以下集群交换机和节点命名规则：

* BES-53248交换机的名称是 `cs1`和 `cs2`。
* 聚类SVM的名称是 `node1`和 `node2`。
* LIF的名称是 `node1_clus1`和 `node1_clus2`在节点 1 上，并且 `node2_clus1`和 `node2_clus2`分别在节点 2 上。
* 这 `cluster1::*>`prompt 指示集群名称。
* 此过程中使用的集群端口为： `e0a`和 `e0b`。
+
这 https://hwu.netapp.com/Home/Index["NetApp硬件世界"^]包含有关您平台实际集群端口的最新信息。





=== 步骤 1：准备迁移

. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 x 为维护窗口的持续时间（小时）。

+

NOTE: AutoSupport消息会通知技术支持此维护任务，以便在维护窗口期间抑制自动创建案例。

+
以下命令可抑制自动创建案件两小时：

+
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. 将权限级别更改为高级，并在提示继续时输入 *y*：
+
`set -privilege advanced`

+
高级提示(`*>`出现。





=== 步骤二：配置端口和线缆

. 禁用新集群交换机 cs1 和 cs2 上所有已激活的面向节点的端口（非 ISL 端口）。
+

NOTE: 您不得禁用 ISL 端口。

+
以下示例显示交换机 cs1 上面向节点的端口 1 到 16 已禁用：

+
[listing, subs="+quotes"]
----
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *shutdown*
(cs1)(Interface 0/1-0/16)# *exit*
(cs1)(Config)# *exit*
----
. 确认两台 BES-53248 交换机 cs1 和 cs2 之间的 ISL 以及 ISL 上的物理端口均已启动：
+
`show port-channel`

+
.显示示例
[%collapsible]
====
以下示例表明交换机 cs1 上的 ISL 端口已启动：

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
以下示例表明交换机 cs2 上的 ISL 端口已启动：

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. 显示相邻设备列表：
+
`show isdp neighbors`

+
此命令提供有关连接到系统的设备的信息。

+
.显示示例
[%collapsible]
====
以下示例列出了交换机 cs1 上的相邻设备：

[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
以下示例列出了交换机 cs2 上的相邻设备：

[listing, subs="+quotes"]
----
(cs2)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
====
. 请确认集群所有端口均已启动：
+
`network port show -ipspace Cluster`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy
----
====
. 确认所有集群 LIF 都已启动并正常运行：
+
`network interface show -vserver Cluster`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. 禁用集群 LIF 的自动回滚功能。
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. 断开节点 1 上的集群端口 e0a 的电缆，然后使用 BES-53248 交换机支持的适当电缆将 e0a 连接到集群交换机 cs1 上的端口 1。
+
这 https://hwu.netapp.com/Home/Index["NetApp硬件世界"^]包含更多关于布线的信息。

. 断开节点 2 上的集群端口 e0a 的电缆，然后使用 BES-53248 交换机支持的适当电缆将 e0a 连接到集群交换机 cs1 上的端口 2。
. 启用集群交换机 cs1 上所有面向节点的端口。
+
以下示例显示交换机 cs1 上的端口 1 到 16 已启用：

+
[listing, subs="+quotes"]
----
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *no shutdown*
(cs1)(Interface 0/1-0/16)# *exit*
(cs1)(Config)# *exit*
----
. 请确认集群所有端口均已启动：
+
`network port show -ipspace Cluster`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. 确认所有集群 LIF 都已启动并正常运行：
+
`network interface show -vserver Cluster`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true
----
====
. 显示集群中节点的状态信息：
+
`cluster show`

+
.显示示例
[%collapsible]
====
以下示例显示了集群中节点的健康状况和资格信息：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. 断开节点 1 上的集群端口 e0b 的电缆，然后使用 BES-53248 交换机支持的适当电缆将 e0b 连接到集群交换机 cs2 上的端口 1。
. 断开节点 2 上的集群端口 e0b 的电缆，然后使用 BES-53248 交换机支持的适当电缆将 e0b 连接到集群交换机 cs2 上的端口 2。
. 启用集群交换机 cs2 上所有面向节点的端口。
+
以下示例显示交换机 cs2 上的端口 1 到 16 已启用：

+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *interface 0/1-0/16*
(cs2)(Interface 0/1-0/16)# *no shutdown*
(cs2)(Interface 0/1-0/16)# *exit*
(cs2)(Config)# *exit*
----
. 请确认集群所有端口均已启动：
+
`network port show -ipspace Cluster`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====




=== 步骤 3：验证配置

. 启用集群 LIF 的自动回滚功能。
+
[listing, subs="+quotes"]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true
----
. 在交换机 cs2 上，关闭并重新启动所有集群端口，以触发所有不在它们所属端口上的集群 LIF 的自动恢复。
+
[listing, subs="+quotes"]
----
cs2> *enable*
cs2# *configure*
cs2(config)# *interface 0/1-0/16*
cs2(config-if-range)# *shutdown*

(Wait for 5-10 seconds before re-enabling the ports)

cs2(config-if-range)# *no shutdown*

(After executing the no shutdown command, the nodes detect the change and begin to auto-revert the cluster LIFs to their home ports)

cs2(config-if-range)# *exit*
cs2(config)# *exit*
cs2#
----
. 验证集群 LIF 是否已恢复到其原端口（这可能需要一分钟）：
+
`network interface show -vserver Cluster`

+
如果集群中的任何 LIF 尚未恢复到其主端口，请手动将其恢复。您必须连接到拥有该 LIF 的本地节点的每个节点管理 LIF 或SP/ BMC系统控制台：

+
`network interface revert -vserver Cluster -lif *`

. 确认所有界面均显示 `true`为了 `Is Home`：
+
`network interface show -vserver Cluster`

+

NOTE: 这可能需要几分钟才能完成。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true
----
====
. 确认两个节点都分别与每个交换机建立了一条连接：
+
`show isdp neighbors`

+
.显示示例
[%collapsible]
====
以下示例显示了两种开关的正确结果：

[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform -- Port ID
-------------- ------------ --------- ------------ ----------- ----------
node1          0/1          175       H            FAS2750     e0a
node2          0/2          157       H            FAS2750     e0a
cs2            0/55         178       R            BES-53248   0/55
cs2            0/56         178       R            BES-53248   0/56


(cs2)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform    Port ID
-------------- ------------ --------- ------------ ----------- ------------
node1          0/1          137       H            FAS2750     e0b
node2          0/2          179       H            FAS2750     e0b
cs1            0/55         175       R            BES-53248   0/55
cs1            0/56         175       R            BES-53248   0/56
----
====
. 显示集群中已发现的网络设备信息：
+
`network device-discovery show -protocol cdp`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
----
====
. 请确认这些设置已禁用：
+
`network options switchless-cluster show`

+

NOTE: 命令可能需要几分钟才能完成。等待“3分钟生命即将结束”的公告。

+
这 `false`以下示例的输出表明配置设置已被禁用：

+
[listing, subs="+quotes"]
----
cluster1::*> network options switchless-cluster show
Enable Switchless Cluster: *false*
----
. 验证集群中节点成员的状态：
+
`cluster show`

+
.显示示例
[%collapsible]
====
以下示例显示了集群中节点的健康状况和资格信息：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. 验证远程集群接口的连接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`执行命令以启动集群连接性检查，然后显示详细信息：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*运行程序前请等待几秒钟 `show`显示详细信息的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2_clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none

node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有ONTAP版本
--
对于所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`检查连接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. 步骤10：将权限级别改回管理员：
+
`set -privilege admin`

. 如果您已禁用自动创建案例功能，请通过调用AutoSupport消息重新启用该功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
+
更多信息请参见： https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetApp知识库文章：如何在计划维护窗口期间禁止自动创建案例"^]



.下一步是什么？
交换机迁移完成后，您可以…… link:../switch-cshm/config-overview.html["配置交换机健康监控"]。
