---
permalink: switch-bes-53248/migrate-to-2n-switched-overview.html 
sidebar: sidebar 
keywords: two-node switchless cluster environments,migrating to a two-node switched BES-53248 cluster environment,switchless cluster environments,tnsc,TNSC,2-node 
summary: 如果您有一个现有的双节点无交换机集群环境，则可以使用支持 Broadcom 的 BES-53248 集群交换机迁移到双节点有交换机集群环境，以便可以扩展到集群中的两个节点以上。 
---
= 使用支持 Broadcom 的 BES-53248 集群交换机迁移到交换式 NetApp 集群环境
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您有一个现有的双节点无交换机集群环境，则可以使用支持 Broadcom 的 BES-53248 集群交换机迁移到双节点有交换机集群环境，以便可以扩展到集群中的两个节点以上。

双节点无交换机配置：

* 双节点无交换机配置必须已正确设置并正常运行。
* 节点必须运行 ONTAP 9.5P8 及更高版本。从 EFOS 固件版本 3.4.4.6 及更高版本开始，支持 40/100 GbE 集群端口。
* 所有集群端口都必须处于已启动状态。
* 所有集群逻辑接口（ LIF ）都必须处于 up 状态并位于其主端口上。


Broadcom 支持的 BES-53248 集群交换机配置：

* BES-53248 集群交换机必须在这两台交换机上完全正常运行。
* 两台交换机都必须具有管理网络连接。
* 必须能够通过控制台访问集群交换机。
* BES-53248 节点到节点交换机和交换机到交换机连接必须使用双轴电缆或光缆。
+
_NetApp__Hardware Universe 包含有关 ONTAP 兼容性，支持的 EFOS 固件以及 BES-53248 交换机布线的信息。

+
https://hwu.netapp.com/Switch/Index["Hardware Universe —交换机"]

* 交换机间链路（ ISL ）缆线必须连接到两个 BES-53248 交换机上的端口 0/55 和 0/56 。
* 必须完成对两个 BES-53248 交换机的初始自定义。这样：
+
** BES-53248 交换机正在运行最新版本的软件
** BES-53248 交换机已安装可选端口许可证（如果已购买）
** 参考配置文件（ Reference Configuration Files ， RCF ）已应用于交换机
+
必须在新交换机上配置任何站点自定义，例如 SMTP ， SNMP 和 SSH 。





此操作步骤中的示例使用以下集群交换机和节点命名：

* BES-53248 交换机的名称是 `CS1` 和 `CS2` 。
* 集群 SVM 的名称为 `node1` 和 `node2` 。
* LIF 的名称分别为节点 1 上的 `node1_clus1` 和 `node1_clus2` ，节点 2 上的 `node2_clus1` 和 `node2_clus2` 。
* `cluster1 ：：： * >` 提示符指示集群的名称。
* 此操作步骤中使用的集群端口为 `e0a` 和 `e0b` 。
+
_cluster_ Hardware Universe 包含有关平台的实际集群端口的最新信息。

+
https://hwu.netapp.com["Hardware Universe"]



.步骤
. 如果在此集群上启用了 AutoSupport ，则通过调用 AutoSupport 消息禁止自动创建案例：
+
`ssystem node AutoSupport invoke -node * -type all -message MAINT=xh`

+
其中 x 是维护时段的持续时间，以小时为单位。

+

NOTE: AutoSupport 消息会通知技术支持此维护任务，以便在维护窗口期间禁止自动创建案例。

+
以下命令将禁止自动创建案例 2 小时：

+
[listing]
----
cluster1::*> **system node autosupport invoke -node \* -type all -message MAINT=2h**
----
. 将权限级别更改为高级，在系统提示您继续时输入 * y * ：
+
`set -privilege advanced`

+
此时将显示高级提示符（` * >` ）。

. 在新集群交换机 CS1 * 和 * CS2 上禁用所有已激活的面向节点的端口（而不是 ISL 端口）。
+

NOTE: 不得禁用 ISL 端口。

+
以下示例显示了交换机 CS1 上面向节点的端口 1 到 16 已禁用：

+
[listing]
----
(cs1)# **configure**
(cs1)(Config)#   **interface 0/1-0/16**
(cs1)(Interface 0/1-0/16)# **shutdown**
(cs1)(Interface 0/1-0/16)# **exit**
(cs1)(Config)# **exit**
----
. 验证两个 BES-53248 交换机 CS1 和 CS2 之间的 ISL 和 ISL 上的物理端口是否为 `up` ：
+
`s如何使用端口通道`

+
以下示例显示交换机 CS1 上的 ISL 端口已启动：

+
[listing]
----
(cs1)# **show port-channel 1/1**
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
+
以下示例显示交换机 CS2 上的 ISL 端口已启动：

+
[listing]
----
(cs2)# **show port-channel 1/1**
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs2) #
----
. 显示相邻设备的列表：
+
`s如何使用 isdp 邻居`

+
此命令可提供有关连接到系统的设备的信息。

+
以下示例列出了交换机 CS1 上的相邻设备：

+
[listing]
----
(cs1)# **show isdp neighbors**

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
+
以下示例列出了交换机 CS2 上的相邻设备：

+
[listing]
----

(cs2)# **show isdp neighbors**

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
. 验证所有集群端口是否均为 `up` ：
+
`network port show -ipspace cluster`

+
对于 `Link` 和 `Healthy` ，每个端口均应显示 up for `Health Status` 。

+
[listing]
----
cluster1::*> **network port show -ipspace Cluster**

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.
----
. `所有集群 LIF 是否均已` 启动 `且正常运行：` network interface show -vserver Cluster
+
每个集群 LIF 应显示 `true` for `is Home` and have a `StStatus Admin/Oper` of `up/up`

+
[listing]
----

cluster1::*> **network interface show -vserver Cluster**

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
. 验证是否已在所有集群 LIF 上启用 `auto-revert` ： `network interface show -vserver cluster -fields auto-revert`
+
[listing]
----
cluster1::*> **network interface show -vserver Cluster -fields auto-revert**

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true

4 entries were displayed.
----
. 从 node1 上的集群端口 e0a 断开缆线连接，然后使用 BES-53248 交换机支持的相应布线方式将 e0a 连接到集群交换机 CS1 上的端口 1 。
+
_NetApp Hardware Universe _ 包含有关布线的详细信息。

+
https://hwu.netapp.com/Switch/Index["Hardware Universe —交换机"]

. 从节点 2 上的集群端口 e0a 断开缆线连接，然后使用 BES-53248 交换机支持的相应布线方式将 e0a 连接到集群交换机 CS1 上的端口 2 。
. 启用集群交换机 CS1 上面向节点的所有端口。
+
以下示例显示交换机 CS1 上的端口 1 到 16 已启用：

+
[listing]
----
(cs1)#  **configure**
(cs1)(Config)#  **interface 0/1-0/16**
(cs1)(Interface 0/1-0/16)# **no shutdown**
(cs1)(Interface 0/1-0/16)# **exit**
(cs1)(Config)# **exit**
----
. 验证所有集群 LIF 是否均已启动，正常运行并显示为 `true` for `is Home` ：
+
`network interface show -vserver cluster`

+
以下示例显示 node1 和 node2 上的所有 LIF 均已启动，并且 `为 Home` Results 为 `true` ：

+
[listing]
----
cluster1::*> **network interface show -vserver Cluster**

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true

4 entries were displayed.
----
. 显示有关集群中节点状态的信息：
+
`cluster show`

+
以下示例显示了有关集群中节点的运行状况和资格的信息：

+
[listing]
----
cluster1::*> **cluster show**

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
. 从 node1 上的集群端口 e0b 断开缆线连接，然后使用 BES-53248 交换机支持的相应布线方式将 e0b 连接到集群交换机 CS2 上的端口 1 。
. 从节点 2 上的集群端口 e0b 断开缆线连接，然后使用 BES-53248 交换机支持的相应布线方式将 e0b 连接到集群交换机 CS2 上的端口 2 。
. 启用集群交换机 CS2 上面向节点的所有端口。
+
以下示例显示交换机 CS2 上的端口 1 到 16 已启用：

+
[listing]
----
(cs2)# **configure**
(cs2)(Config)#  **interface 0/1-0/16**
(cs2)(Interface 0/1-0/16)# **no shutdown**
(cs2)(Interface 0/1-0/16)# **exit**
(cs2)(Config)# **exit**
----
. 验证所有集群端口是否均为 `up` ：
+
`network port show -ipspace cluster`

+
以下示例显示 node1 和 node2 上的所有集群端口均已启动：

+
[listing]
----
cluster1::*> **network port show -ipspace Cluster**

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.
----
. 验证所有接口是否显示 `true` for `is Home` ：
+
`network interface show -vserver cluster`

+

NOTE: 完成此操作可能需要几分钟时间。

+
以下示例显示 node1 和 node2 上的所有 LIF 均已启动，并且 `为 Home` Results 为 `true` ：

+
[listing]
----
cluster1::*> **network interface show -vserver Cluster**

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true

4 entries were displayed.
----
. 验证两个节点与每个交换机之间是否有一个连接：
+
`s如何使用 isdp 邻居`

+
以下示例显示了这两个交换机的相应结果：

+
[listing]
----
(cs1)# **show isdp neighbors**

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform -- Port ID
-------------- ------------ --------- ------------ ----------- ----------
node1          0/1          175       H            FAS2750     e0a
node2          0/2          157       H            FAS2750     e0a
cs2            0/55         178       R            BES-53248   0/55
cs2            0/56         178       R            BES-53248   0/56


(cs2)# **show isdp neighbors**

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform    Port ID
-------------- ------------ --------- ------------ ----------- ------------
node1          0/1          137       H            FAS2750     e0b
node2          0/2          179       H            FAS2750     e0b
cs1            0/55         175       R            BES-53248   0/55
cs1            0/56         175       R            BES-53248   0/56
----
. 显示有关集群中发现的网络设备的信息：
+
`network device-discovery show -protocol cdp`

+
[listing]
----
cluster1::*> **network device-discovery show -protocol cdp**
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248

4 entries were displayed.
----
. 验证这些设置是否已禁用：
+
`network options switchless-cluster show`

+

NOTE: 完成此命令可能需要几分钟的时间。等待 " 三分钟生命周期到期 " 公告。

+
以下示例中的 `false` 输出显示配置设置已禁用：

+
[listing]
----
cluster1::*> **network options switchless-cluster show**
Enable Switchless Cluster: false
----
. 验证集群中节点成员的状态：
+
`cluster show`

+
以下示例显示了有关集群中节点的运行状况和资格的信息：

+
[listing]
----
cluster1::*> **cluster show**

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
. 使用命令确保集群网络具有完全连接：
+
`cluster ping-cluster -node _node-name_`

+
[listing]
----
cluster1::*> **cluster ping-cluster -node local**

Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 192.168.168.26 node1 e0a
Cluster node1_clus2 192.168.168.27 node1 e0b
Cluster node2_clus1 192.168.168.28 node2 e0a
Cluster node2_clus2 192.168.168.29 node2 e0b
Local = 192.168.168.28 192.168.168.29
Remote = 192.168.168.26 192.168.168.27
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 4 path(s):
    Local 192.168.168.28 to Remote 192.168.168.26
    Local 192.168.168.28 to Remote 192.168.168.27
    Local 192.168.168.29 to Remote 192.168.168.26
    Local 192.168.168.29 to Remote 192.168.168.27
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. 将权限级别重新更改为 admin ：
+
`set -privilege admin`

. 如果禁止自动创建案例，请通过调用 AutoSupport 消息重新启用它：
+
`ssystem node AutoSupport invoke -node * -type all -message MAINT=end`

+
[listing]
----
cluster1::*> **system node autosupport invoke -node \* -type all -message MAINT=END**
----


请参见中的 _Configuring the cluster switch log Collection feature_ http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-sw-ix8-setup/home.html["《适用于 Broadcom 支持的 BES-53248 交换机的交换机设置和配置指南》"] 用于启用集群运行状况交换机日志收集以收集交换机相关日志文件所需的步骤。

* 相关信息 *

https://hwu.netapp.com["Hardware Universe"]

http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-sw-ix8-setup/home.html["《适用于 Broadcom 支持的 BES-53248 交换机的交换机设置和配置指南》"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetApp 知识库文章： How to suppress automatic case creation during scheduled maintenance windows."]
