---
permalink: switch-bes-53248/overview-bes53248.html 
sidebar: sidebar 
keywords: cluster-mode,supported versions,switches supported,cluster network,efos 
summary: 在 ONTAP 9.5P8 及更高版本中，支持 Broadcom 的 BES-53248 集群交换机可在 2 到 24 个节点的大小范围内工作。从 EFOS 固件版本 3.4.4.6 及更高版本开始，支持 40/100 GbE 集群端口。 
---
= Broadcom 支持的 BES-53248 集群交换机概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在 ONTAP 9.5P8 及更高版本中，支持 Broadcom 的 BES-53248 集群交换机可在 2 到 24 个节点的大小范围内工作。从 EFOS 固件版本 3.4.4.6 及更高版本开始，支持 40/100 GbE 集群端口。

BES-53248 是在 Broadcom 嵌入式操作系统（称为以太网阵列操作系统（ EFOS ））上运行的交换机。

下表列出了 BES-53248 集群交换机，机架安装导轨套件，风扇和电源的部件号和问题描述：

[cols="1,2"]
|===
| 部件号 | Description 


 a| 
X190005
 a| 
BES-53248 ， CLSW ， 16Pt10/25GB ， PTSX ， BRDCM 支持（ PTSX = 端口侧排气）



 a| 
X190005r
 a| 
BES-53248 ， CLSW ， 16Pt10/25GB ， PSIN ， BRDCM 支持（ PSIN = 端口侧进气）



 a| 
X-RAIL 4Post-190005
 a| 
19 英寸 Ozeki 4 柱机架安装导轨套件



 a| 
X-Fan-190005-R
 a| 
风扇，端口侧进气 X190005



 a| 
X-Fan-190005-F
 a| 
风扇，端口侧排气 X190005



 a| 
X-PSU-190005-R
 a| 
电源，端口侧进气 X190005



 a| 
X-PSU-190005-F
 a| 
电源，端口侧排气 X190005

|===
根据所提供的两种型号，气流概述如下：

* 端口端排气气流（标准空气）：冷空气通过冷通道中的风扇和电源模块进入机箱，并通过热通道中的机箱端口端进行排气。蓝色颜色表示端口端的排气气流。这是最常见的选项。
* 端口侧进气气流（反向空气）：冷空气通过冷通道的端口端进入机箱，并通过热通道中的风扇和电源模块进行排气。


请参见 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch["NetApp 知识库文章： How to add additional port licensing for the Broadcom-supported BES-53248 switch"^] 有关添加其他端口许可证的详细信息。

有关要使用的相关连接器和缆线选项及其部件号的信息，请参见 https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^]。

有关详细信息，请参见 BES-53248 交换机下载站点上的 _Cluster 网络和管理网络兼容性表 _ https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom 集群交换机"^]。
