---
permalink: switch-bes-53248/replace-install-rcf.html 
sidebar: sidebar 
keywords: rcf,install rcf,bes-53248 switch 
summary: 首次设置 BES-53248 集群交换机后以及应用新许可证后，您可以安装 RCF 。如果要从旧版本升级 RCF ，这些文件将有效地合并在一起，您将完成此处详细介绍的步骤。 
---
= 安装参考配置文件（ RCF ）
:icons: font
:imagesdir: ../media/


[role="lead"]
首次设置 BES-53248 集群交换机后以及应用新许可证后，您可以安装 RCF 。如果要从旧版本升级 RCF ，这些文件将有效地合并在一起，您将完成此处详细介绍的步骤。

.步骤
. 将集群交换机连接到管理网络。
. 使用 ping 命令验证与托管 EFOS ，许可证和 RCF 的服务器的连接。
+
如果连接为问题描述，请使用非路由网络并使用 IP 地址 192.168.8.x 或 172.19.x 配置服务端口您可以稍后将服务端口重新配置为生产管理 IP 地址。

+
此示例验证交换机是否已连接到 IP 地址为 172.19.2.1 的服务器：

+
[listing]
----
(cs2) # **ping 172.19.2.1**
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. 使用 copy 命令在 BES-53248 集群交换机上安装 RCF 。
+
[listing]
----
(cs2) # **copy http://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr**

Remote Password ********

Mode........................................... HTTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... BES-53248_RCF_v1.6-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_RCF_v1.6-Cluster-HA.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) **y
**
File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...

Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
+

NOTE: 根据您的环境，您可能需要在 copy 命令中使用双斜杠，例如： ` +copy http://172.19.2.1//tmp/BES-53248_RCF_v1.6-Cluster-HA.txt[] NVRAM ：脚本 BES-53248_RCF_v1.6-Cluser-HA.SCR+` 。

+

NOTE: 在调用脚本之前，必须将 ` .scr` 扩展名设置为文件名的一部分。此扩展是 EFOS 操作系统的扩展。将脚本下载到交换机后，交换机会自动验证该脚本，并将输出传输到控制台。此外，您还可以更改 ` .scr` 的名称以适应控制台屏幕，以便于阅读，例如： ` + copy http://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt[] NVRAM ：脚本 RCF_v1.6-Cluster-HA.SCR+` 。

. 验证脚本是否已下载并保存到您为其指定的文件名中：
+
`s记录列表`

+
[listing]
----
(cs2) # **script list**

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
BES-53248_RCF_v1.6-Cluster-HA.scr        2241         2020 09 30 05:41:00

1 configuration script(s) found.
----
. 将此脚本应用于交换机。
+
`s记录应用`

+
[listing]
----
(cs2) # **script apply BES-53248_RCF_v1.6-Cluster-HA.scr**

Are you sure you want to apply the configuration script? (y/n) **y**

The system has unsaved changes.
Would you like to save them now? (y/n) **y**
Config file 'startup-config' created successfully .
Configuration Saved!

Configuration script 'BES-53248_RCF_v1.6-Cluster-HA.scr' applied.
----
. 应用 RCF 后，请验证用于附加许可证的端口：
+
`s如何全部端口 | 排除断开`

+
[listing]
----
(cs2) # **show port all \| exclude Detach**

                 Admin     Physical     Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode         Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Enable    Auto                    Down   Enable  Enable long
0/2              Enable    Auto                    Down   Enable  Enable long
0/3              Enable    Auto                    Down   Enable  Enable long
0/4              Enable    Auto                    Down   Enable  Enable long
0/5              Enable    Auto                    Down   Enable  Enable long
0/6              Enable    Auto                    Down   Enable  Enable long
0/7              Enable    Auto                    Down   Enable  Enable long
0/8              Enable    Auto                    Down   Enable  Enable long
0/9              Enable    Auto                    Down   Enable  Enable long
0/10             Enable    Auto                    Down   Enable  Enable long
0/11             Enable    Auto                    Down   Enable  Enable long
0/12             Enable    Auto                    Down   Enable  Enable long
0/13             Enable    Auto                    Down   Enable  Enable long
0/14             Enable    Auto                    Down   Enable  Enable long
0/15             Enable    Auto                    Down   Enable  Enable long
0/16             Enable    Auto                    Down   Enable  Enable long
0/49             Enable    40G Full                Down   Enable  Enable long
0/50             Enable    40G Full                Down   Enable  Enable long
0/51             Enable    100G Full               Down   Enable  Enable long
0/52             Enable    100G Full               Down   Enable  Enable long
0/53             Enable    100G Full               Down   Enable  Enable long
0/54             Enable    100G Full               Down   Enable  Enable long
0/55             Enable    100G Full               Down   Enable  Enable long
0/56             Enable    100G Full               Down   Enable  Enable long
----
. 在交换机上验证是否已进行更改：
+
`s如何运行配置`

+
[listing]
----
(cs2) # **show running-config**
----
. 保存正在运行的配置，使其在重新启动交换机时成为启动配置：
+
`写入内存`

+
[listing]
----
(cs2) # **write memory**
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) **y**

Config file 'startup-config' created successfully.

Configuration Saved!
----
. 重新启动交换机并验证正在运行的配置是否正确：
+
`re负载`

+
[listing]
----
(cs2) # **reload**

Are you sure you would like to reset the system? (y/n)**y**

System will now restart!
----

