---
permalink: switch-bes-53248/replace-configure-new-switch.html 
sidebar: sidebar 
keywords: BES-53248 switches,initial installation,new install 
summary: 您可以通过完成本章中详细介绍的步骤来配置新的 BES-53248 集群交换机。 
---
= 配置新的 BES-53248 集群交换机
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过完成本章中详细介绍的步骤来配置新的 BES-53248 集群交换机。

在运行 ONTAP 的系统上安装 BES-53248 集群交换机时，首先需要设置 IP 地址和配置，以使交换机能够通过管理接口进行通信。然后，您可以根据需要安装以太网阵列操作系统（ EFOS ）软件，参考配置文件（ RCF ）和其他许可证。此操作步骤用于在添加控制器之前准备 BES-53248 交换机。此外，您可能需要安装所需的配置文件，以支持 BES-53248 集群交换机的集群交换机运行状况监控器（ Cluster Switch Health Monitor ， CSHM ）。请参见 link:replace_install_cshm_file.md#GUID-53ED7CFF-35AD-4D01-BDAF-CA17ABF3AD4E["安装集群交换机运行状况监控器（ CSHM ）配置文件"] 有关详细信息：

此操作步骤中的示例使用以下交换机和节点命名：

* NetApp 交换机名称是 CS1 和 CS2 。
* 此操作步骤中使用的示例将在第二个交换机 _CS2._ 上启动升级
* 集群 LIF 名称分别为 node1 和 node1_clus1 和 node1_clus2 ， node2 和 node2_clus1 和 node2_clus2 。
* IP 空间名称为集群。
* `cluster1 ：： >` 提示符指示集群的名称。
* 每个节点上的集群端口均名为 e0a 和 e0b 。
+
有关 Hardware Universe 您的平台支持的实际集群端口，请参见 _cluster_ 。

+
https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^]

* NetApp 交换机支持的交换机间链路（ ISL ）为端口 0/55 和 0/56 。
* NetApp 交换机支持的节点连接为端口 0/1 到 0/16 ，并具有默认许可。
* 此操作步骤中的示例使用两个节点，但一个集群中最多可以有 24 个节点。

