---
permalink: switch-bes-53248/replace-upgrade.html 
sidebar: sidebar 
keywords: BES-53248 switches,upgrading,BES-53248 switches 
summary: 升级 BES-53248 集群交换机首先需要准备要升级的控制器，安装 EFOS 软件，许可证和参考配置文件 \ （ RCF\ ）。安装后，您可以在无中断升级 \ （ NDU\ ）和无中断操作 \ （ ND\ ）环境中还原控制器配置。 
---
= 升级BES-53248集群交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照以下步骤升级BES-53248集群交换机。

此 操作步骤 适用场景 是一个正常运行的集群、支持无中断升级(NDU)和无中断运行(NDO)环境。



== 查看要求

在现有NetApp BES-53248集群交换机上安装EFOS软件、许可证和RCF文件之前、请确保：

* 集群是一个功能完备的集群(无错误日志消息或其他问题)。
* 集群不包含任何有故障的集群网络接口卡(NIC)。
* 两个集群交换机上的所有已连接端口均正常工作。
* 所有集群端口均已启动。
* 所有集群LIF均在其主端口上以管理和操作方式启动。
* 每个节点上的前两个集群LIF配置在不同的NIC上、并连接到不同的集群交换机端口。
* ONTAP `cluster ping-cluster -node node1` 高级权限命令指示此情况 `larger than PMTU communication` 在所有路径上均成功。



NOTE: RCF 和 EFOS 版本中的命令语法之间可能存在命令依赖关系。


NOTE: 有关交换机兼容性、请参见上的兼容性表 https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom 集群交换机"^] 页面上显示了受支持的EFOS、RCF和ONTAP 版本。



== 准备控制器

按照此操作步骤 为BES-53248集群交换机升级准备控制器。

.步骤
. 将集群交换机连接到管理网络。
. 使用 ping 命令验证与托管 EFOS ，许可证和 RCF 的服务器的连接。
+
如果是问题描述，请使用非路由网络并使用 IP 地址 192.168.8.x 或 172.19.x 配置服务端口您可以稍后将服务端口重新配置为生产管理 IP 地址。

+
.显示示例
[%collapsible]
====
此示例验证交换机是否已连接到 IP 地址为 172.19.2.1 的服务器：

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. 使用命令验证集群端口是否运行正常并具有链路：
+
`network port show -ipspace cluster`

+
.显示示例
[%collapsible]
====
以下示例显示了所有端口的输出类型，其中 `Link` 值为 up ， a `Health Status` 为 healthy ：

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
------ ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
-----  ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. 使用命令验证集群 LIF 是否已在管理和操作上启动并驻留在其主端口上：
+
`network interface show -vserver cluster`

+
.显示示例
[%collapsible]
====
在此示例中， ` -vserver` 参数显示有关与集群端口关联的 LIF 的信息。`s状态管理 /Oper` 必须已启动且 `为主目录` 必须为 true ：

[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster*

          Logical      Status     Network             Current       Current Is
Vserver   Interface    Admin/Oper Address/Mask        Node          Port    Home
--------- ----------   ---------- ------------------  ------------- ------- ----
Cluster
          node1_clus1
                       up/up      169.254.217.125/16  node1         e0a     true
          node1_clus2
                       up/up      169.254.205.88/16   node1         e0b     true
          node2_clus1
                       up/up      169.254.252.125/16  node2         e0a     true
          node2_clus2
                       up/up      169.254.110.131/16  node2         e0b     true
----
====




== 安装软件

按照以下说明安装软件。

. link:configure-efos-software.html["安装 EFOS 软件"]。在BES-53248集群交换机上下载并安装以太网阵列操作系统(EFOS)软件。
. link:configure-licenses.html["安装 BES-53248 集群交换机的许可证"]。或者、也可以通过购买和安装更多许可证来添加新端口。此交换机基本型号已获得16个10GbE或25GbE端口和两个100GbE端口的许可。
. link:configure-install-rcf.html["安装参考配置文件（ RCF ）"]。在BES-53248集群交换机上安装或升级RCF、然后在应用RCF后验证端口以获取额外许可证。
. link:configure-health-monitor.html["安装集群交换机运行状况监控器（ CSHM ）配置文件"]。安装适用于集群交换机运行状况监控的配置文件。
. link:configure-ssh.html["在 BES-53248 集群交换机上启用 SSH"]。如果使用集群交换机运行状况监控器(Cluster Switch Health Monitor、CSHM)和日志收集功能、请在交换机上启用SSH。
. link:configure-log-collection.html["启用日志收集功能"]。使用此功能可在ONTAP 中收集与交换机相关的日志文件。

