---
permalink: switch-bes-53248/replace-install-cshm-file.html 
sidebar: sidebar 
keywords: CSHM,initial setup,switch health monitor 
summary: 您可以使用此操作步骤安装适用于 BES-53248 集群交换机的集群交换机运行状况监控的配置文件。在 ONTAP 9.5P7 及更早版本以及 9.6P2 及更早版本中，您必须单独下载集群交换机运行状况监控器配置文件。在 ONTAP 9.5P8 及更高版本， 9.6P3 及更高版本以及 9.7 及更高版本中，集群交换机运行状况监控器配置文件与 ONTAP 捆绑在一起。 
---
= 安装集群交换机运行状况监控器（ CSHM ）配置文件
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用此操作步骤安装适用于 BES-53248 集群交换机的集群交换机运行状况监控的配置文件。在 ONTAP 9.5P7 及更早版本以及 9.6P2 及更早版本中，您必须单独下载集群交换机运行状况监控器配置文件。在 ONTAP 9.5P8 及更高版本， 9.6P3 及更高版本以及 9.7 及更高版本中，集群交换机运行状况监控器配置文件与 ONTAP 捆绑在一起。

在为 BES-53248 集群交换机设置交换机运行状况监控器之前，必须确保 ONTAP 集群已启动且正在运行。


NOTE: 建议启用 SSH ，以便使用 CSHM 中提供的所有功能。

.步骤
. 根据相应的 ONTAP 版本下载集群交换机运行状况监控器配置 zip 文件。此文件可从页面获得： https://mysupport.netapp.com/NOW/cgi-bin/software/["NetApp 软件下载"^]
+
.. 在软件下载页面上，选择 * 交换机运行状况监控器配置文件 *
.. 选择平台 = * ONTAP * ，然后单击 * 执行！ *
.. 在 "Switch Health Monitor Configuration Files for ONTAP " 页面上，单击 * 查看并下载 *
.. 在适用于 ONTAP - 问题描述的交换机运行状况监控器配置文件页面上，对于适用的集群交换机型号，单击 * 下载 * ，例如： * Broadcom 支持的 BES-53248*
.. 在最终用户许可协议页面上，单击 * 接受 *
.. 在 "Switch Health Monitor Configuration Files for ONTAP - Download" 页面上，选择适用的配置文件，例如 * Broadcom _BES-53248.zip


. 将适用的 zip 文件上传到 IP 地址为 X.X.X.X.X 的内部 Web 服务器
+
对于内部 Web 服务器 IP 地址 192.168.2.2 并假设存在 /usr/download 目录，您可以使用 scp 将 zip 文件上传到 Web 服务器：

+
[listing]
----
% scp Broadcom_BES-53248.zip admin@192.168.2.20:/usr/download/Broadcom_BES-53248.zip
----
. 使用命令 `set -privilege advanced` 从集群中的一个 ONTAP 系统访问高级模式设置：
+
[listing]
----
cluster1::> set -privilege advanced
----
. 运行 switch health monitor configure 命令 `ssystem cluster-switch configure-health-monitor -node * -package-url \http://server/file-location`:
+
[listing]
----
cluster1::> system cluster-switch configure-health-monitor -node * -package-url
http://192.168.2.20/usr/download/Broadcom_BES-53248.zip
----
. 验证命令输出是否包含文本字符串 "downloaded package processed successfully" 。如果发生错误，请联系 NetApp 支持部门。
. 在 ONTAP 系统上运行命令 `ssystem cluster-switch show` ，并确保在发现集群交换机时已将受监控字段设置为 "True" 。
+
[listing]
----
cluster1::> system cluster-switch show
----
+

NOTE: 如果您随时还原到早期版本的 ONTAP ，则需要重新安装 CSHM 配置文件，以便对 BES-53248 集群交换机启用交换机运行状况监控。


