---
permalink: switch-bes-53248/replace-switch.html 
sidebar: sidebar 
keywords: replace, replacing, defective, broadcom-supported, bes, cluster, switch, network, nondisruptive, procedure, ndu, replace a broadcom-supported bes-53428 cluster switch - bes-53428 switches 
summary: '在集群网络中更换有缺陷的博通支持的 BES-53248 集群交换机是一个非中断程序 \(NDU\)。' 
---
= 更换博通支持的 BES-53248 集群交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照以下步骤更换集群网络中出现故障的博通支持的 BES-53248 集群交换机。这是一个无中断程序 (NDU)。

.关于示例
本流程中的示例使用以下开关和节点命名规则：

* 现有BES-53248交换机的名称是 `cs1`和 `cs2`。
* 新型BES-53248交换机的名称是 `newcs2`。
* 节点名称是 `node1`和 `node2`。
* 每个节点上的集群端口都命名为 `e0a`和 `e0b`。
* 集群 LIF 名称为 `node1_clus1`和 `node1_clus2`对于节点1，以及 `node2_clus1`和 `node2_clus2`对于节点2。
* 提示对所有集群节点进行更改 `cluster1::>`


.关于拓扑结构
此流程基于以下集群网络拓扑结构：

.展示示例拓扑
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false


Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false


cluster1::> *network interface show -vserver Cluster*
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true


cluster1::> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
----
[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater

Device ID                Intf      Holdtime  Capability Platform         Port ID
------------------------ --------- --------- ---------- ---------------- ---------
node1                    0/1       175       H          FAS2750          e0a
node2                    0/2       152       H          FAS2750          e0a
cs2                      0/55      179       R          BES-53248        0/55
cs2                      0/56      179       R          BES-53248        0/56


(cs2)# show isdp neighbors

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater

Device ID                Intf      Holdtime  Capability Platform         Port ID
------------------------ --------- --------- ---------- ---------------- ---------
node1                    0/1       129       H          FAS2750          e0b
node2                    0/2       165       H          FAS2750          e0b
cs1                      0/55      179       R          BES-53248        0/55
cs1                      0/56      179       R          BES-53248        0/56
----
====
.步骤
. 复习link:replace-switch-reqs.html["更换要求"]。
. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 _x_ 为维护窗口的持续时间（小时）。

+

NOTE: AutoSupport消息会通知技术支持此维护任务，以便在维护窗口期间抑制自动创建案例。

. 在交换机 newcs2 上安装相应的参考配置文件 (RCF) 和映像，并进行任何必要的站点准备。
+
如有必要，请验证、下载并安装适用于新交换机的 RCF 和 EFOS 软件的相应版本。如果您已确认新交换机设置正确，并且不需要更新 RCF 和 EFOS 软件，请继续执行步骤 2。

+
.. 您可以从以下位置下载适用于您的集群交换机的 Broadcom EFOS 软件： https://www.broadcom.com/support/bes-switch["博通以太网交换机支持"^]地点。请按照下载页面上的步骤，下载与您要安装的ONTAP软件版本相对应的 EFOS 文件。
.. 可从以下途径获得相应的 RCF： https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["博通集群交换机"^]页。请按照下载页面上的步骤，下载与您要安装的ONTAP软件版本相匹配的正确 RCF 文件。


. 在新交换机上，以以下身份登录： `admin`并关闭所有将连接到节点集群接口的端口（端口 1 至 16）。
+

NOTE: 如果您购买了其他端口的额外许可证，也请关闭这些端口。

+
如果您要更换的交换机无法正常工作且已断电，则集群节点上的 LIF 应该已经故障转移到每个节点的另一个集群端口。

+

NOTE: 无需密码即可进入 `enable`模式。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
User: *admin*
Password:
(newcs2)> *enable*
(newcs2)# *config*
(newcs2)(config)# *interface 0/1-0/16*
(newcs2)(interface 0/1-0/16)# *shutdown*
(newcs2)(interface 0/1-0/16)# *exit*
(newcs2)(config)# *exit*
(newcs2)#
----
====
. 确认所有集群 LIF 都已 `auto-revert`已启用：
+
`network interface show -vserver Cluster -fields auto-revert`

+
.展示示例拓扑
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster -fields auto-revert*

Logical
Vserver   Interface    Auto-revert
--------- ------------ ------------
Cluster   node1_clus1  true
Cluster   node1_clus2  true
Cluster   node2_clus1  true
Cluster   node2_clus2  true
----
====
. 关闭 BES-53248 交换机 cs1 上的 ISL 端口 0/55 和 0/56：
+
.展示示例拓扑
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *config*
(cs1)(config)# *interface 0/55-0/56*
(cs1)(interface 0/55-0/56)# *shutdown*
----
====
. 从 BES-53248 cs2 交换机上移除所有电缆，然后将它们连接到 BES-53248 newcs2 交换机上的相同端口。
. 在 cs1 和 newcs2 交换机之间启动 ISL 端口 0/55 和 0/56，然后验证端口通道运行状态。
+
端口通道 1/1 的链路状态应为 *up*，并且所有成员端口在“端口活动”标题下都应为 True。

+
.显示示例
[%collapsible]
====
此示例启用 ISL 端口 0/55 和 0/56，并显示交换机 cs1 上端口通道 1/1 的链路状态：

[listing, subs="+quotes"]
----
(cs1)# *config*
(cs1)(config)# *interface 0/55-0/56*
(cs1)(interface 0/55-0/56)# *no shutdown*
(cs1)(interface 0/55-0/56)# *exit*
(cs1)# *show port-channel 1/1*

Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port-channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------- -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. 在新交换机 newcs2 上，重新启用所有连接到节点集群接口的端口（端口 1 到 16）。
+

NOTE: 如果您购买了其他端口的额外许可证，也请关闭这些端口。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
User:admin
Password:
(newcs2)> *enable*
(newcs2)# *config*
(newcs2)(config)# *interface 0/1-0/16*
(newcs2)(interface 0/1-0/16)# *no shutdown*
(newcs2)(interface 0/1-0/16)# *exit*
(newcs2)(config)# *exit*
----
====
. 确认端口 e0b 是否已启用：
+
`network port show -ipspace Cluster`

+
.显示示例
[%collapsible]
====
输出结果应与以下内容类似：

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e0a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000  healthy  false

Node: node2
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e0a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/auto   -        false
----
====
. 在与上一步相同的节点上，等待节点 1 上的集群 LIF node1_clus2 自动恢复。
+
.显示示例
[%collapsible]
====
在本例中，如果节点 1 上的 LIF node1_clus2 被成功撤销，则 `Is Home`是 `true`端口为 e0b。

以下命令显示有关两个节点上 LIF 的信息。如果满足以下条件，则启动第一个节点即为成功： `Is Home`是 `true`在本例中，两个集群接口都显示了正确的端口分配。 `e0a`和 `e0b`在节点1上。

[listing, subs="+quotes"]
----
cluster::> *network interface show -vserver Cluster*

            Logical      Status     Network            Current    Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node       Port    Home
----------- ------------ ---------- ------------------ ---------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2      e0a     false
----
====
. 显示集群中节点的相关信息：
+
`cluster show`

+
.显示示例
[%collapsible]
====
此示例显示了节点健康状况 `node1`和 `node2`该集群中是 `true`：

[listing, subs="+quotes"]
----
cluster1::> *cluster show*
Node   Health   Eligibility   Epsilon
------ -------- ------------  --------
node1  true     true          true
node2  true     true          true
----
====
. 请确认以下集群网络配置：
+
`network port show`

+
`network interface show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*
Node: node1
                                                                       Ignore
                                       Speed(Mbps)            Health   Health
Port      IPspace     Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ----------- ---------------- ---- ----- ----------- -------- ------
e0a       Cluster     Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster     Cluster          up   9000  auto/10000  healthy  false

Node: node2
                                                                       Ignore
                                        Speed(Mbps)           Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000 auto/10000  healthy  false


cluster1::> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
====
. 验证集群网络是否运行正常：
+
`show isdp neighbors`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
S - Switch, H - Host, I - IGMP, r - Repeater
Device ID    Intf    Holdtime    Capability    Platform    Port ID
---------    ----    --------    ----------    --------    --------
node1        0/1     175         H             FAS2750     e0a
node2        0/2     152         H             FAS2750     e0a
newcs2       0/55    179         R             BES-53248   0/55
newcs2       0/56    179         R             BES-53248   0/56

(newcs2)# *show isdp neighbors*
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
S - Switch, H - Host, I - IGMP, r - Repeater

Device ID    Intf    Holdtime    Capability    Platform    Port ID
---------    ----    --------    ----------    --------    --------
node1        0/1     129         H             FAS2750     e0b
node2        0/2     165         H             FAS2750     e0b
cs1          0/55    179         R             BES-53248   0/55
cs1          0/56    179         R             BES-53248   0/56
----
====
. 如果您已禁用自动创建案例功能，请通过调用AutoSupport消息重新启用该功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.下一步是什么？
更换开关后，您可以 link:../switch-cshm/config-overview.html["配置交换机健康监控"]。
