---
permalink: switch-bes-53248/replace-switch.html 
sidebar: sidebar 
keywords: replace, replacing, defective, broadcom-supported, bes, cluster, switch, network, nondisruptive, procedure, ndu, replace a broadcom-supported bes-53428 cluster switch - bes-53428 switches 
summary: 在集群网络中更换 Broadcom 支持的故障 BES-53248 集群交换机是无中断操作步骤 \ （ NDU\ ）。 
---
= 更换Broadcom支持的BES-53248集群交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照以下步骤更换集群网络中有缺陷的Broadcom支持的BES-53248集群交换机。这是无中断操作步骤 (NDU)。

.关于示例
此操作步骤中的示例使用以下交换机和节点命名：

* 现有 BES-53248 交换机的名称是 `CS1` 和 `CS2` 。
* 新 BES-53248 交换机的名称是 `newcs2` 。
* 节点名称为 `node1` 和 `node2` 。
* 每个节点上的集群端口分别命名为 `e0a` 和 `e0b` 。
* 集群 LIF 名称是 node1 的 `node1_clus1` 和 `node1_clus2` ， node2 的 `node2_clus1` 和 `node2_clus2` 。
* 对所有集群节点进行更改的提示为 `cluster1 ：： >`


.关于拓扑
此操作步骤 基于以下集群网络拓扑：

.显示示例拓扑
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false


Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false


cluster1::> *network interface show -vserver Cluster*
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true


cluster1::> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
----
[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater

Device ID                Intf      Holdtime  Capability Platform         Port ID
------------------------ --------- --------- ---------- ---------------- ---------
node1                    0/1       175       H          FAS2750          e0a
node2                    0/2       152       H          FAS2750          e0a
cs2                      0/55      179       R          BES-53248        0/55
cs2                      0/56      179       R          BES-53248        0/56


(cs2)# show isdp neighbors

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater

Device ID                Intf      Holdtime  Capability Platform         Port ID
------------------------ --------- --------- ---------- ---------------- ---------
node1                    0/1       129       H          FAS2750          e0b
node2                    0/2       165       H          FAS2750          e0b
cs1                      0/55      179       R          BES-53248        0/55
cs1                      0/56      179       R          BES-53248        0/56
----
====
.步骤
. 查看 link:replace-switch-reqs.html["更换要求"]。
. 如果在此集群上启用了 AutoSupport ，则通过调用 AutoSupport 消息禁止自动创建案例：
+
`ssystem node AutoSupport invoke -node * -type all -message MAINT=xh`

+
其中 _x_ 是维护时段的持续时间，以小时为单位。

+

NOTE: AutoSupport 消息会通知技术支持此维护任务，以便在维护窗口期间禁止自动创建案例。

. 在交换机newcs2上安装相应的参考配置文件(Reference Configuration File、RCF)和映像、并进行必要的站点准备。
+
如有必要，请验证，下载并安装适用于新交换机的 RCF 和 EFOS 软件的相应版本。如果您已确认新交换机设置正确，并且不需要更新 RCF 和 EFOS 软件，请继续执行步骤 2 。

+
.. 您可以从下载适用于集群交换机的 Broadcom EFOS 软件 https://www.broadcom.com/support/bes-switch["Broadcom 以太网交换机支持"^] 站点按照下载页面上的步骤下载要安装的 ONTAP 软件版本的 EFOS 文件。
.. 可从获取相应的 RCF https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom 集群交换机"^] 页面。按照下载页面上的步骤下载适用于您要安装的 ONTAP 软件版本的正确 RCF 。


. 在新交换机上、以身份登录 `admin` 并关闭将连接到节点集群接口的所有端口(端口1到16)。
+

NOTE: 如果您为其他端口购买了额外的许可证，请同时关闭这些端口。

+
如果要更换的交换机无法正常工作并已关闭电源，则集群节点上的 LIF 应已故障转移到每个节点的另一个集群端口。

+

NOTE: 要进入 `enable` 模式，不需要密码。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
User: *admin*
Password:
(newcs2)> *enable*
(newcs2)# *config*
(newcs2)(config)# *interface 0/1-0/16*
(newcs2)(interface 0/1-0/16)# *shutdown*
(newcs2)(interface 0/1-0/16)# *exit*
(newcs2)(config)# *exit*
(newcs2)#
----
====
. 验证所有集群 LIF 是否已启用 `auto-revert` ：
+
`network interface show - vserver cluster -fields auto-revert`

+
.显示示例拓扑
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster -fields auto-revert*

Logical
Vserver   Interface    Auto-revert
--------- ------------ ------------
Cluster   node1_clus1  true
Cluster   node1_clus2  true
Cluster   node2_clus1  true
Cluster   node2_clus2  true
----
====
. 关闭 BES-53248 交换机 CS1 上的 ISL 端口 0/55 和 0/56 ：
+
.显示示例拓扑
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *config*
(cs1)(config)# *interface 0/55-0/56*
(cs1)(interface 0/55-0/56)# *shutdown*
----
====
. 拔下 BES-53248 CS2 交换机上的所有缆线，然后将其连接到 BES-53248 newcs2 交换机上的相同端口。
. 启动 CS1 和 newcs2 交换机之间的 ISL 端口 0/55 和 0/56 ，然后验证端口通道操作状态。
+
端口通道1/1的链路状态应为*启动*、并且端口活动标题下的所有成员端口均应为True。

+
.显示示例
[%collapsible]
====
此示例将启用 ISL 端口 0/55 和 0/56 ，并显示交换机 CS1 上端口通道 1/1 的链路状态：

[listing, subs="+quotes"]
----
(cs1)# *config*
(cs1)(config)# *interface 0/55-0/56*
(cs1)(interface 0/55-0/56)# *no shutdown*
(cs1)(interface 0/55-0/56)# *exit*
(cs1)# *show port-channel 1/1*

Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port-channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------- -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. 在新交换机 newcs2 上，重新启用连接到节点集群接口（端口 1 到 16 ）的所有端口。
+

NOTE: 如果您为其他端口购买了额外的许可证，请同时关闭这些端口。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
User:admin
Password:
(newcs2)> *enable*
(newcs2)# *config*
(newcs2)(config)# *interface 0/1-0/16*
(newcs2)(interface 0/1-0/16)# *no shutdown*
(newcs2)(interface 0/1-0/16)# *exit*
(newcs2)(config)# *exit*
----
====
. 验证端口e0b是否为*启动*：
+
`network port show -ipspace cluster`

+
.显示示例
[%collapsible]
====
输出应类似于以下内容：

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e0a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000  healthy  false

Node: node2
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e0a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/auto   -        false
----
====
. 在上一步使用的同一节点上，等待 node1 上的集群 LIF node1_clus2 自动还原。
+
.显示示例
[%collapsible]
====
在此示例中，如果 `为 Home` 为 `true` 且端口为 e0b ，则 node1 上的 LIF node1_clus2 将成功还原。

以下命令显示两个节点上的 LIF 的相关信息。如果两个集群接口的 `为 Home` 为 `true` 且显示正确的端口分配，则会成功启动第一个节点，此示例中为 node1 上的 `e0a` 和 `e0b` 。

[listing, subs="+quotes"]
----
cluster::> *network interface show -vserver Cluster*

            Logical      Status     Network            Current    Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node       Port    Home
----------- ------------ ---------- ------------------ ---------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2      e0a     false
----
====
. 显示有关集群中节点的信息：
+
`cluster show`

+
.显示示例
[%collapsible]
====
此示例显示此集群中 `node1` 和 `node2` 的节点运行状况为 `true` ：

[listing, subs="+quotes"]
----
cluster1::> *cluster show*
Node   Health   Eligibility   Epsilon
------ -------- ------------  --------
node1  true     true          true
node2  true     true          true
----
====
. 确认以下集群网络配置：
+
`network port show`

+
`network interface show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*
Node: node1
                                                                       Ignore
                                       Speed(Mbps)            Health   Health
Port      IPspace     Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ----------- ---------------- ---- ----- ----------- -------- ------
e0a       Cluster     Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster     Cluster          up   9000  auto/10000  healthy  false

Node: node2
                                                                       Ignore
                                        Speed(Mbps)           Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000 auto/10000  healthy  false


cluster1::> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
====
. 验证集群网络是否运行正常：
+
`s如何使用 isdp 邻居`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
S - Switch, H - Host, I - IGMP, r - Repeater
Device ID    Intf    Holdtime    Capability    Platform    Port ID
---------    ----    --------    ----------    --------    --------
node1        0/1     175         H             FAS2750     e0a
node2        0/2     152         H             FAS2750     e0a
newcs2       0/55    179         R             BES-53248   0/55
newcs2       0/56    179         R             BES-53248   0/56

(newcs2)# *show isdp neighbors*
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
S - Switch, H - Host, I - IGMP, r - Repeater

Device ID    Intf    Holdtime    Capability    Platform    Port ID
---------    ----    --------    ----------    --------    --------
node1        0/1     129         H             FAS2750     e0b
node2        0/2     165         H             FAS2750     e0b
cs1          0/55    179         R             BES-53248   0/55
cs1          0/56    179         R             BES-53248   0/56
----
====
. 如果禁止自动创建案例，请通过调用 AutoSupport 消息重新启用它：
+
`ssystem node AutoSupport invoke -node * -type all -message MAINT=end`



.下一步是什么？
更换开关后，您可以 link:../switch-cshm/config-overview.html["配置交换机健康监控"]。
