---
permalink: switch-bes-53248/replace-upgrade.html 
sidebar: sidebar 
keywords: BES-53248 switches,upgrading,BES-53248 switches 
summary: 升级 BES-53248 集群交换机首先需要准备要升级的控制器，安装 EFOS 软件，许可证和参考配置文件 \ （ RCF\ ）。安装后，您可以在无中断升级 \ （ NDU\ ）和无中断操作 \ （ ND\ ）环境中还原控制器配置。 
---
= 升级 NDS/NDU 环境中的 BES-53248 集群交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
升级 BES-53248 集群交换机时，首先需要准备要升级的控制器，安装 EFOS 软件，许可证和参考配置文件（ RCF ）。安装后，您可以在无中断升级（ NDU ）和无中断运行（ NDO ）环境中还原控制器配置。

在现有 NetApp BES-53248 集群交换机上安装 EFOS 软件，许可证和 RCF 文件之前，必须满足以下条件：

* 集群必须是一个完全正常运行的集群（无错误日志消息或其他问题）。
* 集群不能包含任何有故障的集群网络接口卡（ NIC ）。
* 两个集群交换机上的所有已连接端口都必须正常工作。
* 所有集群端口都必须已启动。
* 所有集群 LIF 都必须在其主端口上以管理和操作方式启动。
* ONTAP `cluster ping-cluster -node node1` advanced privilege 命令必须指示所有路径上的 `大于 PMTU 通信` 成功。
* RCF 和 EFOS 版本中的命令语法之间可能存在命令依赖关系。


您必须查看 NetApp BES-53248 交换机页面上的交换机兼容性表，了解支持的 EFOS ， RCF 和 ONTAP 版本，网址为： http://mysupport.netapp.com/site["NetApp IP 交换机"^]。

此操作步骤适用场景是一个正常运行的集群，支持 NDU 和 NDO 。此操作步骤中的示例使用以下交换机和节点命名：

* NetApp 交换机名称为 `CS1` 和 `CS2` 。
* 此操作步骤中使用的示例将在第二个交换机 _CS2._ 上启动升级
* 集群 LIF 名称是 node1 的 `node1_clus1` 和 `node1_clus2` ， node2 的 `node2_clus1` 和 `node2_clus2` 。
* IP 空间名称为集群。
* `cluster1 ：： >` 提示符指示集群的名称。
* 每个节点上的集群端口分别命名为 `e0a` 和 `e0b` 。
+
请参见 https://hwu.netapp.com/Home/Index["_NetApp Hardware Universe"^] 您的平台支持的实际集群端口。

* NetApp 集群交换机支持的交换机间链路（ ISL ）为端口 0/55 和 0/56 。
* NetApp 集群交换机支持的节点连接为端口 0/1 到 0/16 ，具有默认许可。
* 此操作步骤中的示例使用两个节点，但一个集群中最多可以有 24 个节点。
* 重复本节中的所有过程以升级另一台交换机 *CS1* 上的 EFOS 软件和 RCF 文件。

