---
permalink: switch-bes-53248/required-documentation-bes53248.html 
sidebar: sidebar 
keywords: documentation requirements, BES-53248 switches,cluster switches 
summary: 要设置集群模式配置，您需要特定的交换机和控制器文档。 
---
= BES-53248集群交换机的文档要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
有关BES-53248交换机的安装和维护、请务必查看特定的交换机和控制器文档。



== Broadcom文档

要设置 BES-53248 集群交换机，您需要从 Broadcom 支持站点获取以下文档： https://www.broadcom.com/support/bes-switch["Broadcom 以太网交换机产品线"^]

[cols="1,2"]
|===
| 文档标题 | Description 


 a| 
_EFOS 管理员指南 v3.4.3_
 a| 
提供了如何在典型网络中使用 BES-53248 交换机的示例。



 a| 
_EFOS CLI 命令参考 v3.4.3_
 a| 
介绍用于查看和配置 BES-53248 软件的命令行界面（ CLI ）命令。



 a| 
_EFOS 入门指南 v3.4.3_
 a| 
提供了有关 BES-53248 交换机的详细信息。



 a| 
_EFOS SNMP 参考指南 v3.4.3_
 a| 
提供了如何在典型网络中使用 BES-53248 交换机的示例。



 a| 
_EFOS 扩展参数和值 v3.4.3_
 a| 
介绍在支持的平台上交付和验证 EFOS 软件所使用的默认扩展参数。



 a| 
_EFOS 功能规格 v3.4.3_
 a| 
介绍了受支持平台上 EFOS 软件的规格。



 a| 
_EFOS 发行说明 v3.4.3_
 a| 
提供有关 BES-53248 软件的特定版本信息。



 a| 
_Cluster网络和管理网络兼容性表_
 a| 
提供有关网络兼容性的信息。此表可从BES-53248交换机下载站点获得、网址为 https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom 集群交换机"^]。

|===


== ONTAP 系统文档和知识库文章

要设置 ONTAP 系统，您需要从 NetApp 支持站点获取以下文档，网址为 http://mysupport.netapp.com/["mysupport.netapp.com"^] 或知识库(KB)站点、网址为 https://kb.netapp.com/["kb.netapp.com"^]。

[cols="1,2"]
|===
| Name | Description 


 a| 
https://hwu.netapp.com/Home/Index["NetApp Hardware Universe"^]
 a| 
介绍包括系统机柜在内的所有NetApp硬件的电源和站点要求、并提供有关要使用的相关连接器和缆线选项及其部件号的信息。



 a| 
特定于控制器的安装和设置说明
 a| 
介绍如何安装 NetApp 硬件。



 a| 
ONTAP 9.
 a| 
提供有关 ONTAP 9 版本所有方面的详细信息。



 a| 
_How to add additional port licensing for the Broadcom-supported BES-53248 switch_
 a| 
提供有关添加端口许可证的详细信息。转至 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_add_Additional_Port_Licensing_for_the_Broadcom-Supported_BES-53248_Switch["知识库文章"^]。

|===