---
permalink: switch-bes-53248/upgrade-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,upgrading EFOS software 
summary: '按照以下步骤升级BES-53248集群交换机上的以太网光纤操作系统(Ethernet Fabric OS、EFOS)软件。' 
---
= 升级EFOS软件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照以下步骤升级BES-53248集群交换机上的EFOS软件。

EFOS软件包括一组高级网络功能和协议、用于开发以太网和IP基础架构系统。此软件架构适用于使用需要全面数据包检查或隔离的应用程序的任何网络组织设备。



== 准备升级

.开始之前
* 从下载适用于集群交换机的Broadcom EFOS软件 https://www.broadcom.com/support/bes-switch["Broadcom 以太网交换机支持"^] 站点
* 查看以下有关EFOS版本的注释。


[]
====
* 请注意以下事项： *

* 从 EFOS 3.4.x.x 升级到 EFOS 3.7.x.x 或更高版本时，交换机必须运行 EFOS 3.4.4.6 （或更高版本 3.4.x.x ）。如果您运行的是之前的版本，请先将交换机升级到 EFOS 3.4.4.6 （或更高版本 3.4.x.x ），然后再将交换机升级到 EFOS 3.7.x.x 或更高版本。
* EFOS 3.4.x.x 和 3.7.x.x 或更高版本的配置有所不同。要将 EFOS 版本从 3.4.x.x 更改为 3.7.x.x 或更高版本，或者反之，则需要将交换机重置为出厂默认值，并重新应用相应 EFOS 版本的 RCF 文件。此操作步骤需要通过串行控制台端口进行访问。
* 从 EFOS 3.7.x.x 或更高版本开始，可以使用非 FIPS 兼容版本和 FIPS 兼容版本。从不符合FIPS的版本迁移到符合FIPS的版本时、需要执行不同的步骤、反之亦然。将 EFOS 从不符合 FIPS 的版本更改为符合 FIPS 的版本，或者反之，则会将交换机重置为出厂默认值。此操作步骤需要通过串行控制台端口进行访问。


====
|===


| * 操作步骤 * | * 当前 EFOS 版本 * | * 新 EFOS 版本 * | * 高级步骤 * 


 a| 
在两个（非） FIPS 兼容版本之间升级 EFOS 的步骤
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
使用升级新的EFOS映像 <<方法1：升级EFOS>>。
配置和许可证信息会保留下来。



 a| 
3.4.4.6 （或更高版本 3.4.x.x ）
 a| 
不符合 FIPS 的 3.7.x.x 或更高版本
 a| 
使用升级EFOS <<方法1：升级EFOS>>。
将交换机重置为出厂默认设置、并对EFOS 3.7.x.x或更高版本应用RCF文件。



.2+| 不符合 FIPS 的 3.7.x.x 或更高版本  a| 
3.4.4.6 （或更高版本 3.4.x.x ）
 a| 
使用降级EFOS <<方法1：升级EFOS>>。
将交换机重置为出厂默认值、并为EFOS 3.4.x.X应用RCF文件



 a| 
不符合 FIPS 的 3.7.x.x 或更高版本
 a| 
使用升级新的EFOS映像 <<方法1：升级EFOS>>。配置和许可证信息会保留下来。



 a| 
符合 3.7.x.x 或更高版本 FIPS
 a| 
符合 3.7.x.x 或更高版本 FIPS
 a| 
使用升级新的EFOS映像 <<方法1：升级EFOS>>。
配置和许可证信息会保留下来。



 a| 
升级到 / 从 FIPS 兼容 EFOS 版本的步骤
 a| 
不符合 FIPS
 a| 
符合 FIPS
 a| 
使用升级EFOS映像 <<方法2：使用ONIE操作系统安装升级EFOS>>。交换机配置和许可证信息将丢失。



 a| 
符合 FIPS
 a| 
不符合 FIPS

|===
[IMPORTANT]
====
要检查您的EFOS版本是否符合FIPS兼容或非FIPS兼容、请使用 `show fips status` 命令：在以下示例中，*IP_switch_A1*正在使用FIPS兼容的EFOS，而*IP_switch_A2*正在使用非FIPS兼容的EFOS。

* 在交换机IP_switch_A1 (FIPS兼容EFOS)上：
+
[listing, subs="+quotes"]
----
IP_switch_a1 # *show fips status*

System running in FIPS mode
----
* 在交换机IP_switch_A2 (非FIPS兼容EFOS)上：
+
[listing, subs="+quotes"]
----
IP_switch_a2 # *show fips status*
                     ^
% Invalid input detected at ^ marker.
----


====


== 升级软件

使用以下方法之一：

* <<方法1：升级EFOS>>。适用于大多数情况(请参见上表)。
* <<方法2：使用ONIE操作系统安装升级EFOS>>。如果一个EFOS版本符合FIPS、而另一个EFOS版本不符合FIPS、则使用。



NOTE: 一次升级一个交换机上的EFOS、以确保集群网络持续运行。



=== 方法1：升级EFOS

执行以下步骤升级EFOS软件。


IMPORTANT: 请注意，将 BES-53248 集群交换机从 EFOS 3.3.x.x 或 3.4.x.x 升级到 EFOS 3.7.0.4 或 3.8.0.2 后，交换机间链路（ ISL ）和端口通道将标记为 * 关闭 * 状态。请参见此知识库文章： https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["BES-53248集群交换机NDU无法升级到EFOS 3.7.0.4及更高版本"^] 了解更多详细信息。

.步骤
. 将 BES-53248 集群交换机连接到管理网络。
. 使用 `ping` 命令验证与托管 EFOS ，许可证和 RCF 文件的服务器的连接。
+
此示例验证交换机是否已连接到 IP 地址为 172.19.2.1 的服务器：

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. 在集群 LIF 上禁用自动还原。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. 显示活动配置和备份配置的启动映像：
+
`s如何启动 var`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

 Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6       3.7.0.4           3.7.0.4

----
====
. 备份 CS2 上的当前活动映像：
+
[source, cli]
----
copy active backup
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy active backup*
Copying active to backup
Management access will be blocked for the duration of the operation
Copy operation successful

(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :
 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6       3.7.0.4           3.7.0.4
(cs2)#
----
====
. 验证运行的 EFOS 软件版本：
+
`s如何使用版本`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.7.0.4, Linux 4.4.117-ceeeb99d, 2016.05.00.05
Machine Type................................... BES-53248A1
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260014
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:12:3D
Software Version............................... 3.7.0.4
Operating System............................... Linux 4.4.117-ceeeb99d
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
+

NOTE: 如果您安装了任何许可证、请查看其状态。

. 将映像文件下载到交换机。
+
将映像文件复制到活动映像意味着，重新启动时，该映像将建立正在运行的 EFOS 版本。上一个映像仍可用作备份。

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. 显示活动配置和备份配置的启动映像：
+
`s如何启动 var`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====
. 重新启动交换机：
+
`re负载`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. 重新登录并验证 EFOS 软件的新版本：
+
`s如何使用版本`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. 对交换机CS1重复步骤5到10。
. 在集群 LIF 上启用自动还原。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. 验证集群 LIF 是否已还原到其主端口：
+
[source, cli]
----
network interface show -role Cluster
----
+
有关更多详细信息、请参见 link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["将 LIF 还原到其主端口"]。





=== 方法2：使用ONIE操作系统安装升级EFOS

如果一个 EFOS 版本符合 FIPS ，而另一个 EFOS 版本不符合 FIPS ，则可以执行以下步骤。如果交换机无法启动、可使用以下步骤从ONIE升级非FIPS或FIPS兼容EFOS 3.7.x.x.x.X的映像。


NOTE: 此功能仅适用于不符合 FIPS 的 EFOS 3.7.x.x 或更高版本。


CAUTION: 如果您使用ONIE OS安装升级EFOS、则配置将重置为出厂默认值并删除许可证。要使交换机恢复正常运行、您必须设置交换机并安装许可证和受支持的RC框架。

.步骤
. 在集群 LIF 上禁用自动还原。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. 将交换机启动至 ONIE 安装模式。
+
在启动期间、在看到提示时选择ONIE：

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
选择* ONIE*后、交换机将加载并为您提供多个选项。选择*安装OS*。

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
交换机将启动至ONIE安装模式。

. 停止 ONIE 发现并配置以太网接口。
+
出现以下消息时、按*输入*以调用ONIE控制台：

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIE发现将继续、并将消息打印到控制台。

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. 配置以太网接口并使用 `ifconfig eth0 <ipAddress> netmask <netmask> up` 和 `route add default gw <gatewayAddress>` 添加路由
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. 验证托管 ONIE 安装文件的服务器是否可访问：
+
`ping`

+
.显示示例
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. 安装新的交换机软件：
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.显示示例
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
软件将安装并重新启动交换机。让交换机正常重新启动到新的 EFOS 版本。

. 验证是否已安装新的交换机软件：
+
`s如何启动 var`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
   1    3.7.0.4     3.7.0.4  3.7.0.4         3.10.0.3
(cs2) #
----
====
. 完成安装。交换机在未应用任何配置的情况下重新启动、并重置为出厂默认值。完成以下步骤以重新配置交换机：
+
.. link:configure-licenses.html["安装许可证"]
.. link:configure-install-rcf.html["安装RCF"]
.. link:configure-ssh.html["启用 SSH ："]
.. link:CSHM_log_collection.html["启用日志收集"]
.. link:CSHM_snmpv3.html["配置SNMPv3以进行监控"]


. 对交换机CS1重复步骤2到8。
. 在集群 LIF 上启用自动还原。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. 验证集群 LIF 是否已还原到其主端口：
+
[source, cli]
----
network interface show -role Cluster
----
+
有关更多详细信息、请参见 link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["将 LIF 还原到其主端口"]。


