---
permalink: switch-bes-53248/upgrade-rcf.html 
sidebar: sidebar 
keywords: upgrade rcf,setup rcf,rcf file 
summary: '配置 BES-53248 集群交换机并应用任何新许可证后，您可以升级参考配置文件 (RCF)。' 
---
= 升级参考配置文件（RCF）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
升级 BES-53248 集群交换机 EFOS 并应用任何新许可证后，您可以升级参考配置文件 (RCF)。

.开始之前
请确保您拥有以下物品：

* 交换机配置的当前备份。
* 一个功能齐全的集群（日志中没有错误或类似问题）。
* 当前 RCF 文件可从以下位置获取： https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["博通集群交换机"^]页。
* RCF 中的启动配置反映了所需的启动映像，如果您仅安装 EFOS 并保留当前的 RCF 版本，则需要此配置。如果需要更改启动配置以反映当前的启动映像，则必须在重新应用 RCF 之前进行更改，以便在以后的重启中实例化正确的版本。
* 从出厂默认状态安装 RCF 时，需要通过控制台连接到交换机。如果您已使用知识库文章，则此要求为可选。 https://kb.netapp.com/onprem/Switches/Broadcom/How_to_clear_configuration_on_a_Broadcom_interconnect_switch_while_retaining_remote_connectivity["如何在保持远程连接的情况下清除博通互连交换机上的配置"^]事先清除配置。


.建议的文档
* 请查阅交换机兼容性列表，了解支持的ONTAP和 RCF 版本。参见 https://mysupport.netapp.com/site/info/broadcom-cluster-switch["EFOS软件下载"^]页。请注意，RCF 中的命令语法与 EFOS 版本中的命令语法之间可能存在命令依赖关系。
* 请参阅网站上提供的相应软件和升级指南。 https://www.broadcom.com/support/bes-switch["博通"^]本网站提供有关 BES-53248 交换机升级和降级程序的完整文档。


.关于示例
本流程中的示例使用以下开关和节点命名规则：

* 这两个 BES-53248 交换机的名称分别是 cs1 和 cs2。
* 节点名称为cluster1-01、cluster1-02、cluster1-03和cluster1-04。
* 集群 LIF 名称为 cluster1-01_clus1、cluster1-01_clus2、cluster1-02_clus1、cluster1-02_clus2、cluster1-03_clus1、cluster1-03_clus2、cluster1-04_clus1 和 cluster1-04_clus2。
* 这 `cluster1::*>`prompt 指示集群名称。
* 本流程中的示例使用了四个节点。这些节点使用两个 10GbE 集群互连端口 `e0a`和 `e0b`。参见 https://hwu.netapp.com/Home/Index["Hardware Universe"^]验证平台上的集群端口是否正确。



NOTE: 命令输出可能因ONTAP版本不同而有所差异。

.关于此任务
该程序需要同时使用ONTAP命令和 Broadcom 交换机命令；除非另有说明，否则使用ONTAP命令。

在此过程中不需要任何可操作的交换机间链路 (ISL)。这是设计使然，因为 RCF 版本的更改可能会暂时影响 ISL 连接。为确保集群运行不中断，以下步骤将所有集群 LIF 迁移到运行伙伴交换机，同时在目标交换机上执行相应步骤。


CAUTION: 在安装新的交换机软件版本和 RCF 之前，请先阅读知识库文章。 https://kb.netapp.com/onprem/Switches/Broadcom/How_to_clear_configuration_on_a_Broadcom_interconnect_switch_while_retaining_remote_connectivity["如何在保持远程连接的情况下清除博通互连交换机上的配置"^] 。如果必须完全清除交换机设置，则需要重新进行基本配置。您必须使用串行控制台连接到交换机，因为完全清除配置会重置管理网络的配置。



== 第一步：准备升级

. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 _x_ 为维护窗口的持续时间（小时）。

+

NOTE: AutoSupport消息会通知技术支持此维护任务，以便在维护窗口期间抑制自动创建案例。

+
以下命令可抑制自动创建案件两小时：

+
[source, cli]
----
system node autosupport invoke -node * -type all -message MAINT=2h
----
. 将权限级别更改为高级，并在提示继续时输入 *y*：
+
[source, cli]
----
set -privilege advanced
----
+
出现高级提示符（*>）。

. 显示每个节点上连接到集群交换机的集群端口：
+
[source, cli]
----
network device-discovery show
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
cluster1-01/cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
cluster1-02/cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
cluster1-03/cdp
            e0a    cs1                       0/4               BES-53248
            e0b    cs2                       0/4               BES-53248
cluster1-04/cdp
            e0a    cs1                       0/3               BES-53248
            e0b    cs2                       0/3               BES-53248
cluster1::*>
----
====
. 检查每个集群端口的管理和运行状态。
+
.. 确认集群所有端口均已启动且状态正常：
+
[source, cli]
----
network port show -ipspace cluster
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace cluster*

Node: cluster1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: cluster1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false
8 entries were displayed.

Node: cluster1-03

   Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: cluster1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
cluster1::*>
----
====
.. 确认所有集群接口（LIF）都位于主端口上：
+
[source, cli]
----
network interface show -vserver cluster
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver cluster*
            Logical            Status     Network           Current      Current Is
Vserver     Interface          Admin/Oper Address/Mask      Node         Port    Home
----------- ------------------ ---------- ----------------- ------------ ------- ----
Cluster
            cluster1-01_clus1  up/up     169.254.3.4/23     cluster1-01  e0a     true
            cluster1-01_clus2  up/up     169.254.3.5/23     cluster1-01  e0b     true
            cluster1-02_clus1  up/up     169.254.3.8/23     cluster1-02  e0a     true
            cluster1-02_clus2  up/up     169.254.3.9/23     cluster1-02  e0b     true
            cluster1-03_clus1  up/up     169.254.1.3/23     cluster1-03  e0a     true
            cluster1-03_clus2  up/up     169.254.1.1/23     cluster1-03  e0b     true
            cluster1-04_clus1  up/up     169.254.1.6/23     cluster1-04  e0a     true
            cluster1-04_clus2  up/up     169.254.1.7/23     cluster1-04  e0b     true
----
====


. 确认集群显示两个集群交换机的信息。


[role="tabbed-block"]
====
.ONTAP 9.8 及更高版本
--
从ONTAP 9.8 开始，使用以下命令：

[source, cli]
----
system switch ethernet show -is-monitoring-enabled-operational true
----
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
.ONTAP 9.7 及更低版本
--
对于ONTAP 9.7 及更早版本，请使用以下命令：

[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
====
. [[step6]]禁用集群 LIF 的自动还原功能。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----




== 步骤 2：配置端口

. 在交换机 cs2 上，确认连接到集群中节点的端口列表。
+
[source, cli]
----
show isdp neighbor
----
. 在交换机 cs2 上，关闭连接到节点集群端口的端口。例如，如果端口 0/1 到 0/16 连接到ONTAP节点：
+
[listing, subs="+quotes"]
----
(cs2)> *enable*
(cs2)# *configure*
(cs2)(Config)# *interface 0/1-0/16*
(cs2)(Interface 0/1-0/16)# *shutdown*
(cs2)(Interface 0/1-0/16)# *exit*
(cs2)(Config)#
----
. 验证集群 LIF 是否已迁移到集群交换机 cs1 上托管的端口。这可能需要几秒钟。
+
[source, cli]
----
network interface show -vserver cluster
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver cluster*
            Logical           Status     Network            Current       Current Is
Vserver     Interface         Admin/Oper Address/Mask       Node          Port    Home
----------- ----------------- ---------- ------------------ ------------- ------- ----
Cluster
            cluster1-01_clus1 up/up      169.254.3.4/23     cluster1-01   e0a     true
            cluster1-01_clus2 up/up      169.254.3.5/23     cluster1-01   e0a     false
            cluster1-02_clus1 up/up      169.254.3.8/23     cluster1-02   e0a     true
            cluster1-02_clus2 up/up      169.254.3.9/23     cluster1-02   e0a     false
            cluster1-03_clus1 up/up      169.254.1.3/23     cluster1-03   e0a     true
            cluster1-03_clus2 up/up      169.254.1.1/23     cluster1-03   e0a     false
            cluster1-04_clus1 up/up      169.254.1.6/23     cluster1-04   e0a     true
            cluster1-04_clus2 up/up      169.254.1.7/23     cluster1-04   e0a     false
cluster1::*>
----
====
. 验证集群是否运行正常：
+
`cluster show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
----
====
. 如果您尚未保存当前交换机配置，请将以下命令的输出复制到日志文件中：
+
[source, cli]
----
show running-config
----
. 清除交换机 cs2 上的配置并执行基本设置。
+

CAUTION: 更新或应用新的 RCF 时，必须清除交换机设置并执行基本配置。必须使用串口控制台连接到交换机才能清除交换机设置。如果您已使用知识库文章，则此要求为可选。 https://kb.netapp.com/onprem/Switches/Broadcom/How_to_clear_configuration_on_a_Broadcom_interconnect_switch_while_retaining_remote_connectivity["如何在保持远程连接的情况下清除博通互连交换机上的配置"]事先清除配置。

+

NOTE: 清除配置不会删除许可证。

+
.. 通过SSH连接到交换机。
+
只有当交换机端口上的所有集群 LIF 都被移除，并且交换机准备好清除配置时，才能继续执行此操作。

.. 进入特权模式：
+
[listing]
----
(cs2)> enable
(cs2)#
----
.. 复制并粘贴以下命令以删除之前的 RCF 配置（根据之前使用的 RCF 版本，如果缺少特定设置，某些命令可能会出错）：
+
[source, cli]
----
clear config interface 0/1-0/56
y
clear config interface lag 1
y
configure
deleteport 1/1 all
no policy-map CLUSTER
no policy-map WRED_25G
no policy-map WRED_100G
no policy-map InShared
no policy-map InMetroCluster
no policy-map InCluster
no policy-map InClusterRdma
no class-map CLUSTER
no class-map HA
no class-map RDMA
no class-map c5
no class-map c4
no class-map CLUSTER
no class-map CLUSTER_RDMA
no class-map StorageSrc
no class-map StorageDst
no class-map RdmaSrc
no class-map RdmaDstA
no classofservice dot1p-mapping
no random-detect queue-parms 0
no random-detect queue-parms 1
no random-detect queue-parms 2
no random-detect queue-parms 3
no random-detect queue-parms 4
no random-detect queue-parms 5
no random-detect queue-parms 6
no random-detect queue-parms 7
no cos-queue min-bandwidth
no cos-queue random-detect 0
no cos-queue random-detect 1
no cos-queue random-detect 2
no cos-queue random-detect 3
no cos-queue random-detect 4
no cos-queue random-detect 5
no cos-queue random-detect 6
no cos-queue random-detect 7
exit
vlan database
no vlan 17
no vlan 18
exit
show running-config
----
.. 将运行配置保存到启动配置中：
+
`write memory`

+
[listing, subs="+quotes"]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
----
.. 重启交换机：
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*
Are you sure you would like to reset the system? (y/n) *y*
----
.. 使用 SSH 再次登录交换机以完成 RCF 安装。


. 请注意以下事项：
+
.. 如果交换机上安装了额外的端口许可证，则必须修改 RCF 以配置额外的许可端口。看 link:configure-licenses.html#activate-newly-licensed-ports["激活新授权的端口"] 详情请见下文。但是，升级到 RCF 1.12 或更高版本时，不再需要进行这些修改，因为所有接口现在都已预先配置。
.. 记录之前 RCF 中所做的任何自定义设置，并将这些设置应用到新的 RCF 中。例如，设置端口速度或硬编码 FEC 模式。




[role="tabbed-block"]
====
.EFOS 版本 3.12.x 及更高版本
--
. 使用以下传输协议之一将 RCF 复制到交换机 cs2 的 bootflash：HTTP、HTTPS、FTP、TFTP、SFTP 或 SCP。
+
此示例展示了如何使用 SFTP 将 RCF 文件复制到交换机 cs2 的启动闪存中：



[listing, subs="+quotes"]
----
(cs2)# *copy sftp://172.19.2.1/BES-53248-RCF-v1.9-Cluster-HA.txt nvram:reference-config*
Remote Password:**
Mode........................................... TFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /
Filename....................................... BES-53248_RCF_v1.9-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... reference-config.scr
Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
TFTP Code transfer starting...
File transfer operation completed successfully.
----
. 请确认脚本已下载并以您指定的文件名保存：
+
`script list`

+
[listing, subs="+quotes"]
----
(cs2)# *script list*

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
reference-config.scr                       2680         2024 05 31 21:54:22
2 configuration script(s) found.
2042 Kbytes free.
----
. 将脚本应用到交换机：
+
`script apply`

+
[listing, subs="+quotes"]
----
(cs2)# *script apply reference-config.scr*

Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*
Config file 'startup-config' created successfully.
Configuration Saved!

Configuration script 'reference-config.scr' applied.
----


--
.所有其他 EFOS 版本
--
. 使用以下传输协议之一将 RCF 复制到交换机 cs2 的 bootflash：HTTP、HTTPS、FTP、TFTP、SFTP 或 SCP。
+
此示例展示了如何使用 SFTP 将 RCF 文件复制到交换机 cs2 的启动闪存中：



[listing, subs="+quotes"]
----
(cs2)# *copy sftp://172.19.2.1/tmp/BES-53248_RCF_v1.9-Cluster-HA.txt
nvram:script BES-53248_RCF_v1.9-Cluster-HA.scr*
Remote Password:**
Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... BES-53248_RCF_v1.9-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_RCF_v1.9-Cluster-HA.scr
Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...
File transfer operation completed successfully.
----
. 请确认脚本已下载并保存到您指定的文件名：
+
`script list`

+
[listing, subs="+quotes"]
----
(cs2)# *script list*

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
BES-53248_RCF_v1.9-Cluster-HA.scr          2241         2020 09 30 05:41:00

1 configuration script(s) found.
----
. 将脚本应用到交换机：
+
`script apply`

+
[listing, subs="+quotes"]
----
(cs2)# *script apply BES-53248_RCF_v1.9-Cluster-HA.scr*

Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*
Config file 'startup-config' created successfully.
Configuration Saved!

Configuration script 'BES-53248_RCF_v1.9-Cluster-HA.scr' applied.
----


--
====
. 步骤11：检查横幅输出。 `show clibanner`命令。您必须阅读并遵循这些说明以确保交换机的正确配置和操作。
+
`show clibanner`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show clibanner*

Banner Message configured :
=========================
BES-53248 Reference Configuration File v1.9 for Cluster/HA/RDMA

Switch   : BES-53248
Filename : BES-53248-RCF-v1.9-Cluster.txt
Date     : 10-26-2022
Version  : v1.9
Port Usage:
Ports 01 - 16: 10/25GbE Cluster Node Ports, base config
Ports 17 - 48: 10/25GbE Cluster Node Ports, with licenses
Ports 49 - 54: 40/100GbE Cluster Node Ports, with licenses, added right to left
Ports 55 - 56: 100GbE Cluster ISL Ports, base config
NOTE:
- The 48 SFP28/SFP+ ports are organized into 4-port groups in terms of port
speed:
Ports 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44,
45-48
The port speed should be the same (10GbE or 25GbE) across all ports in a 4-port
group
- If additional licenses are purchased, follow the 'Additional Node Ports
activated with Licenses' section for instructions
- If SSH is active, it will have to be re-enabled manually after 'erase
startup-config'
command has been executed and the switch rebooted
----
====
. 在交换机上，验证应用 RCF 后是否出现了新增的授权端口：
+
[source, cli]
----
show port all | exclude Detach
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show port all | exclude Detach*

                 Admin     Physical     Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode         Status     Status Trap    Mode   Timeout
--------- ------ --------- ------------ ---------- ------ ------- ------ --------
0/1              Enable    Auto                    Down   Enable  Enable long
0/2              Enable    Auto                    Down   Enable  Enable long
0/3              Enable    Auto                    Down   Enable  Enable long
0/4              Enable    Auto                    Down   Enable  Enable long
0/5              Enable    Auto                    Down   Enable  Enable long
0/6              Enable    Auto                    Down   Enable  Enable long
0/7              Enable    Auto                    Down   Enable  Enable long
0/8              Enable    Auto                    Down   Enable  Enable long
0/9              Enable    Auto                    Down   Enable  Enable long
0/10             Enable    Auto                    Down   Enable  Enable long
0/11             Enable    Auto                    Down   Enable  Enable long
0/12             Enable    Auto                    Down   Enable  Enable long
0/13             Enable    Auto                    Down   Enable  Enable long
0/14             Enable    Auto                    Down   Enable  Enable long
0/15             Enable    Auto                    Down   Enable  Enable long
0/16             Enable    Auto                    Down   Enable  Enable long
0/49             Enable    40G Full                Down   Enable  Enable long
0/50             Enable    40G Full                Down   Enable  Enable long
0/51             Enable    100G Full               Down   Enable  Enable long
0/52             Enable    100G Full               Down   Enable  Enable long
0/53             Enable    100G Full               Down   Enable  Enable long
0/54             Enable    100G Full               Down   Enable  Enable long
0/55             Enable    100G Full               Down   Enable  Enable long
0/56             Enable    100G Full               Down   Enable  Enable long
----
====
. 请在交换机上确认您的更改已生效。
+
[source, cli]
----
show running-config
----
. 保存运行配置，以便重启交换机时将其作为启动配置：
+
`write memory`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
----
====
. 重启交换机并验证运行配置是否正确。
+
`reload`

+
[listing, subs="+quotes"]
----
(cs2)# *reload*
Are you sure you would like to reset the system? (y/n) *y*
System will now restart!
----
. 在集群交换机 cs2 上，启动连接到节点集群端口的端口。
+
[listing, subs="+quotes"]
----
(cs2)> *enable*
(cs2)# *configure*
(cs2)(Config)# *interface 0/1-0/16*
(cs2)(Interface 0/1-0/16)# *no shutdown*
(cs2)(Config)# *exit*
----
. 将运行配置保存到启动配置中：
+
`write memory`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
----
====
. 请检查交换机 cs2 上的端口：
+
[source, cli]
----
show interfaces status all | exclude Detach
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *show interfaces status all | exclude Detach*

                                Link    Physical    Physical    Media       Flow
Port       Name                 State   Mode        Status      Type        Control     VLAN
---------  -------------------  ------  ----------  ----------  ----------  ----------  ------
.
.
.
0/16       10/25GbE Node Port   Down    Auto                                Inactive    Trunk
0/17       10/25GbE Node Port   Down    Auto                                Inactive    Trunk
0/18       10/25GbE Node Port   Up      25G Full    25G Full    25GBase-SR  Inactive    Trunk
0/19       10/25GbE Node Port   Up      25G Full    25G Full    25GBase-SR  Inactive    Trunk
.
.
.
0/50       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/51       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/52       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/53       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/54       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/55       Cluster   ISL Port   Up      Auto        100G Full   Copper      Inactive    Trunk
0/56       Cluster   ISL Port   Up      Auto        100G Full   Copper      Inactive    Trunk
----
====
. 检查集群上集群端口的运行状况。
+
.. 验证集群中所有节点的 e0b 端口是否已启动且运行状况良好：
+
[source, cli]
----
network port show -ipspace cluster
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace cluster*

Node: cluster1-01
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: cluster1-02

                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: cluster1-03
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false

Node: cluster1-04
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy false
----
====
.. 从集群验证交换机运行状况：
+
[source, cli]
----
network device-discovery show
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-01/cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
cluster01-2/cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
cluster01-3/cdp
            e0a    cs1                       0/4               BES-53248
            e0b    cs2                       0/4               BES-53248
cluster1-04/cdp
            e0a    cs1                       0/3               BES-53248
            e0b    cs2                       0/2               BES-53248
----
====


. 确认集群显示两个集群交换机的信息。


[role="tabbed-block"]
====
.ONTAP 9.8 及更高版本
--
从ONTAP 9.8 开始，使用以下命令：

[source, cli]
----
system switch ethernet show -is-monitoring-enabled-operational true
----
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
.ONTAP 9.7 及更低版本
--
对于ONTAP 9.7 及更早版本，请使用以下命令：

[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs1                         cluster-network    10.228.143.200   BES-53248
           Serial Number: QTWCU22510008
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP

cs2                         cluster-network    10.228.143.202   BES-53248
           Serial Number: QTWCU22510009
            Is Monitored: true
                  Reason: None
        Software Version: 3.10.0.3
          Version Source: CDP/ISDP
cluster1::*>
----
--
====
. [[step21]]在交换机 cs1 上重复步骤 1 到 20。
. 启用集群 LIF 的自动回滚功能：
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. 。确认集群 LIF 已恢复到其原端口：
+
[source, cli]
----
network interface show -vserver Cluster
----
+
更多详情请参见link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["将 LIF 恢复到其母端口"]。





== 步骤 3：验证配置

. 在交换机 cs1 上，确认连接到集群端口的交换机端口是否已启动：
+
[source, cli]
----
show interfaces status all
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# show interfaces status all | exclude Detach

                                Link    Physical    Physical    Media       Flow
Port       Name                 State   Mode        Status      Type        Control     VLAN
---------  -------------------  ------  ----------  ----------  ----------  ----------  ------
.
.
.
0/16       10/25GbE Node Port   Down    Auto                                Inactive    Trunk
0/17       10/25GbE Node Port   Down    Auto                                Inactive    Trunk
0/18       10/25GbE Node Port   Up      25G Full    25G Full    25GBase-SR  Inactive    Trunk
0/19       10/25GbE Node Port   Up      25G Full    25G Full    25GBase-SR  Inactive    Trunk
.
.
.
0/50       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/51       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/52       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/53       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/54       40/100GbE Node Port  Down    Auto                                Inactive    Trunk
0/55       Cluster   ISL Port   Up      Auto        100G Full   Copper      Inactive    Trunk
0/56       Cluster   ISL Port   Up      Auto        100G Full   Copper      Inactive    Trunk
----
====
. 验证交换机 cs1 和 cs2 之间的 ISL 是否正常工作：
+
[source, cli]
----
show port-channel 1/1
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port-channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)
Mbr     Device/       Port      Port
Ports   Timeout       Speed     Active
------- ------------- --------- -------
0/55    actor/long    Auto      True
        partner/long
0/56    actor/long    Auto      True
        partner/long
----
====
. 确认集群 LIF 已恢复到其原端口：
+
[source, cli]
----
network interface show -vserver cluster
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> network interface show -vserver cluster
            Logical            Status     Network            Current             Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node                Port    Home
----------- ------------------ ---------- ------------------ ------------------- ------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.3.4/23     cluster1-01         e0a     true
            cluster1-01_clus2  up/up      169.254.3.5/23     cluster1-01         e0b     true
            cluster1-02_clus1  up/up      169.254.3.8/23     cluster1-02         e0a     true
            cluster1-02_clus2  up/up      169.254.3.9/23     cluster1-02         e0b     true
            cluster1-03_clus1  up/up      169.254.1.3/23     cluster1-03         e0a     true
            cluster1-03_clus2  up/up      169.254.1.1/23     cluster1-03         e0b     true
            cluster1-04_clus1  up/up      169.254.1.6/23     cluster1-04         e0a     true
            cluster1-04_clus2  up/up      169.254.1.7/23     cluster1-04         e0b     true
----
====
. 验证集群是否运行正常：
+
`cluster show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
----
====
. 验证远程集群接口的连接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`执行命令以启动集群连接性检查，然后显示详细信息：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*运行程序前请等待几秒钟 `show`显示详细信息的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source              Destination         Packet
Node   Date                       LIF                 LIF                 Loss
------ -------------------------- ------------------- ------------------- -------
cluster1-01
       3/5/2022 19:21:18 -06:00   cluster1-01_clus2   cluster01-02_clus1  none
       3/5/2022 19:21:20 -06:00   cluster1-01_clus2   cluster01-02_clus2  none

cluster1-02
       3/5/2022 19:21:18 -06:00   cluster1-02_clus2   cluster1-02_clus1   none
       3/5/2022 19:21:20 -06:00   cluster1-02_clus2   cluster1-02_clus2   none
----
--
.所有ONTAP版本
--
对于所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`检查连接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is cluster1-03
Getting addresses from network interface table...
Cluster cluster1-03_clus1 169.254.1.3 cluster1-03 e0a
Cluster cluster1-03_clus2 169.254.1.1 cluster1-03 e0b
Cluster cluster1-04_clus1 169.254.1.6 cluster1-04 e0a
Cluster cluster1-04_clus2 169.254.1.7 cluster1-04 e0b
Cluster cluster1-01_clus1 169.254.3.4 cluster1-01 e0a
Cluster cluster1-01_clus2 169.254.3.5 cluster1-01 e0b
Cluster cluster1-02_clus1 169.254.3.8 cluster1-02 e0a
Cluster cluster1-02_clus2 169.254.3.9 cluster1-02 e0b
Local = 169.254.1.3 169.254.1.1
Remote = 169.254.1.6 169.254.1.7 169.254.3.4 169.254.3.5 169.254.3.8
169.254.3.9
Cluster Vserver Id = 4294967293
Ping status:
............
Basic connectivity succeeds on 12 path(s)
Basic connectivity fails on 0 path(s)
................................................
Detected 9000 byte MTU on 12 path(s):
  Local 169.254.1.3 to Remote 169.254.1.6
  Local 169.254.1.3 to Remote 169.254.1.7
  Local 169.254.1.3 to Remote 169.254.3.4
  Local 169.254.1.3 to Remote 169.254.3.5
  Local 169.254.1.3 to Remote 169.254.3.8
  Local 169.254.1.3 to Remote 169.254.3.9
  Local 169.254.1.1 to Remote 169.254.1.6
  Local 169.254.1.1 to Remote 169.254.1.7
  Local 169.254.1.1 to Remote 169.254.3.4
  Local 169.254.1.1 to Remote 169.254.3.5
  Local 169.254.1.1 to Remote 169.254.3.8
  Local 169.254.1.1 to Remote 169.254.3.9
Larger than PMTU communication succeeds on 12 path(s)
RPC status:
6 paths up, 0 paths down (tcp check)
6 paths up, 0 paths down (udp check)
----
--
====
. 将权限级别改回管理员：
+
[source, cli]
----
set -privilege admin
----
. 如果您已禁用自动创建案例功能，请通过调用AutoSupport消息重新启用该功能：
+
[source, cli]
----
system node autosupport invoke -node * -type all -message MAINT=END
----

