---
permalink: switch-bes-53248/upgrade-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,upgrading EFOS software 
summary: '请按照以下步骤升级 BES-53248 集群交换机上的以太网结构操作系统 (EFOS) 软件。' 
---
= 升级 EFOS 软件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
请按照以下步骤升级 BES-53248 集群交换机上的 EFOS 软件。

EFOS 软件包含一套用于开发以太网和 IP 基础设施系统的高级网络功能和协议。这种软件架构适用于任何使用需要彻底数据包检查或分离的应用程序的网络组织设备。



== 准备升级

.开始之前
* 从以下位置下载适用于您的集群交换机的 Broadcom EFOS 软件： https://www.broadcom.com/support/bes-switch["博通以太网交换机支持"^]地点。
* 请查看以下有关 EFOS 版本的说明。


[]
====
*请注意以下事项：*

* 从 EFOS 3.4.xx 升级到 EFOS 3.7.xx 或更高版本时，交换机必须运行 EFOS 3.4.4.6（或更高版本的 3.4.xx）。如果您运行的是之前的版本，请先将交换机升级到 EFOS 3.4.4.6（或更高版本的 3.4.xx），然后再将交换机升级到 EFOS 3.7.xx 或更高版本。
* EFOS 3.4.xx 和 3.7.xx 或更高版本的配置有所不同。将 EFOS 版本从 3.4.xx 更改为 3.7.xx 或更高版本，反之亦然，需要将交换机重置为出厂默认设置，并（重新）应用相应 EFOS 版本的 RCF 文件。此过程需要通过串行控制台端口进行访问。
* 从 EFOS 版本 3.7.xx 或更高版本开始，提供不符合 FIPS 标准的版本和符合 FIPS 标准的版本。从不符合 FIPS 标准的版本过渡到符合 FIPS 标准的版本或反之亦然时，需要采取不同的步骤。将 EFOS 从不符合 FIPS 标准的版本更改为符合 FIPS 标准的版本，反之亦然，会将交换机重置为出厂默认设置。此过程需要通过串行控制台端口进行访问。


====
|===


| *程序* | *当前EFOS版本* | *全新EFOS版本* | *高级步骤* 


 a| 
在两个（非）符合 FIPS 标准的版本之间升级 EFOS 的步骤
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
使用以下方式升级新的 EFOS 映像<<方法一：升级EFOS>>。配置和许可证信息将被保留。



 a| 
3.4.4.6（或更高版本的 3.4.xx）
 a| 
3.7.xx 或更高版本不符合 FIPS 标准
 a| 
使用以下方式升级 EFOS<<方法一：升级EFOS>> 。将交换机重置为出厂默认设置，并应用适用于 EFOS 3.7.xx 或更高版本的 RCF 文件。



.2+| 3.7.xx 或更高版本不符合 FIPS 标准  a| 
3.4.4.6（或更高版本的 3.4.xx）
 a| 
使用降级 EFOS<<方法一：升级EFOS>> 。将交换机重置为出厂默认设置，并应用适用于 EFOS 3.4.xx 的 RCF 文件。



 a| 
3.7.xx 或更高版本不符合 FIPS 标准
 a| 
使用以下方式升级新的 EFOS 映像<<方法一：升级EFOS>>。配置和许可证信息将被保留。



 a| 
3.7.xx 或更高版本符合 FIPS 标准
 a| 
3.7.xx 或更高版本符合 FIPS 标准
 a| 
使用以下方式升级新的 EFOS 映像<<方法一：升级EFOS>>。配置和许可证信息将被保留。



 a| 
从符合 FIPS 标准的 EFOS 版本升级到/从符合 FIPS 标准的 EFOS 版本升级的步骤
 a| 
不符合FIPS标准
 a| 
符合FIPS标准
 a| 
使用以下方式升级 EFOS 映像<<方法二：使用 ONIE OS 安装程序升级 EFOS>>。交换机配置和许可证信息将会丢失。



 a| 
符合FIPS标准
 a| 
不符合FIPS标准

|===
[IMPORTANT]
====
要检查您的 EFOS 版本是否符合 FIPS 标准，请使用以下方法： `show fips status`命令。在以下示例中，*IP_switch_a1* 使用的是符合 FIPS 标准的 EFOS，而 *IP_switch_a2* 使用的是不符合 FIPS 标准的 EFOS。

* 在交换机 IP_switch_a1（符合 FIPS 标准的 EFOS）上：
+
[listing, subs="+quotes"]
----
IP_switch_a1 # *show fips status*

System running in FIPS mode
----
* 在交换机 IP_switch_a2（非 FIPS 合规 EFOS）上：
+
[listing, subs="+quotes"]
----
IP_switch_a2 # *show fips status*
                     ^
% Invalid input detected at ^ marker.
----


====


== 升级软件

请使用以下方法之一：

* <<方法一：升级EFOS>>。适用于大多数情况（见上表）。
* <<方法二：使用 ONIE OS 安装程序升级 EFOS>>。如果一个 EFOS 版本符合 FIPS 标准，而另一个 EFOS 版本不符合 FIPS 标准，则可以使用此方法。



NOTE: 一次升级一台交换机上的 EFOS，以确保集群网络持续运行。



=== 方法一：升级EFOS

请按照以下步骤升级 EFOS 软件。


IMPORTANT: 请注意，将 BES-53248 集群交换机从 EFOS 3.3.xx 或 3.4.xx 升级到 EFOS 3.7.0.4 或 3.8.0.2 后，交换机间链路 (ISL) 和端口通道将被标记为 *Down* 状态。这是预期行为，除非您在自动还原 LIF 时遇到问题，否则可以安全地继续升级。请参阅知识库文章： https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["BES-53248 集群交换机 NDU 升级到 EFOS 3.7.0.4 及更高版本失败"^]更多详情请见下文。

.步骤
. 将 BES-53248 集群交换机连接到管理网络。
. 使用 `ping`用于验证与托管 EFOS、许可证和 RCF 文件的服务器的连接性的命令。
+
此示例验证交换机是否已连接到 IP 地址为 172.19.2.1 的服务器：

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. 禁用集群 LIF 的自动回滚功能。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. 显示活动配置和备份配置的启动映像：
+
`show bootvar`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

 Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.4.4.6              3.7.0.4        3.7.0.4

----
====
. 将镜像文件下载到交换机。
+
将映像文件复制到备份映像意味着当您重新启动时，该映像将建立正在运行的 EFOS 版本，从而完成更新。

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk backup*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... backup

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. 显示活动配置和备份配置的启动映像：
+
`show bootvar`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1      3.7.0.4    3.7.0.4             3.7.0.4       3.10.0.3
----
====
. 从备份配置启动系统：
+
`boot system backup`

+
[listing, subs="+quotes"]
----
(cs2)# *boot system backup*
Activating image backup ..
----
. 显示活动配置和备份配置的启动映像：
+
`show bootvar`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
------------------------------------------------------------------
 unit      active      backup      current-active    next-active
------------------------------------------------------------------
    1    3.10.0.3    3.10.0.3            3.10.0.3       3.10.0.3
----
====
. 将运行配置保存到启动配置中：
+
`write memory`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *write memory*
This operation may take a few minutes.

Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
----
====
. 重启交换机：
+
`reload`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. 请重新登录并验证EFOS软件的新版本：
+
`show version`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. 在交换机 cs1 上重复步骤 5 到 11。
. 启用集群 LIF 的自动回滚功能。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. 确认集群 LIF 已恢复到其原端口：
+
[source, cli]
----
network interface show -vserver Cluster
----
+
更多详情请参见link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["将 LIF 恢复到其母端口"]。





=== 方法二：使用 ONIE OS 安装程序升级 EFOS

如果一个 EFOS 版本符合 FIPS 标准，而另一个 EFOS 版本不符合 FIPS 标准，则可以执行以下步骤。如果交换机无法启动，可以使用以下步骤从 ONIE 升级非 FIPS 或符合 FIPS 标准的 EFOS 3.7.xx 映像。


NOTE: 此功能仅适用于不符合 FIPS 标准的 EFOS 3.7.xx 或更高版本。


CAUTION: 如果使用 ONIE OS 安装程序升级 EFOS，则配置将重置为出厂默认设置，许可证将被删除。您必须设置交换机并安装许可证和受支持的 RCF，才能使交换机恢复正常运行。

.步骤
. 禁用集群 LIF 的自动回滚功能。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----
. 将交换机启动到 ONIE 安装模式。
+
启动过程中，看到提示时选择 ONIE：

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
选择 *ONIE* 后，开关会加载并向您展示几个选项。选择“安装操作系统”。

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
交换机启动进入 ONIE 安装模式。

. 停止 ONIE 发现并配置以太网接口。
+
当出现以下消息时，按 *Enter* 键打开 ONIE 控制台：

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIE 检测仍在继续，消息会打印到控制台。

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. 配置以太网接口并添加路由 `ifconfig eth0 <ipAddress> netmask <netmask> up`和 `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. 请确认托管 ONIE 安装文件的服务器可以访问：
+
`ping`

+
.显示示例
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. 安装新的交换机软件：
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.显示示例
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
软件安装完成后，交换机将重启。让交换机正常重启进入新的 EFOS 版本。

. 确认新交换机软件已安装：
+
`show bootvar`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
   1    3.7.0.4     3.7.0.4  3.7.0.4         3.10.0.3
(cs2) #
----
====
. 完成安装。交换机重启后未应用任何配置，并重置为出厂默认设置。请按照以下步骤重新配置交换机：
+
.. link:configure-licenses.html["安装许可证"]
.. link:configure-install-rcf.html["安装 RCF"]
.. link:configure-ssh.html["启用 SSH"]
.. link:CSHM_log_collection.html["启用日志收集"]
.. link:CSHM_snmpv3.html["配置 SNMPv3 进行监控"]


. 在交换机 cs1 上重复步骤 2 至 8。
. 启用集群 LIF 的自动回滚功能。
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----
. 确认集群 LIF 已恢复到其原端口：
+
[source, cli]
----
network interface show -vserver Cluster
----
+
更多详情请参见link:https://docs.netapp.com/us-en/ontap/networking/revert_a_lif_to_its_home_port.html["将 LIF 恢复到其母端口"]。


