---
permalink: switch-cisco-3132q-v/cn1610-prepare-to-migrate.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: 您可以在AFF或FAS集群中使用Cisco Nexus 3132q-v 交换机作为集群交换机。 
---
= 准备从 CN1610 交换机迁移到 3132Q-V 交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
请按照以下步骤准备您的 CN1610 交换机，以便迁移到Cisco Nexus 3132Q-V 交换机。

.步骤
. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ 是维护窗口的持续时间，单位为小时。

+

NOTE: AutoSupport消息会通知技术支持此维护任务，以便在维护窗口期间抑制自动创建案例。

. 显示配置中设备的相关信息：
+
`network device-discovery show`

+
.显示示例
[%collapsible]
====
以下示例显示了每个节点上每个集群互连交换机配置的集群互连接口数量：

[listing]
----
cluster::> network device-discovery show

       Local  Discovered
Node   Port   Device       Interface   Platform
------ ------ ------------ ----------- ----------
n1     /cdp
        e0a   CL1          0/1         CN1610
        e0b   CL2          0/1         CN1610
        e0c   CL2          0/2         CN1610
        e0d   CL1          0/2         CN1610
n2     /cdp
        e0a   CL1          0/3         CN1610
        e0b   CL2          0/3         CN1610
        e0c   CL2          0/4         CN1610
        e0d   CL1          0/4         CN1610

8 entries were displayed.
----
====
. 确定每个集群接口的管理或运行状态。
+
.. 显示集群网络端口属性：
+
`network port show`

+
.显示示例
[%collapsible]
====
以下示例显示系统上的网络端口属性：

[listing]
----
cluster::*> network port show -role Cluster
       (network port show)

Node: n1
                Broadcast              Speed (Mbps) Health Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status Health Status
----- --------- ---------- ----- ----- ------------ ------ -------------
e0a   cluster   cluster    up    9000  auto/10000     -        -
e0b   cluster   cluster    up    9000  auto/10000     -        -
e0c   cluster   cluster    up    9000  auto/10000     -        -
e0d   cluster   cluster    up    9000  auto/10000     -        -

Node: n2
                Broadcast              Speed (Mbps) Health Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status Health Status
----- --------- ---------- ----- ----- ------------ ------ -------------
e0a   cluster   cluster    up    9000  auto/10000     -        -
e0b   cluster   cluster    up    9000  auto/10000     -        -
e0c   cluster   cluster    up    9000  auto/10000     -        -
e0d   cluster   cluster    up    9000  auto/10000     -        -

8 entries were displayed.
----
====
.. 显示逻辑接口信息：+
`network interface show`
+
.显示示例
[%collapsible]
====
以下示例显示系统中所有 LIF 的一般信息：

[listing]
----
cluster::*> network interface show -role Cluster
       (network interface show)

         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0a      true
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0d      true
         n2_clus1   up/up       10.10.0.5/24   n2       e0a      true
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0d      true

8 entries were displayed.
----
====
.. 显示已发现的集群交换机的相关信息：
+
`system cluster-switch show`

+
.显示示例
[%collapsible]
====
以下示例显示了集群已知的集群交换机及其管理 IP 地址：

[listing]
----
cluster::> system cluster-switch show

Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.2.0.7
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.2.0.7
    Version Source: ISDP

2 entries were displayed.
----
====


. 设置 `-auto-revert`在两个节点上，将集群 LIF clus1 和 clus4 的参数设置为 false：
+
`network interface modify`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node1 -lif clus4 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus4 -auto-revert false
----
====
. 确认新的 3132Q-V 交换机上已根据您的要求安装了相应的 RCF 和映像，并进行任何必要的站点自定义，例如用户和密码、网络地址等。
+
此时您必须准备好这两个开关。如果需要升级 RCF 和镜像，请按照以下步骤操作：

+
.. 看link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco以太网交换机"^]在NetApp支持网站上。
.. 请记下您交换机的型号以及该页表格中所需的软件版本。
.. 下载相应版本的RCF。
.. 在“描述”页面上选择“继续”，接受许可协议，然后按照“下载”页面上的说明下载 RCF。
.. 下载相应版本的图像处理软件。
+
https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco集群和管理网络交换机参考配置文件下载"^]



. 迁移与待替换的第二台 CN1610 交换机相关的 LIF：
+
`network interface migrate`

+
[NOTE]
====
您必须通过服务处理器或节点管理接口，从与节点的连接迁移集群 LIF，该连接拥有要迁移的集群 LIF。

====
+
.显示示例
[%collapsible]
====
以下示例显示了 n1 和 n2，但 LIF 迁移必须在所有节点上执行：

[listing]
----

cluster::*> network interface migrate -vserver Cluster -lif n1_clus2 -destination-node  n1  -destination-port  e0a
cluster::*> network interface migrate -vserver Cluster -lif n1_clus3 -destination-node  n1  -destination-port  e0d
cluster::*> network interface migrate -vserver Cluster -lif n2_clus2 -destination-node  n2  -destination-port  e0a
cluster::*> network interface migrate -vserver Cluster -lif n2_clus3 -destination-node  n2  -destination-port  e0d
----
====
. 验证集群健康状况：
+
`network interface show`

+
.显示示例
[%collapsible]
====
以下示例展示了前一个结果。 `network interface migrate`命令：

[listing]
----
cluster::*> network interface show -role Cluster
       (network interface show)

         Logical    Status      Network         Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask    Node     Port     Home
-------- ---------- ----------- --------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24    n1       e0a      true
         n1_clus2   up/up       10.10.0.2/24    n1       e0a      false
         n1_clus3   up/up       10.10.0.3/24    n1       e0d      false
         n1_clus4   up/up       10.10.0.4/24    n1       e0d      true
         n2_clus1   up/up       10.10.0.5/24    n2       e0a      true
         n2_clus2   up/up       10.10.0.6/24    n2       e0a      false
         n2_clus3   up/up       10.10.0.7/24    n2       e0d      false
         n2_clus4   up/up       10.10.0.8/24    n2       e0d      true

8 entries were displayed.
----
====
. 关闭与交换机 CL2 物理连接的集群互连端口：
+
`network port modify`

+
.显示示例
[%collapsible]
====
以下命令关闭 n1 和 n2 上的指定端口，但必须关闭所有节点上的端口：

[listing]
----
cluster::*> network port modify -node n1 -port e0b -up-admin false
cluster::*> network port modify -node n1 -port e0c -up-admin false
cluster::*> network port modify -node n2 -port e0b -up-admin false
cluster::*> network port modify -node n2 -port e0c -up-admin false
----
====
. 验证远程集群接口的连接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`执行命令以启动集群连接性检查，然后显示详细信息：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*运行 show 命令显示详细信息之前，请等待几秒钟。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source      Destination   Packet
Node   Date                       LIF         LIF           Loss
------ -------------------------- ---------- -------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2   n1_clus1       none
       3/5/2022 19:21:20 -06:00   n1_clus2   n2_clus2       none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2   n1_clus1       none
       3/5/2022 19:21:20 -06:00   n2_clus2   n1_clus2       none
----
--
.所有ONTAP版本
--
对于所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`检查连接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node n1*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8

Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step10]] 关闭活动 CN1610 交换机 CL1 上的 ISL 端口 13 至 16：
+
`shutdown`

+
.显示示例
[%collapsible]
====
以下示例展示了如何关闭 CN1610 交换机 CL1 上的 ISL 端口 13 至 16：

[listing]
----
(CL1)# configure
(CL1)(Config)# interface 0/13-0/16
(CL1)(Interface 0/13-0/16)# shutdown
(CL1)(Interface 0/13-0/16)# exit
(CL1)(Config)# exit
(CL1)#
----
====
. 在 CL1 和 C2 之间建立临时 ISL：
+
.显示示例
[%collapsible]
====
以下示例在 CL1（端口 13-16）和 C2（端口 e1/24/1-4）之间建立临时 ISL：

[listing]
----
C2# configure
C2(config)# interface port-channel 2
C2(config-if)# switchport mode trunk
C2(config-if)# spanning-tree port type network
C2(config-if)# mtu 9216
C2(config-if)# interface breakout module 1 port 24 map 10g-4x
C2(config)# interface e1/24/1-4
C2(config-if-range)# switchport mode trunk
C2(config-if-range)# mtu 9216
C2(config-if-range)# channel-group 2 mode active
C2(config-if-range)# exit
C2(config-if)# exit
----
====


.下一步是什么？
link:cn1610-configure-ports.html["配置端口"]。
