---
permalink: switch-cisco-3132q-v/cn1610-configure-ports.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: 您可以在AFF或FAS集群中使用Cisco Nexus 3132q-v 交换机作为集群交换机。 
---
= 配置端口以从 CN1610 交换机迁移到 3132Q-V 交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
请按照以下步骤配置端口，以便从 CN1610 交换机迁移到新的 Nexus 3132Q-V 交换机。

.步骤
. 在所有节点上，拆下连接到 CN1610 交换机 CL2 的电缆。
+
使用支持的布线，您必须将所有节点上断开的端口重新连接到 Nexus 3132Q-V 交换机 C2。

. 从 CN1610 交换机 CL1 的 13 至 16 号端口移除四根 ISL 电缆。
+
您必须将合适的Cisco QSFP 转 SFP+ 分支电缆连接到新的Cisco 3132Q-V 交换机 C2 的端口 1/24 和现有 CN1610 交换机 CL1 的端口 13 至 16。

+

NOTE: 将任何电缆重新连接到新的Cisco 3132Q-V 交换机时，必须使用光纤或Cisco双绞线电缆。

. 要使 ISL 动态化，请将活动 CN1610 交换机上的 ISL 接口 3/1 配置为禁用静态模式： `no port-channel static`
+
此配置与在步骤 11 中两个交换机上启动 ISL 时 3132Q-V 交换机 C2 上的 ISL 配置相匹配。

+
.显示示例
[%collapsible]
====
以下示例展示了如何使用以下方式配置 ISL 接口 3/1： `no port-channel static`使 ISL 动态化的命令：

[listing]
----
(CL1)# configure
(CL1)(Config)# interface 3/1
(CL1)(Interface 3/1)# no port-channel static
(CL1)(Interface 3/1)# exit
(CL1)(Config)# exit
(CL1)#
----
====
. 在活动的 CN1610 交换机 CL1 上启动 ISL 13 至 16。
+
.显示示例
[%collapsible]
====
以下示例说明了在端口通道接口 3/1 上启动 ISL 端口 13 至 16 的过程：

[listing]
----
(CL1)# configure
(CL1)(Config)# interface 0/13-0/16,3/1
(CL1)(Interface 0/13-0/16,3/1)# no shutdown
(CL1)(Interface 0/13-0/16,3/1)# exit
(CL1)(Config)# exit
(CL1)#
----
====
. 确认 ISL 是否为 `up`在 CN1610 交换机 CL1 上：
+
`show port-channel`

+
“链路状态”应为 `Up`“类型”应为 `Dynamic`并且“端口活动”列应为： `True`端口 0/13 至 0/16：

+
.显示示例
[%collapsible]
====
[listing]
----
(CL1)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port        Port
Ports  Timeout       Speed       Active
------ ------------- ----------  -------
0/13   actor/long    10 Gb Full  True
       partner/long
0/14   actor/long    10 Gb Full  True
       partner/long
0/15   actor/long    10 Gb Full  True
       partner/long
0/16   actor/long    10 Gb Full  True
       partner/long
----
====
. 确认 ISL 是否为 `up`在 3132Q-V 开关 C2 上：
+
`show port-channel summary`

+
.显示示例
[%collapsible]
====
端口 Eth1/24/1 至 Eth1/24/4 应指示 `(P)`这意味着所有四个 ISL 端口都在端口通道中运行。  Eth1/31 和 eth1/32 应表示 `(D)`因为它们之间没有联系：

[listing]
----
C2# show port-channel summary

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        S - Switched    R - Routed
        U - Up (port-channel)
        M - Not in use. Min-links not met
------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(D)   Eth1/32(D)
2     Po2(SU)     Eth      LACP      Eth1/24/1(P) Eth1/24/2(P) Eth1/24/3(P)
                                     Eth1/24/4(P)
----
====
. 在所有节点上启用连接到 3132Q-V 交换机 C2 的所有集群互连端口：
+
`network port modify`

+
.显示示例
[%collapsible]
====
以下示例展示了如何启动连接到 3132Q-V 交换机 C2 的集群互连端口：

[listing]
----
cluster::*> network port modify -node n1 -port e0b -up-admin true
cluster::*> network port modify -node n1 -port e0c -up-admin true
cluster::*> network port modify -node n2 -port e0b -up-admin true
cluster::*> network port modify -node n2 -port e0c -up-admin true
----
====
. 撤销所有已迁移的、连接到所有节点上 C2 的集群互连 LIF：
+
`network interface revert`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n1_clus3
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus3
----
====
. 确认所有集群互连端口都已恢复到其原始端口：
+
`network interface show`

+
.显示示例
[%collapsible]
====
以下示例表明 clus2 上的 LIF 已恢复到其源端口，并且如果“当前端口”列中的端口状态为“已恢复”，则表明 LIF 已成功恢复。 `true`在“是否在家”一栏中。如果房屋价值是 `false`那么 LIF 就不会被撤销。

[listing]
----
cluster::*> network interface show -role cluster
       (network interface show)

         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0a      true
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0d      true
         n2_clus1   up/up       10.10.0.5/24   n2       e0a      true
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0d      true

8 entries were displayed.
----
====
. 确认集群所有端口均已连接：
+
`network port show`

+
.显示示例
[%collapsible]
====
以下示例展示了前一个结果。 `network port modify`命令，验证所有集群互连是否都已连接 `up`：

[listing]
----
cluster::*> network port show -role Cluster
       (network port show)

Node: n1
                Broadcast               Speed (Mbps) Health   Ignore
Port  IPspace   Domain      Link  MTU   Admin/Open   Status   Health Status
----- --------- ----------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster     up    9000  auto/10000     -        -
e0b   cluster   cluster     up    9000  auto/10000     -        -
e0c   cluster   cluster     up    9000  auto/10000     -        -
e0d   cluster   cluster     up    9000  auto/10000     -        -

Node: n2
                Broadcast               Speed (Mbps) Health   Ignore
Port  IPspace   Domain      Link  MTU   Admin/Open   Status   Health Status
----- --------- ----------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster     up    9000  auto/10000     -        -
e0b   cluster   cluster     up    9000  auto/10000     -        -
e0c   cluster   cluster     up    9000  auto/10000     -        -
e0d   cluster   cluster     up    9000  auto/10000     -        -

8 entries were displayed.
----
====
. 验证远程集群接口的连接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`执行命令以启动集群连接性检查，然后显示详细信息：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*运行 show 命令显示详细信息之前，请等待几秒钟。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source      Destination   Packet
Node   Date                       LIF         LIF           Loss
------ -------------------------- ---------- -------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2   n1_clus1       none
       3/5/2022 19:21:20 -06:00   n1_clus2   n2_clus2       none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2   n1_clus1       none
       3/5/2022 19:21:20 -06:00   n2_clus2   n1_clus2       none
----
--
.所有ONTAP版本
--
对于所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`检查连接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node n1*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8

Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step12]] 在集群中的每个节点上，迁移与第一个待替换的 CN1610 交换机 CL1 关联的接口：
+
`network interface migrate`

+
.显示示例
[%collapsible]
====
以下示例显示了节点 n1 和 n2 上正在迁移的端口或 LIF：

[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus1 -destination-node n1 -destination-port e0b
cluster::*> network interface migrate -vserver Cluster -lif n1_clus4 -destination-node n1 -destination-port e0c
cluster::*> network interface migrate -vserver Cluster -lif n2_clus1 -destination-node n2 -destination-port e0b
cluster::*> network interface migrate -vserver Cluster -lif n2_clus4 -destination-node n2 -destination-port e0c
----
====
. 验证集群状态：
+
`network interface show`

+
.显示示例
[%collapsible]
====
以下示例表明，所需的集群 LIF 已迁移到集群交换机 C2 上托管的相应集群端口：

[listing]
----
cluster::*> network interface show -role Cluster
       (network interface show)

         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0b      false
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0c      false
         n2_clus1   up/up       10.10.0.5/24   n2       e0b      false
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0c      false

8 entries were displayed.
----
====
. 关闭所有节点上连接到 CL1 的节点端口：
+
`network port modify`

+
.显示示例
[%collapsible]
====
以下示例展示了如何关闭节点 n1 和 n2 上的指定端口：

[listing]
----
cluster::*> network port modify -node n1 -port e0a -up-admin false
cluster::*> network port modify -node n1 -port e0d -up-admin false
cluster::*> network port modify -node n2 -port e0a -up-admin false
cluster::*> network port modify -node n2 -port e0d -up-admin false
----
====
. 关闭活动 3132Q-V 交换机 C2 上的 ISL 端口 24、31 和 32：
+
`shutdown`

+
.显示示例
[%collapsible]
====
以下示例展示了如何关闭活动 3132Q-V 交换机 C2 上的 ISL 24、31 和 32：

[listing]
----
C2# configure
C2(config)# interface ethernet 1/24/1-4
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# interface ethernet 1/31-32
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
C2#
----
====
. 拆下所有节点上连接到 CN1610 交换机 CL1 的电缆。
+
使用支持的布线，您必须将所有节点上断开的端口重新连接到 Nexus 3132Q-V 交换机 C1。

. 从 Nexus 3132Q-V C2 端口 e1/24 上移除 QSFP 电缆。
+
您必须使用支持的Cisco QSFP 光纤或直连电缆将 C1 上的 e1/31 和 e1/32 端口连接到 C2 上的 e1/31 和 e1/32 端口。

. 恢复端口 24 的配置，并通过复制以下内容删除 C2 上的临时端口通道 2： `running-configuration`文件到 `startup-configuration`文件。
+
.显示示例
[%collapsible]
====
以下示例复制了 `running-configuration`文件到 `startup-configuration`文件：

[listing]
----
C2# configure
C2(config)# no interface breakout module 1 port 24 map 10g-4x
C2(config)# no interface port-channel 2
C2(config-if)# interface e1/24
C2(config-if)# description 40GbE Node Port
C2(config-if)# spanning-tree port type edge
C2(config-if)# spanning-tree bpduguard enable
C2(config-if)# mtu 9216
C2(config-if-range)# exit
C2(config)# exit
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====
. 在 C2（活动的 3132Q-V 交换机）上启用 ISL 端口 31 和 32：
+
`no shutdown`

+
.显示示例
[%collapsible]
====
以下示例展示了如何在 3132Q-V 交换机 C2 上启动 ISL 31 和 32：

[listing]
----

C2# configure
C2(config)# interface ethernet 1/31-32
C2(config-if-range)# no shutdown
C2(config-if-range)# exit
C2(config)# exit
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====


.下一步是什么？
link:cn1610-complete-migration.html["完成迁移"]。
