---
permalink: switch-cisco-3132q-v/concept-migrate-a-cn1610-switch-to-a-cisco-nexus-3232c-cluster-switch.html 
sidebar: sidebar 
keywords: replace, cn1610 cluster switches, cisco nexus 3132q-v 
summary: 将 CN1610 集群交换机更换为 Cisco Nexus 3132Q-V 集群交换机时，您必须了解某些配置信息，端口连接和布线要求。 
---
= 将 CN1610 集群交换机更换为 Cisco Nexus 3132Q-V 集群交换机
:icons: font
:imagesdir: ../media/


[role="lead"]
将 CN1610 集群交换机更换为 Cisco Nexus 3132Q-V 集群交换机时，您必须了解某些配置信息，端口连接和布线要求。

* 支持以下集群交换机：
+
** NetApp CN1610
** Cisco Nexus 3132Q-V


* 集群交换机支持以下节点连接：
+
** NetApp CN1610 ：端口 0/1 到 0/12 （ 10 GbE ）
** Cisco Nexus 3132Q-V ：端口 E1/1-30 （ 40/100 GbE ）


* 集群交换机使用以下交换机间链路（ ISL ）端口：
+
** NetApp CN1610 ：端口 0/13 至 0/16 （ 10 GbE ）
** Cisco Nexus 3132Q-V ：端口 E1/31 至 32 （ 40/100 GbE ）


* _Nexus _ 包含有关支持的 Hardware Universe 3132Q-V 交换机布线的信息：
+
** 具有 10 GbE 集群连接的节点需要使用 QSFP 到 SFP+ 光纤分支电缆或 QSFP 到 SFP+ 铜分支电缆
** 具有 40/100 GbE 集群连接的节点需要支持的 QSFP/QSFP28 光纤模块以及光缆或 QSFP28 铜缆


* 相应的 ISL 布线如下所示：
+
** 开始：对于 CN1610 到 CN1610 （ SFP+ 到 SFP+ ），需要四根 SFP+ 光纤或铜缆直连缆线
** 过渡：对于 CN1610 到 Nexus 3132Q-V （ QSFP 到四个 SFP+ 分支），使用一根 QSFP 到 SFP+ 光纤或铜分支缆线
** 最终版本：对于 Nexus 3132Q-V 到 Nexus 3132Q-V （ QSFP28 到 QSFP28 ），请使用两根 QSFP28 光纤或铜缆直连缆线


* NetApp 双轴电缆与 Cisco Nexus 3132Q-V 交换机不兼容。
+
如果您当前的 CN1610 配置使用 NetApp 双轴电缆进行集群节点到交换机连接或 ISL 连接，并且您希望在环境中继续使用双轴电缆，则需要购买 Cisco 双轴电缆。或者，您也可以使用光缆进行 ISL 连接和集群节点到交换机连接。

* 在 Nexus 3132Q-V 交换机上，您可以将 QSFP/QSFP28 端口用作 40/100 Gb 以太网或 4 个 10 Gb 以太网模式。
+
默认情况下， 40/100 Gb 以太网模式下有 32 个端口。这些 40 Gb 以太网端口按 2 元组命名约定进行编号。例如，第二个 40 Gb 以太网端口编号为 1/2 。将配置从 40 Gb 以太网更改为 10 Gb 以太网的过程称为 _break_ ，将配置从 10 Gb 以太网更改为 40 Gb 以太网的过程称为 _breakin 。将 40/100 Gb 以太网端口拆分为 10 Gb 以太网端口时，生成的端口将使用三元组命名约定进行编号。例如，第二个 40 Gb 以太网端口的分支端口编号为 1/2/1 ， 1/2/2 ， 1/2/3 和 1/2/4 。

* Nexus 3132Q-V 交换机左侧是一组四个 SFP+ 端口，这些端口会多路传输到第一个 QSFP 端口。
+
默认情况下，参考配置文件（ RCF ）的结构使用第一个 QSFP 端口。

+
对于 Nexus 3132Q-V 交换机，您可以使用 `hardware profile Front portmode SFP+` 命令将四个 SFP+ 端口设为活动状态，而不是 QSFP 端口。同样，您也可以使用 `hardware profile Front portmode QSFP` 命令将 Nexus 3132Q-V 交换机重置为使用 QSFP 端口，而不是四个 SFP+ 端口。

+
[NOTE]
====
使用前四个 SFP+ 端口时，它将禁用第一个 40GbE QSFP 端口。

====
* 您必须已将 Nexus 3132Q-V 交换机上的某些端口配置为以 10 GbE 或 40/100 GbE 运行。
+
您可以使用 `interface breakout module 1 port 1-6 map 10g-4x` 命令将前六个端口细分为 4 个 10 GbE 模式。同样，您也可以使用 `no interface breakout module 1 port 1-6 map 10g-4x` 命令从 _break_ 配置对前六个 QSFP + 端口进行重新分组。

* 您必须已完成有关从节点到 Nexus 3132Q-V 集群交换机的 10 GbE 和 40/100 GbE 连接的规划，迁移和阅读所需文档。
* 此操作步骤 支持的 ONTAP 和 NX-OS 版本列在 "Cisco 以太网交换机 " 页面上。
+
http://support.netapp.com/NOW/download/software/cm_switches/["Cisco 以太网交换机"^]

* 此操作步骤 支持的 ONTAP 和 FastPath 版本列在 "NetApp CN1601 和 CN1610 交换机 " 页面上。
+
http://support.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 交换机"^]


