---
permalink: switch-cisco-3132q-v/concept-migrate-from-a-cisco-5596-switch-to-a-cisco-nexus-3232c.html 
sidebar: sidebar 
keywords: replace, cisco nexus 5596 cluster switch, 3132q-v 
summary: 在将 Cisco Nexus 5596 集群交换机更换为 Cisco Nexus 3132Q-V 集群交换机时，您必须了解某些配置信息，端口连接和布线要求。 
---
= 将 Cisco Nexus 5596 集群交换机更换为 Cisco Nexus 3132Q-V 集群交换机
:icons: font
:imagesdir: ../media/


[role="lead"]
在将 Cisco Nexus 5596 集群交换机更换为 Cisco Nexus 3132Q-V 集群交换机时，您必须了解某些配置信息，端口连接和布线要求。

* 支持以下集群交换机：
+
** Nexus 5596
** Nexus 3132Q-V


* 10 GbE 和 40/100 GbE 端口的数量在上提供的参考配置文件（ RCF ）中定义 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 集群网络交换机参考配置文件下载"^] 页面。
* 集群交换机使用以下端口连接到节点：
+
** 端口 E1/1-40 （ 10 GbE ）： Nexus 5596
** 端口 E1/1-30 （ 40/100 GbE ）： Nexus 3132Q-V


* 集群交换机使用以下交换机间链路（ ISL ）端口：
+
** 端口 E1/41-48 （ 10 GbE ）： Nexus 5596
** 端口 E1/31 至 32 （ 40/100 GbE ）： Nexus 3132Q-V


* _Nexus _ 包含有关支持的 Hardware Universe 3132Q-V 交换机布线的信息：
+
** 具有 10 GbE 集群连接的节点需要使用 QSFP 到 SFP+ 光纤分支电缆或 QSFP 到 SFP+ 铜分支电缆。
** 具有 40/100 GbE 集群连接的节点需要使用光缆或 QSFP28 铜缆支持的 QSFP/QSFP28 光纤模块。


* 集群交换机使用适当的 ISL 布线：
+
** 起始： Nexus 5596 到 Nexus 5596 （ SFP+ 到 SFP+ ）
+
*** 8 根 SFP+ 光纤或铜缆直连缆线


** 中间： Nexus 5596 到 Nexus 3132Q-V （ QSFP 到 4xSFP+ 细分）
+
*** 1 根 QSFP 到 SFP+ 光纤分出或铜缆分出缆线


** 最终结果： Nexus 3132Q-V 到 Nexus 3132Q-V （ QSFP28 到 QSFP28 ）
+
*** 2 根 QSFP28 光纤或铜缆直连缆线




* 在 Nexus 3132Q-V 交换机上，您可以将 QSFP/QSFP28 端口作为 40/100 千兆以太网模式或 4 个 10 千兆以太网模式运行。
+
默认情况下， 40/100 千兆以太网模式下有 32 个端口。这 40 个千兆以太网端口按照 2 元组命名约定进行编号。例如，第二个 40 千兆以太网端口编号为 1/2 。将配置从 40 千兆以太网更改为 10 千兆以太网的过程称为 _break_ ，将配置从 10 千兆以太网更改为 40 千兆以太网的过程称为 _breakin 。将 40/100 千兆以太网端口拆分为 10 千兆以太网端口时，生成的端口将使用三元组命名约定进行编号。例如，第二个 40 千兆以太网端口的分出端口编号为 1/2/1 ， 1/2/2 ， 1/2/3 和 1/2/4 。

* Nexus 3132Q-V 交换机左侧是一组 4 个 SFP+ 端口，这些端口会多路传输到该 QSFP28 端口。
+
默认情况下， RCF 的结构使用 QSFP28 端口。

+
[NOTE]
====
您可以使用 `hardware profile FRONT portmode sfp-plus` 命令使 Nexus 3132Q-V 交换机的 4 个 SFP+ 端口处于活动状态，而不是 QSFP 端口。同样，您也可以使用 `hardware profile Front portmode QSFP` 命令将 Nexus 3132Q-V 交换机重置为使用 QSFP 端口，而不是 4 个 SFP+ 端口。

====
* 您已将 Nexus 3132Q-V 交换机上的某些端口配置为以 10 GbE 或 40/100 GbE 运行。
+
[NOTE]
====
您可以使用 `interface breakout module 1 port 1-6 map 10g-4x` 命令将前六个端口细分为 4x10 GbE 模式。同样，您也可以使用 `no interface breakout module 1 port 1-6 map 10g-4x` 命令对分支配置中的前六个 QSFP + 端口进行重新分组。

====
* 您已经完成了从节点到 Nexus 3132Q-V 集群交换机的 10 GbE 和 40/100 GbE 连接的规划，迁移并阅读了相关文档。
* 此操作步骤中支持的 ONTAP 和 NX-OS 版本位于 _Cisco 以太网交换机 _ 页面上。
+
http://support.netapp.com/NOW/download/software/cm_switches/["Cisco 以太网交换机"^]


