---
permalink: switch-cisco-3132q-v/concept-migrate-from-a-two-node-switchless-cluster-to-a-cluster-with-cisco-nexus-3232c-cluster-switches.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, cisco nexus 3132q-v 
summary: 在使用 Cisco Nexus 3132Q-V 集群交换机迁移到双节点交换集群时，您必须了解某些配置信息，端口连接和布线要求。 
---
= 迁移到使用 Cisco Nexus 3132Q-V 集群交换机的双节点交换集群
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用 Cisco Nexus 3132Q-V 集群交换机迁移到双节点交换集群时，您必须了解某些配置信息，端口连接和布线要求。

* 10 GbE 和 40/100 GbE 端口的数量在上提供的参考配置文件（ RCF ）中定义 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 集群网络交换机参考配置文件下载"^] 页面。
* 集群交换机使用交换机间链路（ ISL ）端口 E1/31 至 32 。
* 。 link:https://hwu.netapp.com/["Hardware Universe"^] 包含有关支持的 Nexus 3132Q-V 交换机布线的信息：
+
** 具有 10 GbE 集群连接的节点需要使用分支光缆的 QSFP 光纤模块或 QSFP 到 SFP+ 铜缆的分支。
** 具有 40/100 GbE 集群连接的节点需要支持的 QSFP/QSFP28 光纤模块以及光缆或 QSFP28 铜缆。
** 集群交换机使用适当的 ISL 布线： 2 根 QSFP28 光纤或铜缆直连缆线。


* 在 Nexus 3132Q-V 上，您可以将 QSFP 端口作为 40/100 Gb 以太网或 4 个 10 Gb 以太网模式运行。
+
默认情况下， 40/100 Gb 以太网模式下有 32 个端口。这些 40 Gb 以太网端口按 2 元组命名约定进行编号。例如，第二个 40 Gb 以太网端口编号为 1/2 。将配置从 40 Gb 以太网更改为 10 Gb 以太网的过程称为 _break_ ，将配置从 10 Gb 以太网更改为 40 Gb 以太网的过程称为 _breakin 。将 40/100 Gb 以太网端口拆分为 10 Gb 以太网端口时，生成的端口将使用三元组命名约定进行编号。例如，第二个 40/100 Gb 以太网端口的分支端口编号为 1/2/1 ， 1/2/2 ， 1/2/3 ， 1/2/4 。

* Nexus 3132Q-V 的左侧是一组四个 SFP+ 端口，这些端口会多路传输到第一个 QSFP 端口。
+
默认情况下， RCF 的结构使用第一个 QSFP 端口。

+
您可以使用 `hardware profile FRONT portmode sfp-plus` 命令使 Nexus 3132Q-V 的四个 SFP+ 端口处于活动状态，而不是 QSFP 端口。同样，您也可以使用 `hardware profile Front portmode QSFP` 命令将 Nexus 3132Q-V 重置为使用 QSFP 端口，而不是四个 SFP+ 端口。

* 您必须已将 Nexus 3132Q-V 上的某些端口配置为以 10 GbE 或 40/100 GbE 运行。
+
您可以使用 `interface breakout module 1 port 1-6 map 10g-4x` 命令将前六个端口细分为 4x10 GbE 模式。同样，您也可以使用 `no interface breakout module 1 port 1-6 map 10g-4x` 命令对分支配置中的前六个 QSFP + 端口进行重新分组。

* 您必须已完成有关从节点到 Nexus 3132Q-V 集群交换机的 10 GbE 和 40/100 GbE 连接的规划，迁移和阅读所需文档。
+
。 link:http://mysupport.netapp.com/NOW/download/software/cm_switches/["Cisco 以太网交换机"^] 页面提供了有关此操作步骤 支持的 ONTAP 和 NX-OS 版本的信息。


