---
permalink: switch-cisco-3132q-v/index.html 
sidebar: sidebar 
keywords: Cisco, 3132Q-V 
summary: 迁移到双节点交换集群 
---
= 概述和要求：Cisco Nexus 3132Q-V交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
对于Cisco Nexus 3132Q-V交换机的安装和维护、请务必查看所有要求和建议的文档。



== 任务概述

您可以将 Cisco Nexus 3132Q-V 交换机用作 AFF 或 FAS 集群中的集群交换机。安装和维护任务包括：

* 在Cisco Nexus 3132Q-V集群交换机上安装NX-OS和参考配置文件(RCF)。
* 使用Cisco Nexus 3132Q-V集群交换机从双节点无交换机集群环境迁移到双节点有交换机环境。
* 更换集群中存在故障的Cisco Nexus 3132Q-V交换机、然后下载交换机操作系统和参考配置文件。
* 将Cisco Nexus 5596、Nexus 5020或Nexus 5010集群交换机更换为Cisco Nexus 3132Q-V交换机。
* 将NetApp CN1610交换机更换为Cisco Nexus 3132Q-V集群交换机。




== 配置要求

要配置集群，您需要为交换机配置适当数量和类型的缆线和缆线连接器。根据您最初配置的交换机类型，您需要使用随附的控制台缆线连接到交换机控制台端口；您还需要提供特定的网络信息。



== 网络要求

所有交换机配置都需要以下网络信息：

* 用于管理网络流量的IP子网。
* 每个存储系统控制器和所有适用交换机的主机名和IP地址。
* 大多数存储系统控制器通过 e0M 接口连接到以太网服务端口（扳手图标）进行管理。在 AFF A800 和 AFF A700 系统上， e0M 接口使用专用以太网端口。


请参见 https://hwu.netapp.com["Hardware Universe"^] 了解最新信息。



== 智能自动通报要求

智能自动通报功能可监控网络上的硬件和软件组件，以生成基于电子邮件的关键系统情况通知。当设备上发生事件时，智能自动通报会向目标配置文件中配置的所有收件人发出警报。

您必须将集群网络交换机配置为使用电子邮件与智能自动通报系统进行通信。您可以选择设置集群网络交换机，以利用 Cisco 的嵌入式智能自动通报支持功能。

在使用智能自动通报功能之前、请注意以下注意事项：

* 电子邮件服务器必须已就位。
* 交换机必须与电子邮件服务器建立 IP 连接。
* 必须配置联系人姓名（ SNMP 服务器联系人），电话号码和街道地址信息。要确定收到的消息的来源，必须执行此操作。
* CCO ID 必须与贵公司的相应 Cisco SMARTnet 服务合同相关联。
* 要注册设备，必须已安装 Cisco SMARTnet 服务。


。 http://www.cisco.com/c/en/us/products/switches/index.html["Cisco 支持站点"^] 包含有关用于配置智能自动通报的命令的信息。



== 文档要求

要设置3132Q-V交换机和ONTAP 集群、您需要特定的交换机和控制器文档。



=== 交换机文档

要设置Cisco Nexus 3132Q-V交换机、您需要中的以下文档 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Cisco Nexus 3000 系列交换机支持"^] 页面。

[cols="1,2"]
|===
| 文档标题 | Description 


 a| 
_Nexus 3000 系列硬件安装指南 _
 a| 
提供有关站点要求，交换机硬件详细信息和安装选项的详细信息。



 a| 
_Cisco Nexus 3000 系列交换机软件配置指南 _ （选择适用于交换机上安装的 NX-OS 版本的指南）
 a| 
提供为 ONTAP 操作配置交换机之前所需的初始交换机配置信息。



 a| 
_Cisco Nexus 3000 系列 NX-OS 软件升级和降级指南 _ （选择适用于交换机上安装的 NX-OS 版本的指南）
 a| 
提供有关如何根据需要将交换机降级为 ONTAP 支持的交换机软件的信息。



 a| 
_Cisco Nexus 3000 系列 NX-OS 命令参考主索引 _
 a| 
提供 Cisco 提供的各种命令参考的链接。



 a| 
_Cisco Nexus 3000 MIB 参考 _
 a| 
介绍 Nexus 3000 交换机的管理信息库（ Management Information Base ， MIB ）文件。



 a| 
_Nexus 3000 系列 NX-OS 系统消息参考 _
 a| 
介绍 Cisco Nexus 3000 系列交换机的系统消息，信息性消息以及可能有助于诊断链路，内部硬件或系统软件问题的其他消息。



 a| 
_Cisco Nexus 3000 系列 NX-OS 发行说明（为交换机上安装的 NX-OS 版本选择注释） _
 a| 
介绍 Cisco Nexus 3000 系列的功能，错误和限制。



 a| 
Cisco Nexus 6000 ， Cisco Nexus 5000 系列， Cisco Nexus 3000 系列和 Cisco Nexus 2000 系列的法规，合规性和安全信息
 a| 
提供 Nexus 3000 系列交换机的国际机构合规性，安全性和法定信息。

|===


=== ONTAP 系统文档

要设置 ONTAP 系统，您需要在中为您的操作系统版本提供以下文档 https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 文档中心"^]。

[cols="1,2"]
|===
| Name | Description 


 a| 
特定于控制器的安装和设置说明
 a| 
介绍如何安装 NetApp 硬件。



 a| 
ONTAP 文档
 a| 
提供有关 ONTAP 版本各个方面的详细信息。



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
提供 NetApp 硬件配置和兼容性信息。

|===


=== 导轨套件和机柜文档

要在NetApp机柜中安装3132Q-V Cisco交换机、请参见以下硬件文档。

[cols="1,2"]
|===
| Name | Description 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["42U 系统机柜，深度指南"^]
 a| 
介绍与 42U 系统机柜关联的 FRU ，并提供维护和 FRU 更换说明。



 a| 
link:task-install-a-cisco-nexus-3232c-cluster-switch-and-pass-through-panel-in-a-netapp-cabinet.html["在NetApp机柜中安装Cisco Nexus 3132Q-V交换机"^]
 a| 
介绍如何在四柱 NetApp 机柜中安装 Cisco Nexus 3132Q-V 交换机。

|===