---
permalink: switch-cisco-3132q-v/migrate-switchless-prepare-to-migrate.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: 准备从双节点无交换机集群迁移到 Cisco Nexus 3132Q-V 集群交换机。 
---
= 准备迁移到 Cisco Nexus 3132Q-V 集群交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 Cisco Nexus 3132Q-V 集群交换机将双节点无交换机集群迁移到有交换机集群做好准备。

.步骤
. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ 是维护窗口的持续时间，单位为小时。

+
[NOTE]
====
AutoSupport消息会通知技术支持此维护任务，以便在维护窗口期间抑制自动创建案例。

====
. 确定每个集群接口的管理或运行状态：
+
.. 显示网络端口属性：
+
`network port show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====
.. 显示有关逻辑接口的信息：
+
`network interface show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====


. 验证新的 3132Q-V 交换机上是否根据需要安装了适当的 RCF 和映像，并进行任何必要的站点自定义，例如用户和密码、网络地址等。
+
此时必须准备好两台交换机。如果您需要升级 RCF 和映像软件，则必须执行以下步骤：

+
.. 转到 NetApp 支持站点上的 link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco以太网交换机"^]。
.. 在该页面的表格中记下您的交换机和所需的软件版本。
.. 下载适当版本的 RCF。
.. 在*描述*页面上选择*继续*，接受许可协议，然后按照*下载*页面上的说明下载 RCF。
.. 下载合适版本的映像软件。


. 在*描述*页面上选择*继续*，接受许可协议，然后按照*下载*页面上的说明下载 RCF。


.下一步是什么？
在您准备好迁移交换机之后，您就可以link:migrate-switchless-configure-ports.html["配置端口"]了。
