---
permalink: switch-cisco-3132q-v/migrate-switchless-to-switched-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: 在配置Cisco Nexus 3132q-v 交换机之前，请先查看流程概述和命名规则。 
---
= 迁移要求
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
如果您有一个双节点无交换机集群，请查看此过程，了解迁移到双节点交换集群的适用要求。

[NOTE]
====
该过程需要同时使用ONTAP命令和Cisco Nexus 3000 系列交换机命令；除非另有说明，否则使用ONTAP命令。

====
有关详细信息，请参阅：For more information, see:

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 和 CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco以太网交换机"^]
* link:http://hwu.netapp.com["Hardware Universe"^]


.端口和节点连接
当您迁移到使用Cisco Nexus 3132Q-V 集群交换机的双节点交换集群时，请务必了解端口和节点连接以及布线要求。

* 集群交换机使用交换机间链路 (ISL) 端口 e1/31-32。
* 这link:https://hwu.netapp.com/["Hardware Universe"^]包含有关 Nexus 3132Q-V 交换机支持的布线信息：
+
** 具有 10 GbE 集群连接的节点需要 QSFP 光模块和分支光纤电缆或 QSFP 转 SFP+ 铜缆分支电缆。
** 具有 40 GbE 集群连接的节点需要支持 QSFP/QSFP28 光模块，并配备光纤电缆或 QSFP/QSFP28 铜缆直连电缆。
** 集群交换机使用合适的 ISL 布线：2x QSFP28 光纤或铜缆直连电缆。


* 在 Nexus 3132Q-V 上，您可以将 QSFP 端口用作 40 Gb 以太网或 4x10 Gb 以太网模式。
+
默认情况下，40Gb以太网模式下有32个端口。这些 40 Gb 以太网端口采用二元组命名规则进行编号。例如，第二个 40 Gb 以太网端口编号为 1/2。将配置从 40 Gb 以太网更改为 10 Gb 以太网的过程称为 _breakout_，将配置从 10 Gb 以太网更改为 40 Gb 以太网的过程称为 _breakin_。当您将 40 Gb 以太网端口拆分为 10 Gb 以太网端口时，生成的端口将使用三元组命名约定进行编号。例如，第二个 40 Gb 以太网端口的分线端口编号为 1/2/1、1/2/2、1/2/3 和 1/2/4。

* Nexus 3132Q-V 的左侧有一组四个 SFP+ 端口，复用到第一个 QSFP 端口。
+
默认情况下，RCF 结构为使用第一个 QSFP 端口。

+
您可以使用以下方法将 Nexus 3132Q-V 的四个 SFP+ 端口设置为活动状态，而不是一个 QSFP 端口： `hardware profile front portmode sfp-plus`命令。同样，您可以使用以下方法将 Nexus 3132Q-V 重置为使用 QSFP 端口而不是四个 SFP+ 端口： `hardware profile front portmode qsfp`命令。

* 请确保已将 Nexus 3132Q-V 上的某些端口配置为以 10 GbE 或 40 GbE 运行。
+
您可以使用以下方法将前六个端口分接成 4x10 GbE 模式： `interface breakout module 1 port 1-6 map 10g-4x`命令。同样，您可以使用以下方法将前六个 QSFP+ 端口从分支配置中重新分组： `no interface breakout module 1 port 1-6 map 10g-4x`命令。

* 10 GbE 和 40 GbE 端口的数量在参考配置文件 (RCF) 中定义，这些文件可在以下位置获取：link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco集群网络交换机参考配置文件下载"^] 。


.开始之前
* 配置已正确设置并正常运行。
* 运行ONTAP 9.4 或更高版本的节点。
* 集群中的所有端口 `up`状态。
* 支持Cisco Nexus 3132Q-V 集群交换机。
* 现有集群网络配置具有：
+
** Nexus 3132 集群基础设施在两个交换机上都是冗余的，并且功能齐全。
** 交换机上已安装最新的 RCF 和 NX-OS 版本。
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco以太网交换机"^]包含有关此过程中支持的ONTAP和 NX-OS 版本的信息。

** 两台交换机均具备管理连接功能。
** 可通过控制台访问两台交换机。
** 集群中的所有逻辑接口（LIF） `up`未迁移的状态。
** 交换机的初始定制。
** 所有ISL端口均已启用并连接线缆。




此外，您还必须规划、迁移并阅读有关从节点到 Nexus 3132Q-V 集群交换机的 10 GbE 和 40 GbE 连接的必要文档。

.关于所使用的示例
本流程中的示例使用以下开关和节点命名规则：

* Nexus 3132Q-V 集群交换机，C1 和 C2。
* 节点分别为 n1 和 n2。


[NOTE]
====
本流程中的示例使用两个节点，每个节点使用两个 40 GbE 集群互连端口 *e4a* 和 *e4e*。这link:https://hwu.netapp.com/["Hardware Universe"^]包含有关您平台上集群端口的详细信息。

====
本流程涵盖以下几种情况：

* *n1_clus1* 是连接到集群交换机 C1 的第一个集群逻辑接口 (LIF)，用于节点 *n1*。
* *n1_clus2* 是第一个连接到集群交换机 C2 的集群 LIF，用于节点 *n1*。
* *n2_clus1* 是第一个连接到集群交换机 C1 的集群 LIF，用于节点 *n2*。
* *n2_clus2* 是第二个要连接到集群交换机 C2 的集群 LIF，用于节点 *n2*。
* 10 GbE 和 40 GbE 端口的数量在参考配置文件 (RCF) 中定义，这些文件可在以下位置获取：link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco集群网络交换机参考配置文件下载"^] 。


[NOTE]
====
该过程需要同时使用ONTAP命令和Cisco Nexus 3000 系列交换机命令；除非另有说明，否则使用ONTAP命令。

====
* 集群由两个连接并运行的节点组成，采用双节点无交换机集群设置。
* 第一个集群端口移至 C1。
* 第二个集群端口已移至 C2。
* 双节点无交换机集群选项已禁用。


.下一步是什么？
在您查看完迁移要求后，您可以link:migrate-switchless-prepare-to-migrate.html["准备迁移交换机"]。
