---
permalink: switch-cisco-3132q-v/migrate-switchless-to-switched-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: 在配置Cisco Nexus 3132q-v交换机之前、请查看此过程和术语的概述。 
---
= 迁移要求
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
如果您使用的是双节点无交换机集群、请查看此过程以了解迁移到双节点有交换机集群的适用要求。

[NOTE]
====
操作步骤 要求同时使用 ONTAP 命令和 Cisco Nexus 3000 系列交换机命令；除非另有说明，否则使用 ONTAP 命令。

====
有关详细信息，请参见

* http://support.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 问题描述 页面"^]
* http://support.netapp.com/NOW/download/software/cm_switches/["Cisco 以太网交换机问题描述 页面"^]
* http://hwu.netapp.com["Hardware Universe"^]


.端口和节点连接
在使用Cisco Nexus 3132Q-V集群交换机迁移到双节点交换集群时、请确保了解端口和节点连接以及布线要求。

* 集群交换机使用交换机间链路（ ISL ）端口 E1/31 至 32 。
* 。 link:https://hwu.netapp.com/["Hardware Universe"^] 包含有关支持的 Nexus 3132Q-V 交换机布线的信息：
+
** 具有 10 GbE 集群连接的节点需要使用分支光缆的 QSFP 光纤模块或 QSFP 到 SFP+ 铜缆的分支。
** 具有40 GbE集群连接的节点需要使用受支持的QSFP/QSFP28光纤模块以及光缆或QSFP/QSFP28铜质直连缆线。
** 集群交换机使用适当的 ISL 布线： 2 根 QSFP28 光纤或铜缆直连缆线。


* 在Nexus 3132Q-V上、您可以将QSFPs"端口作为40 Gb以太网或4x10 Gb以太网模式运行。
+
默认情况下、40 Gb以太网模式下有32个端口。这些 40 Gb 以太网端口按 2 元组命名约定进行编号。例如，第二个 40 Gb 以太网端口编号为 1/2 。将配置从 40 Gb 以太网更改为 10 Gb 以太网的过程称为 _break_ ，将配置从 10 Gb 以太网更改为 40 Gb 以太网的过程称为 _breakin 。当您将40 Gb以太网端口划分为10 Gb以太网端口时、将使用三元组命名约定对生成的端口进行编号。例如，第二个 40 Gb 以太网端口的分支端口编号为 1/2/1 ， 1/2/2 ， 1/2/3 和 1/2/4 。

* Nexus 3132Q-V 的左侧是一组四个 SFP+ 端口，这些端口会多路传输到第一个 QSFP 端口。
+
默认情况下， RCF 的结构使用第一个 QSFP 端口。

+
您可以使用 `hardware profile FRONT portmode sfp-plus` 命令使 Nexus 3132Q-V 的四个 SFP+ 端口处于活动状态，而不是 QSFP 端口。同样，您也可以使用 `hardware profile Front portmode QSFP` 命令将 Nexus 3132Q-V 重置为使用 QSFP 端口，而不是四个 SFP+ 端口。

* 确保已将Nexus 3132Q-V上的某些端口配置为以10 GbE或40 GbE运行。
+
您可以使用 `interface breakout module 1 port 1-6 map 10g-4x` 命令将前六个端口细分为 4x10 GbE 模式。同样，您也可以使用 `no interface breakout module 1 port 1-6 map 10g-4x` 命令对分支配置中的前六个 QSFP + 端口进行重新分组。

* 10 GbE和40 GbE端口的数量在页面上提供的参考配置文件(Reference Configuration Files、RCF)中定义 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 集群网络交换机参考配置文件下载"^]。


.开始之前
* 配置已正确设置并正常运行。
* 运行ONTAP 9.4或更高版本的节点。
* 中的所有集群端口 `up` 状态。
* 支持 Cisco Nexus 3132Q-V 集群交换机。
* 现有集群网络配置具有：
+
** Nexus 3132 集群基础架构在两台交换机上均为冗余且功能完备。
** 交换机上的最新 RCF 和 NX-OS 版本。
+
。 link:http://mysupport.netapp.com/NOW/download/software/cm_switches/["Cisco 以太网交换机"^] 页面提供了有关此操作步骤 支持的 ONTAP 和 NX-OS 版本的信息。

** 两台交换机上的管理连接。
** 对两个交换机的控制台访问。
** 所有处于 `up` 状态的集群逻辑接口（ LIF ）均未迁移。
** 交换机的初始自定义。
** 所有 ISL 端口均已启用并已布线。




此外、您还必须规划、迁移和阅读有关从节点到Nexus 3132Q-V集群交换机的10 GbE和40 GbE连接的必要文档。

.关于所用示例
此操作步骤中的示例使用以下交换机和节点命名：

* Nexus 3132Q-V 集群交换机， C1 和 C2 。
* 节点为 n1 和 n2 。


[NOTE]
====
此过程中的示例使用两个节点、每个节点使用两个40 GbE集群互连端口* e4A*和* e4e*。link:https://hwu.netapp.com/["Hardware Universe"^]提供了有关您的平台上的集群端口的详细信息。

====
此操作步骤 包括以下情形：

* *n1_clus1*是第一个连接到节点*n1*的集群交换机C1的集群逻辑接口(LIF)。
* *n1_clus2*是第一个连接到节点*n1*的集群交换机C2的集群LIF。
* *n2_clus1*是第一个连接到节点*n2*的集群交换机C1的集群LIF。
* *n2_clus2*是连接到节点*n2*的集群交换机C2的第二个集群LIF。
* 10 GbE和40 GbE端口的数量在页面上提供的参考配置文件(Reference Configuration Files、RCF)中定义 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 集群网络交换机参考配置文件下载"^]。


[NOTE]
====
操作步骤 要求同时使用 ONTAP 命令和 Cisco Nexus 3000 系列交换机命令；除非另有说明，否则使用 ONTAP 命令。

====
* 集群首先连接两个节点，并在双节点无交换机集群设置下运行。
* 第一个集群端口将移至C1。
* 第二个集群端口将移至C2。
* 已禁用双节点无交换机集群选项。


.下一步是什么？
link:migrate-switchless-prepare-to-migrate.html["准备迁移"](英文)
