---
permalink: switch-cisco-3132q-v/prepare-install-cisco-nexus-3132q.html 
sidebar: sidebar 
keywords: install, nx-os software, rcfs, cisco nexus 3132q-v, cluster switches 
summary: Cisco Nexus 3132Q-V 集群交换机上必须安装 Cisco NX-OS 软件和参考配置文件（ RCF ）。 
---
= 准备安装NX-OS软件和参考配置文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在安装NX-OS软件和参考配置文件(Reference Configuration File、RCF)之前、请遵循此操作步骤。

.关于示例
此操作步骤中的示例使用两个节点。这些节点使用两个 10GbE 集群互连端口 `e0a` 和 `e0b` 。

请参见 link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] 验证平台上的集群端口是否正确。


NOTE: 根据不同版本的 ONTAP ，命令输出可能会有所不同。

此操作步骤中的示例使用以下交换机和节点命名：

* 这两台 Cisco 交换机的名称分别为 `CS1` 和 `CS2` 。
* 节点名称为 `cluster1-01` 和 `cluster1-02` 。
* 集群 LIF 名称为 `cluster1-01_clus1` 和 `cluster1-01_clus2` （对于 cluster1-01 ）和 `cluster1-02_clus1` 和 `cluster1-02_clus2` （对于 cluster1-02 ）。
* `cluster1 ：：： * >` 提示符指示集群的名称。


.关于此任务
操作步骤 要求同时使用 ONTAP 命令和 Cisco Nexus 3000 系列交换机命令；除非另有说明，否则使用 ONTAP 命令。

.步骤
. 如果在此集群上启用了 AutoSupport ，则通过调用 AutoSupport 消息禁止自动创建案例：
+
`ssystem node AutoSupport invoke -node * -type all -message MAINT=xh`

+
其中 _x_ 是维护时段的持续时间，以小时为单位。

+

NOTE: AutoSupport 消息会通知技术支持此维护任务，以便在维护窗口期间禁止自动创建案例。

. 将权限级别更改为高级，在系统提示您继续时输入 * y * ：
+
`set -privilege advanced`

+
此时将显示高级提示符（` * >` ）。

. 显示每个集群互连交换机的每个节点中配置的集群互连接口数量：
+
`network device-discovery show -protocol cdp`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/cdp
            e0a    cs1                       Eth1/2            N3K-C3132Q-V
            e0b    cs2                       Eth1/2            N3K-C3132Q-V
cluster1-01/cdp
            e0a    cs1                       Eth1/1            N3K-C3132Q-V
            e0b    cs2                       Eth1/1            N3K-C3132Q-V
----
====
. 检查每个集群接口的管理或运行状态。
+
.. 显示网络端口属性：
+
`network port show – IP 空间集群`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: cluster1-02
                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: cluster1-01
                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy
----
====
.. 显示有关 LIF 的信息：
+
`network interface show -vserver cluster`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical            Status     Network            Current       Current Is
Vserver     Interface          Admin/Oper Address/Mask       Node          Port    Home
----------- ------------------ ---------- ------------------ ------------- ------- ----
Cluster
            cluster1-01_clus1  up/up      169.254.209.69/16  cluster1-01   e0a     true
            cluster1-01_clus2  up/up      169.254.49.125/16  cluster1-01   e0b     true
            cluster1-02_clus1  up/up      169.254.47.194/16  cluster1-02   e0a     true
            cluster1-02_clus2  up/up      169.254.19.183/16  cluster1-02   e0b     true
----
====


. 验证远程集群接口的连接：


[role="tabbed-block"]
====
.ONTAP 9.9.1及更高版本
--
您可以使用 `network interface check cluster-connectivity` 命令启动集群连接的可访问性检查、然后显示详细信息：

`network interface check cluster-connectivity start` 和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注：*请等待几秒钟、然后再运行show命令显示详细信息。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source              Destination         Packet
Node   Date                       LIF                 LIF                 Loss
------ -------------------------- ------------------- ------------------- -----------
cluster1-01
       3/5/2022 19:21:18 -06:00   cluster1-01_clus2   cluster1-02_clus1   none
       3/5/2022 19:21:20 -06:00   cluster1-01_clus2   cluster1-02_clus2   none

cluster1-02
       3/5/2022 19:21:18 -06:00   cluster1-02_clus2   cluster1-01_clus1   none
       3/5/2022 19:21:20 -06:00   cluster1-02_clus2   cluster1-01_clus2   none
----
--
.所有ONTAP版本
--
对于所有ONTAP版本、您还可以使用 `cluster ping-cluster -node <name>` 用于检查连接的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is cluster1-02
Getting addresses from network interface table...
Cluster cluster1-01_clus1 169.254.209.69 cluster1-01     e0a
Cluster cluster1-01_clus2 169.254.49.125 cluster1-01     e0b
Cluster cluster1-02_clus1 169.254.47.194 cluster1-02     e0a
Cluster cluster1-02_clus2 169.254.19.183 cluster1-02     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[STEP6]]验证是否 `auto-revert`已在所有集群Lifs上启用命令：
+
`network interface show - vserver cluster -fields auto-revert`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*

          Logical
Vserver   Interface           Auto-revert
--------- ------------------- ------------
Cluster
          cluster1-01_clus1   true
          cluster1-01_clus2   true
          cluster1-02_clus1   true
          cluster1-02_clus2   true
----
====


.下一步是什么？
link:install-nx-os-software-3132q-v.html["安装NX-OS软件"]。
