---
permalink: switch-cisco-3132q-v/replace-cisco-nexus-3132q-v.html 
sidebar: sidebar 
keywords: replace, cisco nexus 3132q-v cluster switches 
summary: 更换集群网络中有故障的 Cisco Nexus 3132Q-V 交换机是一种无中断操作步骤 （ NDO ），您必须执行一系列特定的任务。 
---
= 更换 Cisco Nexus 3132Q-V 集群交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照此操作步骤 更换集群网络中有故障的Cisco Nexus 3132Q-V交换机。替代操作步骤 是无中断操作步骤 (NDO)。



== 查看要求

.交换机要求
查看 link:switch-requirements.html["更换Cisco Nexus 3132Q-V集群交换机的要求"]。

.您需要的内容
* 现有集群和网络配置具有：
+
** Nexus 3132Q-V集群基础架构在两台交换机上均为冗余基础架构、并可完全正常运行。
+
。 link:http://support.netapp.com/NOW/download/software/cm_switches/["Cisco 以太网交换机"^] 页面提供了交换机上最新的 RCF 和 NX-OS 版本。

** 所有集群端口均位于中 `up` 状态。
** 这两台交换机上都存在管理连接。
** 所有集群逻辑接口(LIF)均位于中 `up` 状态并已迁移。


* 对于Nexus 3132Q-V更换交换机、请确保：
+
** 替代交换机上的管理网络连接正常工作。
** 可以通过控制台访问替代交换机。
** 所需的RCF和NX-OS操作系统映像交换机将加载到此交换机上。
** 交换机的初始自定义已完成。


* http://hwu.netapp.com["Hardware Universe"^]




== 启用控制台日志记录

NetApp强烈建议您在使用的设备上启用控制台日志记录、并在更换交换机时采取以下措施：

* 在维护期间保持AutoSupport处于启用状态。
* 在维护前后触发维护AutoSupport、以便在维护期间禁用案例创建。请参见此知识库文章 https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92：如何禁止在计划维护时段自动创建案例"^] 了解更多详细信息。
* 为所有命令行界面会话启用会话日志记录。有关如何启用会话日志记录的说明、请查看此知识库文章中的"记录会话输出"一节 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["如何配置PuTTY以优化与ONTAP系统的连接"^]。




== 更换交换机

此操作步骤 将第二个 Nexus 3132Q-V 集群交换机 CL2 替换为新的 3132Q-V 交换机 C2 。

.关于示例
此操作步骤中的示例使用以下交换机和节点命名：

* N1_clus1 是连接到节点 n1 的集群交换机 C1 的第一个集群逻辑接口（ LIF ）。
* N1_clus2 是连接到节点 n1 的集群交换机 CL2 或 C2 的第一个集群 LIF 。
* n1_clus3 是连接到节点 n1 的集群交换机 C2 的第二个 LIF 。
* n1_clus4 是连接到节点 n1 的集群交换机 CL1 的第二个 LIF 。
* 10 GbE和40 GbE端口的数量在页面上提供的参考配置文件(Reference Configuration Files、RCF)中定义link:https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 集群网络交换机参考配置文件下载"^]。
* 节点为 n1 ， n2 ， n3 和 n4 。—此操作步骤 中的示例使用四个节点：两个节点使用四个 10 GB 集群互连端口： e0a ， e0b ， e0c 和 e0d 。其他两个节点使用两个 40 Gb 集群互连端口： E4A 和 e4e 。请参见 link:https://hwu.netapp.com/["Hardware Universe"^] 用于您平台上的实际集群端口。


.关于此任务
此操作步骤包括以下情形：

* 集群开始时，四个节点连接到两个 Nexus 3132Q-V 集群交换机 CL1 和 CL2 。
* 集群交换机CL2将替换为C2
+
** 在每个节点上，连接到 CL2 的集群 LIF 会迁移到连接到 CL1 的集群端口。
** 断开 CL2 上所有端口的布线，然后重新连接到替代交换机 C2 上的相同端口。
** 在每个节点上，其迁移的集群 LIF 都会进行还原。






=== 第1步：准备更换

. 如果在此集群上启用了 AutoSupport ，则通过调用 AutoSupport 消息禁止自动创建案例：
+
`ssystem node AutoSupport invoke -node * -type all - 消息 MAINT=xh`

+
_x_ 是维护时段的持续时间，以小时为单位。

+
[NOTE]
====
AutoSupport 消息会通知技术支持此维护任务，以便在维护窗口期间禁止自动创建案例。

====
. 显示有关配置中设备的信息：
+
`network device-discovery show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface         Platform
----------- ------ ------------------- ----------------  ----------------
n1         /cdp
            e0a    CL1                 Ethernet1/1/1    N3K-C3132Q-V
            e0b    CL2                 Ethernet1/1/1    N3K-C3132Q-V
            e0c    CL2                 Ethernet1/1/2    N3K-C3132Q-V
            e0d    CL1                 Ethernet1/1/2    N3K-C3132Q-V
n2         /cdp
            e0a    CL1                 Ethernet1/1/3    N3K-C3132Q-V
            e0b    CL2                 Ethernet1/1/3    N3K-C3132Q-V
            e0c    CL2                 Ethernet1/1/4    N3K-C3132Q-V
            e0d    CL1                 Ethernet1/1/4    N3K-C3132Q-V
n3         /cdp
            e4a    CL1                 Ethernet1/7      N3K-C3132Q-V
            e4e    CL2                 Ethernet1/7      N3K-C3132Q-V
n4         /cdp
            e4a    CL1                 Ethernet1/8      N3K-C3132Q-V
            e4e    CL2                 Ethernet1/8      N3K-C3132Q-V

12 entries were displayed
----
====
. 确定每个集群接口的管理或运行状态：
+
.. 显示网络端口属性：
+
`network port show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster
       (network port show)

Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
12 entries were displayed.
----
====
.. 显示有关逻辑接口的信息：
+
`network interface show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
       (network interface show)

             Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e0a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e0e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e0a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e0e     true

12 entries were displayed.
----
====
.. 显示有关已发现的集群交换机的信息：
+
`ssystem cluster-switch show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                          cluster-network   10.10.1.101      NX3132V
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

CL2                          cluster-network   10.10.1.102      NX3132V
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

2 entries were displayed.
----
====


. 根据您的需要，验证是否在新的 Nexus 3132Q-V 交换机上安装了适当的 RCF 和映像，并进行任何必要的站点自定义。
+
此时，您必须准备更换交换机。如果需要升级 RCF 和映像，必须执行以下步骤：

+
.. 在 NetApp 支持站点上，转至 link:http://support.netapp.com/NOW/download/software/cm_switches/["Cisco 以太网交换机"^] 页面。
.. 请记下该页面上的表中的交换机和所需的软件版本。
.. 下载适当版本的 RCF 。
.. 单击 * RCF* 页面上的 * 继续 * ，接受许可协议，然后按照 * 下载 * 页面上的说明下载问题描述 。
.. 下载相应版本的映像软件。


. 迁移与连接到交换机 C2 的集群端口关联的 LIF ：
+
`网络接口迁移`

+
.显示示例
[%collapsible]
====
此示例显示 LIF 迁移已在所有节点上完成：

[listing]
----

cluster::*> network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1 –destination-node n1 -destination-port e0a
cluster::*> network interface migrate -vserver Cluster -lif n1_clus3 -source-node n1 –destination-node n1 -destination-port e0d
cluster::*> network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2 –destination-node n2 -destination-port e0a
cluster::*> network interface migrate -vserver Cluster -lif n2_clus3 -source-node n2 –destination-node n2 -destination-port e0d
cluster::*> network interface migrate -vserver Cluster -lif n3_clus2 -source-node n3 –destination-node n3 -destination-port e4a
cluster::*> network interface migrate -vserver Cluster -lif n4_clus2 -source-node n4 –destination-node n4 -destination-port e4a
----
====
. 验证集群的运行状况：
+
`network interface show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
       (network interface show)

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0a     false
            n1_clus3   up/up      10.10.0.3/24       n1            e0d     false
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0a     false
            n2_clus3   up/up      10.10.0.7/24       n2            e0d     false
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4a     false
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4a     false
12 entries were displayed.
----
====
. 关闭物理连接到交换机 CL2 的集群互连端口：
+
`network port modify`

+
.显示示例
[%collapsible]
====
此示例显示了所有节点上正在关闭的指定端口：

[listing]
----
cluster::*> network port modify -node n1 -port e0b -up-admin false
cluster::*> network port modify -node n1 -port e0c -up-admin false
cluster::*> network port modify -node n2 -port e0b -up-admin false
cluster::*> network port modify -node n2 -port e0c -up-admin false
cluster::*> network port modify -node n3 -port e4e -up-admin false
cluster::*> network port modify -node n4 -port e4e -up-admin false
----
====
. 验证远程集群接口的连接：


[role="tabbed-block"]
====
.ONTAP 9.9.1及更高版本
--
您可以使用 `network interface check cluster-connectivity` 命令启动集群连接的可访问性检查、然后显示详细信息：

`network interface check cluster-connectivity start` 和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注：*请等待几秒钟、然后再运行show命令显示详细信息。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source     Destination   Packet
Node   Date                       LIF        LIF           Loss
------ -------------------------- ---------- ------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2   n2_clus1      none
       3/5/2022 19:21:20 -06:00   n1_clus2   n2_clus2      none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2   n1_clus1      none
       3/5/2022 19:21:20 -06:00   n2_clus2   n1_clus2      none
n3
...
...
n4
...
...
----
--
.所有ONTAP版本
--
对于所有ONTAP版本、您还可以使用 `cluster ping-cluster -node <name>` 用于检查连接的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster::*> cluster ping-cluster -node n1
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e0a	10.10.0.1
Cluster n1_clus2 n1		e0b	10.10.0.2
Cluster n1_clus3 n1		e0c	10.10.0.3
Cluster n1_clus4 n1		e0d	10.10.0.4
Cluster n2_clus1 n2		e0a	10.10.0.5
Cluster n2_clus2 n2		e0b	10.10.0.6
Cluster n2_clus3 n2		e0c	10.10.0.7
Cluster n2_clus4 n2		e0d	10.10.0.8
Cluster n3_clus1 n4		e0a	10.10.0.9
Cluster n3_clus2 n3		e0e	10.10.0.10
Cluster n4_clus1 n4		e0a	10.10.0.11
Cluster n4_clus2 n4		e0e	10.10.0.12

Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8 10.10.0.9 10.10.0.10 10.10.0.11 10.10.0.12
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 32 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.1 to Remote 10.10.0.9
    Local 10.10.0.1 to Remote 10.10.0.10
    Local 10.10.0.1 to Remote 10.10.0.11
    Local 10.10.0.1 to Remote 10.10.0.12
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.9
    Local 10.10.0.2 to Remote 10.10.0.10
    Local 10.10.0.2 to Remote 10.10.0.11
    Local 10.10.0.2 to Remote 10.10.0.12
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.9
    Local 10.10.0.3 to Remote 10.10.0.10
    Local 10.10.0.3 to Remote 10.10.0.11
    Local 10.10.0.3 to Remote 10.10.0.12
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.9
    Local 10.10.0.4 to Remote 10.10.0.10
    Local 10.10.0.4 to Remote 10.10.0.11
    Local 10.10.0.4 to Remote 10.10.0.12

Larger than PMTU communication succeeds on 32 path(s)
RPC status:
8 paths up, 0 paths down (tcp check)
8 paths up, 0 paths down (udp check)
----
--
====
. [[Step9]]关闭CL1上的端口1/31和1/32以及活动Nexus 3132Q-V交换机：
+
`s下行`

+
.显示示例
[%collapsible]
====
此示例显示了交换机 CL1 上正在关闭的 ISL 端口 1/31 和 1/32 ：

[listing]
----
(CL1)# configure
(CL1)(Config)# interface e1/31-32
(CL1)(config-if-range)# shutdown
(CL1)(config-if-range)# exit
(CL1)(Config)# exit
(CL1)#
----
====




=== 第2步：配置端口

. 拔下连接到 Nexus 3132Q-V 交换机 CL2 的所有缆线，然后将其重新连接到所有节点上的替代交换机 C2 。
. 从 CL2 上的端口 E1/31 和 E1/32 拔下 ISL 缆线，然后将其重新连接到替代交换机 C2 上的相同端口。
. 启动Nexus 3132Q-V交换机CL1上的ISL端口1/31和1/32：
+
[listing]
----
(CL1)# configure
(CL1)(Config)# interface e1/31-32
(CL1)(config-if-range)# no shutdown
(CL1)(config-if-range)# exit
(CL1)(Config)# exit
(CL1)#
----
. 验证 ISL 在 CL1 上是否已启动：
+
`s如何使用端口通道`

+
端口 Eth1/31 和 Eth1/32 应指示 ` （ P ）` ，这意味着 ISL 端口在端口通道中已启动。

+
.显示示例
[%collapsible]
====
[listing]
----
CL1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member 						Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. 验证 C2 上的 ISL 是否已启动：
+
`s如何执行端口通道摘要`

+
端口 Eth1/31 和 Eth1/32 应指示 ` （ P ）` ，这意味着端口通道中的两个 ISL 端口均已启动。

+
.显示示例
[%collapsible]
====
[listing]
----
C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. 在所有节点上、启动连接到Nexus 3132Q-V交换机C2的所有集群互连端口：
+
`network port modify`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node n1 -port e0b -up-admin true
cluster::*> network port modify -node n1 -port e0c -up-admin true
cluster::*> network port modify -node n2 -port e0b -up-admin true
cluster::*> network port modify -node n2 -port e0c -up-admin true
cluster::*> network port modify -node n3 -port e4e -up-admin true
cluster::*> network port modify -node n4 -port e4e -up-admin true
----
====
. 对于所有节点，还原所有迁移的集群互连 LIF ：
+
`网络接口还原`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n1_clus3
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus3
Cluster::*> network interface revert –vserver Cluster –lif n3_clus2
Cluster::*> network interface revert –vserver Cluster –lif n4_clus2
----
====
. 验证集群互连端口现在是否已还原到其主端口：
+
`network interface show`

+
.显示示例
[%collapsible]
====
此示例显示所有 LIF 均已成功还原，因为 `Current Port` 列下列出的端口在 `is Home` 列中的状态为 `true` 。如果 `为主页` 列值为 `false` ，则表示尚未还原 LIF 。

[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4e     true
12 entries were displayed.
----
====
. 验证集群端口是否已连接：
+
`network port show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
12 entries were displayed.
----
====
. 验证远程集群接口的连接：


[role="tabbed-block"]
====
.ONTAP 9.9.1及更高版本
--
您可以使用 `network interface check cluster-connectivity` 命令启动集群连接的可访问性检查、然后显示详细信息：

`network interface check cluster-connectivity start` 和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注：*请等待几秒钟、然后再运行show命令显示详细信息。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source     Destination   Packet
Node   Date                       LIF        LIF           Loss
------ -------------------------- ---------- ------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2   n2_clus1      none
       3/5/2022 19:21:20 -06:00   n1_clus2   n2_clus2      none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2   n1_clus1      none
       3/5/2022 19:21:20 -06:00   n2_clus2   n1_clus2      none
n3
...
...
n4
...
...
----
--
.所有ONTAP版本
--
对于所有ONTAP版本、您还可以使用 `cluster ping-cluster -node <name>` 用于检查连接的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster::*> cluster ping-cluster -node n1
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e0a	10.10.0.1
Cluster n1_clus2 n1		e0b	10.10.0.2
Cluster n2_clus1 n2		e0a	10.10.0.5
Cluster n2_clus2 n2		e0b	10.10.0.6
Cluster n2_clus3 n2		e0c	10.10.0.7
Cluster n2_clus4 n2		e0d	10.10.0.8
Cluster n3_clus1 n3		e0a	10.10.0.9
Cluster n3_clus2 n3		e0e	10.10.0.10
Cluster n4_clus1 n4		e0a	10.10.0.11
Cluster n4_clus2 n4		e0e	10.10.0.12

Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8 10.10.0.9 10.10.0.10 10.10.0.11 10.10.0.12
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 32 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.1 to Remote 10.10.0.9
    Local 10.10.0.1 to Remote 10.10.0.10
    Local 10.10.0.1 to Remote 10.10.0.11
    Local 10.10.0.1 to Remote 10.10.0.12
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.9
    Local 10.10.0.2 to Remote 10.10.0.10
    Local 10.10.0.2 to Remote 10.10.0.11
    Local 10.10.0.2 to Remote 10.10.0.12
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.9
    Local 10.10.0.3 to Remote 10.10.0.10
    Local 10.10.0.3 to Remote 10.10.0.11
    Local 10.10.0.3 to Remote 10.10.0.12
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.9
    Local 10.10.0.4 to Remote 10.10.0.10
    Local 10.10.0.4 to Remote 10.10.0.11
    Local 10.10.0.4 to Remote 10.10.0.12

Larger than PMTU communication succeeds on 32 path(s)
RPC status:
8 paths up, 0 paths down (tcp check)
8 paths up, 0 paths down (udp check)
----
--
====


=== 第3步：验证配置

. 显示有关配置中的设备的信息：
+
** `network device-discovery show`
** `network port show -role cluster`
** `network interface show -role cluster`
** `ssystem cluster-switch show`


+
.显示示例
[%collapsible]
====
[listing]
----
cluster::> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    C1                 Ethernet1/1/1    N3K-C3132Q-V
            e0b    C2                 Ethernet1/1/1    N3K-C3132Q-V
            e0c    C2                 Ethernet1/1/2    N3K-C3132Q-V
            e0d    C1                 Ethernet1/1/2    N3K-C3132Q-V
n2         /cdp
            e0a    C1                 Ethernet1/1/3    N3K-C3132Q-V
            e0b    C2                 Ethernet1/1/3    N3K-C3132Q-V
            e0c    C2                 Ethernet1/1/4    N3K-C3132Q-V
            e0d    C1                 Ethernet1/1/4    N3K-C3132Q-V
n3         /cdp
            e4a    C1                 Ethernet1/7      N3K-C3132Q-V
            e4e    C2                 Ethernet1/7      N3K-C3132Q-V
n4         /cdp
            e4a    C1                 Ethernet1/8      N3K-C3132Q-V
            e4e    C2                 Ethernet1/8      N3K-C3132Q-V
12 entries were displayed.
----
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
12 entries were displayed.
----
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4e     true
12 entries were displayed.
----
[listing]
----
cluster::*> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                          cluster-network   10.10.1.101      NX3132V
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

CL2                          cluster-network   10.10.1.102      NX3132V
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP
C2                          cluster-network    10.10.1.103      NX3132V
     Serial Number: FOX000003
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

3 entries were displayed.
----
====
. 如果尚未自动删除更换的 Nexus 3132Q-V 交换机，请将其卸下：
+
`ssystem cluster-switch delete`

+
[listing]
----
cluster::*> system cluster-switch delete –device CL2
----
. 验证是否监控了正确的集群交换机：
+
`ssystem cluster-switch show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                          cluster-network    10.10.1.101      NX3132V
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network     10.10.1.103      NX3132V
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

2 entries were displayed.
----
====
. 如果禁止自动创建案例，请通过调用 AutoSupport 消息重新启用它：
+
`ssystem node AutoSupport invoke -node * -type all -message MAINT=end`



.下一步是什么？
link:../switch-cshm/config-overview.html["配置交换机运行状况监控"]
