---
permalink: switch-cisco-3132q-v/switch-requirements.html 
sidebar: sidebar 
keywords: replace, cisco nexus 3132q-v cluster switches 
summary: 更换 Cisco Nexus 3132Q-V 集群交换机时，您必须了解某些配置信息，端口连接和布线要求。 
---
= 更换Cisco Nexus 3132Q-V集群交换机的要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
更换集群交换机时、请确保您了解配置要求、端口连接和布线要求。



== Cisco Nexus 3132Q-V要求

* 支持 Cisco Nexus 3132Q-V 集群交换机。
* 10 GbE 和 40/100 GbE 端口的数量在上提供的参考配置文件（ RCF ）中定义 link:https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 集群网络交换机参考配置文件下载"^] 页面。
* 集群交换机使用交换机间链路（ ISL ）端口 E1/31 至 32 。
* 。 link:https://hwu.netapp.com["Hardware Universe"^] 包含有关支持的 Nexus 3132Q-V 交换机布线的信息：
+
** 具有 10 GbE 集群连接的节点需要使用分支光缆的 QSFP 光纤模块或 QSFP 到 SFP+ 铜缆的分支。
** 具有 40/100 GbE 集群连接的节点需要支持的 QSFP/QSFP28 光纤模块以及光缆或 QSFP28 铜缆。
** 集群交换机使用适当的 ISL 布线： 2 根 QSFP28 光纤或铜缆直连缆线。


* 在 Nexus 3132Q-V 上，您可以将 QSFP 端口作为 40/100 Gb 以太网或 4 个 10 Gb 以太网模式运行。
+
默认情况下， 40/100 Gb 以太网模式下有 32 个端口。这些 40 Gb 以太网端口按 2 元组命名约定进行编号。例如，第二个 40 Gb 以太网端口编号为 1/2 。将配置从 40 Gb 以太网更改为 10 Gb 以太网的过程称为 _break_ ，将配置从 10 Gb 以太网更改为 40 Gb 以太网的过程称为 _breakin 。将 40/100 Gb 以太网端口拆分为 10 Gb 以太网端口时，生成的端口将使用三元组命名约定进行编号。例如，第二个 40/100 Gb 以太网端口的分支端口编号为 1/2/1 ， 1/2/2 ， 1/2/3 ， 1/2/4 。

* Nexus 3132Q-V 的左侧是一组四个 SFP+ 端口，这些端口会多路传输到第一个 QSFP 端口。
+
默认情况下， RCF 的结构使用第一个 QSFP 端口。

+
您可以使用 `hardware profile FRONT portmode sfp-plus` 命令使 Nexus 3132Q-V 的四个 SFP+ 端口处于活动状态，而不是 QSFP 端口。同样，您也可以使用 `hardware profile Front portmode QSFP` 命令将 Nexus 3132Q-V 重置为使用 QSFP 端口，而不是四个 SFP+ 端口。

* 您必须已将 Nexus 3132Q-V 上的某些端口配置为以 10 GbE 或 40/100 GbE 运行。
+
您可以使用 `interface breakout module 1 port 1-6 map 10g-4x` 命令将前六个端口细分为 4x10 GbE 模式。同样，您也可以使用 `no interface breakout module 1 port 1-6 map 10g-4x` 命令对分支配置中的前六个 QSFP + 端口进行重新分组。

* 您必须已完成有关从节点到 Nexus 3132Q-V 集群交换机的 10 GbE 和 40/100 GbE 连接的规划，迁移和阅读所需文档。
+
。 link:http://mysupport.netapp.com/NOW/download/software/cm_switches/["Cisco 以太网交换机"^] 页面提供了有关此操作步骤 支持的 ONTAP 和 NX-OS 版本的信息。





== Cisco Nexus 5596要求

* 支持以下集群交换机：
+
** Nexus 5596
** Nexus 3132Q-V


* 10 GbE 和 40/100 GbE 端口的数量在上提供的参考配置文件（ RCF ）中定义 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 集群网络交换机参考配置文件下载"^] 页面。
* 集群交换机使用以下端口连接到节点：
+
** 端口 E1/1-40 （ 10 GbE ）： Nexus 5596
** 端口 E1/1-30 （ 40/100 GbE ）： Nexus 3132Q-V


* 集群交换机使用以下交换机间链路（ ISL ）端口：
+
** 端口 E1/41-48 （ 10 GbE ）： Nexus 5596
** 端口 E1/31 至 32 （ 40/100 GbE ）： Nexus 3132Q-V


* 。 link:https://hwu.netapp.com/["Hardware Universe"^] 包含有关支持的 Nexus 3132Q-V 交换机布线的信息：
+
** 具有 10 GbE 集群连接的节点需要使用 QSFP 到 SFP+ 光纤分支电缆或 QSFP 到 SFP+ 铜分支电缆。
** 具有 40/100 GbE 集群连接的节点需要使用光缆或 QSFP28 铜缆支持的 QSFP/QSFP28 光纤模块。


* 集群交换机使用适当的 ISL 布线：
+
** 起始： Nexus 5596 到 Nexus 5596 （ SFP+ 到 SFP+ ）
+
*** 8 根 SFP+ 光纤或铜缆直连缆线


** 中间： Nexus 5596 到 Nexus 3132Q-V （ QSFP 到 4xSFP+ 细分）
+
*** 1 根 QSFP 到 SFP+ 光纤分出或铜缆分出缆线


** 最终结果： Nexus 3132Q-V 到 Nexus 3132Q-V （ QSFP28 到 QSFP28 ）
+
*** 2 根 QSFP28 光纤或铜缆直连缆线




* 在 Nexus 3132Q-V 交换机上，您可以将 QSFP/QSFP28 端口作为 40/100 千兆以太网模式或 4 个 10 千兆以太网模式运行。
+
默认情况下， 40/100 千兆以太网模式下有 32 个端口。这 40 个千兆以太网端口按照 2 元组命名约定进行编号。例如，第二个 40 千兆以太网端口编号为 1/2 。将配置从 40 千兆以太网更改为 10 千兆以太网的过程称为 _break_ ，将配置从 10 千兆以太网更改为 40 千兆以太网的过程称为 _breakin 。将 40/100 千兆以太网端口拆分为 10 千兆以太网端口时，生成的端口将使用三元组命名约定进行编号。例如，第二个 40 千兆以太网端口的分出端口编号为 1/2/1 ， 1/2/2 ， 1/2/3 和 1/2/4 。

* Nexus 3132Q-V 交换机左侧是一组 4 个 SFP+ 端口，这些端口会多路传输到该 QSFP28 端口。
+
默认情况下， RCF 的结构使用 QSFP28 端口。

+

NOTE: 您可以使用 `hardware profile FRONT portmode sfp-plus` 命令使 Nexus 3132Q-V 交换机的 4 个 SFP+ 端口处于活动状态，而不是 QSFP 端口。同样，您也可以使用 `hardware profile Front portmode QSFP` 命令将 Nexus 3132Q-V 交换机重置为使用 QSFP 端口，而不是 4 个 SFP+ 端口。

* 您已将 Nexus 3132Q-V 交换机上的某些端口配置为以 10 GbE 或 40/100 GbE 运行。
+

NOTE: 您可以使用 `interface breakout module 1 port 1-6 map 10g-4x` 命令将前六个端口细分为 4x10 GbE 模式。同样，您也可以使用 `no interface breakout module 1 port 1-6 map 10g-4x` 命令对分支配置中的前六个 QSFP + 端口进行重新分组。

* 您已经完成了从节点到 Nexus 3132Q-V 集群交换机的 10 GbE 和 40/100 GbE 连接的规划，迁移并阅读了相关文档。
* 此操作步骤 支持的 ONTAP 和 NX-OS 版本位于上 link:http://support.netapp.com/NOW/download/software/cm_switches/["Cisco 以太网交换机"^] 页面。




== NetApp CN1610要求

* 支持以下集群交换机：
+
** NetApp CN1610
** Cisco Nexus 3132Q-V


* 集群交换机支持以下节点连接：
+
** NetApp CN1610 ：端口 0/1 到 0/12 （ 10 GbE ）
** Cisco Nexus 3132Q-V ：端口 E1/1-30 （ 40/100 GbE ）


* 集群交换机使用以下交换机间链路（ ISL ）端口：
+
** NetApp CN1610 ：端口 0/13 至 0/16 （ 10 GbE ）
** Cisco Nexus 3132Q-V ：端口 E1/31 至 32 （ 40/100 GbE ）


* 。 link:https://hwu.netapp.com/["Hardware Universe"^] 包含有关支持的 Nexus 3132Q-V 交换机布线的信息：
+
** 具有 10 GbE 集群连接的节点需要使用 QSFP 到 SFP+ 光纤分支电缆或 QSFP 到 SFP+ 铜分支电缆
** 具有 40/100 GbE 集群连接的节点需要支持的 QSFP/QSFP28 光纤模块以及光缆或 QSFP28 铜缆


* 相应的 ISL 布线如下所示：
+
** 开始：对于 CN1610 到 CN1610 （ SFP+ 到 SFP+ ），需要四根 SFP+ 光纤或铜缆直连缆线
** 过渡：对于 CN1610 到 Nexus 3132Q-V （ QSFP 到四个 SFP+ 分支），使用一根 QSFP 到 SFP+ 光纤或铜分支缆线
** 最终版本：对于 Nexus 3132Q-V 到 Nexus 3132Q-V （ QSFP28 到 QSFP28 ），请使用两根 QSFP28 光纤或铜缆直连缆线


* NetApp 双轴电缆与 Cisco Nexus 3132Q-V 交换机不兼容。
+
如果您当前的 CN1610 配置使用 NetApp 双轴电缆进行集群节点到交换机连接或 ISL 连接，并且您希望在环境中继续使用双轴电缆，则需要购买 Cisco 双轴电缆。或者，您也可以使用光缆进行 ISL 连接和集群节点到交换机连接。

* 在 Nexus 3132Q-V 交换机上，您可以将 QSFP/QSFP28 端口用作 40/100 Gb 以太网或 4 个 10 Gb 以太网模式。
+
默认情况下， 40/100 Gb 以太网模式下有 32 个端口。这些 40 Gb 以太网端口按 2 元组命名约定进行编号。例如，第二个 40 Gb 以太网端口编号为 1/2 。将配置从 40 Gb 以太网更改为 10 Gb 以太网的过程称为 _break_ ，将配置从 10 Gb 以太网更改为 40 Gb 以太网的过程称为 _breakin 。将 40/100 Gb 以太网端口拆分为 10 Gb 以太网端口时，生成的端口将使用三元组命名约定进行编号。例如，第二个 40 Gb 以太网端口的分支端口编号为 1/2/1 ， 1/2/2 ， 1/2/3 和 1/2/4 。

* Nexus 3132Q-V 交换机左侧是一组四个 SFP+ 端口，这些端口会多路传输到第一个 QSFP 端口。
+
默认情况下，参考配置文件（ RCF ）的结构使用第一个 QSFP 端口。

+
对于 Nexus 3132Q-V 交换机，您可以使用 `hardware profile Front portmode SFP+` 命令将四个 SFP+ 端口设为活动状态，而不是 QSFP 端口。同样，您也可以使用 `hardware profile Front portmode QSFP` 命令将 Nexus 3132Q-V 交换机重置为使用 QSFP 端口，而不是四个 SFP+ 端口。

+

NOTE: 使用前四个 SFP+ 端口时，它将禁用第一个 40GbE QSFP 端口。

* 您必须已将 Nexus 3132Q-V 交换机上的某些端口配置为以 10 GbE 或 40/100 GbE 运行。
+
您可以使用 `interface breakout module 1 port 1-6 map 10g-4x` 命令将前六个端口细分为 4 个 10 GbE 模式。同样，您也可以使用 `no interface breakout module 1 port 1-6 map 10g-4x` 命令从 _break_ 配置对前六个 QSFP + 端口进行重新分组。

* 您必须已完成有关从节点到 Nexus 3132Q-V 集群交换机的 10 GbE 和 40/100 GbE 连接的规划，迁移和阅读所需文档。
* 上列出了此操作步骤 支持的 ONTAP 和 NX-OS 版本 link:http://support.netapp.com/NOW/download/software/cm_switches/["Cisco 以太网交换机"^] 页面。
* 上列出了此操作步骤 支持的 ONTAP 和快速路径版本 link:http://support.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 交换机"^] 页面。

