---
permalink: switch-cisco-3132q-v/task-how-to-migrate-from-a-two-node-switchless-cluster-to-a-cluster-with-cisco-nexus-3132q-v-cluster-switches.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, cisco nexus 3132q-v 
summary: 如果您使用双节点无交换机集群，则可以无中断地迁移到包含 Cisco Nexus 3132Q-V 集群网络交换机的双节点交换集群。 
---
= 如何迁移使用 Cisco Nexus 3132Q-V 集群交换机的双节点交换集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用双节点无交换机集群，则可以无中断地迁移到包含 Cisco Nexus 3132Q-V 集群网络交换机的双节点交换集群。

.开始之前
* 这些配置必须设置正确且正常运行。
* 节点必须运行 ONTAP 9.4 或更高版本。
* 所有集群端口都必须处于 `up` 状态。
* 必须支持 Cisco Nexus 3132Q-V 集群交换机。
* 现有集群网络配置必须具有：
+
** Nexus 3132 集群基础架构在两台交换机上均为冗余且功能完备。
+
交换机上的最新 RCF 和 NX-OS 版本。

** 两台交换机上的管理连接。
** 对两个交换机的控制台访问。
** 所有处于 `up` 状态的集群逻辑接口（ LIF ）均未迁移。
** 交换机的初始自定义。
** 所有 ISL 端口均已启用并已布线。




此操作步骤中的示例使用以下交换机和节点命名：

* Nexus 3132Q-V 集群交换机， C1 和 C2 。
* 节点为 n1 和 n2 。


[NOTE]
====
此操作步骤 中的示例使用两个节点，每个节点使用两个 40/100 GbE 集群互连端口 E4A 和 e4e 。。 link:https://hwu.netapp.com/["Hardware Universe"^] 提供有关平台上集群端口的详细信息。

====
* N1_clus1 是第一个连接到节点 n1 的集群交换机 C1 的集群逻辑接口（ LIF ）。
* n1_clus2 是第一个连接到节点 n1 的集群交换机 C2 的集群 LIF 。
* n2_clus1 是连接到节点 n2 的集群交换机 C1 的第一个集群 LIF 。
* n2_clus2 是要连接到节点 n2 的集群交换机 C2 的第二个集群 LIF 。
* 10 GbE 和 40/100 GbE 端口的数量在上提供的参考配置文件（ RCF ）中定义 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 集群网络交换机参考配置文件下载"^] 页面。


[NOTE]
====
操作步骤 要求同时使用 ONTAP 命令和 Cisco Nexus 3000 系列交换机命令；除非另有说明，否则使用 ONTAP 命令。

====
* 集群首先连接两个节点，并在双节点无交换机集群设置下运行。
* 第一个集群端口已移至 C1 （,步骤 1.- ,20）
* 第二个集群端口已移至 C2 （,步骤 21- ,32）。
* 禁用双节点无交换机集群选项（,步骤 33- ,35）


.步骤
. 【 ｛ step1_migrate_2node3132q]] 如果在此集群上启用了 AutoSupport ，则通过调用 AutoSupport 消息禁止自动创建案例：
+
`ssystem node AutoSupport invoke -node * -type all - 消息 MAINT=xh`

+
_x_ 是维护时段的持续时间，以小时为单位。

+
[NOTE]
====
AutoSupport 消息会通知技术支持此维护任务，以便在维护窗口期间禁止自动创建案例。

====
. 确定每个集群接口的管理或运行状态：
+
.. 显示网络端口属性：
+
`network port show`

+
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
.. 显示有关逻辑接口的信息：
+
`network interface show`

+
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----


. 根据您的需要，验证新的 3132Q-V 交换机上是否安装了适当的 RCF 和映像，并进行任何必要的站点自定义，例如用户和密码，网络地址等。
+
此时必须准备两个交换机。如果您需要升级 RCF 和映像软件，必须按照以下步骤进行操作：

+
.. 转至 link:http://support.netapp.com/NOW/download/software/cm_switches/["Cisco 以太网交换机"^] 页面。
.. 请记下该页面上的表中的交换机和所需的软件版本。
.. 下载适当版本的 RCF 。
.. 单击 * RCF* 页面上的 * 继续 * ，接受许可协议，然后按照 * 下载 * 页面上的说明下载问题描述 。
.. 下载相应版本的映像软件。


. 单击 * RCF* 页面上的 * 继续 * ，接受许可协议，然后按照 * 下载 * 页面上的说明下载问题描述 。
. 在 Nexus 3132Q-V 交换机 C1 和 C2 上，禁用所有面向节点的端口 C1 和 C2 ，但不要禁用 ISL 端口。
+
以下示例显示了使用 RCF 支持的配置在 Nexus 3132Q-V 集群交换机 C1 和 C2 上禁用端口 1 到 30

+
`NX3132_RCF_v1.1_24p10g_26p40g.txt` ：

+
[listing]
----
C1# copy running-config startup-config
[########################################] 100%
Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit

C2# copy running-config startup-config
[########################################] 100%
Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
. 使用支持的布线将 C1 上的端口 1/31 和 1/32 连接到 C2 上的相同端口。
. 验证 C1 和 C2 上的 ISL 端口是否正常运行：
+
`s如何执行端口通道摘要`

+
[listing]
----
C1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
. 显示交换机上相邻设备的列表：
+
`s如何使用 cdp 邻居`

+
[listing]
----
C1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3132Q-V  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3132Q-V  Eth1/32

Total entries displayed: 2

C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3132Q-V  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3132Q-V  Eth1/32

Total entries displayed: 2
----
. 显示每个节点上的集群端口连接：
+
`network device-discovery show`

+
以下示例显示了双节点无交换机集群配置。

+
[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
. 将 clus1 接口迁移到托管 clus2 的物理端口：
+
`网络接口迁移`

+
从每个本地节点执行此命令。

+
[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus1 -source-node n1
–destination-node n1 -destination-port e4e
cluster::*> network interface migrate -vserver Cluster -lif n2_clus1 -source-node n2
–destination-node n2 -destination-port e4e
----
. 验证集群接口迁移：
+
`network interface show`

+
[listing]
----

cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
. 关闭两个节点上的集群端口 clus1 LIF ：
+
`network port modify`

+
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin false
cluster::*> network port modify -node n2 -port e4a -up-admin false
----
. 对远程集群接口执行 Ping 操作并执行 RPC 服务器检查：
+
`cluster ping-cluster`

+
[listing]
----
cluster::*> cluster ping-cluster -node n1
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e4a	10.10.0.1
Cluster n1_clus2 n1		e4e	10.10.0.2
Cluster n2_clus1 n2		e4a	10.10.0.3
Cluster n2_clus2 n2		e4e	10.10.0.4

Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
. 断开节点 n1 上 E4A 的缆线。
+
您可以参考正在运行的配置，并使用 Nexus 3132Q-V 上支持的布线方式将交换机 C1 上的第一个 40 GbE 端口（本示例中的端口 1/7 ）连接到 n1 上的 E4A

+

NOTE: 将任何缆线重新连接到新的 Cisco 集群交换机时，使用的缆线必须为光纤或 Cisco 支持的缆线。

. 断开节点 n2 上 E4A 的缆线。
+
您可以参考运行配置，并使用支持的布线方式将 E4A 连接到 C1 端口 1/8 上的下一个可用 40 GbE 端口。

. 启用 C1 上面向节点的所有端口。
+
以下示例显示了使用 RCF 支持的配置在 Nexus 3132Q-V 集群交换机 C1 和 C2 上启用的端口 1 到 30

+
`NX3132_RCF_v1.1_24p10g_26p40g.txt` ：

+
[listing]
----
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# no shutdown
C1(config-if-range)# exit
C1(config)# exit
----
. 在每个节点上启用第一个集群端口 E4A ：
+
`network port modify`

+
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin true
cluster::*> network port modify -node n2 -port e4a -up-admin true
----
. 验证两个节点上的集群是否均已启动：
+
`network port show`

+
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
. 对于每个节点，还原所有迁移的集群互连 LIF ：
+
`网络接口还原`

+
以下示例显示了要还原到其主端口的已迁移 LIF 。

+
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus1
cluster::*> network interface revert -vserver Cluster -lif n2_clus1
----
. 【第 20 步 _migrate_2node3132q]] 验证所有集群互连端口现在是否均已还原到其主端口：
+
`network interface show`

+
对于 `Current Port` 列中列出的所有端口， `Is Home` 列应显示值 `true` 。如果显示的值为 `false` ，则表示端口尚未还原。

+
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
. 【第 21 步 _migrate_2node3132q]] 显示每个节点上的集群端口连接：
+
`network device-discovery show`

+
[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3132Q-V
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3132Q-V
            e4e    n1                  e4e              FAS9000
----
. 在每个节点的控制台上，将 clus2 迁移到端口 E4A ：
+
`网络接口迁移`

+
[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1
–destination-node n1 -destination-port e4a
cluster::*> network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2
–destination-node n2 -destination-port e4a
----
. 关闭两个节点上的集群端口 clus2 LIF ：
+
`network port modify`

+
以下示例显示了两个节点上都要关闭的指定端口：

+
[listing]
----
	cluster::*> network port modify -node n1 -port e4e -up-admin false
	cluster::*> network port modify -node n2 -port e4e -up-admin false
----
. 验证集群 LIF 状态：
+
`network interface show`

+
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
. 断开节点 n1 上 e4e 的缆线。
+
您可以参考正在运行的配置，并使用 Nexus 3132Q-V 上支持的布线方式将交换机 C2 上的第一个 40 GbE 端口（本示例中的端口 1/7 ）连接到 n1 上的 e4e

. 断开节点 n2 上 e4e 的缆线。
+
您可以参考正在运行的配置，并使用支持的布线方式将 e4e 连接到 C2 端口 1/8 上的下一个可用 40 GbE 端口。

. 在 C2 上启用所有面向节点的端口。
+
以下示例显示了使用 RCF 支持的配置在 Nexus 3132Q-V 集群交换机 C1 和 C2 上启用端口 1 到 30

+
`NX3132_RCF_v1.1_24p10g_26p40g.txt` ：

+
[listing]
----
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# no shutdown
C2(config-if-range)# exit
C2(config)# exit
----
. 在每个节点上启用第二个集群端口 e4e ：
+
`network port modify`

+
以下示例显示了正在启动的指定端口：

+
[listing]
----
	cluster::*> network port modify -node n1 -port e4e -up-admin true
	cluster::*> network port modify -node n2 -port e4e -up-admin true
----
. 对于每个节点，还原所有迁移的集群互连 LIF ：
+
`网络接口还原`

+
以下示例显示了要还原到其主端口的已迁移 LIF 。

+
[listing]
----
	cluster::*> network interface revert -vserver Cluster -lif n1_clus2
	cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
. 验证所有集群互连端口现在是否均已还原到其主端口：
+
`network interface show`

+
对于 `Current Port` 列中列出的所有端口， `Is Home` 列应显示值 `true` 。如果显示的值为 `false` ，则表示端口尚未还原。

+
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
. 验证所有集群互连端口是否均处于 `up` 状态。
+
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
. 【第 32 步 _migrate_2node3132q]] 显示每个节点上每个集群端口连接到的集群交换机端口号：
+
`network device-discovery show`

+
[listing]
----
	cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3132Q-V
            e4e    C2                  Ethernet1/7      N3K-C3132Q-V
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3132Q-V
            e4e    C2                  Ethernet1/8      N3K-C3132Q-V
----
. 【第 33 步 _migrate_2node3132q]] 显示发现和监控的集群交换机：
+
`ssystem cluster-switch show`

+
[listing]
----
cluster::*> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                         cluster-network     10.10.1.101      NX3132V
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network     10.10.1.102      NX3132V
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

2 entries were displayed.
----
. 在任何节点上禁用双节点无交换机配置设置：
+
`网络选项 switchless-cluster`

+
[listing]
----
network options switchless-cluster modify -enabled false
----
. `s步骤 35_migrate_2node3132q]] 验证是否已禁用 " 无交换机集群` " 选项。
+
[listing]
----
network options switchless-cluster show
----
. 对远程集群接口执行 Ping 操作并执行 RPC 服务器检查：
+
`cluster ping-cluster`

+
[listing]
----
cluster::*> cluster ping-cluster -node n1
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e4a	10.10.0.1
Cluster n1_clus2 n1		e4e	10.10.0.2
Cluster n2_clus1 n2		e4a	10.10.0.3
Cluster n2_clus2 n2		e4e	10.10.0.4

Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
. 启用集群交换机运行状况监控器日志收集功能以收集交换机相关的日志文件：
+
`ssystem cluster-switch log setup-password`

+
`ssystem cluster-switch log enable-Collection`

+
[listing]
----
cluster::*> **system cluster-switch log setup-password**
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
C1
C2

cluster::*> system cluster-switch log setup-password

Enter the switch name: C1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster::*> system cluster-switch log setup-password

Enter the switch name: C2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster::*> system cluster-switch log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster::*>
----
+

NOTE: 如果其中任何一个命令返回错误，请联系 NetApp 支持部门。

. 如果禁止自动创建案例，请通过调用 AutoSupport 消息重新启用它：
+
`ssystem node AutoSupport invoke -node * -type all -message MAINT=end`


