---
permalink: switch-cisco-3232c-storage/install-rcf-software-3232c-storage.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 3232c 
summary: '使用集群交换机健康监视器 (CSHM) 和日志收集功能时需要 SSH。要在Cisco 3232c 集群交换机上启用 SSH，您需要先生成 SSH 密钥，然后启用 SSH。' 
---
= 安装参考配置文件（RCF）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
首次设置 Nexus 3232C 交换机后，安装参考配置文件 (RCF)。

.开始之前
请核实以下安装和连接：

* 交换机配置的当前备份。
* 一个功能齐全的集群（日志中没有错误或类似问题）。
* 当前的RCF。
* 与交换机的控制台连接，这是安装 RCF 时需要的。


.关于此任务
该过程需要同时使用ONTAP命令和Cisco Nexus 3000 系列交换机命令；除非另有说明，否则使用ONTAP命令。

完成 link:prepare-install-cisco-nexus-3232c-storage.html["准备安装 NX-OS 和 RCF"] 中的步骤，然后按照以下步骤操作。



== 步骤 1：在交换机上安装 RCF

. 使用 SSH 或串行控制台登录到交换机 s2。
. 使用以下传输协议之一将 RCF 复制到交换机 s2 的 bootflash：FTP、TFTP、SFTP 或 SCP。有关 Cisco 命令的详细信息，请参见 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Cisco Nexus 3000 系列 NX-OS 命令参考"^]中的相应指南。
+
.显示示例
[%collapsible]
====
此示例显示使用 TFTP 将 RCF 复制到交换机 s2 上的 bootflash：

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX3232C-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 将之前下载的 RCF 文件应用到启动闪存中。
+
有关Cisco命令的更多信息，请参阅 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Cisco Nexus 3000 系列 NX-OS 命令参考"^]。

+
.显示示例
[%collapsible]
====
此示例显示了在交换机 s2 上安装的 RCF 文件 `NX9336C-FX2-RCF-v1.13-1-Storage.txt`：

[listing, subs="+quotes"]
----
s2# *copy NX9336C-FX2-RCF-v1.13-1-Storage.txt running-config echo-commands*
----
====
+
[NOTE]
====
请务必仔细阅读 RCF 的 *Installation notes*、*Important Notes* 和 *banner* 部分。您必须阅读并遵循这些说明来验证交换机的正确配置和操作。

====
. 检查横幅输出 `show banner motd`命令。您必须阅读并遵循“重要提示”下的说明，以确保交换机的正确配置和操作。
. 请确认 RCF 是否为正确的最新版本：
+
`show running-config`

+
检查输出结果以验证是否拥有正确的 RCF 时，请确保以下信息正确：

+
** RCF横幅
** 节点和端口设置
** 定制
+
输出结果会根据您的网站配置而有所不同。检查端口设置，并参考发行说明，了解您安装的 RCF 版本是否有任何特定更改。



. 将之前对交换机配置所做的任何自定义设置重新应用。
. 确认 RCF 版本和交换机设置正确后，复制以下内容： `running-config`文件到 `startup-config`文件。
+
`s2# copy running-config startup-config [########################################] 100% Copy complete`

. 重启交换机 s2：
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 在交换机 s1 上重复步骤 1 至 8。
. 将 ONTAP 集群中所有节点的节点存储端口和存储架端口连接到交换机 s1 和 s2。




== 步骤 2：验证交换机连接

. 验证交换机端口是否为 *up* 状态。
+
`show interface brief`

. 使用以下命令验证节点存储端口和存储架端口是否位于其正确的 VLAN 中：
+
`show vlan brief`

+
`show interface trunk`





== 步骤 3：设置ONTAP集群

NetApp建议您使用系统管理器来设置新的集群。

系统管理器为集群设置和配置提供了简单易行的工作流程，包括分配节点管理 IP 地址、初始化集群、创建本地层、配置协议和配置初始存储。

参考 https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["使用 System Manager 在新集群上配置ONTAP"]了解设置说明。

.下一步是什么？
安装完 RCF 后，您可以…… link:configure-ssh-keys.html["验证 SSH 配置"]。
