---
permalink: switch-cisco-3232c-storage/install-nx-os-software-3232c-storage.html 
sidebar: sidebar 
keywords: install, nx-os software 
summary: 您可以使用此过程在 Nexus 3232C 存储交换机上安装 NX-OS 软件。 
---
= 安装或升级 NX-OS 软件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用此过程在 Nexus 3232C 存储交换机上安装 NX-OS 软件。

.开始之前
验证您是否具有以下条件：

* 交换机配置的当前备份。
* 一个功能齐全的集群（日志中没有错误或类似问题）。
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco以太网交换机页面"^]。请查阅交换机兼容性表格，了解支持的ONTAP和 NX-OS 版本。
* link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["CiscoNexus 3000 系列交换机"^]。有关Cisco交换机升级和降级程序的完整文档，请参阅Cisco网站上提供的相应软件和升级指南。




== 安装或升级软件

该过程需要同时使用ONTAP命令和Cisco Nexus 3000 系列交换机命令；除非另有说明，否则使用ONTAP命令。

完成 link:prepare-install-cisco-nexus-3232c-storage.html["准备安装 NX-OS 和 RCF"] 中的步骤，然后按照以下步骤操作。

.步骤
. 将交换机连接到管理网络。
. 使用 `ping`用于验证与托管 NX-OS 软件和 RCF 的服务器的连接性的命令。
+
.显示示例
[%collapsible]
====
此示例验证交换机可以访问 IP 地址为 172.19.2.1 的服务器：

[listing, subs="+quotes"]
----
s2# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. 如果您是首次设置交换机，请跳至第 5 步。如果要升级交换机，请继续下一步。
. 检查每个节点存储端口和存储盘架端口的管理或运行状态。
+
.. 显示节点存储端口属性：
+
`storage port show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
cluster1-02

               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
.
.
----
====
.. 显示存储架端口属性：+
`storage shelf port show`
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*
Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. 确认已为交换机启用交换机健康监控 (CSHM)，以便对其进行监控：
+
`system switch ethernet show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.0.0.0          N3K-C3232C
     Serial Number: FFFYYYYYYY1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    1.1.0.0           N3K-C3232C
     Serial Number: FEEYYYYYYY2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====


. 使用 SSH 或串行控制台登录到该交换机。
. 将 NX-OS 软件和 EPLD 映像复制到 Nexus 3232C 交换机。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos.9.3.4.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/nxos.9.3.4.bin  /bootflash/nxos.9.3.4.bin
/code/nxos.9.3.4.bin  100% 1261MB   9.3MB/s   02:15
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.


s2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/n9000-epld.9.3.4.img*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: user1

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/n9000-epld.9.3.4.img  /bootflash/n9000-epld.9.3.4.img
/code/n9000-epld.9.3.4.img  100%  161MB   9.5MB/s   00:16
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. 请确认NX-OS软件的运行版本：
+
`show version`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2019, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 08.37
  NXOS: version 9.3(3)
  BIOS compile time:  01/28/2020
  NXOS image file is: bootflash:///nxos.9.3.3.bin
  NXOS compile time:  12/22/2019 2:00:00 [12/22/2019 14:00:37]

Hardware
  cisco Nexus3000 C3232C Chassis (Nexus 9000 Series)
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOCXXXXXXGD

  Device name: s2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 36 second(s)

Last reset at 74117 usecs after Tue Nov 24 06:24:23 2020
  Reason: Reset Requested by CLI command reload
  System version: 9.3(3)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):
----
====
. 安装 NX-OS 镜像。
+
安装镜像文件后，每次交换机重启时都会加载该文件。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *install all nxos bootflash:nxos.9.3.4.bin*
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.9.3.4.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS

Compatibility check is done:
Module  bootable          Impact              Install-type  Reason
------- ----------------- ------------------- ------------- ----------
     1     Yes            Disruptive          Reset         Default upgrade is not hitless

Images will be upgraded according to following table:
Module       Image       Running-Version(pri:alt)                New-Version          Upg-Required
------------ ----------- --------------------------------------- -------------------- ------------
     1       nxos        9.3(3)                                  9.3(4)               yes
     1       bios        v08.37(01/28/2020):v08.32(10/18/2016)   v08.37(01/28/2020)   no


Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS


Finishing the upgrade, switch will reboot in 10 seconds.
----
====
. 交换机重启后，请验证NX-OS软件的新版本：
+
`show version`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 08.37
  NXOS: version 9.3(4)
  BIOS compile time:  01/28/2020
  NXOS image file is: bootflash:///nxos.9.3.4.bin
  NXOS compile time:  4/28/2020 21:00:00 [04/29/2020 06:28:31]

Hardware
 cisco Nexus3000 C3232C Chassis (Nexus 9000 Series)
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOCXXXXXXGS

  Device name: rtpnpi-mcc01-8200-ms-A1
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 14 second(s)

Last reset at 196755 usecs after Tue Nov 24 06:37:36 2020
  Reason: Reset due to upgrade
  System version: 9.3(3)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):
----
====
. 升级EPLD镜像并重启交换机。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI   FPGA                       0x12
IO   FPGA                       0x11

s2# *install epld bootflash:n9000-epld.9.3.4.img module 1*
Compatibility check:
Module        Type         Upgradable    Impact      Reason
------  -----------------  ----------    ----------  -----------------
     1         SUP         Yes           Disruptive  Module Upgradable

Retrieving EPLD versions.... Please wait.
Images will be upgraded according to following table:
Module  Type   EPLD              Running-Version   New-Version  Upg-Required
------  ----  -----------------  ---------------   -----------  ------------
     1   SUP   MI FPGA                0x12         0x12         No
     1   SUP   IO FPGA                0x11         0x12         Yes
The above modules require upgrade.
The switch will be reloaded at the end of the upgrade
Do you want to continue (y/n) ?  [n] *y*

Proceeding to upgrade Modules.

Starting Module 1 EPLD Upgrade

Module 1 : IO FPGA [Programming] : 100.00% (     64 of      64 sectors)
Module 1 EPLD upgrade is successful.
Module        Type  Upgrade-Result
------  ------------------  --------------
     1         SUP         Success

Module 1 EPLD upgrade is successful.
----
====
. 如果您要升级到 NX-OS 版本 9.3(11)，则必须升级 EPLD。 `golden`镜像并再次重启交换机。否则，跳至步骤 12。
+
看 https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/93x/epld-rn/nxos_n9K_epldRN_9311.html["EPLD 升级版本说明，版本 9.3(11)"^]更多详情请见下文。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *install epld bootflash:n9000-epld.9.3.11.img module 1 golden*
Digital signature verification is successful
Compatibility check:
Module        Type         Upgradable     Impact      Reason
------  -----------------  -------------  ----------  -----------------
     1        SUP          Yes            Disruptive  Module Upgradable

Retrieving EPLD versions.... Please wait.
The above modules require upgrade.
The switch will be reloaded at the end of the upgrade
Do you want to continue (y/n) ?  [n] *y*

Proceeding to upgrade Modules.

 Starting Module 1 EPLD Upgrade

Module 1 : MI FPGA [Programming] : 100.00% (     64 of      64 sect)
Module 1 : IO FPGA [Programming] : 100.00% (     64 of      64 sect)
Module 1 EPLD upgrade is successful.
Module        Type          Upgrade-Result
------  ------------------  --------------
     1         SUP          Success

EPLDs upgraded.

Module 1 EPLD upgrade is successful.
----
====
. 交换机重启后，登录以验证新版本的 EPLD 是否已成功加载。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
s2# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI   FPGA                        0x12
IO   FPGA                        0x12
----
====
. 如果您是首次设置交换机，请跳至第 15 步。如果要升级交换机，请继续下一步。
. 验证每个节点存储端口和存储盘架端口的运行状况。
+
.. 显示节点存储端口属性：
+
`storage port show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
cluster1-02

               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
----
====
.. 显示存储架端口属性：+
`storage shelf port show`
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*
Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. 确认已为交换机启用交换机健康监控 (CSHM)，以便对其进行监控：
+
`system switch ethernet show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.0.0.0          N3K-C3232C
     Serial Number: FFFYYYYYYY1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    1.1.0.0           N3K-C3232C
     Serial Number: FEEYYYYYYY2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP  false
----
====


. 重复步骤 5 至 13，在交换机 s1 上安装 NX-OS 软件。


.下一步是什么？
安装 NX-OS 软件后，您可以link:install-rcf-software-3232c-storage.html["安装或升级参考配置文件（RCF）"]。
