---
permalink: switch-cisco-3232c-storage/prepare-install-cisco-nexus-3232c-storage.html 
sidebar: sidebar 
keywords: nx-os software, install, cisco nexus storage switches, 3232c, rcfs 
summary: '必须在 Cisco Nexus 3232C 存储交换机上安装 Cisco NX-OS 软件和参考配置文件 (RCF)。' 
---
= 准备安装 NX-OS 软件和参考配置文件 (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在安装 NX-OS 软件和参考配置文件 (RCF) 之前，请按照以下步骤操作。

.关于示例
本流程中的示例使用以下开关和节点命名规则：

* 两台 Cisco 交换机的名称是 s1 和 s2。
* 节点名称为 cluster1-01 和 cluster1-02。


请参阅 link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] 以验证您平台上的正确网络端口。有关交换机安装要求的详细信息，请参见 link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["安装HWU中没有的设备还需要哪些额外信息？"^]。

.关于此任务
该过程需要同时使用ONTAP命令和Cisco Nexus 3000 系列交换机命令；除非另有说明，否则使用ONTAP命令。

.步骤
. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
`system node autosupport invoke -node * -type all -message MAINT=x h`
+
其中 _x_ 为维护窗口的持续时间（小时）。

+
[NOTE]
====
AutoSupport消息会通知技术支持此维护任务，以便在维护窗口期间抑制自动创建案例。

====
. 将权限级别更改为高级，并在提示继续时输入 *y*：
+
`set -privilege advanced`

+
高级提示(`*>`出现。

. 显示每个交换机在每个节点中配置的接口数量：
+
`network device-discovery show -protocol cdp`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/cdp
            e5a    s1                        Eth1/2            N3K-C3232C
            e3b    s2                        Eth1/2            N3K-C3232C
cluster1-01/cdp
            e5a    s1                        Eth1/1            N3K-C3232C
            e3b    s2                        Eth1/1            N3K-C3232C
.
.
----
====
. 检查每个节点存储端口和存储盘架端口的管理或运行状态。
+
.. 显示节点存储端口属性：
+
`storage port show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
cluster1-02

               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
.
.
----
====
.. 显示存储架端口属性：+
`storage shelf port show`
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*
Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. 确认已为交换机启用交换机健康监控 (CSHM)，以便对其进行监控：
+
`system switch ethernet show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch             Type               Address          Model
  ------------------ ------------------ ---------------- ---------------
  s1                 storage-network    1.0.0.0          N3K-C3232C
     Serial Number: FFFYYYYYYY1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                 storage-network    1.1.0.0           N3K-C3232C
     Serial Number: FEEYYYYYYY2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====




.下一步是什么？
在您准备好安装 NX-OS 软件和 RCF 之后，您就可以link:install-nx-os-software-3232c-storage.html["安装 NX-OS 软件"]了。
