---
permalink: switch-cisco-3232c-storage/setup-switch-3232c-storage.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: 如果您还没有所需的配置信息和文档，则需要在设置集群和管理网络交换机之前收集这些信息。 
---
= 配置 3232C 存储交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照以下步骤设置和配置Cisco Nexus 3232C 交换机。

.开始之前
* 在安装现场访问 HTTP、FTP 或 TFTP 服务器，以下载适用的 NX-OS 和参考配置文件 (RCF) 版本。
* 适用的NX-OS版本，可从以下网址下载： https://software.cisco.com/download/home["Cisco软件下载"^]页。
* 所需的网络和管理网络交换机文档。
+
有关更多信息，请参见 link:required-documentation-3232c-storage.html["所需文件"]。

* 需要提供控制器文档和ONTAP文档。
+
https://netapp.com/us/documenation/index.aspx["NetApp文档"^]

* 适用的许可证、网络和配置信息以及线缆。
* 适用的 NetApp 存储网络和管理网络 RCF，从 NetApp 支持站点 http://mysupport.netapp.com/["mysupport.netapp.com"^]为您收到的交换机下载。所有 Cisco 存储网络和管理网络交换机均采用标准的 Cisco 出厂默认配置。这些交换机还具有当前版本的 NX-OS 软件，但没有加载 RCF。


.步骤
. 架设存储网络和管理网络交换机和控制器。
+
[cols="1,2"]
|===
| 如果您正在安装…… | 操作 


 a| 
NetApp系统机柜中的Cisco Nexus 3232C
 a| 
有关在 NetApp 机柜中安装交换机的说明，请参阅 _Installing a Cisco Nexus 3232C switch and pass-through panel in a NetApp cabinet_ 指南。



 a| 
电信机架中的设备
 a| 
请参阅交换机硬件安装指南和NetApp安装设置说明中提供的步骤。

|===
. 使用完成的布线工作表将存储网络和管理网络交换机布线到控制器。
. 打开存储网络和管理网络交换机和控制器的电源。
. 执行存储网络交换机的初始配置。
+
首次启动交换机时，请对以下初始设置问题提供相应的答案。您网站的安全策略定义了要启用的响应和服务。

+
[cols="1,2"]
|===
| 迅速的 | 响应 


 a| 
中止自动配置并继续进行正常设置？  （是/否）
 a| 
请回答“是”。默认值为否。



 a| 
您是否希望强制执行安全密码标准？  （是/否）
 a| 
请回答“是”。默认值为“是”。



 a| 
请输入管理员密码。
 a| 
默认密码为“`admin`”；您必须创建一个新的、强密码。弱密码可能会被拒绝。



 a| 
您想进入基本配置对话框吗？  （是/否）
 a| 
在交换机的初始配置阶段，请回答“是”。



 a| 
创建另一个登录帐户？  （是/否）
 a| 
答案取决于您网站关于备用管理员的政策。默认值为*否*。



 a| 
配置只读 SNMP 团体字符串？  （是/否）
 a| 
回答“不”。默认值为否。



 a| 
配置读写 SNMP 团体字符串？  （是/否）
 a| 
回答“不”。默认值为否。



 a| 
请输入交换机名称。
 a| 
交换机名称限制为 63 个字母数字字符。



 a| 
继续进行带外（mgmt0）管理配置？  （是/否）
 a| 
在该提示出现时，请回答“是”（默认值）。在 mgmt0 IPv4 地址提示符处，输入您的 IP 地址：ip_address。



 a| 
配置默认网关？  （是/否）
 a| 
请回答“是”。在默认网关的 IPv4 地址提示符处，输入您的默认网关。



 a| 
配置高级 IP 选项？  （是/否）
 a| 
回答“不”。默认值为否。



 a| 
启用 Telnet 服务？  （是/否）
 a| 
回答“不”。默认值为否。



 a| 
已启用 SSH 服务？  （是/否）
 a| 
请回答“是”。默认值为“是”。


NOTE: 使用以太网交换机健康监视器 (CSHM) 时，建议使用 SSH 进行日志收集。为了提高安全性，建议使用 SSHv2。



 a| 
请输入要生成的 SSH 密钥类型（dsa/rsa/rsa1）。
 a| 
默认值为 *rsa*。



 a| 
请输入密钥位数（1024-2048）。
 a| 
请输入1024-2048之间的密钥位数。



 a| 
配置NTP服务器？  （是/否）
 a| 
回答“不”。默认值为否。



 a| 
配置默认接口层（L3/L2）：
 a| 
请用*L2*回复。默认值为 L2。



 a| 
配置交换机端口接口的默认状态（关闭/不关闭）：
 a| 
回复 *noshut*。默认设置为 noshut。



 a| 
配置 CoPP 系统配置文件（严格/中等/宽松/严格）：
 a| 
回复时请使用 *strict*。默认设置为严格。



 a| 
您想修改配置吗？  （是/否）
 a| 
此时您应该可以看到新的配置。请检查并对您刚刚输入的配置进行必要的更改。如果对配置满意，请在提示时回答“否”。如果要编辑配置设置，请回复“是”。



 a| 
使用此配置并保存？  （是/否）
 a| 
回复“是”以保存配置。这会自动更新启动镜像和系统镜像。


NOTE: 如果此时不保存配置，下次重启交换机时，所有更改都将失效。

|===
. 在设置结束时显示的界面中，确认您所做的配置选择，并确保保存配置。
. 检查网络交换机上的版本，如有必要，请从  https://software.cisco.com/download/home["Cisco软件下载"^] 页面将 NetApp 支持的软件版本下载到交换机。


.下一步是什么？
配置好交换机后，您就可以link:prepare-install-cisco-nexus-3232c-storage.html["准备安装 NX-OS 和 RCF"]了。
