---
permalink: switch-cisco-3232c-storage/upgrade-rcf-software-3232c-storage.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: 您可以使用此过程升级您的 RCF 版本。 
---
= 升级您的参考配置文件 (RCF)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当您的运行交换机上已安装了现有版本的 RCF 文件时，您需要升级 RCF 版本。

.开始之前
请确保您拥有以下物品：

* 交换机配置的当前备份。
* 一个功能齐全的集群（日志中没有错误或类似问题）。
* 当前的RCF。
* 如果您要更新 RCF 版本，则需要在 RCF 中进行启动配置，以反映所需的启动映像。
+
如果需要更改引导配置以反映当前的引导映像，则必须在重新应用 RCF 之前执行此操作，以便在将来的重新启动中包含正确的版本。




CAUTION: 安装新的交换机软件版本和 RCF 之前，必须清除交换机设置并执行基本配置。在清除交换机设置之前，您必须使用串行控制台连接到交换机，或者保留基本配置信息。



== 第一步：准备升级

. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 _x_ 为维护窗口的持续时间（小时）。

. 将权限级别更改为高级，并在提示继续时输入 *y*：
+
`set -privilege advanced`

+
出现高级提示符（*>）。

. 显示每个节点上连接到交换机的端口：
+
[source, cli]
----
network device-discovery show
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID) Interface       Platform
----------- ------ ------------------------ --------------- ---------
cluster1-01/cdp
            e5a    s1                       Ethernet1/7     N3K-C3232C
            e3b    s2                       Ethernet1/7     N3K-C3232C
cluster1-02/cdp
            e5a    s1                       Ethernet1/8     N3K-C3232C
            e3b    s2                       Ethernet1/8     N3K-C3232C
.
.
----
====
. 检查每个节点存储端口和存储盘架端口的管理或运行状态。
+
.. 验证所有节点存储端口是否处于正常状态：
+
[source, cli]
----
storage port show -port-type ENET
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e5a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
cluster1-02
                   e5a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
.
.
----
====
.. 验证所有存储架端口是否处于正常状态：
+
[source, cli]
----
storage shelf port show
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. 确认正在监控交换机。
+
[source, cli]
----
system switch ethernet show
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.2.3.4          N3K-C3232C
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    2.3.4.5          N3K-C3232C
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====






== 步骤 2：升级 RCF

. 使用 SSH 或通过串行控制台登录到交换机 s2。
. 关闭连接到节点所有端口的端口。
+
[listing, subs="+quotes"]
----
s2> *enable*
s2# *configure*
s2(config)# *interface e1/1-32*
s2(config-if-range)# *shutdown*
s2(config-if-range)# *exit*
s2(config)# *exit*
----
+

CAUTION: 确保关闭所有连接的端口以避免任何网络连接问题。请参阅知识库文章 https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["在切换操作系统升级期间迁移集群 LIF 时，节点脱离仲裁。"^]更多详情请见下文。

. 如果您尚未保存当前交换机配置，请将以下命令的输出复制到文本文件中：
+
`show running-config`

+
.. 记录当前版本与当前版本之间的任何自定义添加内容。 `running-config`以及正在使用的 RCF 文件（例如贵组织的 SNMP 配置）。
.. 对于 NX-OS 10.2 及更高版本，请使用 `show diff running-config`用于与 bootflash 中保存的 RCF 文件进行比较的命令。否则，请使用第三方差异比较工具。


. 保存基本配置详细信息 `write_erase.cfg`启动闪存上的文件。
+
[NOTE]
====
确保配置以下内容：

** 用户名和密码
** 管理 IP 地址
** 默认网关
** 交换机名称


====
+
`s2# show run | section "switchname" > bootflash:write_erase.cfg`

+
`s2# show run | section "hostname" >> bootflash:write_erase.cfg`

+
`s2# show run | i "username admin password" >> bootflash:write_erase.cfg`

+
`s2# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`s2# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
请参阅知识库文章link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["如何在保持远程连接的情况下清除Cisco互连交换机上的配置"^]更多详情请见下文。

. 确认 `write_erase.cfg`文件已按预期填充：
+
`*show file bootflash:write_erase.cfg*`

. 问题 `write erase`清除当前已保存配置的命令：
+
`s2# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. 将之前保存的基本配置复制到启动配置中。
+
`s2# *copy bootflash:write_erase.cfg startup-config*`

. 重启交换机：
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 管理 IP 地址恢复正常后，通过 SSH 登录交换机。
+
您可能需要更新与 SSH 密钥相关的 hosts 文件条目。

. 使用以下传输协议之一将 RCF 复制到交换机 s2 的 bootflash：FTP、TFTP、SFTP 或 SCP。
+
有关 Cisco 命令的详细信息，请参见  https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html#CommandReferences["Cisco Nexus 3000 系列 NX-OS 文档"^] 中的相应指南。

+
.显示示例
[%collapsible]
====
此示例显示使用 TFTP 将 RCF 复制到交换机 s2 上的 bootflash：

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX3232C-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 将之前下载的 RCF 文件应用到启动闪存中。
+
有关 Cisco 命令的详细信息，请参见  https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Cisco Nexus 3000 系列文档"^] 中的相应指南。

+
此示例显示了在交换机 s2 上安装的 RCF 文件 `NX3232C-RCF-v1.13-1-Storage.txt`：

+
[listing, subs="+quotes"]
----
s2# *copy NX3232C-RCF-v1.13-1-Storage.txt running-config echo-commands*
----
+
[CAUTION]
====
确保仔细阅读 RCF 的 *安装说明*、*重要说明* 和 *横幅* 部分。您必须阅读并遵循这些说明以确保交换机的正确配置和操作。

====
. 请确认 RCF 文件是否为最新版本：
+
`show running-config`

+
检查输出结果以验证是否拥有正确的 RCF 时，请确保以下信息正确：

+
** RCF横幅
** 节点和端口设置
** 定制
+
输出结果会根据您的网站配置而有所不同。检查端口设置，并参考发行说明，了解您安装的 RCF 版本是否有任何特定更改。



. 将之前对交换机配置所做的任何自定义设置重新应用。
. 确认 RCF 版本、自定义添加项和交换机设置正确后，复制以下内容： `running-config`文件到 `startup-config`文件。
+
有关 Cisco 命令的详细信息，请参见  https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Cisco Nexus 9000 系列文档"^] 中的相应指南。

+
`s2# *copy running-config startup-config*`

+
`[########################################] 100% Copy complete`

. 重新启动交换机 s2。交换机重新启动时，可以忽略节点上报告的"`cluster switch health monitor`"警报和"`cluster ports down`"事件。
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 检查每个节点存储端口和存储盘架端口的管理或运行状态。
+
.. 验证所有存储端口均处于正常状态：
+
[source, cli]
----
storage port show -port-type ENET
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e5a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
cluster1-02
                   e5a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
.
.
----
====
.. 验证所有存储架端口是否处于正常状态：
+
[source, cli]
----
storage shelf port show
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. 验证交换机是否正在被监控：
+
[source, cli]
----
system switch ethernet show
----
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show*
  Switch           Type               Address          Model
  ---------------- ------------------ ---------------- ---------------
  s1               storage-network    1.2.3.4          N3K-C3232C
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2               storage-network    2.3.4.5          N3K-C3232C
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====


. 对交换机 s1 重复步骤 1 至 16。




== 步骤 3：验证存储网络

在每个存储交换机上完成以下步骤，以确认 RCF 升级后存储网络运行正常。

. 验证交换机端口是否为 *up* 状态。
+
[source, cli]
----
show interface brief
----
. 验证预期的节点存储端口是否仍然连接：
+
[source, cli]
----
show cdp neighbors
----
. 验证预期的存储盘架端口是否仍然已连接：
+
[source, cli]
----
show lldp neighbors
----
. 使用以下命令验证节点存储端口和存储架端口是否位于其正确的 VLAN 中：
+
[source, cli]
----
show vlan brief
----
+
[source, cli]
----
show interface trunk
----


.下一步是什么？
升级 RCF 后，您可以link:configure-ssh-keys.html["验证 SSH 配置"]。
