---
permalink: switch-netapp-cn1610/install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: 在 NetApp 交换机上安装 FASTPATH 软件时，您必须从第二个交换机 cs2 开始升级。 
---
= 安装 FASTPATH 软件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在您的 NetApp 交换机上安装 FASTPATH 软件时，您必须从第二台交换机 _cs2_ 开始升级。



[[review-requirements]]
== 审查要求

.开始之前
请确保您拥有以下物品：

* 交换机配置的当前备份。
* 完全正常运行的集群（日志中没有错误，也没有故障的集群网络接口卡 (NIC) 或类似问题）。
* 集群交换机上功能齐全的端口连接。
* 已设置所有集群端口。
* 所有集群逻辑接口(LIF)设置（必须尚未迁移）。
* 成功的通信路径：ONTAP (privilege: advanced) `cluster ping-cluster -node node1` 命令必须指示 `larger than PMTU communication`在所有路径上均成功。
* 支持的 FASTPATH 和 ONTAP 版本。
+
请务必查阅 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 开关"^]页面上的交换机兼容性表，以了解受支持的 FASTPATH 和 ONTAP 版本。





[[install-fastpath]]
== 安装 FASTPATH

以下过程使用集群模式 Data ONTAP 8.2 语法。因此，集群 Vserver、LIF 名称和 CLI 输出与 Data ONTAP 8.3 中的不同。

RCF 和 FASTPATH 版本中的命令语法之间可能存在命令依赖关系。

.关于示例
本流程中的示例使用以下开关和节点命名规则：

* 这两个 NetApp 交换机是 cs1 和 cs2。
* 两个集群 LIF 是 clus1 和 clus2。
* Vserver 是 vs1 和 vs2。
* The `cluster::*>` 提示符指示集群的名称。
* 每个节点上的集群端口命名为 e1a 和 e2a。
+
link:https://hwu.netapp.com/["Hardware Universe"^] 包含有关您平台上支持的实际集群端口的更多信息。

* 支持的交换机间链路 (ISL) 是端口 0/13 到 0/16。
* 支持的节点连接为端口 0/1 至 0/12。




[[step-1-migrate-cluster]]
=== 步骤 1：迁移集群

. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_ 是维护窗口的持续时间，单位为小时。

+

NOTE: AutoSupport消息会通知技术支持此维护任务，以便在维护窗口期间抑制自动创建案例。

. 以管理员身份登录交换机。默认情况下没有密码。在 `(cs2) #`提示符处，输入 `enable`命令。同样，默认情况下没有密码。这使您可以访问特权 EXEC 模式，该模式允许您配置网络接口。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
====
. 在每个节点的控制台上，将 clus2 迁移到端口 e1a：
+
`network interface migrate`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
====
. 在每个节点的控制台上，验证是否进行了迁移：
+
`network interface show`

+
以下示例显示 clus2 已迁移到两个节点上的端口 e1a：

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
====




[[step-2-install-fastpath-software]]
=== 步骤2：安装FASTPATH软件

. 关闭两个节点上的集群端口 e2a：
+
`network port modify`

+
.显示示例
[%collapsible]
====
以下示例显示了在两个节点上关闭端口 e2a 的情况：

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 验证两个节点上的端口 e2a 是否已关闭：
+
`network port show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
====
. 关闭 cs1 上的交换机间链路 (ISL) 端口，活动 NetApp 交换机：
+
.显示示例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
====
. 备份 cs2 上的当前活动映像。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
====
. 将镜像文件下载到交换机。
+
将映像文件复制到活动映像意味着当您重新启动时，该映像将建立正在运行的 FASTPATH 版本。上一个映像仍可用作备份。

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. 确认正在运行的 FASTPATH 软件版本。
+
`show version`

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
====
. 查看活动和备份配置的启动映像。
+
`show bootvar`

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
====
. 重新启动交换机。
+
`reload`

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
====




[[step-3-validate-installation]]
=== 步骤 3：验证安装

. 重新登录，并验证新版本的 FASTPATH 软件。
+
`show version`

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
====
. 打开活动交换机 cs1 上的 ISL 端口。
+
`configure`

+
.显示示例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====
. 验证ISL是否正常运行：
+
`show port-channel 3/1`

+
Link State 字段应显示 `Up`。

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 当您对软件版本和交换机设置感到满意时，将 `running-config`文件复制到 `startup-config`文件。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
====
. 在每个节点上启用第二个集群端口 e2a：
+
`network port modify`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
====
. 还原与端口 e2a 关联的 clus2：
+
`network interface revert`

+
LIF可能会自动还原，具体取决于您的ONTAP软件版本。

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. 验证 LIF 现在是否在两个节点上均处于主位置（(`true`）：
+
`network interface show -_role cluster_`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. 查看节点的状态：
+
`cluster show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
====
. 重复前面的步骤，在另一台交换机 cs1 上安装 FASTPATH 软件。
. 如果您已禁用自动创建案例功能，请通过调用AutoSupport消息重新启用该功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`


