---
permalink: switch-netapp-cn1610/install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: 在 NetApp 交换机上安装 FastPath 软件时，必须从第二个交换机 CS2 开始升级。 
---
= 安装 FastPath 软件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在 NetApp 交换机上安装 FastPath 软件时，必须从第二个交换机 _CS2_ 开始升级。



== 查看要求

.您需要的内容
* 交换机配置的当前备份。
* 一个完全正常运行的集群(日志中没有错误、并且集群网络接口卡(NIC)没有缺陷或类似问题)。
* 集群交换机上功能完备的端口连接。
* 已设置所有集群端口。
* 已设置所有集群逻辑接口(LIF)(不得迁移)。
* 成功的通信路径：ONTAP (权限：高级) `cluster ping-cluster -node node1` 命令必须指明这一点 `larger than PMTU communication` 在所有路径上均成功。
* 支持的FastPath和ONTAP 版本。
+
请务必参考上的交换机兼容性表 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 交换机"^] 页面上显示了支持的快速路径和ONTAP 版本。





== 安装FastPath

以下操作步骤 使用集群模式Data ONTAP 8.2语法。因此、集群Vserver、LIF名称和命令行界面输出与Data ONTAP 8.3中的不同。

RCF 和 FastPath 版本中的命令语法之间可能存在命令依赖关系。

.关于示例
此操作步骤中的示例使用以下交换机和节点命名：

* 这两个 NetApp 交换机是 CS1 和 CS2 。
* 两个集群 LIF 分别为 clus1 和 clus2 。
* SVM 为 vs1 和 vs2 。
* `cluster ：：： * >` 提示符用于指示集群的名称。
* 每个节点上的集群端口分别命名为 e1a 和 e2a 。
+
https://hwu.netapp.com/["Hardware Universe"^] 提供有关您的平台支持的实际集群端口的详细信息。

* 支持的交换机间链路(ISL)为端口0/13到0/16。
* 支持的节点连接为端口0/1到0/12。




=== 第1步：迁移集群

. 如果在此集群上启用了 AutoSupport ，则通过调用 AutoSupport 消息禁止自动创建案例：
+
`ssystem node AutoSupport invoke -node * -type all - 消息 MAINT=xh`

+
_x_ 是维护时段的持续时间，以小时为单位。

+

NOTE: AutoSupport 消息会通知技术支持此维护任务，以便在维护窗口期间禁止自动创建案例。

. 以管理员身份登录到交换机。默认情况下没有密码。在 ` （ CS2 ） #` 提示符处，输入 `enable` 命令。同样，默认情况下不存在密码。这样，您就可以访问特权执行模式，从而可以配置网络接口。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
====
. 在每个节点的控制台上、将clus2迁移到端口e1a：
+
`网络接口迁移`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
====
. 在每个节点的控制台上、验证是否已进行迁移：
+
`network interface show`

+
以下示例显示 clus2 已迁移到两个节点上的端口 e1a ：

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
====




=== 第2步：安装FastPath软件

. 关闭两个节点上的集群端口E2A：
+
`network port modify`

+
.显示示例
[%collapsible]
====
以下示例显示了两个节点上的端口 E2A 均已关闭：

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 验证两个节点上的端口E2A是否均已关闭：
+
`network port show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
====
. 关闭处于活动状态的 NetApp 交换机 CS1 上的交换机间链路（ ISL ）端口：
+
.显示示例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
====
. 备份 CS2 上的当前活动映像。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
====
. 将映像文件下载到交换机。
+
将映像文件复制到活动映像意味着，重新启动时，该映像将建立正在运行的 FastPath 版本。上一个映像仍可用作备份。

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. 验证正在运行的 FastPath 软件版本。
+
`s如何使用版本`

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
====
. 查看活动配置和备份配置的启动映像。
+
`s如何启动 var`

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
====
. 重新启动交换机。
+
`re负载`

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
====




=== 第3步：验证安装

. 重新登录并验证新版本的 FastPath 软件。
+
`s如何使用版本`

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
====
. 启动活动交换机 CS1 上的 ISL 端口。
+
`配置`

+
.显示示例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====
. 验证 ISL 是否正常运行：
+
`s如何使用端口通道 3/1`

+
链路状态字段应指示 `up` 。

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 如果对软件版本和交换机设置满意，请将 `running-config` 文件复制到 `starstartup-config` 文件。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
====
. 在每个节点上启用第二个集群端口E2A：
+
`network port modify`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
====
. 还原与端口E2A关联的clus2：
+
`网络接口还原`

+
根据您的 ONTAP 软件版本， LIF 可能会自动还原。

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. 验证两个节点上的 LIF 现在是否为主（`true` ）：
+
`network interface show -_role cluster_`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. 查看节点的状态：
+
`cluster show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
====
. 重复上述步骤、在另一台交换机CS1上安装FastPath软件。
. 如果禁止自动创建案例，请通过调用 AutoSupport 消息重新启用它：
+
`ssystem node AutoSupport invoke -node * -type all -message MAINT=end`


