---
permalink: switch-netapp-cn1610/install-rcf-file.html 
sidebar: sidebar 
keywords: reference configuration, file ,install, cn1610, switch, install rcf 
summary: '安装参考配置文件 (RCF) 时，必须先将集群 LIF 从交换机 cs2 迁移出去。  RCF 安装并验证完成后，LIF 即可迁移回去。' 
---
= 在 CN1610 交换机上安装参考配置文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
请按照以下步骤安装参考配置文件 (RCF)。

在安装 RCF 之前，必须先将集群 LIF 从交换机 cs2 迁移出去。  RCF 安装并验证完成后，LIF 即可迁移回去。



== 审查要求

.开始之前
请确保您拥有以下物品：

* 交换机配置的当前备份。
* 一个功能齐全的集群（日志中没有错误，集群网络接口卡（NIC）也没有缺陷或类似问题）。
* 集群交换机上的端口连接功能齐全。
* 所有集群端口均已设置。
* 所有集群逻辑接口（LIF）均已设置。
* 一条成功的沟通路径： ONTAP （权限：高级） `cluster ping-cluster -node node1`命令必须表明 `larger than PMTU communication`在所有路径上都取得了成功。
* 受支持的 RCF 和ONTAP版本。
+
请务必查阅交换机兼容性表格。 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 交换机"^]本页列出了支持的 RCF 和ONTAP版本。





== 安装 RCF

以下步骤使用集群式Data ONTAP 8.2 语法。因此，集群 Vserver、LIF 名称和 CLI 输出与Data ONTAP 8.3 中的不同。

RCF 和 FASTPATH 版本中的命令语法可能存在命令依赖关系。


NOTE: 由于安全问题，RCF 版本 1.2 中已明确禁用对 Telnet 的支持。为避免在安装 RCF 1.2 时出现连接问题，请确认安全外壳 (SSH) 已启用。这 https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp CN1610 交换机管理员指南"^]包含更多关于 SSH 的信息。

.关于示例
本流程中的示例使用以下开关和节点命名规则：

* 这两台NetApp交换机分别是 cs1 和 cs2。
* 这两个簇 LIF 分别是 clus1 和 clus2。
* 虚拟服务器为 vs1 和 vs2。
* 这 `cluster::*>`prompt 指示集群名称。
* 每个节点上的集群端口分别命名为 e1a 和 e2a。
+
https://hwu.netapp.com/["Hardware Universe"^]包含有关您的平台支持的实际集群端口的更多信息。

* 支持的交换机间链路 (ISL) 为端口 0/13 至 0/16。
* 支持的节点连接为端口 0/1 至 0/12。
* 支持的 FASTPATH、RCF 和ONTAP版本。
+
请务必查阅交换机兼容性表格。 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 交换机"^]支持的 FASTPATH、RCF 和ONTAP版本页面。





=== 步骤 1：迁移集群

. 保存您当前的交换机配置信息：
+
`write memory`

+
.显示示例
[%collapsible]
====
以下示例展示了如何将当前交换机配置保存到启动配置中。(`startup-config` ) 文件在交换机 cs2 上：

[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 在每个节点的控制台上，将 clus2 迁移到端口 e1a：
+
`network interface migrate`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -source-node node1 -destnode node1 -dest-port e1a

cluster::*> network interface migrate -vserver vs2 -lif clus2 -source-node node2 -destnode node2 -dest-port e1a
----
====
. 在每个节点的控制台上，验证迁移是否已完成：
+
`network interface show -role cluster`

+
.显示示例
[%collapsible]
====
以下示例表明 clus2 已迁移到两个节点上的 e1a 端口：

[listing]
----
cluster::*> network port show -role cluster
         clus1      up/up      10.10.10.1/16   node2    e1a     true
         clus2      up/up      10.10.10.2/16   node2    e1a     false
----
====
. 关闭两个节点上的 e2a 端口：
+
`network port modify`

+
.显示示例
[%collapsible]
====
以下示例显示了两个节点上的 e2a 端口均已关闭：

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 请确认两个节点上的 e2a 端口均已关闭：
+
`network port show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                  Auto-Negot  Duplex      Speed (Mbps)
Node   Port   Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ------ -------- ---- ----- ----------- ----------  -----------
node1
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
node2
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
----
====
. 关闭活动NetApp交换机 cs1 上的 ISL 端口。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (interface 0/13-0/16) # shutdown
(cs1) (interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====




=== 步骤 2：安装 RCF

. 将 RCF 复制到交换机。
+

NOTE: 你必须设置 `.scr`在调用脚本之前，将文件扩展名作为文件名的一部分。此扩展程序是适用于 FASTPATH 操作系统的扩展程序。

+
交换机会在脚本下载到交换机时自动对其进行验证，并将输出结果输出到控制台。

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.10.0.1/CN1610_CS_RCF_v1.1.txt nvram:script CN1610_CS_RCF_v1.1.scr

[the script is now displayed line by line]
Configuration script validated.
File transfer operation completed successfully.
----
====
. 请确认脚本已下载并以您指定的文件名保存。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # script list
Configuration Script Name        Size(Bytes)
-------------------------------- -----------
running-config.scr               6960
CN1610_CS_RCF_v1.1.scr           2199

2 configuration script(s) found.
6038 Kbytes free.
----
====
. 验证脚本。
+

NOTE: 下载过程中会对脚本进行验证，以确保每一行都是有效的交换机命令行。

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # script validate CN1610_CS_RCF_v1.1.scr
[the script is now displayed line by line]
Configuration script 'CN1610_CS_RCF_v1.1.scr' validated.
----
====
. 将脚本应用到交换机上。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.1.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.1.scr' applied.
----
====
. 请确认您的更改已在交换机上生效。
+
[listing]
----
(cs2) # show running-config
----
+
该示例展示了 `running-config`文件在交换机上。您必须将该文件与 RCF 进行比较，以验证您设置的参数是否符合预期。

. 保存更改。
. 设置 `running-config`文件将成为标准文件。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.
----
====
. 重启交换机并验证 `running-config`文件正确。
+
重启完成后，您必须登录并查看 `running-config`然后查找文件，并在接口 3/64 上查找描述，这是 RCF 的版本标签。

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # reload

The system has unsaved changes.
Would you like to save them now? (y/n) y


Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. 在活动交换机 cs1 上启用 ISL 端口。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config)# interface 0/13-0/16
(cs1) (Interface 0/13-0/16)# no shutdown
(cs1) (Interface 0/13-0/16)# exit
(cs1) (config)# exit
----
====
. 确认ISL是否正常运行：
+
`show port-channel 3/1`

+
“链路状态”字段应指示 `Up`。

+
.显示示例
[%collapsible]
====
[listing]
----

(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 在两个节点上启动集群端口 e2a：
+
`network port modify`

+
.显示示例
[%collapsible]
====
以下示例展示了如何在节点 1 和节点 2 上启动端口 e2a：

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====




=== 步骤 3：验证安装

. 请确认两个节点上的 e2a 端口均已启动：
+
`network port show -_role cluster_`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- ----  ----------- ----------  ------------
node1
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
----
====
. 在两个节点上，还原与端口 e2a 关联的 clus2：
+
`network interface revert`

+
LIF 可能会自动恢复，具体取决于您的ONTAP版本。

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
. 确认 LIF 现在已归位(`true`）在两个节点上：
+
`network interface show -_role cluster_`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

        Logical    Status     Network        Current  Current Is
Vserver Interface  Admin/Oper Address/Mask   Node     Port    Home
------- ---------- ---------- -------------- -------- ------- ----
vs1
        clus1      up/up      10.10.10.1/24  node1    e1a     true
        clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
        clus1      up/up      10.10.10.1/24  node2    e1a     true
        clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. 查看节点成员的状态：
+
`cluster show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node           Health  Eligibility
-------------- ------- ------------
node1
               true    true
node2
               true    true
----
====
. 复制 `running-config`文件到 `startup-config`当您对软件版本和开关设置满意后，请提交文件。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 重复上述步骤，在另一台交换机 cs1 上安装 RCF。


.下一步是什么？
link:../switch-cshm/config-overview.html["配置交换机健康监控"]
