---
permalink: switch-netapp-cn1610/install-rcf-file.html 
sidebar: sidebar 
keywords: reference configuration, file ,install, cn1610, switch, install rcf 
summary: 在安装参考配置文件（ RCF ）时，必须先将集群 LIF 从交换机 CS2 迁移出。安装并验证 RCF 后，可以将 LIF 迁移回。 
---
= 在 CN1610 交换机上安装参考配置文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照此操作步骤 安装参考配置文件(RCF)。

在安装RCF之前、必须先将集群LIF从交换机CS2迁移出来。安装并验证 RCF 后，可以将 LIF 迁移回。



== 查看要求

.您需要的内容
* 交换机配置的当前备份。
* 一个完全正常运行的集群(日志中没有错误、并且集群网络接口卡(NIC)没有缺陷或类似问题)。
* 集群交换机上功能完备的端口连接。
* 已设置所有集群端口。
* 已设置所有集群逻辑接口(LIF)。
* 成功的通信路径：ONTAP (权限：高级) `cluster ping-cluster -node node1` 命令必须指明这一点 `larger than PMTU communication` 在所有路径上均成功。
* 受支持的RCF和ONTAP 版本。
+
请务必参考上的交换机兼容性表 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 交换机"^] 页面上显示了受支持的RCF和ONTAP 版本。





== 安装RCF

以下操作步骤 使用集群模式Data ONTAP 8.2语法。因此、集群Vserver、LIF名称和命令行界面输出与Data ONTAP 8.3中的不同。

RCF 和 FastPath 版本中的命令语法之间可能存在命令依赖关系。


NOTE: 在 RCF 1.2 版中，出于安全考虑，已明确禁用对 Telnet 的支持。要在安装RCF 1.2时避免连接问题、请验证是否已启用安全外壳(SSH)。。 https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["《NetApp CN1610交换机管理员指南》"^] 了解有关 SSH 的详细信息。

.关于示例
此操作步骤中的示例使用以下交换机和节点命名：

* 这两个 NetApp 交换机是 CS1 和 CS2 。
* 两个集群 LIF 分别为 clus1 和 clus2 。
* SVM 为 vs1 和 vs2 。
* `cluster ：：： * >` 提示符用于指示集群的名称。
* 每个节点上的集群端口分别命名为 e1a 和 e2a 。
+
https://hwu.netapp.com/["Hardware Universe"^] 提供有关您的平台支持的实际集群端口的详细信息。

* 支持的交换机间链路(ISL)为端口0/13到0/16。
* 支持的节点连接为端口0/1到0/12。
* 受支持的FastPath、RCF和ONTAP 版本。
+
请务必参考上的交换机兼容性表 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 交换机"^] 页面上显示了受支持的 FastPath ， RCF 和 ONTAP 版本。





=== 第1步：迁移集群

. 保存当前交换机配置信息：
+
`写入内存`

+
.显示示例
[%collapsible]
====
以下示例显示了要保存到交换机 CS2 上的启动配置（ `starstartup-config` ）文件中的当前交换机配置：

[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 在每个节点的控制台上、将clus2迁移到端口e1a：
+
`网络接口迁移`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -source-node node1 -destnode node1 -dest-port e1a

cluster::*> network interface migrate -vserver vs2 -lif clus2 -source-node node2 -destnode node2 -dest-port e1a
----
====
. 在每个节点的控制台上、验证是否已进行迁移：
+
`network interface show -role cluster`

+
.显示示例
[%collapsible]
====
以下示例显示 clus2 已迁移到两个节点上的端口 e1a ：

[listing]
----
cluster::*> network port show -role cluster
         clus1      up/up      10.10.10.1/16   node2    e1a     true
         clus2      up/up      10.10.10.2/16   node2    e1a     false
----
====
. 关闭两个节点上的端口E2A：
+
`network port modify`

+
.显示示例
[%collapsible]
====
以下示例显示了两个节点上的端口 E2A 均已关闭：

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 验证两个节点上的端口E2A是否均已关闭：
+
`network port show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                  Auto-Negot  Duplex      Speed (Mbps)
Node   Port   Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ------ -------- ---- ----- ----------- ----------  -----------
node1
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
node2
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
----
====
. 关闭活动 NetApp 交换机 CS1 上的 ISL 端口。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (interface 0/13-0/16) # shutdown
(cs1) (interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====




=== 第2步：安装RCF

. 将 RCF 复制到交换机。
+

NOTE: 在调用脚本之前，必须将 ` .scr` 扩展名设置为文件名的一部分。此扩展是 FastPath 操作系统的扩展。

+
将脚本下载到交换机后，交换机将自动验证该脚本，输出将转到控制台。

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.10.0.1/CN1610_CS_RCF_v1.1.txt nvram:script CN1610_CS_RCF_v1.1.scr

[the script is now displayed line by line]
Configuration script validated.
File transfer operation completed successfully.
----
====
. 验证脚本是否已使用您为其提供的文件名下载并保存。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # script list
Configuration Script Name        Size(Bytes)
-------------------------------- -----------
running-config.scr               6960
CN1610_CS_RCF_v1.1.scr           2199

2 configuration script(s) found.
6038 Kbytes free.
----
====
. 验证脚本。
+

NOTE: 此脚本会在下载期间进行验证，以验证每行是否为有效的交换机命令行。

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # script validate CN1610_CS_RCF_v1.1.scr
[the script is now displayed line by line]
Configuration script 'CN1610_CS_RCF_v1.1.scr' validated.
----
====
. 将此脚本应用于交换机。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.1.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.1.scr' applied.
----
====
. 验证您的更改是否已在交换机上实施。
+
[listing]
----
(cs2) # show running-config
----
+
此示例显示了交换机上的 `running-config` 文件。您必须将文件与 RCF 进行比较，以验证设置的参数是否符合预期。

. 保存更改。
. 将 `running-config` 文件设置为标准文件。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.
----
====
. 重新启动交换机并验证 `running-config` 文件是否正确。
+
重新启动完成后，您必须登录并查看 `running-config` 文件，然后在接口 3/64 上查找问题描述 ，该接口是 RCF 的版本标签。

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # reload

The system has unsaved changes.
Would you like to save them now? (y/n) y


Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. 启动活动交换机 CS1 上的 ISL 端口。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config)# interface 0/13-0/16
(cs1) (Interface 0/13-0/16)# no shutdown
(cs1) (Interface 0/13-0/16)# exit
(cs1) (config)# exit
----
====
. 验证 ISL 是否正常运行：
+
`s如何使用端口通道 3/1`

+
链路状态字段应指示 `up` 。

+
.显示示例
[%collapsible]
====
[listing]
----

(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 在两个节点上启动集群端口E2A：
+
`network port modify`

+
.显示示例
[%collapsible]
====
以下示例显示了 node1 和 node2 上正在启动的端口 E2A ：

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====




=== 第3步：验证安装

. 验证两个节点上的端口E2A是否均已启动：
+
`network port show -_role cluster_`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- ----  ----------- ----------  ------------
node1
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
----
====
. 在两个节点上、还原与端口E2A关联的clus2：
+
`网络接口还原`

+
根据您的 ONTAP 版本， LIF 可能会自动还原。

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
. 验证两个节点上的 LIF 现在是否为主（`true` ）：
+
`network interface show -_role cluster_`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

        Logical    Status     Network        Current  Current Is
Vserver Interface  Admin/Oper Address/Mask   Node     Port    Home
------- ---------- ---------- -------------- -------- ------- ----
vs1
        clus1      up/up      10.10.10.1/24  node1    e1a     true
        clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
        clus1      up/up      10.10.10.1/24  node2    e1a     true
        clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. 查看节点成员的状态：
+
`cluster show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node           Health  Eligibility
-------------- ------- ------------
node1
               true    true
node2
               true    true
----
====
. 如果对软件版本和交换机设置满意，请将 `running-config` 文件复制到 `starstartup-config` 文件。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 重复上述步骤、在另一台交换机CS1上安装RCF。

