---
permalink: switch-netapp-cn1610/install-rcf-file.html 
sidebar: sidebar 
keywords: reference configuration, file ,install, cn1610, switch, install rcf 
summary: 在安装参考配置文件 RCF 时，必须首先从交换机 cs2 迁移集群 LIF。在安装和验证 RCF 后，可以将 LIF 迁回。 
---
= 在 CN1610 交换机上安装参考配置文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照此步骤安装参考配置文件(RCF)。

在安装 RCF 之前，您必须首先将集群 LIF 从交换机 cs2 迁移出去。安装并验证 RCF 后，可以将 LIF 迁回。



[[review-requirements]]
== 审查要求

.开始之前
请确保您拥有以下物品：

* 交换机配置的当前备份。
* 完全正常运行的集群（日志中没有错误，也没有故障的集群网络接口卡 (NIC) 或类似问题）。
* 集群交换机上功能齐全的端口连接。
* 已设置所有集群端口。
* 已设置所有集群逻辑接口 (LIF)。
* 成功的通信路径：ONTAP (privilege: advanced) `cluster ping-cluster -node node1` 命令必须指示 `larger than PMTU communication`在所有路径上均成功。
* 受支持版本的 RCF 和 ONTAP。
+
请务必查阅 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 开关"^]页面上的交换机兼容性表，以了解支持的 RCF 和 ONTAP 版本。





[[install-the-rcf]]
== 安装 RCF

以下过程使用集群模式 Data ONTAP 8.2 语法。因此，集群 Vserver、LIF 名称和 CLI 输出与 Data ONTAP 8.3 中的不同。

RCF 和 FASTPATH 版本中的命令语法之间可能存在命令依赖关系。


NOTE: 在 RCF 1.2 版中，由于安全问题，已明确禁用对 Telnet 的支持。要避免在安装 RCF 1.2 时出现连接问题，请验证已启用 Secure Shell (SSH)。有关 SSH 的更多信息，请参阅 https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp CN1610 交换机管理员指南"^]。

.关于示例
本流程中的示例使用以下开关和节点命名规则：

* 这两个 NetApp 交换机是 cs1 和 cs2。
* 两个集群 LIF 是 clus1 和 clus2。
* Vserver 是 vs1 和 vs2。
* The `cluster::*>` 提示符指示集群的名称。
* 每个节点上的集群端口命名为 e1a 和 e2a。
+
link:https://hwu.netapp.com/["Hardware Universe"^] 包含有关您平台上支持的实际集群端口的更多信息。

* 支持的交换机间链路 (ISL) 是端口 0/13 到 0/16。
* 支持的节点连接为端口 0/1 至 0/12。
* 支持的 FASTPATH、RCF 和 ONTAP 版本。
+
请务必查阅 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 开关"^]页面上的交换机兼容性表，以了解受支持的 FASTPATH、RCF 和 ONTAP 版本。





[[step-1-migrate-cluster]]
=== 步骤 1：迁移集群

. 保存您当前的交换机配置信息：
+
`write memory`

+
.显示示例
[%collapsible]
====
以下示例显示了将当前交换机配置保存到交换机 cs2 上的启动配置(`startup-config`）文件的操作：

[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 在每个节点的控制台上，将 clus2 迁移到端口 e1a：
+
`network interface migrate`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -source-node node1 -destnode node1 -dest-port e1a

cluster::*> network interface migrate -vserver vs2 -lif clus2 -source-node node2 -destnode node2 -dest-port e1a
----
====
. 在每个节点的控制台上，验证是否发生迁移：
+
`network interface show -role cluster`

+
.显示示例
[%collapsible]
====
以下示例显示 clus2 已迁移到两个节点上的端口 e1a：

[listing]
----
cluster::*> network port show -role cluster
         clus1      up/up      10.10.10.1/16   node2    e1a     true
         clus2      up/up      10.10.10.2/16   node2    e1a     false
----
====
. 关闭两个节点上的端口 e2a：
+
`network port modify`

+
.显示示例
[%collapsible]
====
以下示例显示了在两个节点上关闭端口 e2a 的情况：

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 验证两个节点上的端口 e2a 是否已关闭：
+
`network port show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                  Auto-Negot  Duplex      Speed (Mbps)
Node   Port   Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ------ -------- ---- ----- ----------- ----------  -----------
node1
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
node2
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
----
====
. 关闭活动 NetApp 交换机 cs1 上的 ISL 端口。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (interface 0/13-0/16) # shutdown
(cs1) (interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====




[[step-2-install-rcf]]
=== 步骤 2：安装 RCF

. 将 RCF 复制到交换机。
+

NOTE: 在调用脚本之前，必须将 `.scr`扩展名设置为文件名的一部分。此扩展名是 FASTPATH 操作系统的扩展名。

+
当脚本下载到交换机时，交换机将自动验证该脚本，输出将传输到控制台。

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.10.0.1/CN1610_CS_RCF_v1.1.txt nvram:script CN1610_CS_RCF_v1.1.scr

[the script is now displayed line by line]
Configuration script validated.
File transfer operation completed successfully.
----
====
. 验证脚本是否已下载并以您指定的文件名保存。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # script list
Configuration Script Name        Size(Bytes)
-------------------------------- -----------
running-config.scr               6960
CN1610_CS_RCF_v1.1.scr           2199

2 configuration script(s) found.
6038 Kbytes free.
----
====
. 验证脚本。
+

NOTE: 该脚本在下载过程中经过验证，以确认每行都是有效的交换机命令行。

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # script validate CN1610_CS_RCF_v1.1.scr
[the script is now displayed line by line]
Configuration script 'CN1610_CS_RCF_v1.1.scr' validated.
----
====
. 将该脚本应用到该交换机。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.1.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.1.scr' applied.
----
====
. 验证您的更改是否已在交换机上实施。
+
[listing]
----
(cs2) # show running-config
----
+
该示例在交换机上显示该 `running-config`文件。您必须将该文件与 RCF 进行比较，以验证您设置的参数是否符合预期。

. 保存更改。
. 将 `running-config`文件设置为标准文件。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.
----
====
. 重新启动交换机并验证 `running-config`文件是否正确。
+
重新启动完成后，必须登录，查看 `running-config`文件，然后在接口 3/64 上查找说明，该接口是 RCF 的版本标签。

+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # reload

The system has unsaved changes.
Would you like to save them now? (y/n) y


Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. 打开活动交换机 cs1 上的 ISL 端口。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config)# interface 0/13-0/16
(cs1) (Interface 0/13-0/16)# no shutdown
(cs1) (Interface 0/13-0/16)# exit
(cs1) (config)# exit
----
====
. 验证ISL是否正常运行：
+
`show port-channel 3/1`

+
Link State 字段应显示 `Up`。

+
.显示示例
[%collapsible]
====
[listing]
----

(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 在两个节点上打开集群端口 e2a：
+
`network port modify`

+
.显示示例
[%collapsible]
====
以下示例显示端口 e2a 在 node1 和 node2 上启动：

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====




[[step-3-validate-installation]]
=== 步骤 3：验证安装

. 确认端口 e2a 在两个节点上都处于打开状态：
+
`network port show -_role cluster_`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- ----  ----------- ----------  ------------
node1
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
----
====
. 在两个节点上，恢复与端口 e2a 关联的 clus2：
+
`network interface revert`

+
LIF 可能会自动还原，具体取决于您的 ONTAP 版本。

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
. 验证 LIF 现在是否在两个节点上均处于主位置（(`true`）：
+
`network interface show -_role cluster_`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

        Logical    Status     Network        Current  Current Is
Vserver Interface  Admin/Oper Address/Mask   Node     Port    Home
------- ---------- ---------- -------------- -------- ------- ----
vs1
        clus1      up/up      10.10.10.1/24  node1    e1a     true
        clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
        clus1      up/up      10.10.10.1/24  node2    e1a     true
        clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. 查看节点成员的状态：
+
`cluster show`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node           Health  Eligibility
-------------- ------- ------------
node1
               true    true
node2
               true    true
----
====
. 当您对软件版本和交换机设置感到满意时，将 `running-config`文件复制到 `startup-config`文件。
+
.显示示例
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 重复上述步骤，在另一台交换机 cs1 上安装 RCF。


.下一步是什么？
link:../switch-cshm/config-overview.html["配置交换机健康监控"]
