---
permalink: switch-netapp-cn1610/migrate-fas22xx-systems.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, fas22xx systems, single, network connection 
summary: 如果您在现有的双节点无交换机集群中拥有 FAS22xx 系统，其中每个控制器模块都有一个用于集群连接的单条背靠背 10 GbE 连接，则可以使用无交换机集群联网选项，并将直接背靠背连接替换为交换机连接。 
---
= 在 FAS22xx 系统中，使用单个集群网络连接迁移到双节点交换集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您在现有的双节点无交换机集群中拥有 FAS22xx 系统，其中每个控制器模块都有一个用于集群连接的单条背靠背 10 GbE 连接，则可以使用无交换机集群联网选项，并将直接背靠背连接替换为交换机连接。



== 审查要求

.开始之前
请确保您拥有以下物品：

* 两个集群连接，用于从无交换机配置迁移到有交换机配置。
* 集群运行状况良好，由两个通过背靠背连接连接的节点组成。
* 节点运行的是ONTAP 8.2 或更高版本。
* 无交换机集群功能不能用于两个以上的节点。
* 所有集群端口都在 `up`状态。


.相关信息
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetApp 知识库文章 1010449：如何在计划的维护时间段禁止自动创建案例"^]



== 迁移交换机

该过程是一个非中断性过程，它在无交换机环境中移除直接集群连接，并将每个与交换机的连接替换为与伙伴节点的连接。



=== 步骤 1：准备迁移

. 将权限级别更改为高级，输入 `y`当系统提示继续时：
+
`set -privilege advanced`

+
高级提示(`*>`出现。

. 在任一节点的系统控制台上检查节点的集群状态：
+
`cluster show`

+
.显示示例
[%collapsible]
====
以下示例显示了集群中节点的健康状况和资格信息：

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. 在任一节点的系统控制台上检查HA对的状态： `storage failover show`
+
.显示示例
[%collapsible]
====
以下示例显示了节点 1 和节点 2 的状态：

[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
====
. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
`x`是维护窗口的持续时间，以小时为单位。

+

NOTE: 该消息通知技术支持部门此维护任务，以便在维护期间禁止自动创建案例。

+
.显示示例
[%collapsible]
====
以下命令可抑制自动创建案件两小时：

[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
====
. 确认无交换机集群的当前状态为： `true`然后禁用无开关集群模式：
+
`network options switchless-cluster modify -enabled false`

. 接管目标节点：
+
`storage failover takeover -ofnode _target_node_name_`

+
哪个节点是目标节点并不重要。当目标节点被接管后，它会自动重启并显示以下内容： `Waiting for giveback...`信息。

+
当前活动节点正在为被接管的伙伴（目标）节点提供数据服务。

. 接管受损节点后，请等待两分钟以确认接管已成功完成。
. 目标节点显示 `Waiting for giveback...`消息已发送，请关闭。
+
关闭节点的方法取决于您是否通过节点服务处理器（SP）进行远程管理。

+
|===
| 如果SP | 操作 


 a| 
已配置
 a| 
登录到出现故障的节点SP，然后关闭系统电源： `system power off`



 a| 
未配置
 a| 
在出现故障节点提示时，按 `Ctrl-C`然后回应 `y`停止节点运行。

|===




=== 步骤 2：配置线缆和端口

. 在每个控制器模块上，断开将 10 GbE 集群端口连接到无交换机集群的电缆。
. 将两个控制器模块上的 10 GbE 集群端口连接到交换机。
. 确认交换机上连接的 10 GbE 集群端口配置为属于同一个 VLAN。
+
如果您计划将每个控制器模块上的集群端口连接到不同的交换机，则必须验证每个交换机上连接集群端口的端口是否配置为相同的 VLAN，以及两个交换机上是否正确配置了链路聚合。

. 将存储空间返还给目标节点：
+
`storage failover giveback -ofnode node2`

. 监控回馈活动的进展情况：
+
`storage failover show-giveback`

. 交还操作完成后，确认HA对运行正常且可以接管：
+
`storage failover show`

+
.显示示例
[%collapsible]
====
输出结果应与以下内容类似：

[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
====
. 验证集群端口 LIF 是否正常工作：
+
`network interface show -role cluster`

+
.显示示例
[%collapsible]
====
以下示例表明 LIF 是 `up`在节点 1 和节点 2 上，“是否在家”列的结果是 `true`：

[listing]
----

cluster::*> network interface show -role cluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
node1
            clus1        up/up    192.168.177.121/24  node1        e1a     true
node2
            clus1        up/up    192.168.177.123/24  node2        e1a     true

2 entries were displayed.
----
====
. 在任一节点的系统控制台上检查节点的集群状态：
+
`cluster show`

+
.显示示例
[%collapsible]
====
以下示例显示了集群中节点的健康状况和资格信息：

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. 验证远程集群接口的连接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`执行命令以启动集群连接性检查，然后显示详细信息：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*运行程序前请等待几秒钟 `show`显示详细信息的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有ONTAP版本
--
对于所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`检查连接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====


=== 步骤 3：完成该步骤

. 如果您已禁用自动创建案例功能，请通过调用AutoSupport消息重新启用该功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
. 将权限级别改回管理员：
+
`set -privilege admin`


