---
permalink: switch-netapp-cn1610/migrate-switched-netapp-cn1610.html 
sidebar: sidebar 
keywords: migrate, switchless cluster environment, switched netapp cn1610 
summary: 使用 NetApp CN1610 集群交换机从双节点无交换机集群迁移到交换机集群环境。 
---
= 从无交换机集群迁移到使用 NetApp CN1610 交换机的集群环境
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 NetApp CN1610 集群交换机从双节点无交换机集群环境迁移到有交换机集群环境。此迁移使您能够将集群扩展到两个节点以上。



[[review-requirements]]
== 审查要求

.开始之前
请确保您拥有以下物品：

对于双节点无开关配置，请确保：

* 双节点无交换机配置已正确设置并运行正常。
* 此节点正在运行 ONTAP 8.2 或更高版本。
* 所有集群端口都处于 `up`状态。
* 所有集群逻辑接口（LIF）都处于 `up`状态并位于其主端口上。


对于 CN1610 集群交换机配置：

* CN1610集群交换机基础架构在两台交换机上均可完全运行。
* 两台交换机都具备管理网络连接功能。
* 可以通过控制台访问集群交换机。
* CN1610 节点到节点交换机和交换机到交换机连接使用双轴或光纤电缆。
+
link:https://hwu.netapp.com/["Hardware Universe"^] 包含有关布线的详细信息。

* 交换机间链路 (ISL) 电缆连接到两个 CN1610 交换机上的端口 13 至 16。
* 两台 CN1610 交换机的初始自定义均已完成。
+
任何以前的站点自定义（例如 SMTP、SNMP 和 SSH）应复制到新交换机。



.相关信息
* link:http://hwu.netapp.com["Hardware Universe"^]
* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 和 CN1610"]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMP1118645["CN1601 和 CN1610 交换机设置和配置"^]
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetApp 知识库文章 1010449：如何在计划的维护时间段禁止自动创建案例"^]




[[migrate-the-switches]]
== 迁移交换机

.关于示例
本流程中的示例使用以下集群交换机和节点命名规则：

* CN1610 交换机的名称为 cs1 和 cs2。
* LIF 的名称是 clus1 和 clus2。
* 节点名称为 node1 和 node2。
* The `cluster::*>` 提示符指示集群的名称。
* 此过程中使用的集群端口为 e1a 和 e2a。
+
link:https://hwu.netapp.com/["Hardware Universe"^] 包含有关平台的实际集群端口的最新信息。





[[step-1-prepare-for-migration]]
=== 步骤 1：准备迁移

. 将权限级别更改为高级，输入 `y`当系统提示继续时：
+
`set -privilege advanced`

+
出现高级提示符（*>）。

. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
_x_ 是维护窗口的持续时间，单位为小时。

+

NOTE: AutoSupport消息会通知技术支持此维护任务，以便在维护窗口期间抑制自动创建案例。

+
.显示示例
[%collapsible]
====
以下命令可抑制自动创建案件两小时：

[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
====




[[step-2-configure-ports]]
=== 步骤 2：配置端口

. 禁用新集群交换机 cs1 和 cs2 上的所有面向节点的端口（而非 ISL 端口）。
+
您不得禁用 ISL 端口。

+
.显示示例
[%collapsible]
====
以下示例显示交换机 cs1 上面向节点的端口 1 到 12 已禁用：

[listing]
----

(cs1)> enable
(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
以下示例显示交换机 cs2 上面向节点的端口 1 到 12 已禁用：

[listing]
----

(c2)> enable
(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
====
. 验证两个 CN1610 集群交换机 cs1 和 cs2 之间的 ISL 和 ISL 上的物理端口是否为 `up`：
+
`show port-channel`

+
.显示示例
[%collapsible]
====
以下示例显示 ISL 端口位于交换机 cs1 上 `up`：

[listing]
----

(cs1)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
以下示例显示 ISL 端口位于交换机 cs2 `up` 上：

[listing]
----

(cs2)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 显示相邻设备列表：
+
`show isdp neighbors`

+
此命令提供有关连接到系统的设备的信息。

+
.显示示例
[%collapsible]
====
以下示例列出了交换机 cs1 上的相邻设备：

[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16
----
以下示例列出了交换机 cs2 上的相邻设备：

[listing]
----

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
====
. 显示集群端口列表：
+
`network port show`

+
.显示示例
[%collapsible]
====
以下示例显示了可用的群集端口：

[listing]
----

cluster::*> network port show -ipspace Cluster
Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false
12 entries were displayed.
----
====
. 验证每个集群端口均连接到其伙伴集群节点上的相应端口：
+
`run * cdpd show-neighbors`

+
.显示示例
[%collapsible]
====
以下示例显示了集群端口 e1a 和 e2a 连接到其集群伙伴节点上的同一端口：

[listing]
----

cluster::*> run * cdpd show-neighbors
2 entries were acted on.

Node: node1
Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node2           e1a                    FAS3270           137   H
e2a    node2           e2a                    FAS3270           137   H


Node: node2

Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node1           e1a                    FAS3270           161   H
e2a    node1           e2a                    FAS3270           161   H
----
====
. 验证所有集群 LIF 是否 `up`正常运行：
+
`network interface show -vserver Cluster`

+
每个集群 LIF 都应在 "`Is Home`" 列中显示 `true`。

+
.显示示例
[%collapsible]
====
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up      10.10.10.1/16 node1         e1a     true
            clus2      up/up      10.10.10.2/16 node1         e2a     true
node2
            clus1      up/up      10.10.11.1/16 node2         e1a     true
            clus2      up/up      10.10.11.2/16 node2         e2a     true

4 entries were displayed.
----
====
+

NOTE: 步骤 10 至 13 中的以下修改和迁移命令必须从本地节点执行。

. 验证所有群集端口是否均为 `up`：
+
`network port show -ipspace Cluster`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> network port show -ipspace Cluster

                                       Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link  MTU   Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ----- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. 将两个节点上的集群 LIF clus1 和 clus2 的 `-auto-revert`参数设置为 `false`：
+
`network interface modify`

+
.显示示例
[%collapsible]
====
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert false
----
====
+

NOTE: 对于 8.3 版及更高版本，请使用以下命令： `network interface modify -vserver Cluster -lif * -auto-revert false`

. 验证远程集群接口的连接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`执行命令以启动集群连接性检查，然后显示详细信息：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*运行程序前请等待几秒钟 `show`显示详细信息的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有ONTAP版本
--
对于所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`检查连接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step10]] 将 clus1 迁移到每个节点控制台上的端口 e2a：
+
`network interface migrate`

+
.显示示例
[%collapsible]
====
以下示例显示了将 clus1 迁移到 node1 和 node2 上的端口 e2a 的过程：

[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus1 -source-node node1 -dest-node node1 -dest-port e2a
cluster::*> network interface migrate -vserver node2 -lif clus1 -source-node node2 -dest-node node2 -dest-port e2a
----
====
+

NOTE: 对于 8.3 版及更高版本，请使用以下命令： `network interface migrate -vserver Cluster -lif clus1 -destination-node node1 -destination-port e2a`

. 验证是否已进行迁移：
+
`network interface show -vserver Cluster`

+
.显示示例
[%collapsible]
====
以下示例验证 clus1 是否已迁移到 node1 和 node2 上的端口 e2a：

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e2a     false
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e2a     false
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
====
. 关闭两个节点上的集群端口 e1a：
+
`network port modify`

+
.显示示例
[%collapsible]
====
以下示例显示了如何关闭 node1 和 node2 上的端口 e1a：

[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin false
cluster::*> network port modify -node node2 -port e1a -up-admin false
----
====
. 验证端口状态：
+
`network port show`

+
.显示示例
[%collapsible]
====
以下示例显示端口 e1a 位于 node1 和 node2 `down`上：

[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. 断开 node1 上集群端口 e1a 的电缆，然后使用 CN1610 交换机支持的相应电缆将 e1a 连接到集群交换机 cs1 上的端口 1。
+
link:https://hwu.netapp.com/Switch/Index["Hardware Universe"^] 包含有关布线的详细信息。

. 断开 node2 上集群端口 e1a 的电缆，然后使用 CN1610 交换机支持的相应电缆将 e1a 连接到集群交换机 cs1 上的端口 2。
. 启用集群交换机 cs1 上所有面向节点的端口。
+
.显示示例
[%collapsible]
====
以下示例显示交换机 cs1 上的端口 1 到 12 已启用：

[listing]
----

(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# no shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
====
. 在每个节点上启用第一个集群端口 e1a：
+
`network port modify`

+
.显示示例
[%collapsible]
====
以下示例显示了如何在 node1 和 node2 上启用端口 e1a：

[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin true
cluster::*> network port modify -node node2 -port e1a -up-admin true
----
====
. 验证所有群集端口是否均为 `up`：
+
`network port show -ipspace Cluster`

+
.显示示例
[%collapsible]
====
以下示例显示了所有集群端口都在 node1 和 node2 `up` 上：

[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. 在两个节点上将 clus1（先前已迁移）还原为 e1a：
+
`network interface revert`

+
.显示示例
[%collapsible]
====
以下示例显示了如何将 clus1 还原为 node1 和 node2 上的端口 e1a：

[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus1
cluster::*> network interface revert -vserver node2 -lif clus1
----
====
+

NOTE: 对于 8.3 版及更高版本，请使用以下命令： `network interface revert -vserver Cluster -lif <nodename_clus<N>>`

. 验证所有集群 LIF 是否均 `up`、正常运行，并在 "Is Home" 列中显示为 `true`：
+
`network interface show -vserver Cluster`

+
.显示示例
[%collapsible]
====
以下示例显示所有 LIF 都在 node1 和 node2 `up`上，并且"Is Home"列结果为 `true`：

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
====
. 显示集群中节点的状态信息：
+
`cluster show`

+
.显示示例
[%collapsible]
====
以下示例显示了集群中节点的健康状况和资格信息：

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. 将 clus2 迁移到每个节点控制台上的端口 e1a：
+
`network interface migrate`

+
.显示示例
[%collapsible]
====
以下示例显示了将 clus2 迁移到 node1 和 node2 上的端口 e1a 的过程：

[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus2 -source-node node1 -dest-node node1 -dest-port e1a
cluster::*> network interface migrate -vserver node2 -lif clus2 -source-node node2 -dest-node node2 -dest-port e1a
----
====
+

NOTE: 对于 8.3 版及更高版本，请使用以下命令： `network interface migrate -vserver Cluster -lif node1_clus2 -dest-node node1 -dest-port e1a`

. 验证是否已进行迁移：
+
`network interface show -vserver Cluster`

+
.显示示例
[%collapsible]
====
以下示例验证 clus2 是否已迁移到 node1 和 node2 上的端口 e1a：

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e1a     false
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e1a     false

4 entries were displayed.
----
====
. 关闭两个节点上的集群端口 e2a：
+
`network port modify`

+
.显示示例
[%collapsible]
====
以下示例显示了如何关闭 node1 和 node2 上的端口 e2a：

[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 验证端口状态：
+
`network port show`

+
.显示示例
[%collapsible]
====
以下示例显示端口 e2a 在 node1 和 node2 上 `down`：

[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. 断开 node1 上集群端口 e2a 的电缆，然后使用 CN1610 交换机支持的相应电缆将 e2a 连接到集群交换机 cs2 上的端口 1。
. 断开节点2上集群端口e2a的电缆，然后使用CN1610交换机支持的相应电缆将e2a连接到集群交换机cs2上的端口2。
. 启用集群交换机 cs2 上所有面向节点的端口。
+
.显示示例
[%collapsible]
====
以下示例显示交换机 cs2 上的端口 1 到 12 已启用：

[listing]
----

(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# no shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
====
. 在每个节点上启用第二个集群端口 e2a。
+
.显示示例
[%collapsible]
====
以下示例显示了如何在 node1 和 node2 上启用端口 e2a：

[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====
. 验证所有群集端口是否均为 `up`：
+
`network port show -ipspace Cluster`

+
.显示示例
[%collapsible]
====
以下示例显示了所有集群端口都在 node1 和 node2 `up` 上：

[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. 在两个节点上将 clus2（先前已迁移）还原为 e2a：
+
`network interface revert`

+
.显示示例
[%collapsible]
====
以下示例显示了如何将 clus2 还原为 node1 和 node2 上的端口 e2a：

[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
+

NOTE: 对于 8.3 版及更高版本，命令包括：
`cluster::*> network interface revert -vserver Cluster -lif node1_clus2`和
`cluster::*> network interface revert -vserver Cluster -lif node2_clus2`





[[step-3-complete-the-configuration]]
=== 步骤 3：完成配置

. 验证所有接口在"Is Home"列中均显示 `true`：
+
`network interface show -vserver Cluster`

+
.显示示例
[%collapsible]
====
以下示例显示所有 LIF 都在 node1 和 node2 `up`上，并且"Is Home"列结果为 `true`：

[listing]
----

cluster::*> network interface show -vserver Cluster

             Logical    Status     Network            Current     Current Is
Vserver      Interface  Admin/Oper Address/Mask       Node        Port    Home
-----------  ---------- ---------- ------------------ ----------- ------- ----
node1
             clus1      up/up      10.10.10.1/16      node1       e1a     true
             clus2      up/up      10.10.10.2/16      node1       e2a     true
node2
             clus1      up/up      10.10.11.1/16      node2       e1a     true
             clus2      up/up      10.10.11.2/16      node2       e2a     true
----
====
. 验证远程集群接口的连接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`执行命令以启动集群连接性检查，然后显示详细信息：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*运行程序前请等待几秒钟 `show`显示详细信息的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有ONTAP版本
--
对于所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`检查连接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step3]] 确认两个节点都与每个交换机有两个连接：
+
`show isdp neighbors`

+
.显示示例
[%collapsible]
====
以下示例显示了两种开关的正确结果：

[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e1a
node2                  0/2          163       H            FAS3270   e1a
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e2a
node2                  0/2          163       H            FAS3270   e2a
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
====
. 显示与配置中的设备相关的信息：
+
`network device discovery show`

. 使用 advanced privilege 命令在两个节点上禁用双节点无交换机配置设置：
+
`network options detect-switchless modify`

+
.显示示例
[%collapsible]
====
以下示例显示了如何禁用无交换机配置设置：

[listing]
----

cluster::*> network options detect-switchless modify -enabled false
----
====
+

NOTE: 对于9.2版及更高版本，请跳过此步骤，因为配置会自动转换。

. 请确认这些设置已禁用：
+
`network options detect-switchless-cluster show`

+
.显示示例
[%collapsible]
====
这 `false`以下示例的输出表明配置设置已被禁用：

[listing]
----

cluster::*> network options detect-switchless-cluster show
Enable Switchless Cluster Detection: false
----
====
+

NOTE: 对于 9.2 版及更高版本，请等待，直到  `Enable Switchless Cluster` 设置为 false。这可能需要长达三分钟的时间。

. 配置集群 clus1 和 clus2 在每个节点上自动还原并确认。
+
.显示示例
[%collapsible]
====
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert true
----
====
+

NOTE: 对于 8.3 版及更高版本，请使用以下命令： `network interface modify -vserver Cluster -lif * -auto-revert true`以在集群中的所有节点上启用自动恢复。

. 验证集群中节点成员的状态：
+
`cluster show`

+
.显示示例
[%collapsible]
====
以下示例显示了集群中节点的健康状况和资格信息：

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. 如果您已禁用自动创建案例功能，请通过调用AutoSupport消息重新启用该功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
. 将权限级别改回管理员：
+
`set -privilege admin`


