---
permalink: switch-netapp-cn1610/migrate-fas22xx-systems.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, fas22xx systems, single, network connection 
summary: 使用 NetApp CN1610 集群交换机将 FAS22xx 系统从具有单个集群网络连接的无交换机集群迁移到有交换机集群。 
---
= 使用 NetApp CN1610 集群交换机迁移 FAS22xx 系统
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 NetApp CN1610 集群交换机，将每个控制器具有单个 10 GbE 连接的双节点无交换机集群中的 FAS22xx 系统迁移到有交换机集群。



[[review-requirements]]
== 审查要求

.开始之前
请确保您拥有以下物品：

* 两个集群连接，用于从无交换机配置迁移到有交换机配置。
* 集群运行状况良好，由通过背靠背连接方式相互连接的两个节点组成。
* 此节点正在运行 ONTAP 8.2 或更高版本。
* 无交换机集群功能不能用于两个以上的节点。
* 所有集群端口都处于 `up`状态。


.相关信息
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetApp 知识库文章 1010449：如何在计划的维护时间段禁止自动创建案例"^]



[[migrate-the-switches]]
== 迁移交换机

此过程是一个无中断过程，在无交换机环境中删除直接集群连接，并将每个到交换机的连接替换为到配对节点的连接。



[[step-1-prepare-for-migration]]
=== 步骤 1：准备迁移

. 将权限级别更改为高级，输入 `y`当系统提示继续时：
+
`set -privilege advanced`

+
高级提示(`*>`出现。

. 检查任一节点的系统控制台上节点的集群状态：
+
`cluster show`

+
.显示示例
[%collapsible]
====
以下示例显示了集群中节点的健康状况和资格信息：

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. 在任一节点的系统控制台检查 HA 对的状态： `storage failover show`
+
.显示示例
[%collapsible]
====
以下示例显示了 node1 和 node2 的状态：

[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
====
. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
`x` 是维护窗口的持续时间（以小时为单位）。

+

NOTE: 此消息会将此维护任务通知技术支持，以便在维护窗口期间禁止自动创建案例。

+
.显示示例
[%collapsible]
====
以下命令可抑制自动创建案件两小时：

[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
====
. 验证无切换集群的当前状态是否为 `true`，然后禁用无切换集群模式：
+
`network options switchless-cluster modify -enabled false`

. 接管目标节点：
+
`storage failover takeover -ofnode _target_node_name_`

+
哪个节点是目标节点并不重要。接管后，目标节点会自动重新启动并显示 `Waiting for giveback...`消息。

+
活动节点现在正在为已接管的合作伙伴（目标）节点提供数据。

. 在接管受损节点后等待两分钟，以确认接管已成功完成。
. 目标节点显示 `Waiting for giveback...`消息后，将其关闭。
+
用于关闭节点的方法取决于是否通过节点 Service Processor (SP) 使用远程管理。

+
|===
| 如果 SP | 操作 


 a| 
已配置
 a| 
登录到受损节点 SP，然后关闭系统电源： `system power off`



 a| 
未配置
 a| 
在受损节点提示符下，按  `Ctrl-C`，然后响应  `y` 以停止该节点。

|===




[[step-2-configure-cables-and-ports]]
=== 步骤 2：配置线缆和端口

. 在每个控制器模块上，断开将 10 GbE 集群端口连接到无交换机集群的电缆。
. 将 10 GbE 集群端口连接到两个控制器模块上的交换机。
. 验证交换机上连接的 10 GbE 集群端口是否配置为同一 VLAN 的一部分。
+
如果您计划将每个控制器模块上的集群端口连接到不同的交换机，则必须验证每个交换机上连接集群端口的端口是否配置为同一 VLAN，并且在两台交换机上都正确配置了中继。

. 将存储返还给目标节点：
+
`storage failover giveback -ofnode node2`

. 监控回馈操作进度：
+
`storage failover show-giveback`

. 交还操作完成后，确认 HA 对运行正常且可以进行接管：
+
`storage failover show`

+
.显示示例
[%collapsible]
====
输出结果应与以下内容类似：

[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
====
. 验证集群端口 LIF 是否正常运行：
+
`network interface show -role cluster`

+
.显示示例
[%collapsible]
====
以下示例显示 LIF 位于 node1 和 node2 `up`上，并且"Is Home"列结果为 `true`：

[listing]
----

cluster::*> network interface show -role cluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
node1
            clus1        up/up    192.168.177.121/24  node1        e1a     true
node2
            clus1        up/up    192.168.177.123/24  node2        e1a     true

2 entries were displayed.
----
====
. 检查任一节点的系统控制台上节点的集群状态：
+
`cluster show`

+
.显示示例
[%collapsible]
====
以下示例显示了集群中节点的健康状况和资格信息：

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. 验证远程集群接口的连接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`执行命令以启动集群连接性检查，然后显示详细信息：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*运行程序前请等待几秒钟 `show`显示详细信息的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有ONTAP版本
--
对于所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`检查连接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====


[[step-3-complete-the-procedure]]
=== 步骤 3：完成该步骤

. 如果您已禁用自动创建案例功能，请通过调用AutoSupport消息重新启用该功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.显示示例
[%collapsible]
====
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
. 将权限级别改回管理员：
+
`set -privilege admin`


