---
permalink: switch-netapp-cn1610/prepare-install-fastpath-rcfs.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs, netapp cluster switch 
summary: '您必须在NetApp CN1610 集群交换机上安装 FASTPATH 软件和参考配置文件 (RCF)。' 
---
= 准备在NetApp集群交换机上安装 FASTPATH 软件和 RCF。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须在NetApp CN1610 集群交换机上安装 FASTPATH 软件和参考配置文件 (RCF)。

.开始之前
* 该集群必须是功能齐全的集群。
* 集群网络接口卡（NIC）不得有任何缺陷，集群交换机上的所有连接端口必须功能正常。
* 集群所有端口必须处于启用状态。
* 所有集群逻辑接口（LIF）必须处于启用状态，且不得已迁移。
* ONTAP （权限：高级） `cluster ping-cluster -node node1`命令必须表明 `larger than PMTU communication`在所有路径上都取得了成功。
* 您必须查阅交换机兼容性表格。 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 和 CN1610 交换机"^]此页面列出了支持的 FASTPATH、RCF 和ONTAP版本。
+
RCF 和 FASTPATH 版本中的命令语法可能存在命令依赖关系。




NOTE: 由于安全问题，RCF 版本 1.2 中已明确禁用对 Telnet 的支持。为避免在安装 RCF 1.2 时出现连接问题，必须确认安全外壳 (SSH) 已启用。这 https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp CN1610 交换机管理员指南"^]包含更多关于 SSH 的信息。

.关于此任务
本流程中的示例使用以下开关和节点命名规则：

* 本文档中的程序使用集群式Data ONTAP 8.2 语法。因此，集群 Vserver、LIF 名称和 CLI 输出将与Data ONTAP 8.3 中的不同。
* 这两台NetApp交换机分别是 cs1 和 cs2。
* 这两个簇 LIF 分别是 clus1 和 clus2。
* 虚拟服务器为 vs1 和 vs2。
* 这 `cluster::*>`prompt 指示集群名称。
* 每个节点上的集群端口分别命名为 e1a 和 e2a。
+
这 https://hwu.netapp.com/["Hardware Universe"^]包含有关您的平台支持的实际集群端口的更多信息。

* NetApp集群交换机支持的交换机间链路 (ISL) 为端口 0/13 至 0/16。
* NetApp集群交换机支持的节点连接端口为 0/1 至 0/12。


该程序分为两部分：

* link:install-fastpath-software.html["安装 FASTPATH 软件"]介绍如何安装 FASTPATH 软件。
* link:install-rcf-file.html["在 CN1610 交换机上安装 RCF"]描述如何安装 RCF。

