---
permalink: switch-netapp-cn1610/replace-cn1610-switch.html 
sidebar: sidebar 
keywords: replace, netapp cn1610, cluster switch 
summary: 更换有缺陷的 NetApp CN1610 集群交换机。这是一个无中断操作步骤。 
---
= 更换 NetApp CN1610 集群交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在不中断集群运行的情况下，更换集群网络中有缺陷的 NetApp CN1610 集群交换机。此无中断程序（NDU）涉及准备更换交换机并从故障交换机迁移连接。



[[review-requirements]]
== 审查要求

.开始之前
在执行交换机更换之前，当前环境中以及现有集群和网络基础设施的更换交换机上必须满足以下条件：

* 必须使用至少一个完全连接的集群交换机来验证现有集群是否完全正常工作。
* 所有集群端口必须为 *up*。
* 所有集群逻辑接口(LIF)必须处于启动状态，并且必须尚未迁移。
* ONTAP 集群 `ping-cluster -node node1`命令必须指示基本连接和大于 PMTU 的通信在所有路径上均成功。




[[enable-console-logging]]
== 启用控制台日志记录

NetApp强烈建议您在使用的设备上启用控制台日志记录，并在更换交换机时执行以下操作：

* 维护期间请保持AutoSupport功能启用。
* 在维护前后触发维护 AutoSupport，以在维护期间禁用案例创建。有关更多详细信息，请参阅此知识库文章 link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92：如何在计划维护窗口期间抑制自动创建案例"^]。
* 启用所有 CLI 会话的会话日志记录。有关如何启用会话日志记录的说明，请查看此知识库文章中的“记录会话输出”部分。link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["如何配置 PuTTY 以获得与ONTAP系统的最佳连接"^] 。




[[replace-the-switch]]
== 更换开关

.关于此任务
您必须从集群 LIF 所在的节点执行迁移集群 LIF 的命令。

本流程中的示例使用以下集群交换机和节点命名规则：

* 两个 CN1610 集群交换机的名称为 `cs1`和 `cs2`。
* 要更换的 CN1610 交换机（有故障的交换机）名称为 `old_cs1`。
* 新 CN1610 交换机（更换交换机）的名称为 `new_cs1`。
* 未被替换的合作伙伴交换机的名称为 `cs2`。


.步骤
. 确认启动配置文件与运行配置文件匹配。您必须在本地保存这些文件，以便在更换过程中使用。
+
以下示例中的配置命令适用于 FASTPATH 1.2.0.7：

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)> *enable*
(old_cs1)# *show running-config*
(old_cs1)# *show startup-config*
----
====
. 创建运行配置文件的副本。
+
以下示例中的命令适用于 FASTPATH 1.2.0.7：

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *show running-config filename.scr*
Config script created successfully.
----
====



NOTE: 您可以使用除 `CN1610_CS_RCF_v1.2.scr`之外的任何文件名。文件名必须具有 *.scr* 扩展名。

. [[step3]]将交换机的运行配置文件保存到外部主机，为更换做准备。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *copy nvram:script filename.scr scp://<Username>@<remote_IP_address>/path_to_file/filename.scr*
----
====
. 验证交换机和 ONTAP 版本是否在兼容性列表中匹配。有关详细信息，请参阅link:https://mysupport.netapp.com/site/info/netapp-cluster-switch["NetApp CN1601 和 CN1610 开关"^]。
. 从 NetApp 支持站点的 link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/downloads-tab["软件下载页面"^] 中，选择 NetApp 群集交换机以下载相应的 RCF 和 FASTPATH 版本。
. 使用 FASTPATH、RCF 和保存的配置 `.scr`文件设置简单文件传输协议 (TFTP) 服务器，以便与新交换机配合使用。
. 将串行端口（交换机右侧标有"IOIOI"的 RJ-45 连接器）连接到具有终端仿真的可用主机。
. 在主机上，设置串行终端连接设置：
+
.. 9600 波特
.. 8 位数据
.. 1 停止位
.. 奇偶性：无
.. 流量控制：无


. 将管理端口（交换机左侧的 RJ-45 扳手端口）连接到 TFTP 服务器所在的同一网络。
. 准备使用 TFTP 服务器连接到网络。
+
如果使用动态主机配置协议 (DHCP)，则此时无需为交换机配置 IP 地址。默认情况下，服务端口设置为使用 DHCP。对于 IPv4 和 IPv6 协议设置，网络管理端口设置为 none。如果扳手端口连接到具有 DHCP 服务器的网络，则会自动配置服务器设置。

+
要设置静态 IP 地址，应使用 serviceport protocol、network protocol 和 serviceport ip 命令。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *serviceport ip <ipaddr> <netmask> <gateway>*
----
====
. 或者，如果 TFTP 服务器在笔记本电脑上，则使用标准以太网电缆将 CN1610 交换机连接到笔记本电脑，然后使用备用 IP 地址在同一网络中配置其网络端口。
+
您可以使用 `ping`命令验证地址。如果无法建立连接，则应使用非路由网络，并使用 IP 192.168.x 或 172.16.x 配置服务端口。您可以稍后将服务端口重新配置为生产管理 IP 地址。

. （可选）为新交换机验证并安装相应版本的 RCF 和 FASTPATH 软件。如果您已验证新交换机设置正确，并且不需要更新 RCF 和 FASTPATH 软件，则应转到步骤 13。
+
.. 验证新的交换机设置。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show version*
----
====
.. 将 RCF 下载到新交换机。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr*
Mode.	TFTP
Set Server IP.	172.22.201.50
Path.	/
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr
File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. please wait...
Validating configuration script...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script validated.
File transfer operation completed successfully.
----
====
.. 验证 RCF 是否已下载到交换机。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script list*
Configuration Script Nam   Size(Bytes)
-------------------------- -----------
CN1610_CS_RCF_v1.1.scr            2191
CN1610_CS_RCF_v1.2.scr            2240
latest_config.scr                 2356

4 configuration script(s) found.
2039 Kbytes free.
----
====


. 将 RCF 应用于 CN1610 交换机。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply CN1610_CS_RCF_v1.2.scr*
Are you sure you want to apply the configuration script? (y/n) *y*
...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script 'CN1610_CS_RCF_v1.2.scr' applied. Note that the script output will go to the console.
After the script is applied, those settings will be active in the running-config file. To save them to the startup-config file, you must use the write memory command, or if you used the reload answer yes when asked if you want to save the changes.
----
====
+
.. 保存运行配置文件，以便在重新启动交换机时成为启动配置文件。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. 将映像下载到 CN1610 交换机。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/NetApp_CN1610_1.2.0.7.stk active*
Mode.	TFTP
Set Server IP.	tftp_server_ip_address
Path.	/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type.	Code
Destination Filename.	active

Management access will be blocked for the duration of the transfer

Are you sure you want to start? (y/n) *y*

TFTP Code transfer starting...

File transfer operation completed successfully.
----
====
.. 通过重新启动交换机来运行新的活动启动映像。
+
必须重新启动交换机，才能使步骤 6 中的命令反映新映像。输入 reload 命令后，您可能会看到两种可能的响应视图。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *reload*
The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved! System will now restart!
.
.
.
Cluster Interconnect Infrastructure

User:admin Password: (new_cs1) >*enable*
----
====
.. 将已保存的配置文件从旧交换机复制到新交换机。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/<filename>.scr nvram:script <filename>.scr*
----
====
.. 将先前保存的配置应用于新交换机。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply <filename>.scr*
Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. 将运行配置文件保存到启动配置文件。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
----
====


. 如果在此集群上启用了 AutoSupport，请通过调用 AutoSupport 消息来禁止自动创建案例：
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_ 是维护窗口的持续时间，单位为小时。

+
[NOTE]
====
AutoSupport消息会通知技术支持此维护任务，以便在维护窗口期间抑制自动创建案例。

====
. 在新交换机 new_cs1 上，以 admin 用户身份登录，关闭连接到节点集群接口的所有端口（端口 1 到 12）。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
User:*admin*
Password:
(new_cs1)> *enable*
(new_cs1)#
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/1-0/12)# *shutdown*
(new_cs1)(interface 0/1-0/12)# *exit*
(new_cs1)# *write memory*
----
====
. 从连接到 old_cs1 交换机的端口迁移集群 LIF。
+
必须从其当前节点的管理接口迁移每个集群 LIF。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *set -privilege advanced*
cluster::> *network interface migrate -vserver <vserver_name> -lif <Cluster_LIF_to_be_moved> - sourcenode <current_node> -dest-node <current_node> -dest-port <cluster_port_that_is_UP>*
----
====
. 验证所有集群 LIF 是否已移动到每个节点上相应的集群端口。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network interface show -role cluster*
----
====
. 关闭连接到您更换的交换机的集群端口。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node <node_name> -port <port_to_admin_down> -up-admin false*
----
====
. 验证集群的运行状况。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. 验证端口是否已关闭。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node <node_name>*
----
====
. 在交换机 cs2 上，关闭 ISL 端口 13 至 16。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *shutdown*
(cs2)# *show port-channel 3/1*
----
====
. 验证存储管理员是否已准备好更换交换机。
. 卸下 old_cs1 交换机上的所有电缆，然后将电缆连接到 new_cs1 交换机上的相同端口。
. 在 cs2 交换机上，打开 ISL 端口 13 至 16。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *no shutdown*
----
====
. 打开新交换机上与集群节点关联的端口。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/13-0/16)# *no shutdown*
----
====
. 在单个节点上，启动连接到更换交换机的集群节点端口，然后确认链路已启动。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node node1 -port <port_to_be_onlined> -up-admin true*
cluster::*> *network port show -role cluster*
----
====
. 还原同一节点上步骤 25 中与端口关联的集群 LIF。
+
在此示例中，如果"Is Home"列为 true，则 node1 上的 LIF 将成功还原。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver node1 -lif <cluster_lif_to_be_reverted>*
cluster::*> *network interface show -role cluster*
----
====
. 如果第一个节点的集群 LIF 已启动并还原为其主端口，请重复步骤 25 和 26 以启动集群端口并还原集群中其他节点上的集群 LIF。
. 显示有关集群中节点的信息。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. 确认更换后的交换机上的启动配置文件和运行配置文件正确无误。此配置文件应与第 1 步中的输出相匹配。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show running-config*
(new_cs1)# *show startup-config*
----
====
. 如果您已禁用自动创建案例功能，请通过调用AutoSupport消息重新启用该功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`


