---
permalink: switch-cisco-92300/CSHM_snmpv3.html 
sidebar: sidebar 
keywords: SNMP,SNMPv3,SNMPv3 setup,Cisco setup,Cisco switches configuration,NX-OS 
summary: 'SNMPv3可与以太网交换机运行状况监控器(CSHM)结合使用。' 
---
= 配置SNMPv3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按照此操作步骤配置SNMPv3、此SNMPv3支持以太网交换机运行状况监控(CSHM)。

.关于此任务
以下命令可在Cisco 92300YC交换机上配置SNMPv3用户名：

* 对于*no authentication (无身份验证)*：
`snmp-server user _SNMPv3_USER_ NoAuth`
* 对于*MD5/SHA身份验证*：
`snmp-server user _SNMPv3_USER_ auth [md5|sha] _AUTH-PASSWORD_`
* 对于采用AES/DES加密的*MD5/SHA身份验证*：
`snmp-server user _SNMPv3_USER_ AuthEncrypt  auth [md5|sha] _AUTH-PASSWORD_ priv aes-128 _PRIV-PASSWORD_`


以下命令会在ONTAP 端配置SNMPv3用户名：`cluster1：：：*> security login create -user-or-group-name _SNMPv3用户_-application snmp -authentication-method USM -remote-switch-ipaddress _address_`

以下命令将使用CSHM建立SNMPv3用户名：
`cluster1::*> system switch ethernet modify -device _DEVICE_ -snmp-version SNMPv3 -community-or-username _SNMPv3_USER_`

.步骤
. 在交换机上设置SNMPv3用户以使用身份验证和加密：
+
`show snmp user`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
(sw1)(Config)# *snmp-server user SNMPv3User auth md5 <auth_password> priv aes-128 <priv_password>*

(sw1)(Config)# *show snmp user*

-----------------------------------------------------------------------------
                              SNMP USERS
-----------------------------------------------------------------------------

User              Auth            Priv(enforce)   Groups          acl_filter
----------------- --------------- --------------- --------------- -----------
admin             md5             des(no)         network-admin
SNMPv3User        md5             aes-128(no)     network-operator

-----------------------------------------------------------------------------
     NOTIFICATION TARGET USERS (configured  for sending V3 Inform)
-----------------------------------------------------------------------------

User              Auth               Priv
----------------- ------------------ ------------

(sw1)(Config)#
----
====
. 在ONTAP 端设置SNMPv3用户：
+
`security login create -user-or-group-name <username> -application snmp -authentication-method usm -remote-switch-ipaddress 10.231.80.212`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet modify -device "sw1 (b8:59:9f:09:7c:22)" -is-monitoring-enabled-admin true*

cluster1::*> *security login create -user-or-group-name <username> -application snmp -authentication-method usm -remote-switch-ipaddress 10.231.80.212*

Enter the authoritative entity's EngineID [remote EngineID]:

Which authentication protocol do you want to choose (none, md5, sha, sha2-256)
[none]: *md5*

Enter the authentication protocol password (minimum 8 characters long):

Enter the authentication protocol password again:

Which privacy protocol do you want to choose (none, des, aes128) [none]: *aes128*

Enter privacy protocol password (minimum 8 characters long):
Enter privacy protocol password again:
----
====
. 将CSHM配置为使用新SNMPv3用户进行监控：
+
`system switch ethernet show-all -device "sw1" -instance`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show-all -device "sw1" -instance*

                                   Device Name: sw1
                                    IP Address: 10.231.80.212
                                  SNMP Version: SNMPv2c
                                 Is Discovered: true
   SNMPv2c Community String or SNMPv3 Username: cshm1!
                                  Model Number: N9K-C92300YC
                                Switch Network: cluster-network
                              Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 9.3(7)
                     Reason For Not Monitoring: None  *<---- displays when SNMP settings are valid*
                      Source Of Switch Version: CDP/ISDP
                                Is Monitored ?: true
                   Serial Number of the Device: QTFCU3826001C
                                   RCF Version: v1.8X2 for Cluster/HA/RDMA

cluster1::*>
cluster1::*> *system switch ethernet modify -device "sw1" -snmp-version SNMPv3 -community-or-username <username>*
cluster1::*>
----
====
. 确认要使用新创建的SNMPv3用户查询的序列号与CSHM轮询周期完成后上一步中详述的序列号相同。
+
`system switch ethernet polling-interval show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet polling-interval show*
         Polling Interval (in minutes): 5

cluster1::*> *system switch ethernet show-all -device "sw1" -instance*

                                   Device Name: sw1
                                    IP Address: 10.231.80.212
                                  SNMP Version: SNMPv3
                                 Is Discovered: true
   SNMPv2c Community String or SNMPv3 Username: SNMPv3User
                                  Model Number: N9K-C92300YC
                                Switch Network: cluster-network
                              Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 9.3(7)
                     Reason For Not Monitoring: None  *<---- displays when SNMP settings are valid*
                      Source Of Switch Version: CDP/ISDP
                                Is Monitored ?: true
                   Serial Number of the Device: QTFCU3826001C
                                   RCF Version: v1.8X2 for Cluster/HA/RDMA

cluster1::*>
----
====

