---
permalink: switch-cisco-92300/migrate-to-2n-switched.html 
sidebar: sidebar 
keywords: 2-node switched Cisco 92300YC cluster switch migration 
summary: 如果您已有双节点无交换机集群环境，则可以使用Cisco Nexus 92300YC 交换机迁移到双节点有交换机集群环境，以便能够将集群扩展到两个以上节点。 
---
= 迁移到使用Cisco Nexus 92300YC 交换机的双节点交换集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您已经拥有一个双节点无交换机集群环境，则可以使用Cisco Nexus 92300YC 交换机迁移到双节点有交换机集群环境，从而使集群能够扩展到两个节点以上。

具体操作步骤取决于每个控制器上是有两个专用集群网络端口还是只有一个集群端口。记录的过程适用于所有使用光纤或双绞线端口的节点，但如果节点使用板载 10Gb BASE-T RJ45 端口作为集群网络端口，则此交换机不支持此过程。

大多数系统需要在每个控制器上设置两个专用的集群网络端口。


NOTE: 迁移完成后，您可能需要安装所需的配置文件，以支持 92300YC 集群交换机的集群交换机健康监视器 (CSHM)。看link:../switch-cshm/cshm-overview.html["交换机健康监测 (CSHM)"]。



== 审查要求

.开始之前
请确保您拥有以下物品：

对于双节点无交换机配置，请确保：

* 双节点无交换机配置已正确设置并运行正常。
* 这些节点运行的是ONTAP 9.6 及更高版本。
* 集群所有端口均处于*开启*状态。
* 所有集群逻辑接口（LIF）均处于 *up* 状态，并位于其所属端口上。


对于Cisco Nexus 92300YC 交换机配置：

* 两台交换机都具备管理网络连接功能。
* 可以通过控制台访问集群交换机。
* Nexus 92300YC 节点到节点交换机和交换机到交换机的连接使用双绞线或光纤电缆。
+
https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe- 交换机"^]包含更多关于布线的信息。

* 交换机间链路 (ISL) 电缆连接到两个 92300YC 交换机上的端口 1/65 和 1/66。
* 两台 92300YC 交换机的初始定制工作已完成。因此：
+
** 92300YC交换机运行的是最新版本的软件。
** 参考配置文件 (RCF) 应用于交换机。任何站点自定义，如 SMTP、SNMP 和 SSH，均在新交换机上进行配置。






== 迁移交换机

.关于示例
本流程中的示例使用以下集群交换机和节点命名规则：

* 92300YC 交换机的名称是 cs1 和 cs2。
* 聚类SVM的名称分别为node1和node2。
* 节点 1 上的 LIF 名称分别为 node1_clus1 和 node1_clus2，节点 2 上的 LIF 名称分别为 node2_clus1 和 node2_clus2。
* 这 `cluster1::*>`prompt 指示集群名称。
* 此过程中使用的集群端口为 e0a 和 e0b。
+
https://hwu.netapp.com["Hardware Universe"^]包含有关您平台实际集群端口的最新信息。





=== 步骤 1：准备迁移

. 将权限级别更改为高级，输入 `y`当系统提示继续时：
+
`set -privilege advanced`

+
高级提示(`*>`出现。

. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 x 为维护窗口的持续时间（小时）。

+

NOTE: AutoSupport消息会通知技术支持此维护任务，以便在维护窗口期间抑制自动创建案例。

+
.显示示例
[%collapsible]
====
以下命令可抑制自动创建案件两小时：

[listing, subs="+quotes"]
----
cluster1::*> *system node autosupport invoke -node * -type all -message MAINT=2h*
----
====




=== 步骤 2：配置线缆和端口

. 禁用新集群交换机 cs1 和 cs2 上所有面向节点的端口（非 ISL 端口）。
+
您不得禁用 ISL 端口。

+
.显示示例
[%collapsible]
====
以下示例显示交换机 cs1 上面向节点的端口 1 到 64 已禁用：

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e/1-64*
cs1(config-if-range)# *shutdown*
----
====
. 验证两个 92300YC 交换机 cs1 和 cs2 之间的 ISL 以及 ISL 上的物理端口在端口 1/65 和 1/66 上是否处于启动状态：
+
`show port-channel summary`

+
.显示示例
[%collapsible]
====
以下示例表明交换机 cs1 上的 ISL 端口已启动：

[listing, subs="+quotes"]
----
cs1# *show port-channel summary*

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/65(P)   Eth1/66(P)
----
以下示例表明交换机 cs2 上的 ISL 端口已启动：

+

[listing, subs="+quotes"]
----
(cs2)# *show port-channel summary*

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/65(P)   Eth1/66(P)
----
====
. 显示相邻设备列表：
+
`show cdp neighbors`

+
此命令提供有关连接到系统的设备的信息。

+
.显示示例
[%collapsible]
====
以下示例列出了交换机 cs1 上的相邻设备：

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2(FDO220329V5)    Eth1/65        175    R S I s   N9K-C92300YC  Eth1/65
cs2(FDO220329V5)    Eth1/66        175    R S I s   N9K-C92300YC  Eth1/66

Total entries displayed: 2
----
以下示例列出了交换机 cs2 上的相邻设备：

+

[listing, subs="+quotes"]
----
cs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1(FDO220329KU)    Eth1/65        177    R S I s   N9K-C92300YC  Eth1/65
cs1(FDO220329KU)    Eth1/66        177    R S I s   N9K-C92300YC  Eth1/66

Total entries displayed: 2
----
====
. 请确认集群所有端口均已启动：
+
`network port show -ipspace Cluster`

+
每个端口都应该显示出来。 `Link`而且对身体有益 `Health Status`。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.
----
====
. 确认所有集群 LIF 都已启动并正常运行：
+
`network interface show -vserver Cluster`

+
每个聚类 LIF 都应该显示为 true `Is Home`并且拥有 `Status Admin/Oper`向上/向上

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
====
. 确认所有集群 LIF 都已启用自动回滚功能：
+
`network interface show -vserver Cluster -fields auto-revert`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true

4 entries were displayed.
----
====
. 断开节点 1 上的集群端口 e0a 的电缆，然后使用 92300YC 交换机支持的适当电缆将 e0a 连接到集群交换机 cs1 上的端口 1。
+
这 https://hwu.netapp.com/SWITCH/INDEX["硬件宇宙 - 交换机"^]包含更多关于布线的信息。

. 断开节点 2 上的集群端口 e0a 的电缆，然后使用 92300YC 交换机支持的适当电缆将 e0a 连接到集群交换机 cs1 上的端口 2。
. 启用集群交换机 cs1 上所有面向节点的端口。
+
.显示示例
[%collapsible]
====
以下示例显示交换机 cs1 上的端口 1/1 到 1/64 已启用：

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-64*
cs1(config-if-range)# *no shutdown*
----
====
. 验证所有集群 LIF 是否都已启动、运行正常，并且显示为 true。 `Is Home` ：
+
`network interface show -vserver Cluster`

+
.显示示例
[%collapsible]
====
以下示例表明，节点 1 和节点 2 上的所有 LIF 都已启动，并且 `Is Home`结果属实：

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true

4 entries were displayed.
----
====
. 显示集群中节点的状态信息：
+
`cluster show`

+
.显示示例
[%collapsible]
====
以下示例显示了集群中节点的健康状况和资格信息：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. 断开节点 1 上的集群端口 e0b 的电缆，然后使用 92300YC 交换机支持的适当电缆将 e0b 连接到集群交换机 cs2 上的端口 1。
. 断开节点 2 上的集群端口 e0b 的电缆，然后使用 92300YC 交换机支持的适当电缆将 e0b 连接到集群交换机 cs2 上的端口 2。
. 启用集群交换机 cs2 上所有面向节点的端口。
+
.显示示例
[%collapsible]
====
以下示例显示交换机 cs2 上的端口 1/1 到 1/64 已启用：

[listing, subs="+quotes"]
----
cs2# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# *interface e1/1-64*
cs2(config-if-range)# *no shutdown*
----
====




=== 步骤 3：验证配置

. 请确认集群所有端口均已启动：
+
`network port show -ipspace Cluster`

+
.显示示例
[%collapsible]
====
以下示例表明节点 1 和节点 2 上的所有集群端口均已启动：

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.
----
====
. 验证所有接口是否都显示为 true `Is Home` ：
+
`network interface show -vserver Cluster`

+

NOTE: 这可能需要几分钟才能完成。

+
.显示示例
[%collapsible]
====
以下示例表明节点 1 和节点 2 上的所有 LIF 都已启动，并且 `Is Home`结果属实：

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true

4 entries were displayed.
----
====
. 确认两个节点都分别与每个交换机建立了一条连接：
+
`show cdp neighbors`

+
.显示示例
[%collapsible]
====
以下示例显示了两种开关的正确结果：

[listing, subs="+quotes"]
----
(cs1)# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1               Eth1/1         133    H         FAS2980       e0a
node2               Eth1/2         133    H         FAS2980       e0a
cs2(FDO220329V5)    Eth1/65        175    R S I s   N9K-C92300YC  Eth1/65
cs2(FDO220329V5)    Eth1/66        175    R S I s   N9K-C92300YC  Eth1/66

Total entries displayed: 4


(cs2)# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1               Eth1/1         133    H         FAS2980       e0b
node2               Eth1/2         133    H         FAS2980       e0b
cs1(FDO220329KU)
                    Eth1/65        175    R S I s   N9K-C92300YC  Eth1/65
cs1(FDO220329KU)
                    Eth1/66        175    R S I s   N9K-C92300YC  Eth1/66

Total entries displayed: 4
----
====
. 显示集群中已发现的网络设备信息：
+
`network device-discovery show -protocol cdp`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               N9K-C92300YC
            e0b    cs2                       0/2               N9K-C92300YC
node1      /cdp
            e0a    cs1                       0/1               N9K-C92300YC
            e0b    cs2                       0/1               N9K-C92300YC

4 entries were displayed.
----
====
. 请确认这些设置已禁用：
+
`network options switchless-cluster show`

+

NOTE: 命令可能需要几分钟才能完成。等待“3分钟生命即将结束”的公告。

+
.显示示例
[%collapsible]
====
以下示例中的错误输出表明配置设置已被禁用：

[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
====
. 验证集群中节点成员的状态：
+
`cluster show`

+
.显示示例
[%collapsible]
====
以下示例显示了集群中节点的健康状况和资格信息：

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. 验证远程集群接口的连接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`执行命令以启动集群连接性检查，然后显示详细信息：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*运行程序前请等待几秒钟 `show`显示详细信息的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有ONTAP版本
--
对于所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`检查连接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*

Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[步骤8]] 如果您已禁用自动创建案例功能，请通过调用AutoSupport消息重新启用该功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system node autosupport invoke -node * -type all -message MAINT=END*
----
====
. 将权限级别改回管理员：
+
`set -privilege admin`



.下一步是什么？
验证完 SSH 配置后，您可以…… link:../switch-cshm/config-overview.html["配置交换机健康监控"]。
