---
permalink: switch-cisco-92300/migrate-to-92300yc.html 
sidebar: sidebar 
keywords: migration steps for cisco nexus 92300yc cluster switch 
summary: 您可以将ONTAP集群的旧Cisco集群交换机无中断地迁移到Cisco Nexus 92300YC 集群网络交换机。 
---
= 将Cisco交换机迁移到Cisco Nexus 92300YC 交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将ONTAP集群的旧Cisco集群交换机无中断地迁移到Cisco Nexus 92300YC 集群网络交换机。


NOTE: 迁移完成后，您可能需要安装所需的配置文件，以支持 92300YC 集群交换机的集群交换机健康监视器 (CSHM)。看link:../switch-cshm/cshm-overview.html["交换机健康监测 (CSHM)"]。



== 审查要求

.开始之前
请确保您拥有以下物品：

* 一个功能齐全的现有集群。
* 节点到 Nexus 92300YC 集群交换机的 10 GbE 和 40 GbE 连接。
* 集群所有端口均处于启用状态，以确保运行不中断。
* Nexus 92300YC 集群交换机上安装了正确版本的 NX-OS 和参考配置文件 (RCF)。
* 使用较旧的Cisco交换机构建冗余且功能齐全的NetApp集群。
* 对旧款Cisco交换机和新款交换机的管理连接和控制台访问。
* 所有处于启动状态的集群 LIF 都位于其主端口上。
* ISL 端口已启用，并且已在旧款Cisco交换机和新款交换机之间连接了线缆。




== 迁移交换机

.关于示例
本流程中的示例使用以下开关和节点命名规则：

* 现有的Cisco Nexus 5596UP 集群交换机为 c1 和 c2。
* 新的 Nexus 92300YC 集群交换机是 cs1 和 cs2。
* 节点分别为 node1 和 node2。
* 节点 1 上的集群 LIF 分别为 node1_clus1 和 node1_clus2，节点 2 上的集群 LIF 分别为 node2_clus1 和 node2_clus2。
* 首先将交换机 c2 替换为交换机 cs2，然后将交换机 c1 替换为交换机 cs1。
+
** 在 cs1 上建立临时 ISL，将 c1 连接到 cs1。
** 然后断开节点与 c2 之间的电缆与 c2 的连接，并重新连接到 cs2。
** 然后断开节点与 c1 之间的电缆与 c1 的连接，并重新连接到 cs1。
** 然后移除 c1 和 cs1 之间的临时 ISL。




.用于连接的端口
* Nexus 92300YC 交换机上的一些端口配置为以 10 GbE 或 40 GbE 运行。
* 集群交换机使用以下端口连接到节点：
+
** 端口 e1/1-48 (10/25 GbE)、e1/49-64 (40/100 GbE)：Nexus 92300YC
** 端口 e1/1-40 (10 GbE)：Nexus 5596UP
** 端口 e1/1-32 (10 GbE)：Nexus 5020
** 端口 e1/1-12、e2/1-6 (10 GbE)：带扩展模块的 Nexus 5010


* 集群交换机使用以下交换机间链路 (ISL) 端口：
+
** 端口 e1/65-66 (100 GbE)：Nexus 92300YC
** 端口 e1/41-48 (10 GbE)：Nexus 5596UP
** 端口 e1/33-40 (10 GbE)：Nexus 5020
** 端口 e1/13-20 (10 GbE)：Nexus 5010


* https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe- 交换机"^]包含有关所有集群交换机支持的布线信息。
* 本流程支持的ONTAP和 NX-OS 版本如下： https://support.netapp.com/NOW/download/software/cm_switches/["Cisco以太网交换机"^]页。




=== 步骤 1：准备迁移

. 将权限级别更改为高级，并在提示继续时输入 *y*：
+
`set -privilege advanced`

+
出现高级提示符（*>）。

. 如果此集群上启用了AutoSupport ，则通过调用AutoSupport消息来抑制自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 x 为维护窗口的持续时间（小时）。

+

NOTE: AutoSupport消息会通知技术支持此维护任务，以便在维护窗口期间抑制自动创建案例。

+
.显示示例
[%collapsible]
====
以下命令可抑制自动创建案件两小时：

[listing, subs="+quotes"]
----
cluster1::*> *system node autosupport invoke -node * -type all -message MAINT=2h*
----
====
. 确认所有集群 LIF 都已启用自动回滚功能：
+
`network interface show -vserver Cluster -fields auto-revert`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true

4 entries were displayed.
----
====
. 确定每个集群接口的管理或运行状态：
+
每个端口都应该显示出来。 `Link`而且对身体有益 `Health Status`。

+
.. 显示网络端口属性：
+
`network port show -ipspace Cluster`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.
----
====
.. 显示有关逻辑接口及其指定归属节点的信息：
+
`network interface show -vserver Cluster`

+
每个 LIF 都应该显示 up/up。 `Status Admin/Oper`确实如此 `Is Home`。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- -----------  ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true

4 entries were displayed.
----
====


. 使用以下命令（从节点角度）验证每个节点上的集群端口是否已按以下方式连接到现有的集群交换机：
+
`network device-discovery show -protocol cdp`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    c1                        0/2               N5K-C5596UP
            e0b    c2                        0/2               N5K-C5596UP
node1      /cdp
            e0a    c1                        0/1               N5K-C5596UP
            e0b    c2                        0/1               N5K-C5596UP

4 entries were displayed.
----
====
. 使用以下命令验证集群端口和交换机是否按以下方式连接（从交换机的角度来看）：
+
`show cdp neighbors`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1               Eth1/1         124    H         FAS2750            e0a
node2               Eth1/2         124    H         FAS2750            e0a
c2(FOX2025GEFC)     Eth1/41        179    S I s     N5K-C5596UP        Eth1/41

c2(FOX2025GEFC)     Eth1/42        175    S I s     N5K-C5596UP        Eth1/42

c2(FOX2025GEFC)     Eth1/43        179    S I s     N5K-C5596UP        Eth1/43

c2(FOX2025GEFC)     Eth1/44        175    S I s     N5K-C5596UP        Eth1/44

c2(FOX2025GEFC)     Eth1/45        179    S I s     N5K-C5596UP        Eth1/45

c2(FOX2025GEFC)     Eth1/46        179    S I s     N5K-C5596UP        Eth1/46

c2(FOX2025GEFC)     Eth1/47        175    S I s     N5K-C5596UP        Eth1/47

c2(FOX2025GEFC)     Eth1/48        179    S I s     N5K-C5596UP        Eth1/48

Total entries displayed: 10


c2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1               Eth1/1         124    H         FAS2750            e0b
node2               Eth1/2         124    H         FAS2750            e0b
c1(FOX2025GEEX)     Eth1/41        175    S I s     N5K-C5596UP        Eth1/41

c1(FOX2025GEEX)     Eth1/42        175    S I s     N5K-C5596UP        Eth1/42

c1(FOX2025GEEX)     Eth1/43        175    S I s     N5K-C5596UP        Eth1/43

c1(FOX2025GEEX)     Eth1/44        175    S I s     N5K-C5596UP        Eth1/44

c1(FOX2025GEEX)     Eth1/45        175    S I s     N5K-C5596UP        Eth1/45

c1(FOX2025GEEX)     Eth1/46        175    S I s     N5K-C5596UP        Eth1/46

c1(FOX2025GEEX)     Eth1/47        176    S I s     N5K-C5596UP        Eth1/47

c1(FOX2025GEEX)     Eth1/48        176    S I s     N5K-C5596UP        Eth1/48
----
====
. 验证远程集群接口的连接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`执行命令以启动集群连接性检查，然后显示详细信息：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*运行程序前请等待几秒钟 `show`显示详细信息的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有ONTAP版本
--
对于所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`检查连接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====


=== 步骤 2：配置线缆和端口

. 在 c1 和 cs1 之间的端口 e1/41-48 上配置 cs1 上的临时 ISL。
+
.显示示例
[%collapsible]
====
以下示例展示了如何在 c1 和 cs1 上配置新的 ISL：

[listing, subs="+quotes"]
----
cs1# *configure*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/41-48*
cs1(config-if-range)# *description temporary ISL between Nexus 5596UP and Nexus 92300YC*
cs1(config-if-range)# *no lldp transmit*
cs1(config-if-range)# *no lldp receive*
cs1(config-if-range)# *switchport mode trunk*
cs1(config-if-range)# *no spanning-tree bpduguard enable*
cs1(config-if-range)# *channel-group 101 mode active*
cs1(config-if-range)# *exit*
cs1(config)# *interface port-channel 101*
cs1(config-if)# *switchport mode trunk*
cs1(config-if)# *spanning-tree port type network*
cs1(config-if)# *exit*
cs1(config)# *exit*
----
====
. 从 c2 的 e1/41-48 端口移除 ISL 电缆，并将电缆连接到 cs1 的 e1/41-48 端口。
. 验证 ISL 端口和端口通道是否正常工作，连接 c1 和 cs1：
+
`show port-channel summary`

+
.显示示例
[%collapsible]
====
以下示例展示了如何使用Cisco show port-channel summary 命令来验证 c1 和 cs1 上的 ISL 端口是否正常运行：

[listing, subs="+quotes"]
----
c1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/41(P)   Eth1/42(P)   Eth1/43(P)
                                     Eth1/44(P)   Eth1/45(P)   Eth1/46(P)
                                     Eth1/47(P)   Eth1/48(P)


cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/65(P)   Eth1/66(P)
101   Po101(SU)   Eth      LACP      Eth1/41(P)   Eth1/42(P)   Eth1/43(P)
                                     Eth1/44(P)   Eth1/45(P)   Eth1/46(P)
                                     Eth1/47(P)   Eth1/48(P)
----
====
. 对于节点 1，断开 c2 上的 e1/1 电缆，然后使用 Nexus 92300YC 支持的适当电缆将电缆连接到 cs2 上的 e1/1。
. 对于节点 2，断开 c2 上的 e1/2 电缆，然后使用 Nexus 92300YC 支持的适当电缆将电缆连接到 cs2 上的 e1/2。
. 从节点的角度来看，每个节点上的集群端口现在按以下方式连接到集群交换机：
+
`network device-discovery show -protocol cdp`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    c1                        0/2               N5K-C5596UP
            e0b    cs2                       0/2               N9K-C92300YC
node1      /cdp
            e0a    c1                        0/1               N5K-C5596UP
            e0b    cs2                       0/1               N9K-C92300YC

4 entries were displayed.
----
====
. 对于节点 1，断开 c1 上的 e1/1 电缆，然后使用 Nexus 92300YC 支持的适当电缆将电缆连接到 cs1 上的 e1/1。
. 对于节点 2，断开 c1 上的 e1/2 的电缆，然后使用 Nexus 92300YC 支持的适当电缆将电缆连接到 cs1 上的 e1/2。
. 从节点的角度来看，每个节点上的集群端口现在按以下方式连接到集群交换机：
+
`network device-discovery show -protocol cdp`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               N9K-C92300YC
            e0b    cs2                       0/2               N9K-C92300YC
node1      /cdp
            e0a    cs1                       0/1               N9K-C92300YC
            e0b    cs2                       0/1               N9K-C92300YC
4 entries were displayed.
----
====
. 删除 cs1 和 c1 之间的临时 ISL。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1(config)# *no interface port-channel 10*
cs1(config)# *interface e1/41-48*
cs1(config-if-range)# *lldp transmit*
cs1(config-if-range)# *lldp receive*
cs1(config-if-range)# *no switchport mode trunk*
cs1(config-if-range)# *no channel-group*
cs1(config-if-range)# *description 10GbE Node Port*
cs1(config-if-range)# *spanning-tree bpduguard enable*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
----
====




=== 步骤 3：完成迁移

. 验证集群的最终配置：
+
`network port show -ipspace Cluster`

+
每个端口都应该显示出来。 `Link`而且对身体有益 `Health Status`。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.


cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true

4 entries were displayed.


cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               N9K-C92300YC
            e0b    cs2                       0/2               N9K-C92300YC
node1      /cdp
            e0a    cs1                       0/1               N9K-C92300YC
            e0b    cs2                       0/1               N9K-C92300YC

4 entries were displayed.


cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1               Eth1/1         124    H         FAS2750            e0a
node2               Eth1/2         124    H         FAS2750            e0a
cs2(FDO220329V5)    Eth1/65        179    R S I s   N9K-C92300YC  Eth1/65
cs2(FDO220329V5)    Eth1/66        179    R S I s   N9K-C92300YC  Eth1/66


cs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1               Eth1/1         124    H         FAS2750            e0b
node2               Eth1/2         124    H         FAS2750            e0b
cs1(FDO220329KU)
                    Eth1/65        179    R S I s   N9K-C92300YC  Eth1/65
cs1(FDO220329KU)
                    Eth1/66        179    R S I s   N9K-C92300YC  Eth1/66

Total entries displayed: 4
----
====
. 验证远程集群接口的连接性：


[role="tabbed-block"]
====
.ONTAP 9.9.1 及更高版本
--
你可以使用 `network interface check cluster-connectivity`执行命令以启动集群连接性检查，然后显示详细信息：

`network interface check cluster-connectivity start`和 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*注意：*运行程序前请等待几秒钟 `show`显示详细信息的命令。

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.所有ONTAP版本
--
对于所有ONTAP版本，您也可以使用 `cluster ping-cluster -node <name>`检查连接性的命令：

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[步骤3]] 如果您已禁用自动创建案例功能，请通过调用AutoSupport消息重新启用该功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system node autosupport invoke -node * -type all -message MAINT=END*
----
====
. 将权限级别改回管理员：
+
`set -privilege admin`



.下一步是什么？
验证完 SSH 配置后，您可以…… link:../switch-cshm/config-overview.html["配置交换机健康监控"]。
