---
permalink: switch-cshm/monitor-manage.html 
sidebar: sidebar 
keywords: create, remove, switch, cluster, monitor, health, management 
summary: 了解如何手动创建、更改默认监控设置以及从监控中删除以太网交换机。 
---
= 管理以太网交换机的监控
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
大多数情况下，以太网交换机由ONTAP自动发现，并由 CSHM 监控。应用于交换机的参考配置文件 (RCF) 除其他功能外，还启用Cisco发现协议 (CDP) 和/或链路层发现协议 (LLDP)。但是，您可能需要手动添加未被发现的交换机，或者删除不再使用的交换机。您也可以在保留交换机配置的情况下停止主动监控，例如在维护期间。



== 创建交换机条目，以便ONTAP可以对其进行监控。

使用 `system switch ethernet create`手动配置并启用指定以太网交换机的监控命令。如果ONTAP没有自动添加交换机，或者您之前删除了交换机并想重新添加它，这将很有帮助。

[source, cli]
----
system switch ethernet create -device DeviceName -address 1.2.3.4 -snmp-version SNMPv2c -community-or-username cshm1! -model NX3132V -type cluster-network
----
一个典型的例子是添加一个名为 [DeviceName] 的交换机，其 IP 地址为 1.2.3.4，SNMPv2c 凭据设置为 *cshm1!*。使用 `-type storage-network`而不是 `-type cluster-network`如果您正在配置存储交换机。



== 禁用监控而不删除开关

如果您想暂停或停止对某个交换机的监控，但仍希望保留该交换机以供将来监控，请修改其设置。 `is-monitoring-enabled-admim`保留参数而不是删除它。

例如：

[source, cli]
----
system switch ethernet modify -device DeviceName -is-monitoring-enabled-admin false
----
这样可以保留交换机的详细信息和配置，而不会生成新的警报或重新发现。



== 移除不再需要的开关

使用 `system switch ethernet delete`删除已断开连接或不再需要的开关：

[source, cli]
----
system switch ethernet delete -device DeviceName
----
默认情况下，只有当ONTAP当前未通过 CDP 或 LLDP 检测到交换机时，此命令才会成功。要移除已发现的交换机，请使用 `-force`范围：

[source, cli]
----
system switch ethernet delete -device DeviceName -force
----
什么时候 `-force`如果使用该开关， ONTAP再次检测到该开关时，可能会自动重新添加该开关。
