---
permalink: switch-cshm/monitor-manage.html 
sidebar: sidebar 
keywords: create, remove, switch, cluster, monitor, health, management 
summary: 了解如何手动创建、更改默认监控设置以及从监控中删除以太网交换机。 
---
= 管理以太网交换机的监控
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在大多数情况下、以太网交换机会由ONTAP自动发现并由CSHM进行监控。应用于交换机的参考配置文件(Reference Configuration File、RCF)等功能可启用Cisco发现协议(CDP)和/或链路层发现协议(Link Layer Discovery Protocol、LDP)。但是、您可能需要手动添加未发现的交换机或删除不再使用的交换机。您还可以在将交换机保留在配置中的同时停止活动监控、例如在维护期间。



== 创建一个交换机条目、以便ONTAP可以对其进行监控

使用 `system switch ethernet create`命令为指定的以太网交换机手动配置和启用监控。如果ONTAP未自动添加交换机、或者您之前删除了交换机并希望重新添加它、则此功能非常有用。

[source, cli]
----
system switch ethernet create -device DeviceName -address 1.2.3.4 -snmp-version SNMPv2c -community-or-username cshm1! -model NX3132V -type cluster-network
----
典型的示例是添加一个名为[DeviceName]的交换机、IP地址为1.2.3.4、SNMPv2c凭据设置为* cshm1！*。如果要配置存储交换机、请使用、 `-type storage-network`而不是 `-type cluster-network`。



== 禁用监控而不删除交换机

如果要暂停或停止监控某个交换机、但仍保留该交换机以供将来监控、请修改其参数、而不是将其 `is-monitoring-enabled-admim`删除。

例如：

[source, cli]
----
system switch ethernet modify -device DeviceName -is-monitoring-enabled-admin false
----
这样、您就可以保留交换机详细信息和配置、而无需生成新警报或重新发现。



== 删除不再需要的交换机

 `system switch ethernet delete`用于删除已断开连接或不再需要的交换机：

[source, cli]
----
system switch ethernet delete -device DeviceName
----
默认情况下、只有当ONTAP当前未通过CDP或LDP检测到交换机时、此命令才会成功。要删除已发现的交换机、请使用 `-force`参数：

[source, cli]
----
system switch ethernet delete -device DeviceName -force
----
使用时 `-force`、如果ONTAP再次检测到该交换机、则可能会自动重新添加该交换机。
