---
permalink: switch-nvidia-sn2100-storage/install-onie-mode-sn2100-storage.html 
sidebar: sidebar 
keywords: install cumulus onie mode, sn2100 SN2100 switches setup, cumulus linux, onie mode 
summary: '当交换机运行 Cumulus Linux 或 ONIE 时，可以安装 Cumulus Linux (CL) 操作系统。' 
---
= 以 ONIE 模式安装 Cumulus Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当交换机运行在 ONIE 模式下时，请按照以下步骤安装 Cumulus Linux (CL) 操作系统。


NOTE: Cumulus Linux (CL) 操作系统可以在交换机运行 Cumulus Linux 或 ONIE 时安装（参见link:install-cumulus-mode-sn2100-storage.html["以 Cumulus 模式安装"]）。

.关于此任务
您可以使用开放网络安装环境 (ONIE) 安装 Cumulus Linux，该环境允许自动发现网络安装程序映像。这有助于实现通过操作系统选择（例如 Cumulus Linux）来保护交换机的系统模型。使用 ONIE 安装 Cumulus Linux 最简单的方法是通过本地 HTTP 发现。


NOTE: 如果您的主机支持 IPv6，请确保它正在运行 Web 服务器。如果您的主机支持 IPv4，请确保除了 Web 服务器之外，它还运行 DHCP 服务。

本过程演示了管理员在 ONIE 启动后如何升级 Cumulus Linux。

.步骤
. 将 Cumulus Linux 安装文件下载到 Web 服务器的根目录。重命名此文件 `onie-installer`。
. 使用以太网线将主机连接到交换机的管理以太网端口。
. 打开开关电源。交换机下载 ONIE 镜像安装程序并启动。安装完成后，终端窗口中会出现 Cumulus Linux 登录提示符。
+

NOTE: 每次安装 Cumulus Linux 时，整个文件系统结构都会被擦除并重建。

. 重启SN2100交换机：
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo reboot*
----
. 在 GNU GRUB 屏幕上按 *Esc* 键中断正常的启动过程，选择 *ONIE* 并按 *Enter* 键。
. 在显示的下一个屏幕上，选择 *ONIE：安装操作系统*。
. ONIE 安装程序发现过程会运行以搜索自动安装程序。按 *Enter* 键暂时停止该进程。
. 当发现过程停止时：
+
[listing, subs="+quotes"]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----
. 如果您的网络正在运行 DHCP 服务，请验证 IP 地址、子网掩码和默认网关是否已正确分配：
+
`ifconfig eth0`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff

ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.233.204.1    0.0.0.0         UG    0      0      0   eth0
10.233.204.0    *               255.255.254.0   U     0      0      0   eth0
----
====
. 如果 IP 地址方案是手动定义的，请执行以下操作：
+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0 10.233.204.71 netmask 255.255.254.0*
ONIE:/ # *route add default gw 10.233.204.1*
----
. 重复步骤 9 以验证静态信息是否已正确输入。
. 安装 Cumulus Linux：
+
[listing, subs="+quotes"]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-4.4.3-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----
. 安装完成后，登录交换机：
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
====
. 请验证 Cumulus Linux 版本：
+
`net show version`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u4
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3”*
----
====


.下一步是什么？
在 ONIE 模式下安装 Cumulus Linux 后，您可以……link:install-rcf-sn2100-storage.html["安装或升级 RCF 脚本"] 。
