---
permalink: switch-nvidia-sn2100-storage/migrate-cisco-storage-switch-sn2100-storage.html 
sidebar: sidebar 
keywords: migrating to a storage switch with NVIDIA SN2100 storage switches, how to migrate 
summary: 您可以将ONTAP集群中较旧的Cisco交换机无中断地迁移到NVIDIA SN2100 存储交换机。 
---
= 将存储交换机从Cisco)迁移到NVIDIA) SN2100 存储交换机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将ONTAP集群中较旧的Cisco交换机迁移到NVIDIA SN2100 存储交换机。这是一个非破坏性的过程。



== 审查要求

支持以下存储交换机：

* CiscoNexus 9336C-FX2
* CiscoNexus 3232C
* 参见 https://hwu.netapp.com/["Hardware Universe"^]有关支持的端口及其配置的完整详细信息。


.开始之前
确保您具有以下各项：

* 现有集群已正确设置并正常运行。
* 所有存储端口均处于开启状态，以确保运行不中断。
* NVIDIA SN2100 存储交换机已配置并运行在正确版本的 Cumulus Linux 下，并应用了参考配置文件 (RCF)。
* 现有存储网络配置如下：
+
** 使用较旧的Cisco交换机构建冗余且功能齐全的NetApp集群。
** 对旧款Cisco交换机和新款交换机的管理连接和控制台访问。
** 所有处于启动状态的集群 LIF 都位于其主端口上。
** ISL 端口已启用，并且已在旧款Cisco交换机和新款交换机之间连接了线缆。


* 参见 https://hwu.netapp.com/["Hardware Universe"^]有关支持的端口及其配置的完整详细信息。
* NVIDIA SN2100 交换机上的一些端口配置为以 100 GbE 运行。
* 您已规划、迁移并记录了从节点到NVIDIA SN2100 存储交换机的 100 GbE 连接。




== 迁移交换机

.关于示例
在此过程中，使用Cisco Nexus 9336C-FX2 存储交换机作为示例命令和输出。

本流程中的示例使用以下开关和节点命名规则：

* 现有的Cisco Nexus 9336C-FX2 存储交换机型号为 _S1_ 和 _S2_。
* 新的NVIDIA SN2100 存储交换机型号为 _sw1_ 和 _sw2_。
* 节点分别为 _node1_ 和 _node2_。
* 节点 1 上的集群 LIF 分别为 _node1_clus1_ 和 _node1_clus2_，节点 2 上的集群 LIF 分别为 _node2_clus1_ 和 _node2_clus2_。
* 这 `cluster1::*>`prompt 指示集群名称。
* 此过程中使用的网络端口为_e5a_和_e5b_。
* 分支端口采用以下格式：swp1s0-3。例如，swp1 上的四个分支端口分别是 _swp1s0_、_swp1s1_、_swp1s2_ 和 _swp1s3_。
* 首先将交换机 S2 替换为交换机 sw2，然后将交换机 S1 替换为交换机 sw1。
+
** 然后断开节点与 S2 之间的电缆与 S2 的连接，并重新连接到 sw2。
** 然后断开节点与 S1 之间的电缆与 S1 的连接，并重新连接到 sw1。






=== 步骤 1：准备迁移

. 如果启用了AutoSupport，则通过调用AutoSupport消息来阻止自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
其中 _x_ 为维护窗口的持续时间（小时）。

. 将权限级别更改为高级，并在提示继续时输入 *y*：
+
`set -privilege advanced`

+
出现高级提示符（*>）。

. 确定每个存储接口的管理或运行状态：
+
每个端口都应显示为已启用。 `Status` 。





=== 步骤 2：配置线缆和端口

. 显示网络端口属性：
+
`storage port show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. 使用以下命令（从节点角度）验证每个节点上的存储端口是否已按以下方式连接到现有存储交换机：
+
`network device-discovery show -protocol lldp`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/1           -
            e5b    S2 (7c:ad:4f:98:8e:3c)    Eth1/1           -
node2      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/2           -
            e5b    S2 (7c:ad:4f:98:8e:3c)    Eth1/2           -
----
====
. 在交换机 S1 和 S2 上，使用以下命令确保存储端口和交换机按以下方式连接（从交换机的角度来看）：
+
`show lldp neighbors`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
S1# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability           Port ID
node1                 Eth1/1         121         S                    e0c
node2                 Eth1/2         121         S                    e0c
SHFGD1947000186       Eth1/10        120         S                    e0a         
SHFGD1947000186       Eth1/11        120         S                    e0a         
SHFGB2017000269       Eth1/12        120         S                    e0a         
SHFGB2017000269       Eth1/13        120         S                    e0a

S2# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability          Port ID
node1                 Eth1/1         121         S                   e5b
node2                 Eth1/2         121         S                   e5b
SHFGD1947000186       Eth1/10        120         S                   e0b         
SHFGD1947000186       Eth1/11        120         S                   e0b         
SHFGB2017000269       Eth1/12        120         S                   e0b         
SHFGB2017000269       Eth1/13        120         S                   e0b
----
====
. 在交换机 sw2 上，关闭连接到磁盘柜存储端口和节点的端口。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net add interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. 将控制器和磁盘柜的节点存储端口从旧交换机 S2 移至新交换机 sw2，使用NVIDIA SN2100 支持的适当电缆。
. 在交换机 sw2 上，启动连接到节点存储端口和磁盘柜的端口。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net del interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. 从节点的角度来看，请确认每个节点上的存储端口现在是否按以下方式连接到交换机：
+
`network device-discovery show -protocol lldp`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface      Platform
----------- ------ ------------------------- -------------  ----------------
node1      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/1         -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp1           -

node2      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/2         -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp2           -
----
====
. 请验证网络端口属性：
+
`storage port show`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. 在交换机 sw2 上，确认所有节点存储端口均已启动：
+
`net show interface`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. 在交换机 sw1 上，关闭连接到节点和磁盘柜存储端口的端口。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp1-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. 使用NVIDIA SN2100 支持的适当线缆，将控制器的节点存储端口和磁盘柜从旧交换机 S1 移至新交换机 sw1。
. 在交换机 sw1 上，启动连接到节点存储端口和磁盘柜的端口。
+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp1-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. 从节点的角度来看，请确认每个节点上的存储端口现在是否按以下方式连接到交换机：
+
`network device-discovery show -protocol lldp`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0c    sw1 (b8:ce:f6:19:1b:96)   swp1            -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp1            -

node2      /lldp
            e0c    sw1  (b8:ce:f6:19:1b:96)  swp2            -
            e5b    sw2  (b8:ce:f6:19:1a:7e)  swp2            -
----
====




=== 步骤 3：验证配置

. 验证最终配置：
+
`storage port show`

+
每个端口都应显示为已启用。 `State`并已启用 `Status`。

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. 在交换机 sw2 上，确认所有节点存储端口均已启动：
+
`net show interface`

+
.显示示例
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. 确认两个节点都分别与每个交换机建立了一条连接：
+
`net show lldp`

+
.显示示例
[%collapsible]
====
以下示例显示了两种开关的正确结果：

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*
LocalPort  Speed  Mode      RemoteHost             RemotePort
---------  -----  --------  ---------------------  -----------
...
swp1       100G   Trunk/L2  node1                  e0c
swp2       100G   Trunk/L2  node2                  e0c
swp3       100G   Trunk/L2  SHFFG1826000112        e0a
swp4       100G   Trunk/L2  SHFFG1826000112        e0a
swp5       100G   Trunk/L2  SHFFG1826000102        e0a
swp6       100G   Trunk/L2  SHFFG1826000102        e0a

cumulus@sw2:~$ *net show lldp*
LocalPort  Speed  Mode      RemoteHost             RemotePort
---------  -----  --------  ---------------------  -----------
...
swp1       100G   Trunk/L2  node1                  e5b
swp2       100G   Trunk/L2  node2                  e5b
swp3       100G   Trunk/L2  SHFFG1826000112        e0b
swp4       100G   Trunk/L2  SHFFG1826000112        e0b
swp5       100G   Trunk/L2  SHFFG1826000102        e0b
swp6       100G   Trunk/L2  SHFFG1826000102        e0b
----
====


. 将权限级别改回管理员：
+
`set -privilege admin`

. 如果您已禁用自动创建案例功能，请通过调用AutoSupport消息重新启用该功能：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.下一步是什么？
交换机迁移完成后，您可以…… link:../switch-cshm/config-overview.html["配置交换机健康监控"]。
