---
permalink: switch-nvidia-sn2100/required-documentation-sn2100-storage.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: 对于NVIDIA SN2100交换机安装和维护、请务必查看所有建议的文档。 
---
= NVIDIA SN2100交换机的文档要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
对于NVIDIA SN2100交换机安装和维护、请务必查看所有建议的文档。

下表列出了适用于NVIDIA SN2100交换机的文档。

[cols="1,2"]
|===
| 标题 | Description 


 a| 
link:install_setup_sn2100_switches_overview.html["设置和配置NVIDIA SN2100交换机_"^]
 a| 
介绍如何设置和配置NVIDIA SN2100交换机、包括安装Cumulus Linux和适用的RCF。



 a| 
link:migrate_cisco_sn2100_cluster_switch.html["_从Cisco集群交换机迁移到NVIDIA SN2100集群交换机_"^]
 a| 
介绍如何从使用Cisco集群交换机的环境迁移到使用NVIDIA SN2100集群交换机的环境。



 a| 
link:migrate_cisco_sn2100_storage_switch.html["_从Cisco存储交换机迁移到NVIDIA存储交换机_"^]
 a| 
介绍如何从使用Cisco存储交换机的环境迁移到使用NVIDIA SN2100存储交换机的环境。



 a| 
link:migrate_2n_switched_sn2100_switches.html["_迁移到使用NVIDIA SN2100集群交换机的双节点交换集群_"^]
 a| 
介绍如何使用NVIDIA SN2100集群交换机迁移到双节点交换环境。



 a| 
link:replace_sn2100_switch_cluster.html["_更换NVIDIA SN2100集群交换机_"^]
 a| 
介绍用于更换集群中有缺陷的NVIDIA SN2100交换机以及下载Cumulus Linux和参考配置文件的操作步骤。



 a| 
link:replace_sn2100_switch_storage.html["_更换NVIDIA SN2100存储交换机_"^]
 a| 
介绍用于更换有缺陷的NVIDIA SN2100存储交换机以及下载Cumulus Linux和参考配置文件的操作步骤。

|===